### ISSUE TITLE
Unable to open web console (dashboard) when one server is offline.

### ISSUE THREAD

**Issue by Tortue95** [minio/console#1011]
Hi
After a fresh install of 4 servers and 2 drives per server.
If I stop one minio server. I can't access to the dashboard on web console. The other pages work correctly (object-browser/account/logs...)

on my web browser, I have this error on the dashboard page:

![issue_minio](https://user-images.githubusercontent.com/11313869/132320468-9a51f35b-6d16-4d40-a885-d4f7ceddd273.png)

## Expected Behavior
Can see the dashboard page.

## Current Behavior
The dashboard page is blank.

## Steps to Reproduce (for bugs)
on 4 nodes
```
su - minio
export MINIO_ROOT_USER=admin
export MINIO_ROOT_PASSWORD=azeazeaze
/usr/local/bin/minio server --address ":9000" --console-address ":9001" http://wcm-lab-minio{01...04}.my_dom/srv/disk{1...2}/minio/tenant1 

```
=> dashboard page working

stop minio server with ctrl+C on node 3

=> dashboard page is blank

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-09-03T03-56-13Z
* Server setup and configuration: Debian 10.10
* Operating System and version (`uname -a`): Linux wcm-lab-minio01 4.19.0-17-amd64 minio/minio#1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

**Comment by hillar** [comment]
> You need to make sure to point console UI through a LB using

? LB

the error is in javascript in browser side

**Comment by babs** [comment]
The point is, the browser is pointing to an alive host.
I think that when the console (browser side) loads up all the values, it badly handled null objects from dead servers (returned by the api ?).

**Comment by hillar** [comment]
```
[Error] TypeError: undefined is not an object (evaluating 'a.totalSpace.toString')
(anonymous function) — DriveInfoCard.tsx:124
oa — react-dom.production.min.js:157:139
Gl — react-dom.production.min.js:267:463
js — react-dom.production.min.js:250:350
_s — react-dom.production.min.js:250:281
ks — react-dom.production.min.js:250:138
gs — react-dom.production.min.js:243:166
gs
(anonymous function) — react-dom.production.min.js:123:115
(anonymous function) — scheduler.production.min.js:18:343
$o — react-dom.production.min.js:123
Yo — react-dom.production.min.js:122:428
fs — react-dom.production.min.js:237:203
Ea — react-dom.production.min.js:170:411
Ea
(anonymous function) — Dashboard.tsx:51
promiseReactionJob

	ll (2.941b277c.chunk.js:2:1038105)
	(anonymous function) (2.941b277c.chunk.js:2:1040210)
	di (2.941b277c.chunk.js:2:1004022)
	hl (2.941b277c.chunk.js:2:1041954)
	Ps (2.941b277c.chunk.js:2:1058537)
	Ps
	(anonymous function) (2.941b277c.chunk.js:2:1077930)
	Ms (2.941b277c.chunk.js:2:1055272)
	gs (2.941b277c.chunk.js:2:1051358)
	gs
	(anonymous function) (2.941b277c.chunk.js:2:1000511)
	(anonymous function) (2.941b277c.chunk.js:2:1077930)
	$o (2.941b277c.chunk.js:2:1000457)
	Yo (2.941b277c.chunk.js:2:1000392)
	fs (2.941b277c.chunk.js:2:1048502)
	Ea (2.941b277c.chunk.js:2:1020069)
	Ea
	(anonymous function) (main.d668582e.chunk.js:1:277114)
	promiseReactionJob
```

**Comment by dvaldivia** [comment]
This should be fixed on the next release
