### ISSUE TITLE
assets are referenced by relative url (instead of absolute - resulting in not being able to send links to console (other than the login page))

### ISSUE THREAD

**Issue by alexanderankin** [minio/console#1023]
this causes problems like #938.

This would be very easily fixed by simply hard coding a root url (e.g. /scripts/js/main.hash.js) or a configurable prefix. I'm willing to work on this but would like to gauge interest/convince of this need first.

**Comment by dvaldivia** [comment]
anonymous access is not yet supported, it's in the pipeline.

I believe the assets are no longer loaded in a relative fashion
![2021-09-13 18-28-51 2021-09-13 18_30_51](https://user-images.githubusercontent.com/18384552/133179708-374d0f6d-4f81-462e-bf3d-af811d01cd1f.gif)
