### ISSUE TITLE
To update progress bar for uploading large files in a more UI-friendly manner

### ISSUE THREAD

**Issue by wvolkov** [minio/console#1031]
Hi All!

While uploading a large file via console admin panel, it is not really obvious that a progress bar actually exists at the top of the web page. Is it possible to apply some styles a bit in order to increase its size and probably add some percentage progress info over it for easy reference to it?

Something like on a screenshot below:
![minio-extend-progress-bar-example](https://user-images.githubusercontent.com/49549154/132972717-4db6cc77-e085-46d3-ac93-8b37d2a6dd25.png)

Maybe add some setting to display it only for files with size larger than X MB?

**Comment by dvaldivia** [comment]
This is a great suggestion, we are planning to rework the upload to have a small manager where you can monitor the state of multiple uploads, thus we would move this progress bar to a box on the top right corner soon, we'll link to this issue whenever that PR comes
