### ISSUE TITLE
can't access policy with '+' in the name

### ISSUE THREAD

**Issue by soudhaf** [minio/console#1034]
### Description
You get 500 , `{"code":500,"detailedMessage":"The canned policy does not exist. (Specified canned policy does not exist)","message":"an error occurred, please try again"}` 
when you try to access a policy with '+' in the name.

### How to reproduce
example create policy with name test+test try to access it from console

**Comment by dvaldivia** [comment]
Fixed by https://github.com/minio/console/pull/1039
