### ISSUE TITLE
Have plan to support upload folder or drag files to browser? It is very useful for users just use brower

### ISSUE THREAD

**Issue by HaoLiuHust** [minio/console#1053]
In old web UI, users can upload files or folder by drag it to browser, it is a very useful feature for users. Have you plan to support this?

**Comment by dvaldivia** [comment]
@HaoLiuHust yes, we haven't had time to implement this, but probably with the new File Upload we can introduce this

**Comment by dvaldivia** [comment]
Drop to upload will be fixed via https://github.com/minio/console/issues/1163 fix
Upload multiple files is also in the works

**Comment by bexsoft** [comment]
Will handle Drag files to browser functionality in a separated PR. Meanwhile we added upload folder capability in #1272

**Comment by bexsoft** [comment]
Handled in #1331
