### ISSUE TITLE
latest version UI is not as good as old version

### ISSUE THREAD

**Issue by HaoLiuHust** [minio/console#1059]
With previous version, the ui has Object Browser, and buckets display as a list, there is "USER", "ADMIN" ...
![image](https://user-images.githubusercontent.com/7233091/133871371-7a69fcba-390d-4ed4-ab51-dc6402c0f903.png)
but after update to latest version, the Object Browser has gone, and bukcets is not a list any more:
![image](https://user-images.githubusercontent.com/7233091/133871408-aa22ac48-f124-42c0-9ec6-816a78850761.png)

**Comment by dvaldivia** [comment]
hi @HaoLiuHust to do Bucket Management click on the top right gear, I understand it might not be as clear, but we are experimenting reducing the number of screens, the latest changes on Master make this even more obvious
