### ISSUE TITLE
static content breaks if reverse proxy links to a sub URL

### ISSUE THREAD

**Issue by bernd-prager-epam** [minio/console#1060]
Static content (e.g. "/styles/root-styles.css") is absolute to the root which breaks the console if linked to a sub URL via reverse proxy, load balancer etc. Please make it relative ('styles/root-styles.css").

**Comment by TomHellier** [comment]
see #952 and #964

**Comment by dvaldivia** [comment]
Fixed by https://github.com/minio/console/pull/1247 use `CONSOLE_SUBPATH`
