### ISSUE TITLE
no dashboard data

### ISSUE THREAD

**Issue by aceeric** [minio/console#1065]
Hello - I'm experiencing something similar to what others have described (e.g. https://github.com/minio/console/issues/799 and https://github.com/minio/console/issues/787) in which the dashboard displays all the widgets but there is no data in the widgets.

In our case though, a difference is we are running the Rancher RKE2 Kubernetes distro v1.21.3, and deploying our Minio instance via a `Tenant` CR. We have the Minio Operator v4.2.4 running in the `minio-operator` namespace and when we deploy the `Tenant` CR the operator spins up the Minio workload. Minio is working fine.

With RKE2, you install cluster-wide monitoring as part of installing the RKE2 distro, and this results in Prometheus/Grafana being installed into the `cattle-monitoring-system` namespace. Then you have to integrate monitoring for your various workloads into this cluster-wide observability stack. We therefore direct the RKE2 Prometheus instance to scrape Minio by virtue of a `PodMonitor` CR.

Apologies in advance for typos as this is all hand-typed:

So:
```
$ kubectl -n nuxeo-minio describe tenant
...
Name:        minio
Namespace:   nuxeo-minio
Annotations: prometheus.io/path: /minio/v2/metrics/cluster
             prometheus.io/port: 9000
             prometheus.io/scrape: true
API Version:  minio.min.io/v2
Kind: Tenant
...
Spec:
  Cert Config:
    Common Name:
    Dns Names:
    Organization Name:
  Creds Secret:
    Name: minio-creds-secret
  Env:
    Name: MINIO_PROMETHEUS_AUTH_TYPE
    Value: public
    Name: MINIO_PROMETHEUS_URL
    Value: http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local
    Name: CONSOLE_PROMETHEUS_URL
    Value: http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local
    Name: MINIO_PROMETHEUS_JOB_ID
    Value: podMonitor/nuxeo-minio/minio-metrics/0
    Name: CONSOLE_PROMETHEUS_JOB_ID
    Value: podMonitor/nuxeo-minio/minio-metrics/0
  External Ca Cert Secret:
    Name: our-ca-secret
    Type: kubernetes.io/tls
    Name: rancher-ca
    Type: kubernetes.io/tls
  Image: our-internal-registry/our-org/minio:RELEASE.2021-08-05T22-01-19Z
  Pools:
  ...
```
The configuration above reflects multiple attempts to get this to work.

```
$ kubectl -n nuxeo-minio describe podmonitor
...
Name:        minio-metrics
Namespace:   nuxeo-minio
API Version: monitoring.coreos.com/v1
Kind:        PodMonitor
...
Spec:
  Job Label: minio-metrics-exporter
  Pod Metrics Endpoints:
    Interval: 15s
    Path: /minio/v2/metrics/cluster
    Scheme: https
    Scrape Timeout: 15s
    Target Port: 9000
    Tls Config:
      Ca:
        Secret:
          Key: tls.crt
          Name: rancher-ca
      Server Name: minio-hl-nuxeo-minio.svc.cluster.local
  Selector:
    Match Labels:
      v1.min.io/tenant: minio
```
The RKE2 Prometheus workload is configured to scan the cluster and look for `PodMonitor`s (and `ServiceMonitor`s) which it then injects into the Prometheus scape configs. So:

```
$ kubectl -n cattle-monitoring-system exec -it prometheus-rancher-monitoring-prometheus-0\
   -- grep job_name: /etc/prometheus/config_out/prometheus.env.yaml
...
- job_name: podMonitor/nuxeo-minio/minio-metrics/0
...
```
And then:
```
$ kubectl -n cattle-monitoring-system exec -it prometheus-rancher-monitoring-prometheus-0\
   -- grep -e 'job_name: podMonitor/nuxeo-minio/minio-metrics/0'\
   /etc/prometheus/config_out/prometheus.env.yaml -A40
- job_name: podMonitor/nuxeo-minio/minio-metrics/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - nuxeo-minio
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /minio/v2/metrics/cluster
  scheme: https
  tls_config:
    insecure_skip_tls_verify: false
    ca_file: /etc/prometheus/certs/secret_nuxeo-minio_rancher-ca_tls.crt
    server_name: minio-hl.nuxeo-minio.svc.cluster.local
  relabel_configs:
  - source_labels
    - job
    target_label: __tmp_prometheus_job_name
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_label_v1_min_io_tenant
    regex: minio
  ...
```
You can see that the pod monitor name and namespace get mangled into the job name in Prometheus. (It appears as though the job label in the pod monitor is ignored and I'm so far not sure what is configuring the re-labelings - I think it must be Prometheus.)

Anyway: I can see the targets in Prometheus, and I can execute Prometheus queries against all the metrics. E.g. in the Prometheus web UI:

query: minio_bucket_usage_total_bytes
result:
minio_bucket_usage_total_bytes{bucket="nuxeo-minio-nuxeo-bucket", container="minio", endpoint="9000", instance="10.42.131.88:9000", job="nuxeo-minio/minio-metrics", namespace="nuxeo-minio", pod="minio-ss-0-0", server="127.0.0.1:9000"}

I can also port-forward to the minio pod and curl the metrics:

```
$ kubectl -n nuxeo-minio port-forward minio-ss-0-0 9000
Forwarding from 127.0.0.1:9000 -> 9000
```
Then:
```
curl -k https://localhost:9000/minio/v2/metrics/cluster
# HELP minio_bucket_objects_size_distribution Distribution of object sizes in the bucket, includes label for the bucket name.
# TYPE minio_bucket_objects_size_distribution gauge
minio_bucket_object_size_distribution{"nuxeo-minio-nuxeo-bucket" ...
...
```
But so far, can't get the console to populate the widgets. Help is appreciated. Thanks.

**Comment by aceeric** [comment]
In case this helps others. Resolved this with these changes:

1. Only need MINIO_PROMETHEUS_... environment variables, not CONSOLE_PROMETHEUS...
2. Need the port number in the Prometheus URL
3. Job ID should be specified as "namespace name/podmonitor name"

So in the `Tenant` CR:
```
  Env:
    Name: MINIO_PROMETHEUS_AUTH_TYPE
    Value: public
    Name: MINIO_PROMETHEUS_URL
    Value: http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local:9090
    Name: MINIO_PROMETHEUS_JOB_ID
    Value: nuxeo-minio/minio-metrics
```
And all is well.

**Comment by harshavardhana** [comment]
>   metrics_path: /minio/c2/metrics/cluster

There is no metrics called `/minio/c2` it is `/minio/v2`

**Comment by aceeric** [comment]
Fixed typo in origin post.

**Comment by ryuseongryong** [comment]
hello I got the same setting without tls, but not work.
Could I know debug point? minio grafana got the normal metrics but not dashboard.
MINIO_PROMETHEUS_AUTH_TYPE="public"
MINIO_PROMETHEUS_URL="http://prometheus-operated.prometheus.svc.cluster.local:9090"
MINIO_PROMETHEUS_JOB_ID="{{namespace}}/{{podmonitor.name}}"

Could you any advice for me, plz?
