### ISSUE TITLE
Group operations on objects

### ISSUE THREAD

**Issue by chelmike** [minio/console#1082]
Hello!

We are glad to use this great product at all!
But ... could You please implement a simple "Select all" in the current folder? It is really necessary.

Regards, Michael

**Comment by dvaldivia** [comment]
Select all just to delete all the files?

**Comment by ssi444** [comment]
for delete all files or download several or all files

**Comment by ssi444** [comment]
there is also a lack of sorting by existing columns

**Comment by dvaldivia** [comment]
We are working on a download manager to download multiple separate files, for the meanwhile you can already download a whole folder via https://github.com/minio/console/pull/1235
