### ISSUE TITLE
Console share links may lacks version id

### ISSUE THREAD

**Issue by vixns** [minio/console#1095]
## Expected Behavior

A valid share link

## Current Behavior

When sharing a file from the console bucket view, provided links are invalid 

`<Message>Invalid version id specified</Message>`

Links generated for a specific version are valid.

## Steps to Reproduce (for bugs)

1. navigate the minio console to any file on a versioned bucket
2. click on share
3. copy the link and try it

## Your Environment

* Version used (`minio --version`):  2021-09-24T00:24:24Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by dvaldivia** [comment]
@vixns there's a problem when creating the links using a console session, since behind the scenes we use an STS Token instead of the real credentials, unlike `mc` so, when the STS expires, the links also expire, we are looking for a solution to this

**Comment by cesnietor** [comment]
Closing since main issue was solved and expiration issue is dup of https://github.com/minio/console/issues/922
