### ISSUE TITLE
The bucket list cannot support click action with chinese prefix in version RELEASE.2021-10-08T23-58-24Z_1

### ISSUE THREAD

**Issue by qiandu23** [minio/console#1114]
The bucket list cannot support click action with chinese prefix in version RELEASE.2021-10-08T23-58-24Z_1, but its not a bug at previous version.![image](https://user-images.githubusercontent.com/19660157/137428128-5160a891-3bbb-483f-8fcc-fb0c36094c73.png)

**Comment by dvaldivia** [comment]
hmm, we did fixed this for most utf-8 charaters, I think we would need to test with utf-16 perhaps? but the `latin1` range makes me think something is telling the brwoser to use the wrong encoding. I don't think it's router related. cc @bexsoft @Alevsk @adfost

**Comment by dvaldivia** [comment]
Fixed on the latest release `minio/minio:RELEASE.2021-11-05T09-16-26Z`
