### ISSUE TITLE
Improve File Uploading UX With Dropzone

### ISSUE THREAD

**Issue by aaronhayes** [minio/console#1116]
It is currently a real pain/time consumer to have to use the file input to select each file. It would be great if we could convert the list of files into a dropzone so we can easily upload files. 

![image](https://user-images.githubusercontent.com/4180720/137661555-6755a4b4-7b8a-4ada-b60d-132a5f2f540e.png)

**Comment by dvaldivia** [comment]
I believe you can select multiple files on that file selector, we have yet to add `drag & drop` support but we would welcome a PR for it, and have plans for an upload queue.

Meanwhile, use your OS multi-file selector capabilities 
![2021-10-17 21-46-11 2021-10-17 21_47_44](https://user-images.githubusercontent.com/18384552/137670780-66f48b23-3a87-493a-affc-014abbd85b0c.gif)
