### ISSUE TITLE
NaN is displayed in Dashboard and license page is not loaded when clicked

### ISSUE THREAD

**Issue by prakashsvmx** [minio/console#1139]
Access Operator Console -> Manage Tenant -> Dashboard ( when no bucket is created)

#### Issue 1
![Screenshot from 2021-10-22 17-10-31](https://user-images.githubusercontent.com/23444145/138447793-6cb4afbc-a5eb-4859-9a74-58ae8592e55f.png)

#### Issue 2
Click on license link on the left navigation:
OS Ubuntu
Browsers tested: 
- Chrome: Version 95.0.4638.54 (Official Build) (64-bit)
- Firefox : 93.0 (64-bit)

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at License.tsx:621
    at Array.map (<anonymous>)
```

**Comment by bexsoft** [comment]
Hi @prakashsvmx!

What MinIO version are you testing on?, on RELEASE.2021-10-10T16-53-30Z I'm not able to see the issue on a fresh tenant:

<img width="1499" alt="Screen Shot 2021-10-22 at 19 55 40" src="https://user-images.githubusercontent.com/33497058/138536182-9e349699-07b3-42d7-a13d-f864eec4cc89.png">
<img width="1503" alt="Screen Shot 2021-10-22 at 19 55 32" src="https://user-images.githubusercontent.com/33497058/138536183-03a98bc8-6ee5-4b7d-a1a8-8a3fac5e8766.png">
<img width="1496" alt="Screen Shot 2021-10-22 at 19 55 19" src="https://user-images.githubusercontent.com/33497058/138536184-e2aeb59a-7b0c-4b3d-843e-40c2fab429fd.png">
