### ISSUE TITLE
Slow loading of console resource file, latest version

### ISSUE THREAD

**Issue by mmm8955405** [minio/console#1145]
Slow loading of console resource file, latest version
![11](https://user-images.githubusercontent.com/5687907/138584092-a9af45be-5adf-43ef-9cfb-da44518b1d5b.jpg)

**Comment by dvaldivia** [comment]
I agree. If this is OS related it may be something more deep, we serve the static files from the binary so I don't anticipate this being an FS problem. please re-open if the problem persists.
