### ISSUE TITLE
Download of directory gives 0 Bytes 'download' file

### ISSUE THREAD

**Issue by torblerone** [minio/console#1153]
Hey all, first of all thanks for maintaining this Web UI!

We have some issues with it when downloading objects in browser.

When downloading a single object from the console, everything works fine. But when we try to download a directory, our browsers present us a file called 'download' which is 0 Bytes in size.
![Auswahl_107](https://user-images.githubusercontent.com/64590448/138843499-a24af437-9239-4749-a23f-131c9de1776e.png)

![Auswahl_108](https://user-images.githubusercontent.com/64590448/138843495-f56fecc2-08d1-4ac6-bc11-93b9d1ea4e4b.png)

Is anyone else experiencing this issue? Did we miss something when configuring console and/or minio?

Note: We're running an extra instance of `console` outside of `minio` to keep the minio-server separated from the Web UI.

**Comment by dvaldivia** [comment]
We already removed the download button for folders.

We will look into bundling multiple files as a download, starting with folders only.

**Comment by dvaldivia** [comment]
Fixed by https://github.com/minio/console/pull/1235 now downloading a folder returns a zip file with it's contents (at the user's peril)
