### ISSUE TITLE
Minio multi cluster replication - LDAP integrated

### ISSUE THREAD

**Issue by Bhagi33** [minio/console#1173]
Hi Team,

I am new to Minio replication, want to implement replication  for Multi cluster Minio(Located in different Locations) & LDAP Integrated on both clusters.

Can you please guide how to implement replication on LDAP integrated Minio clusters.
./mc admin replicate add backup1 backup2 --insecure                                                             mc: <ERROR> Unable to add sites for replication. This 'admin' API is not supported by server in 'mode-server-distributed-xl'

Note: these policies to both clusters. tried to apply the attached polices to LDAP user But at a time only one policy is applying.
![image](https://user-images.githubusercontent.com/68953135/141098654-b9f3230b-8fc6-4a7d-b8a9-9044f3811daf.png)

**Comment by Bhagi33** [comment]
Can you respond, i have two clusters deployed with LDAP .want to enable active active replication.
Please help and guide me.. 
![image](https://user-images.githubusercontent.com/68953135/141099069-e6373e88-85ce-40fd-a298-cb2dddd653c8.png)

**Comment by Alevsk** [comment]
@Bhagi33 you cannot create aliases based on LDAP credentials, you either use the MinIO root credentials or generate STS tokens based on the LDAP credentials and then generate service account tokens <--- this is the right approach

https://github.com/minio/minio/blob/master/docs/sts/ldap.go

https://github.com/minio/minio/blob/master/docs/sts/ldap.md

so, steps:

1. configure both clusters with LDAP
2. make sure theres connectivity between clusters
3. set appropriated policies to users or groups based on dn, ie: `mc admin policy set [ALIAS] [POLICY] user=DN` (this is the only thing you need to do in minio)
4. use LDAP credentials to generate sts tokens, you can do this via https://github.com/minio/minio/blob/master/docs/sts/ldap.go or enable LDAP on console and login with LDAP
5. create service accounts for each cluster
6. create new mc aliases using the service account tokens and configure replication / configure replication directly via the Console UI

**Comment by Bhagi33** [comment]
Thank you so much for the detailed Information.Please document the same in Minio documentation. 
I did not yet tested we moved on to EKS setup here am testing with AzureAD integration with Minio.

**Comment by harshavardhana** [comment]
> Thank you so much for the detailed Information.Please document the same in Minio documentation.

This is already documented in the way its described.
