### ISSUE TITLE
ServerInfoCard has a logic error when drives = 2

### ISSUE THREAD

**Issue by amhuber** [minio/console#1179]
When a server has 2 drives and both are healthy (2/2), the CircleIcon should show a status of green, but it's showing as yellow due to the math:

https://github.com/minio/console/blob/master/portal-ui/src/screens/Console/Dashboard/BasicDashboard/ServerInfoCard.tsx#L93

**Comment by dvaldivia** [comment]
ah, this is a valid scenario, we should calculate that class in order

**Comment by amhuber** [comment]
Looks good, thanks!
