### ISSUE TITLE
Why is the session duration hardcoded to 45 minutes?

### ISSUE THREAD

**Issue by kevinlul** [minio/console#1197]
From a scan of the source code, the length of a console session has been hardcoded to 45 minutes in multiple places without the option for administrator configuration. The default lifetime of an STS is 1 hour in comparison, and it can be configured with `CONSOLE_STS_DURATION_SECONDS`, but it doesn't affect the lifetime of the cookie set on login.

This pales in comparison to the 24-hour expiry in the old browser, which also relied on when the token itself expired rather than setting an additional hardcoded expiry time. The significantly shortened, unconfigurable session duration is extremely inconvenient if not useless for uploads.

Could this be updated to match the old browser or made administrator-configurable? I don't understand why the console forcibly-replaced the browser when the console isn't at parity and has these usability issues.

**Comment by dvaldivia** [comment]
I don't remember the specifics of the 45 minutes limit, perhaps @Alevsk or @harshavardhana can chime in

**Comment by Alevsk** [comment]
@dvaldivia ill take a look, at the end we depend on the sts credentials expiration lenght

**Comment by harshavardhana** [comment]
> From a scan of the source code, the length of a console session has been hardcoded to 45 minutes in multiple places without the option for administrator configuration. The default lifetime of an STS is 1 hour in comparison, and it can be configured with `CONSOLE_STS_DURATION_SECONDS`, but it doesn't affect the lifetime of the cookie set on login.

This can be easily increased to 24 hours no problem there.

**Comment by Alevsk** [comment]
Session duration will be configurable in the next release

PR https://github.com/minio/console/pull/1202
