### ISSUE TITLE
Setting MINIO_SERVER_URL breaks console previews and downloads

### ISSUE THREAD

**Issue by Uninen** [minio/console#1205]
I'm running Minio with Docker behind traefik with following relevant envs:

- `MINIO_BROWSER_REDIRECT_URL=https://my-console-domain`
- `MINIO_SERVER_URL=https://my-minio-domain`

(The console lives on a different top-level domain.)

Traefik proxies both services and also automatically sets up SSL certs, everything seems to work normally; logs are clean and I can access public content from the Internet, but only if `MINIO_SERVER_URL` is commented out. Problem is, when I have `MINIO_SERVER_URL` set, the console previews and downloads don't work -- I get 0 bytes responses and "access denied" in the logs. 

If `MINIO_SERVER_URL` is not set, the server is identified by its internal Docker IP (something like `172.22.0.13`). Now the console works normally but the Minio server isn't reachable from the Internet. (Preview URLs look like `https://my-console-domain/api/v1/buckets/test/objects/download?preview=true&prefix=Y29kZTIucG5n&version_id=null`, publich shared urls like `http://172.22.0.13:9000/test/test.png?X-Amz-Algorithm=[..]`

Is this a configuration issue or is it an issue with the `MINIO_SERVER_URL` setting and the console? I tried searching for various things but didn't find anything from the docs nor issues.

**Comment by dvaldivia** [comment]
I cannot think of why `MINIO_SERVER_URL` would interfere with preview and download. cc @bexsoft

**Comment by harshavardhana** [comment]
@dvaldivia it would if the certs are not present on the pod to talk to MinIO - basically the traffic is terminated at `Traefik` over TLS but the console service is running on MinIO so it doesn't have access to some self-signed certs or certs with non-trusted CA.

Make sure to drop the public cert from your traefik to MinIO container or pod.

**Comment by Uninen** [comment]
Thanks for the swift response.

> Make sure to save the public cert from your traefik to MinIO container or pod at ~/.minio/certs/CAs

This makes sense, so it's most likely a configuration error and not a bug. I'll try to figure it out. Thank you 👍
