### ISSUE TITLE
regression: files in bucket browser not shown anymore

### ISSUE THREAD

**Issue by flixr** [minio/console#1209]
Logging in to the console with a user that only has access to one bucket doesn't show any files in the bucket browser anymore, just `This location is empty, please try uploading a new file`.
With a different user with global access the files are shown.

Issue with RELEASE.2021-11-09T03-21-45Z (was working before with RELEASE.2021-10-13T00-23-17Z).

Via mc or any other commandline tool it works as expected, so this seem to be only a console issue.
The policy for the user is
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid":"AllowGroupToSeeBucketListInTheConsole",
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListAllMyBuckets"
      ],
      "Resource": [
        "arn:aws:s3:::*"
      ]
    },
    {
      "Sid":"AllowListingInBucket",
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads",
        "s3:ListMultipartUploadParts"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}"
      ]
    },
    {
      "Sid":"AllowReadWriteInBucket",
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:AbortMultipartUpload"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}/*"
      ]
    }
  ]
}
```

**Comment by flixr** [comment]
Probably regression from https://github.com/minio/console/pull/1162

**Comment by harshavardhana** [comment]
Permissions model does not support variables in policy yet @flixr

**Comment by flixr** [comment]
Rather not anymore, right?
Since it correctly showed the files with RELEASE.2021-10-13T00-23-17Z

**Comment by harshavardhana** [comment]
> Rather not anymore, right? Since it correctly showed the files with RELEASE.2021-10-13T00-23-17Z

Well, it didn't do much back then @flixr - i.e it never really applied the right resources. You would have seen more than you would. 

As a side affect you would see either errors from server when accessing such resources they will be visible partially. 

Now that the policy application is console was refactored fully to apply on all resources, it didn't cater for variables in the policies.

**Comment by flixr** [comment]
Ok, got it. Thanks for the explanation. I do like how the console is shaping up!
And we did indeed see some errors if someone tried to access stuff they had no rights for... BUT that was less of a problem than not seeing their own files.

**Comment by user173193** [comment]
I can confirm this behaviour in RELEASE.2021-11-24T23-19-33Z. I'm using `arn:aws:s3:::${ldap:username}` and `arn:aws:s3:::${ldap:username}/*` and I'm also getting `This location is empty, please try uploading a new file` in the web console. The policy is working properly when I use the mc client.

**Comment by harshavardhana** [comment]
> I can confirm this behaviour in RELEASE.2021-11-24T23-19-33Z. I'm using `arn:aws:s3:::${ldap:username}` and `arn:aws:s3:::${ldap:username}/*` and I'm also getting `This location is empty, please try uploading a new file` in the web console. The policy is working properly when I use the mc client.

@user173193 console is yet to support these.
