### ISSUE TITLE
API calls(mc,s3fs) show bucket content, but in console the same user sees empty bucket.

### ISSUE THREAD

**Issue by stereopanda** [minio/console#1218]
Hi, guys.
After upgrading minio server from 2021-06-14T01:29:23Z to latest we’ve got a new console.
We have several Users, several buckets, and several policies which allow one user to use one bucket, another user to use another.
So, after upgrade, all users can list their buckets in console, but can’t see the content of these buckets. Moreover, API works fine(minio-client, s3fs).
When I run trace at the moment of listing a bucket, I see the error:  s3:GetBucketPolicy 404
But we’ve already had it in policy. This is our policy:
```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetBucketLocation",
    "s3:GetBucketPolicy",
    "s3:ListBucket",
    "s3:ListBucketMultipartUploads",
    "s3:PutObjectTagging",
    "s3:GetObjectTagging"
   ],
   "Resource": [
    "arn:aws:s3:::bucket1"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:AbortMultipartUpload",
    "s3:GetObject",
    "s3:GetBucketPolicy",
    "s3:ListMultipartUploadParts",
    "s3:PutObject",
    "s3:PutObjectTagging",
    "s3:GetObjectTagging"
   ],
   "Resource": [
    "arn:aws:s3:::bucket1/*"
   ]
  }
 ]
}
```
Please help!

**Comment by harshavardhana** [comment]
Perhaps related to #1209

**Comment by dvaldivia** [comment]
this one is easy to replicate, we should be listing files:

```
(base)  krew-index git:(minio-v4.3.5) ✗ 
➜ mc ls test1218        
[2021-11-13 17:31:16 PST]     0B bucket1/
(base)  krew-index git:(minio-v4.3.5) ✗ 
➜ mc ls test1218/bucket1
[2021-11-13 17:31:20 PST] 9.8MiB firday yakuza.mp4
```

**Comment by dvaldivia** [comment]
Fixed by https://github.com/minio/console/pull/1226
