### ISSUE TITLE
can not preview image in some bucket

### ISSUE THREAD

**Issue by HaoLiuHust** [minio/console#1230]
in some bucket, I can preview jpg image, but in some bucket, minio remind me to download image when I click preview

**Comment by dvaldivia** [comment]
Can you share the content type of both images? If it's not the correct type, the browser won't inline the content and force a download

**Comment by HaoLiuHust** [comment]
**This image can preview:**
![1632727319511_rgb](https://user-images.githubusercontent.com/7233091/142186680-8e741cdc-845e-4583-823f-ef6c5298e4fe.jpg)

**But this image can not preview:**
![detect_2020-12-01_spot-1606893579876](https://user-images.githubusercontent.com/7233091/142186837-f9b55753-44d4-4ab2-8bea-a827d7b1619e.jpg)

**Comment by vadmeste** [comment]
@HaoLiuHust you need to run `mc stat <alias>/bucket/path/to/image1` and `mc stat <alias>/bucket/path/to/image2` to check content-type, can you do that ?

**Comment by HaoLiuHust** [comment]
**The Image can be previewed:**  
Name      : 1632727319511_rgb.jpg
Date      : 2021-09-30 11:44:18 CST 
Size      : 180 KiB 
ETag      : 8cb479ef4cf6fa75cde44cead5bbe3da 
Type      : file 
Metadata  :
  Content-Type    : image/jpeg 
  X-Amz-Meta-Mtime: 1632737966.4427044 

**The Image can not be previewed:**  
Name      : detect_2020-12-01_spot-1606893579876.jpg
Date      : 2021-10-27 15:30:00 CST 
Size      : 100 KiB 
ETag      : a431c55983cfc7f94bc7c632a9e28176 
Type      : file 
Metadata  :
  Content-Type: binary/octet-stream

**Comment by vadmeste** [comment]
> Content-Type : image/jpeg

> Content-Type: binary/octet-stream

You need to ensure that the content-type is properly set while uploading images

**Comment by HaoLiuHust** [comment]
> > Content-Type : image/jpeg
> 
> > Content-Type: binary/octet-stream
> 
> You need to ensure that the content-type is properly set while uploading images

how to set content-type?

**Comment by vadmeste** [comment]
> how to set content-type?

It depends on how you uploaded those objects, can you tell how you did that ?

**Comment by HaoLiuHust** [comment]
> > how to set content-type?
> 
> It depends on how you uploaded those objects, can you tell how you did that ?

I am uploading objects with minio SDK

**Comment by harshavardhana** [comment]
> I am uploading objects with minio Python SDK

@HaoLiuHust 

> put_object(bucket_name, object_name, data, length, content_type="application/octet-stream", metadata=None, sse=None, progress=None, part_size=0, num_parallel_uploads=3, tags=None, retention=None, legal_hold=False)

Set the `content_type` here

**Comment by harshavardhana** [comment]
Closing this issue as user error.
