### ISSUE TITLE
Console Front-End shows current directory name a child

### ISSUE THREAD

**Issue by karlludwigweise** [minio/console#1259]
## Expected Behavior
The Front-End Console should not show a directory as a child of itself.

## Current Behavior
In RELEASE.2021-11-24T23-19-33Z and some versions before that, the directory a user has opened is also part of it's children (cannot be opened).

## Possible Solution
Do not display directory inside itself.

## Steps to Reproduce (for bugs)
1. Open Console Front-End
2. Login
3. Open a bucket with directories inside
4. Open a directory
5. See that 1st child item is directory name itself

## Context
I try to give other access and not be confused ;)

## Your Environment
Version RELEASE.2021-11-24T23-19-33Z

**Comment by karlludwigweise** [comment]
I can‘t find it in that repo. Should it be copied manually?

**Comment by bexsoft** [comment]
Hi @karlludwigweise!

I'm trying to reproduce the issue but unfortunately I wasn't able to get the same result, In this case, would you please tell us more information about your configuration?:

- OS & Web browser Versions
- Are you working on a Baremetal / K8s instance? 
- Are you working on Distributed mode?
- The bucket is versioned?

<img width="1485" alt="Screen Shot 2021-11-29 at 20 47 21" src="https://user-images.githubusercontent.com/33497058/143977313-80b87978-6dfb-4978-8741-7bccf1f81f42.png">
<img width="1393" alt="Screen Shot 2021-11-29 at 20 47 12" src="https://user-images.githubusercontent.com/33497058/143977315-7ca591a6-8eb8-4a0a-9a9e-c29f63ddca7b.png">

**Comment by karlludwigweise** [comment]
Hey @bexsoft,

this is a screenshot of the actual issue:

<img width="608" alt="Bildschirmfoto 2021-12-01 um 19 01 12" src="https://user-images.githubusercontent.com/11831566/144288545-c7bf08e5-f9f8-451b-b215-56ee21b84d6e.png">

As for your questions:

- OS & Web browser Versions: macOS latest in all browsers
- Are you working on a Baremetal / K8s instance?: No. I'm using the docker official image on debian 10.
- Are you working on Distributed mode? Yes.
- The bucket is versioned? No.

The bucket also has a quota, but that should not be the issue. I think maybe the distributed mode is an issue.

When I look at the front-end request that fetches the data from `/api/v1/buckets/{bucket-name}/objects?prefix={hash}` the directory that should not be shown is part of the response.

**Comment by dvaldivia** [comment]
@karlludwigweise are you running the console on `standalone` mode?

**Comment by dvaldivia** [comment]
Cannot replicate, are you sure it's not some software creating a `.sync` folder inside that `.sync` folder? can you navigate to it? 
<img width="750" alt="Screen Shot 2021-12-01 at 10 39 03 AM" src="https://user-images.githubusercontent.com/18384552/144293919-bda85551-e6dd-47fb-a846-d85bc4662d7a.png">

**Comment by karlludwigweise** [comment]
I just used the `.sync` directory for the screenshot to not spoil my metadata over the open internet. The issue occurs on any directory.

I can't really test which version this was introduced in, because there is no going back from my current version.

I'm not running it in standalone mode. There are four servers.

**Comment by karlludwigweise** [comment]
And most importantly I cannot navigate to the ghost directory. The front-end is not even sending a request out.

**Comment by bexsoft** [comment]
Hi @karlludwigweise,

Doing some reviews, there was an issue with Rewind functionality quite similar to this issue, this is being fixed in https://github.com/minio/console/pull/1297#pullrequestreview-825884919

Are you using rewind to navigate through the folders?

**Comment by karlludwigweise** [comment]
@bexsoft this sounds a lot like it, but I am not using rewind/versioning.

**Comment by bexsoft** [comment]
@karlludwigweise Yesterday we released new versions for MinIO & console, Would you please help us to check if issue is still present in the latest version?

Thank you!

**Comment by karlludwigweise** [comment]
@bexsoft I just updated. This issue is fixed for newly created directories. Great! :)
But, it persists for already created directories. Is there a way to re-inizialize those?
