### ISSUE TITLE
Login with local credentials when openid enabled

### ISSUE THREAD

**Issue by iFrozenPhoenix** [minio/console#1260]
When an openid provider is set the credentials fields are no longer visible on the ui, so no login
with local credentials is possible.
Via mc local logins are still usable.

Also I'm not able to create users with a admin user logged in via sso (Permission denied). The assigned role is consoleAdmin.

In my opinion it would be the best solution to have the credentials fields still visible and the sso button, if openid is configured.

Or am I something missing?

**Comment by prakashsvmx** [comment]
Please refer here: 

https://docs.min.io/minio/baremetal/security/openid-external-identity-management/external-authentication-with-openid-identity-provider.html#minio-external-identity-management-openid

**Comment by iFrozenPhoenix** [comment]
@prakashsvmx thank you for your answer, but the docs are not correct in this point. I'm still able to create local users via mc and I'm able to login with them via mc and other services, so the internal IDP is not disabled in my opinion, it's just hidden from the UI.
But some limitations are set, otherwise I would be able to create users via the UI.
This is a something inconsistent behavior and due to the description in the docs it's also a security risk (They say if one configures sso the internal IDP is disabled, but it is not).
Please check

**Comment by harshavardhana** [comment]
> @prakashsvmx thank you for your answer, but the docs are not correct in this point. I'm still able to create local users via mc and I'm able to login with them via mc and other services, so the internal IDP is not disabled in my opinion, it's just hidden from the UI. But some limitations are set, otherwise I would be able to create users via the UI. This is a something inconsistent behavior and due to the description in the docs it's also a security risk (They say if one configures sso the internal IDP is disabled, but it is not). Please check

You can create, that has always been possible. It is present such the in future multiple IDPs can be supported.

Right now however console doesn't allow that.

**Comment by wokalski** [comment]
@harshavardhana can we rely on this behavior? We're defining IDP users in IaaC and they are used for programmatic access. It's a significant piece of our infrastructure. Can we rely on it?

**Comment by harshavardhana** [comment]
> @harshavardhana can we rely on this behavior? We're defining IDP users in IaaC and they are used for programmatic access. It's a significant piece of our infrastructure. Can we rely on it?

?

**Comment by iFrozenPhoenix** [comment]
Sorry,  what's your  question  exactely ?

Mit freundlichen Grüßen / Kind regards
________________________________

**Comment by wokalski** [comment]
> You can create, that has always been possible. It is present such the in future multiple IDPs can be supported.
> Right now however console doesn't allow that.

Can we rely on logging in using the internal IDP users being possible? We use OIDC for human users and internal IDP for "m2m" users. Can we rely on that without worrying about this support for internal IDP when using OIDC disappearing?
