### ISSUE TITLE
Web console can't download objects with a white space in the filename

### ISSUE THREAD

**Issue by ppizzo** [minio/console#1262]
# Expected Behavior
The web console should be able to download every file.

# Current Behavior
The web console is not able to download files with a white space in the pathname, i.e. a white space in the filename or in a parent directory name. The downloaded file is empty even if the backend API HTTP status code is `200`. The server logs the following message: `The specified key does not exist.`
Minio from command line works fine.

# Steps to Reproduce (for bugs)
* Create a bucket and upload the same not empty file twice with different filenames, one of them with a white space in the name.
* Open the web console and download both files: the file with white spaces in the name will be downloaded with size 0

# Your Environment
Minio running in Docker container on `arm64` architecture, using `latest` tag
Minio version `RELEASE.2021-11-24T23-19-33Z`

**Comment by bexsoft** [comment]
Hi @ppizzo!, Thank you for your message.

This issue was detected and fixed in https://github.com/minio/console/pull/1235, It will be implemented in the next release of console. Will keep this issue opened until new version is released

**Comment by ppizzo** [comment]
Many thanks @bexsoft!

**Comment by bexsoft** [comment]
New console version is released: https://github.com/minio/console/releases/tag/v0.12.6 

Closing this issue accordingly, Please reopen if it is still present in a new version

**Comment by ppizzo** [comment]
It works fine, many thanks for your quick support.
