### ISSUE TITLE
Policy "public get, no listing" in predefined bucket policies list

### ISSUE THREAD

**Issue by makkarpov** [minio/console#1263]
Public policy is very convenient for "file sharing" buckets, but it has a downside: it allows anyone to list the contents. There are situations where you want to allow someone to download a file only if they know exact URL, and disallow object listing.

So, **the suggestion**: add policy "Public read; no listing" to predefined policy list in console.

```json
{
  "Id": "public-read-all",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Action": [
        "s3:GetObject",
        "s3:GetObjectVersion"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::*",
      "Principal": "*"
    }
  ]
}
```

**Comment by Alevsk** [comment]
Hi @makkarpov you can achieve this via share object, ie:

<img width="804" alt="Screen Shot 2021-12-01 at 11 07 40" src="https://user-images.githubusercontent.com/1795553/144297939-25992545-1e87-4745-b238-2e239ad1a8ac.png">

That will generate a pre-signed URL that will allow access to an specific file

**Comment by makkarpov** [comment]
I know about presigned URLs. 

They expire. There is also a bug which invalidates them way sooner than UI counter says (few hours or even tens of minutes), because signing key expires somehow, but this is not a topic of this ticket. Public-but-unlisted URLs do not expire at all.

They are huge. Public URLs can be as short as you want, especially if you have short base domain name (e.g. we have just six character top domain). Unless you process them with something like bit.ly, they are looking very ugly.

Presigned URLs are great thing for API access, microservice interaction and so on, but not for humans.
