### ISSUE TITLE
Can Console 'use/understand' wildcard actions?  Or does it need explicit actions?

### ISSUE THREAD

**Issue by aglahe** [minio/console#1267]
Console v0.12.5

Given the below Policy on a bucket, it appears as though a non consoleAdmin user cannot see the objects in the test bucket..
```
{
   "Version" : "2012-10-17",
   "Statement" : [
      {
         "Effect" : "Allow",
         "Action" : [ "s3:Get*", "s3:List*", "s3:Put*", "s3:Delete*" ],
         "Resource" : ["arn:aws:s3:::test","arn:aws:s3:::test/*"]
      }
   ]
}
```
They see the bucket, and they have the "Browse" button...but when they hit the Browse button into this specific bucket, they get: 

**This location is empty, please try uploading a new file**

even though there are objects in that bucket. However, explicitly adding:
```
            "s3:ListBucket",
            "s3:ListBucketMultipartUploads",
            "s3:ListMultipartUploadParts",

```
Then allows this non-admin user to see objects in the bucket.

**Comment by user173193** [comment]
This does not appear to be working yet. I'm running into the same issue. Also see https://github.com/minio/console/issues/1209
