### ISSUE TITLE
Console : Buckets : browse : not working when lots of directories

### ISSUE THREAD

**Issue by christopheblin** [minio/console#1282]
## Expected Behavior
I have a bucket with 25K directories (note : this is in azure storage)

The browser of the console tries to download ALL of them in one HTTP call, which takes more than a minute (and sometimes fails completely...)

I dont expect to display them when I browse the bucket, however I expect to be able to search them 

## Possible Solution

There could be some way to indicate to minio that some buckets are going to be big and in this case to not display all the objects.

In this case, the search of objects should also directly query the storage (it should not do the search in the browser)

## Context

The underlying storage contain the log files of some batch jobs

## Regression

No, I think the browser has always tried to download all the objects of the bucket

## Your Environment

* Version used (`minio --version`): docker image minio/minio:RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration: azure gateway
* Operating System and version (`uname -a`): see docker

**Comment by christopheblin** [comment]
> S3 does not offer pagination for bucket listings.

I am not sure I am following you here : https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax

max-keys can paginate (in addition to continuation-token)

so you could ask for 1000 items and then provide a "load all objects" ?

However, I see that the search is not correctly handled in the API, so you do not have other choice than loading all the objects and then searching :(

**Comment by klauspost** [comment]
@christopheblin Ah, you mean prefixes inside a bucket and not buckets. 

Pretty much a duplicate of https://github.com/minio/console/issues/943

**Comment by christopheblin** [comment]
@klauspost exaclty, I will close this one and track the progress on the other one :+1:
