### ISSUE TITLE
Console "Upload" button gone if PutObject Resource isn't full wildcard

### ISSUE THREAD

**Issue by enra64** [minio/console#1287]
Hey, I'm trying to only allow my users to upload files to a subfolder corresponding to their name in the `config` bucket, using a policy like in the following example. However, that hides the upload button, which is necessary to keep this easy for us, even though errors might occur with missing permissions.

# Prefix Policy Example
### Policy
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::study-configs/${aws:username}/*"
            ]
        }
    ]
}
```

### Resulting UI

![prefix-policy-no-upload-button](https://user-images.githubusercontent.com/7622426/144575602-d999f460-76d4-4421-a318-1ea19f968a3b.png)

# Wildcard Policy Example

However, this hides the upload button that is available if using a wildcard resource like in the following policy:

### Policy
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::study-configs/*"
            ]
        }
    ]
}
```

### Resulting UI

![image](https://user-images.githubusercontent.com/7622426/144575355-a4648f9b-78ec-4702-bbc9-54b295514a0a.png)

Is this intended behaviour, or is there maybe a workaround using the existing policies that I haven't found? Best, Arne

**Comment by harshavardhana** [comment]
which version of console is this? @enra64

**Comment by enra64** [comment]
So this is running on a standalone minio (for testing) that I downloaded yesterday, version should be `2021-11-24T23:19:33Z`:

![image](https://user-images.githubusercontent.com/7622426/144579361-ca5cdb24-7cb4-41e2-bc37-bc9eb0a6af11.png)

**Comment by enra64** [comment]
Is there any update on this? Seems to be less bad than #1315 but still in the same vein - the console doesn't match the API very well :(
