### ISSUE TITLE
Session ID is not invalidated on logout

### ISSUE THREAD

**Issue by boettcherr** [minio/console#1290]
### Expected Behavior
When a user logs out, the session should be completely deleted on the server side.

### Current Behavior
When a user logs out, their session ID is not invalidated on the server side.

### Possible Solution
If the logout button is used, the corresponding session should be completely deleted on the server side. The deletion of the session must be signalled to the client so that the client also discards the session information and can obtain a new session ID the next time the application is accessed.

### Steps to Reproduce

1.  Log in to console
2. copy session cookie
3. logout of console
4. set previously saved cookie
5. access console without login again

### Your Environment
minio version RELEASE.2021-11-24T23-19-33Z

**Comment by Alevsk** [comment]
@boettcherr this is a known limitation of how STS works, when a user authenticate in console via user credentials MinIO will issue sts credentials (that will expire by default in 1hr). Console is stateless so we proceed to encrypt the STS credentials on a session cookie and return it to the user, console doesn't have anything in memory regarding user credentials/session so we cannot delete anything server side.

Same goes for MinIO, issued sts credentials cannot be expired before the expiration time contained in the sts credentials themselve.

cc @harshavardhana
