### ISSUE TITLE
How to create Service Account for LDAP users? [Question]

### ISSUE THREAD

**Issue by echupriyanov** [minio/console#1291]
Hi!

Is it possible to create user's Service Account through Minio Web Console, with LDAP Identity enabled?

I'm running Minio version 2021-11-24T23:19:33Z
I can log into the Console using my LDAP credentials with consoleAdmin policy attached to the corresponding group.
But when I try to create Service Account, I'm getting Access Denied error (see attached screenshot). Is this is intended behavior?

What I'm trying to achieve is to let my LDAP users possibility to generate Servic
e Accounts for themselves, so they can use traditional S3 tools to access buckets.

<img width="1454" alt="Снимок экрана 2021-12-03 в 16 48 06" src="https://user-images.githubusercontent.com/2070616/144613499-b508c7e9-40e4-4e49-be69-185ddcaec541.png">

**Comment by echupriyanov** [comment]
More detailed screenshot on browser side:

<img width="1454" alt="Снимок экрана 2021-12-06 в 14 16 28" src="https://user-images.githubusercontent.com/2070616/144836988-6908b9a9-52a6-4bf8-b162-661fec5ae1b3.png">

**Comment by vadmeste** [comment]
@echupriyanov can you show what's the exact error that you have ? If you see there is 'Details >' that you can expand

**Comment by echupriyanov** [comment]
@vadmeste Its the same 'Access denied' error in the Details

**Comment by vadmeste** [comment]
@echupriyanov I think it should work. I will test this one and update you.

**Comment by wiegandsh** [comment]
@vadmeste: in our environment, we have exactly the same issue.
