### ISSUE TITLE
For setups that are not distributed, Heal page renders empty

### ISSUE THREAD

**Issue by kaankabalak** [minio/console#1299]
For setups that are not distributed, the heal page renders empty due to the following code on portal-ui/src/screens/Console/Heal/Heal.tsx:255-257:

```
  if (!distributedSetup) {
    return null;
  }
```

![Screen Shot 2021-12-07 at 2 10 40 AM](https://user-images.githubusercontent.com/27314853/145009872-dbf2ee20-6a9c-4be9-93c4-0523cc91f073.png)

We might want to redirect the user if this feature isn't available on non-distributed setups. Alternatively, we can either render a page communicating that this feature is not available for non-distributed setups or not display/disable this option on the sidebar/Tools page links.

**Comment by kaankabalak** [comment]
The Tools page now appears on the sidebar, however the heal page is still rendering empty for me.

**Comment by bexsoft** [comment]
This may get fixed in https://github.com/minio/console/pull/1288, @Alevsk Would you please help us to confirm?

**Comment by kaankabalak** [comment]
> This may get fixed in #1288, @Alevsk Would you please help us to confirm?

My setup is running MinIO in fs mode, I think this is probably why the Heal page didn't get rendered. Will check and keep you updated.

**Comment by kaankabalak** [comment]
On the branch for #1288, as both the admin user and a user that has Heal policy applied; when I try to navigate to the heal page, I get redirected to the Buckets page.

**Comment by kaankabalak** [comment]
It seems to be caused by [this piece of code](https://github.com/minio/console/blob/master/portal-ui/src/screens/Console/Heal/Heal.tsx#L255-L257) in setups that are not distributed mode, maybe we might want to redirect the user or use a cleaner way to communicate to the user that the feature isn't available for setups that are not distributed.

**Comment by harshavardhana** [comment]
> It seems to be caused by [this piece of code](https://github.com/minio/console/blob/master/portal-ui/src/screens/Console/Heal/Heal.tsx#L255-L257) in setups that are not distributed mode, maybe we might want to redirect the user or use a cleaner way to communicate to the user that the feature isn't available for setups that are not distributed.

That entire menu should go away or be redirected to dashboard as a missing page.

**Comment by dvaldivia** [comment]
@kaankabalak @bexsoft we should add a `<HelpBox />` to at least explain why this is a distributed mode only feature

**Comment by dvaldivia** [comment]
@harshavardhana we can take the opportunity to let them see that there's more features on a distributed setup, so rather than disappearing it we can take them to the docs

**Comment by harshavardhana** [comment]
> @harshavardhana we can take the opportunity to let them see that there's more features on a distributed setup, so rather than disappearing it we can take them to the docs

That will also work, show them that this is available as part of distributed setup so please proceed to install distributed setup instead.

**Comment by bexsoft** [comment]
Yes, the help box is a better approach, will implement accordingly

**Comment by bexsoft** [comment]
Part of this is fixed in https://github.com/minio/console/pull/1313

**Comment by bexsoft** [comment]
Will close as https://github.com/minio/console/pull/1313 and https://github.com/minio/console/pull/1288 are merged. Please re-open if issue is still present
