### ISSUE TITLE
Running the console on the same host.domain, but using a /path.

### ISSUE THREAD

**Issue by darkl0rd** [minio/console#1312]
The old Minio would have the console embedded, whereby the console was accessible at /minio.
In the new setup, the console listens on a different port (9001) and seemingly requires it's own sub-domain (e.g. console.my.domain.com).

I have been fiddling with a reverse proxy (traefik) trying to make the new console available under a path (/console, /minio) rather than having to run it on it's own subdomain, but have been unsuccessful. 

Should this be possible? Is there a variable to define the /path that I'm overlooking? Any suggestions or tips are most welcome.

See also https://github.com/minio/minio/issues/12660, in which the last request was exactly this, but sadly that ticket got closed without providing an answer to that question.

Thanks.

**Comment by prakashsvmx** [comment]
https://github.com/minio/console/pull/1247  - could you please have a look ?

**Comment by darkl0rd** [comment]
> #1247 - could you please have a look ?

That’s perfect, sorry I overlooked/missed that issue. Thanks 👍🏻
