### ISSUE TITLE
getting buckets list slow

### ISSUE THREAD

**Issue by zj5220924** [minio/console#1323]
there are 1024 buckets in my minio server， it's very slow when I show buckets in web console，Has anyone had the same issue?

**Comment by zj5220924** [comment]
minio -v
minio version RELEASE.2021-12-10T23-03-39Z

**Comment by dvaldivia** [comment]
This is sort of expected when having a large number of buckets, we are thinking in introducing pagination to the listing of buckets to deal with this.

What is your use case for having so many buckets if you don't mind me asking

**Comment by harshavardhana** [comment]
> This is sort of expected when having a large number of buckets, we are thinking in introducing pagination to the listing of buckets to deal with this.

Mainly this is just poor hardware here.  Even our https://play.min.io can list 1000 buckets easily with local drives.

**Comment by harshavardhana** [comment]
Perhaps running MinIO on some NFS/Networked like mounts

**Comment by harshavardhana** [comment]
actually, this is just a console UI issue seen at https://play.minio.io right now @dvaldivia 

```
~ mc admin trace -a --funcname admin.* play/                                    
2021-12-15T13:01:29:000 [200 OK] admin.AccountInfo play.min.io:9000/minio/admin/v3/accountinfo 147.75.201.93     229.722ms    ↑ 98 B ↓ 484 KiB
2021-12-15T13:01:29:000 [200 OK] admin.AccountInfo play.min.io:9000/minio/admin/v3/accountinfo 147.75.201.93     237.177ms    ↑ 98 B ↓ 484 KiB
2021-12-15T13:02:04:000 [200 OK] admin.AccountInfo play.min.io:9000/minio/admin/v3/accountinfo 147.75.201.93     233.78ms     ↑ 98 B ↓ 484 KiB
2021-12-15T13:02:14:000 [200 OK] admin.AccountInfo play.min.io:9000/minio/admin/v3/accountinfo 147.75.201.93     348.147ms    ↑ 98 B ↓ 484 KiB
```

Relevant API calls return fine its the browser that is slow to render and allocate the Bucket UI

**Comment by dvaldivia** [comment]
yeah, this is a render problem @harshavardhana , we will fix it

**Comment by zj5220924** [comment]
Is there any update on this?

**Comment by prakashsvmx** [comment]
> Is there any update on this?

This is in the queue. We Will work on it soon.

**Comment by AshrafulalamRasel** [comment]
@dvaldivia @prakashsvmx I have faced another problem similar to this. I've a bucket contains thousands of files. I want to fetch all of them with pagination. But according to your documentation I don't find any solutions. Please let me know if you have any.

**Comment by prakashsvmx** [comment]
@AshrafulalamRasel  listObjects api returns only 1000 entries as per s3 spec. the next page needs to be queried with pagination . 

E.g : https://docs.min.io/docs/golang-client-api-reference#ListObjects

other skds do have the api implementation.
