### ISSUE TITLE
Upload and delete object permissions with minio policy on S3 folder doesn't work

### ISSUE THREAD

**Issue by boyka2405** [minio/console#1325]
## Expected Behavior

I am running minio as a gateway for s3. I have enabled openid authentication with an identity provider. The login through openid works fine. I create a IAM policy through minio console which allow the user logged in through openid and have the required claim which map it to the policy created inside minio. The login works fine and the user is able to login with the permissions I give in policy. The policy provides the user access to only one folder in s3 bucket in AWS. But it doesn't work as expected. after login I am able to list only in the desired folder but do not see any option either to upload object in folder or delete the object option

## Current Behavior

After login I am able to only list objects in desired folder myfolder but unable to upload and delete objects from there

## Steps to Reproduce (for bugs)

1)  Run minio as s3 gateway and configure  etcd and openid .  
          2) Configure identity provider so that user is able to login through it from minio UI
          3) Create IAM policy like below 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-minio-bucket/*"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "",
                        "myfolder/*"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::my-minio-bucket/myfolder/*"
            ]
        }
    ]
}
```

4) login with SSO option in minio UI.
5) see the access on myfolder. Only able to list in my-minio-bucket/myfolder and not able to delete and upload there

## Your Environment

* Version used (`minio --version`): RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration: Minio as s3 gateway. Connected to AWS s3 bucket in backend
* Operating System and version (`uname -a`): Running minio as a pod in kubernetes

**Comment by boyka2405** [comment]
@harshavardhana - I also tried to use client applications [web-identity.go](https://github.com/minio/minio/blob/master/docs/sts/web-identity.md) mentioned in minio documentation to make sure my IAM policy is correct. I wanted to fetch the temporary credentials (access key id and secret acccess key) from identity provider. But this application doesn't work on my local. 

I am running below command as mentioned in documentation :

`go run web-identity.go -cid <client-id>` -csec <client-secret> -config-ep "https://<idp_url>/auth/realms/<relam_name>/.well-known/openid-configuration" -sts-ep http://localhost:8080`


I believe above command should open a web page at http://localhost:8080 which redirects me to identity provider url and as an output I should get temporary credentials either in browser or in my local cmd but the output I get is as follows

`2021/12/15 11:38:08 listening on http://:8080/`

Somehow it is not able to connect to identity provider. I might be missing something. Could you please let me know how to use this application?

**Comment by boyka2405** [comment]
@harshavardhana @Alevsk @dvaldivia -  I was wondering if you could help me understand this behavior of minio UI. Is it a feature that you are looking to add in future implementation ? Is there some way to test the IAM policy created in minio through openid credentials from some application ?

**Comment by Alevsk** [comment]
Tested using latest code in master and the problem doesn't exist anymore
