### ISSUE TITLE
only a single policy may be specified here

### ISSUE THREAD

**Issue by wuhlcom** [minio/console#1364]
API: InfoCannedPolicy()
 Time: 08:27:14 UTC 01/05/2022
 DeploymentID: c1758167-4426-454f-9aae-5c3dfdf6df64
 RequestID: 16C752710E74359D
 RemoteHost: 147.75.201.93
 UserAgent: MinIO (linux; amd64) madmin-go/0.0.1
 Error: Only a single policy may be specified here. (*errors.errorString)
        7: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
        6: cmd/admin-handler-utils.go:181:cmd.toAdminAPIErrCode()
        5: cmd/admin-handler-utils.go:168:cmd.toAdminAPIErr()
        4: cmd/admin-handlers-users.go:1202:cmd.adminAPIHandlers.InfoCannedPolicy()
        3: cmd/http-tracer.go:171:cmd.Trace()
        2: cmd/handler-utils.go:375:cmd.httpTraceHdrs.func1()
        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

**Comment by wuhlcom** [comment]
console:
    image: minio/console
    networks:
      - minio_distributed
    command: server
    environment:
      - "CONSOLE_PBKDF_PASSPHRASE=demoapp"
      - "CONSOLE_PBKDF_SALT=demoapp"
      - "CONSOLE_MINIO_SERVER=http://minio{1...4}:9000"
    ports:
      - "9911:9090"

**Comment by wuhlcom** [comment]
![image](https://user-images.githubusercontent.com/12484119/148200973-f2f23c4b-acad-4178-a679-ccdb362222f4.png)

**Comment by harshavardhana** [comment]
@wuhlcom please report things properly.

**Comment by harshavardhana** [comment]
You cannot use the latest console with such an old MinIO release. Please upgrade your MinIO server.
