### ISSUE TITLE
Add VictoriaMetrics support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [minio/console#1373]
VictoriaMetrics is a horizontally scalable prometheus alternative. Primarily It is consists from 3 parts, select, insert and storage.

1. `Select` has a prometheus api + PromQL support:

```
http://some-select-service:8481/select/0/prometheus
```

2. But console checks health url with simple concatenation:
https://github.com/minio/console/blob/c90094e328520cc093b20c085ff23793b53baf3f/restapi/admin_info.go#L929

3. So if i set `MINIO_PROMETHEUS_URL` as `.../select/0/prometheus` prometheus health check(`.../select/0/prometheus/-/healthy`) will not pass

4. VM Select has a `/-/healthy` route

## Solution
1. Remove `MINIO_PROMETHEUS_URL` route + query inside prometheus health check
2. Concatenate with `/-/healthy` - now it is root
3. Use full provided `MINIO_PROMETHEUS_URL` inside `getWidgetDetails` and friends

**Comment by harshavardhana** [comment]
@sergeyshaykhullin are you saying that `/-healthy` shouldn't be used with the FULL Prometheus URL?

**Comment by sergeyshaykhullin** [comment]
@harshavardhana Yes, seems like i overcomplicated 😅

**Comment by bexsoft** [comment]
Added Fall back validation to root URL in case full URL returns error. We want to prioritize the validation over the full URL in case a user has prometheus running inside a subpath
