### ISSUE TITLE
App crashes when a user with Bucket Read policies clicks on Browse button for a Bucket

### ISSUE THREAD

**Issue by kaankabalak** [minio/console#1390]
As stated in the title, when a user with the following policy clicks on the Browse button for a Bucket, the app crashes:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": [
				"s3:ListMultipartUploadParts",
        "s3:ListBucketMultipartUploads",
        "s3:ListBucket",
        "s3:HeadBucket",
        "s3:GetObject",
        "s3:GetBucketLocation"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:s3:::*"
			],
			"Sid": ""
		}
	]
}
```

The errors displayed are as follows:

![Screen Shot 2022-01-12 at 6 53 00 PM](https://user-images.githubusercontent.com/27314853/149257506-5d93d0b4-cd1b-4492-8baa-a1c0c7ed1120.png)
![Screen Shot 2022-01-12 at 6 53 19 PM](https://user-images.githubusercontent.com/27314853/149257508-b6121344-28cf-4eb5-868b-787e862dfdea.png)
![Screen Shot 2022-01-12 at 6 53 38 PM](https://user-images.githubusercontent.com/27314853/149257509-1b8a4969-2bcd-4117-92ff-2e81d7286375.png)

After further investigation, it seems like the extra `input` element here is causing an error while the SecureComponent is rendering, and seems like we can remove it as we already have the input element outside the SecureComponent:
https://github.com/minio/console/blob/1871f2bf9e2bc63a222344b853756fd2babcfc72/portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx#L1222-L1229

**Comment by prakashsvmx** [comment]
@kaankabalak i have removed it here :

https://github.com/minio/console/pull/1392/files#diff-66924f63567a48ea96c3be6d59ed67b5ee3816afe741dcd4284d0ed159c1fac8L1231

 thank you.
