### ISSUE TITLE
Wrong button style

### ISSUE THREAD

**Issue by AlexZIX** [minio/console#1405]
When I click to the "Add Access Rule" button in access rules page of bucket management modal window shows. It have to buttons - clear and save. Seems that styles doesn't applied to the clear button - it looks like standard html button without styles. But may be it's just a point of view of your web designer.

**Comment by prakashsvmx** [comment]
Thank you @AlexZIX .
The UX principle is to have solid fill for Primary button and Just outline for the secondary button.  
The UX is also evolving. we value the feedback and incorporate the common best practices.

Closing this as it does not require a fix.
