### ISSUE TITLE
Support streaming output when browsing the files

### ISSUE THREAD

**Issue by cobolbaby** [minio/console#1419]
![2022-01-20 15-01-29屏幕截图](https://user-images.githubusercontent.com/11460848/150289492-54aa03b5-4107-4ab6-83fd-80a4b0db4093.png)

**Comment by cobolbaby** [comment]
Just like `mc ls`

**Comment by dvaldivia** [comment]
@cobolbaby how many files do you have on this bucket? the only problem with streaming would be the ordering I guess, but also list objects paginates 1,000 object per page

**Comment by cobolbaby** [comment]
> how many files do you have on this bucket? 

over 50000

>  the only problem with streaming would be the ordering I guess, but also list objects paginates 1,000 object per page

In fact, for the large folders, sorting is not necessary.

**Comment by harshavardhana** [comment]
duplicate of #943
