### ISSUE TITLE
Unable to upload the same object ( overwrite) again 

### ISSUE THREAD

**Issue by prakashsvmx** [minio/console#1421]
#### Steps
Create a  bucket ( versioned) for easy test and verification.

Upload an object  verify it with mc

try to upload the same object again. 

#### Expected:

the upload should be successful and two versions should be created.

#### Actual:
upload popup opens -> Select File -> Closes - upload progress is not shown
(Verify with mc that two versions are not created ! )

**Comment by bexsoft** [comment]
Fixed in https://github.com/minio/console/issues/1421
