### ISSUE TITLE
integration with openid connect not working

### ISSUE THREAD

**Issue by jpchev** [minio/console#1422]
I've set up the openid connect authentication, when I use the embedded console I see the button to login via oidc,
but I don't see that button in the standalone minio console.

Could you please help?

**Comment by harshavardhana** [comment]
> I've set up the openid connect authentication, when I use the embedded console I see the button to login via oidc,
> but I don't see that button in the standalone minio console.

You shouldn't be running standalone console when you are running embedded console? why are you doing this?

**Comment by jpchev** [comment]
I don't run the two together, just I tried the standalone and then deleted and tried the embedded.
Could you please help ? Is the standalone console supposed to work with openidc?

Also, how comes that there is an embedded and a standalone console?
How to switch off the embedded then?
I don't see this in the doc

**Comment by harshavardhana** [comment]
> I don't run the two together, just I tried the standalone and then deleted and tried the embedded. Could you please help ? Is the standalone console supposed to work with openidc?
> 
> Also, how comes that there is an embedded and a standalone console? How to switch off the embedded then? I don't see this in the doc

Don't use standalone that's all. 

> Also, how comes that there is an embedded and a standalone console?

Console is embedded to MinIO - they are just separate projects.

**Comment by jpchev** [comment]
the benefit of using the standalone console is that I managed to access it behind a reverse proxy (nginx) and to mount it on a non-root URL (ex. https://myminio.blabla.com/minio-console) whereas it seems the same cannot be done with the embedded (it seems it works only with root URL)

**Comment by harshavardhana** [comment]
> the benefit of using the standalone console is that I managed to access it behind a reverse proxy (nginx) and to mount it on a non-root URL (ex. https://myminio.blabla.com/minio-console) whereas it seems the same cannot be done with the embedded (it seems it works only with root URL)

Yes, subpath will be supported in the future for Embedded console @jpchev you shouldn't use standalone and we are not going to document running standalone instances of console sorry!

**Comment by jpchev** [comment]
ok, thanks
