### ISSUE TITLE
Downloading produces an HTML content instead of a file

### ISSUE THREAD

**Issue by Haarolean** [minio/console#1429]
Downloading any file downloads this file (right name, right extension) with some HTML of minio console inside.

Version
2022-01-08T03:11:54Z

**Comment by vadmeste** [comment]
@Haarolean I am not able to reproduce. Can you give steps to reproduce this ?

**Comment by Haarolean** [comment]
@vadmeste There's nothing special -- I'm trying to upload a file to a bucket and then trying to download it. Also tried this via a public bucket. How can I help investigating this?

**Comment by prakashsvmx** [comment]
@Haarolean  Please share logs/trace screenshots if any.  also do you have any load balancer/proxy setup which could cause this?

**Comment by Haarolean** [comment]
Hey folks, thank you for the quick reply.

There are no related logs/errors.
Yes, actually minio is behind a proxy and there's a problem with the links. Minio console generates a link like this:
`http://minio:9000/bucket/%3C...%3E`
which obviously won't work because it's a docker's hostname. I've replaced it with my domain name manually which got me into the described issue.
I realised that minio console generates a link for minio itself, but considering my replacement that link became a console's link.
I tried exposing minio port directly right now and I see the following error:
```
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
```

So, two questions:
1. Sorry if that's a common question, but I don't remember seeing any info regarding this when I set the minio up and couldn't quickly google anything right now: How do I specify a domain to use when generating such links? So I don't have to edit it manually.
2. Do I have to download the file via minio itself? Can't I do this via console?
3. How do I fix the `SignatureDoesNotMatch` issue?

**Comment by prakashsvmx** [comment]
@Haarolean 
Please explore the environment variables documented at:
https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#minio-console

**Comment by Haarolean** [comment]
I just did. 
I already have these variables set for `minio/console`:
```    environment:
      CONSOLE_PBKDF_PASSPHRASE: ${CONSOLE_PBKDF_PASSPHRASE}
      CONSOLE_PBKDF_SALT: ${CONSOLE_PBKDF_SALT}
      CONSOLE_MINIO_SERVER: "http://minio:9000/"
```
Variable like `CONSOLE_MINIO_SERVER` is not described anyware at the page you've provided (I've checked both minio and console pages), but authentication doesn't work without this variable.
I also added these:
```
      MINIO_BROWSER_REDIRECT_URL: "https://external.domain/"
      MINIO_SERVER_URL: "http://minio:9000/"
```
These haven't changed anything.

**Comment by Haarolean** [comment]
This #13190 is a part of my problem.

So, turns out `CONSOLE_MINIO_SERVER` comes from docker hub [readme](https://hub.docker.com/r/minio/console), but is not described anywhere else.

I've got these settings:
```
      CONSOLE_MINIO_SERVER: "http://minio:9000/"
      MINIO_SERVER_URL: "http://external.domain/"
      MINIO_BROWSER_REDIRECT_URL: "https://external.domain/"
```
Generated URLs still have `minio:9000` in them. Trying to access them via proxy produces `SignatureDoesNotMatch`.
Tried the same with `curl` from console container, works fine.

So, one problem and one question left.
1. Am I missing something to be able to access the files via proxy? I have a bunch of headers forwarding set up:
```
X-Real-IP  
X-Forwarded-For     
X-Forwarded-Proto  
Host    
X-Forwarded-Host     
X-Forwarded-Server 
X-Forwarded-Port
```
2. How do I generate URLs with an external domain? Is there yet another env variable for this or is this a bug?

Thanks

**Comment by Haarolean** [comment]
Any help on this? Still doesn't work with the latest version. There's no way to share the file via static link as far as I see.

**Comment by harshavardhana** [comment]
> This [issue](https://github.com/minio/minio/issues/13190) seems related
> 
> So, turns out `CONSOLE_MINIO_SERVER` comes from docker hub [readme](https://hub.docker.com/r/minio/console), but is not described anywhere else.
> 
> I've got these settings:
> 
> ```
>       CONSOLE_MINIO_SERVER: "http://minio:9000/"
>       MINIO_SERVER_URL: "http://external.domain/"
>       MINIO_BROWSER_REDIRECT_URL: "https://external.domain/"
> ```
> 
> Generated URLs still have `minio:9000` in them. Trying to access them via proxy produces `SignatureDoesNotMatch`. Tried the same with `curl` from console container, works fine.
> 
> So, one problem and one question left.
> 
> 1. Am I missing something to be able to access the files via proxy? I have a bunch of headers forwarding set up:
> 
> ```
> X-Real-IP  
> X-Forwarded-For     
> X-Forwarded-Proto  
> Host    
> X-Forwarded-Host     
> X-Forwarded-Server 
> X-Forwarded-Port
> ```
> 
> 2. How do I generate URLs with an external domain? Is there yet another env variable for this or is this a bug?
> 
> Thanks

These settings are wrong

```
CONSOLE_MINIO_SERVER: "http://minio:9000/"
      MINIO_SERVER_URL: "http://external.domain/"
      MINIO_BROWSER_REDIRECT_URL: "https://external.domain
```

You should never set CONSOLE_ since that is internal ENV and is not honored since MinIO is embedding console UI.

Second your browser redirect URL should be towards Console UI endpoint that runs on a separate port.

**Comment by harshavardhana** [comment]
> Any help on this? Still doesn't work with the latest version. There's no way to share the file via static link as far as I see.

Mostly you have the same mistake and perhaps you have skipped this section entirely https://github.com/minio/minio#things-to-consider

**Comment by Haarolean** [comment]
@harshavardhana doesn't seem like I've skipped it. There's no chance I got an "internal" env variable from somewhere, I've followed docker images documentation months ago when I initially set it up, even before console was split apart from the minio image itself.
Since you're telling me using "CONSOLE_" vars is wrong, I've tried removing them aaand I can't even log in without them (`Post "http://localhost:9000/": dial tcp 127.0.0.1:9000: connect: connection refused`).
Considering the error message, that's wrong to assume minio should be available at localhost (it's another container).

**Comment by Haarolean** [comment]
`CONSOLE_MINIO_SERVER` variable is still listed [here](https://hub.docker.com/r/minio/console), which contradicts your words @harshavardhana

**Comment by Haarolean** [comment]
it's present even in [README](https://github.com/minio/console#start-console-service)

**Comment by dvaldivia** [comment]
@Haarolean `CONSOLE_MINIO_SERVER` is only honored if you start console by it self, if started from MinIO you need to use `MINIO_SERVER_URL`
