### ISSUE TITLE
Console redirecting incorrectly behind reverse proxy

### ISSUE THREAD

**Issue by samip5** [minio/console#1439]
Hi,

I'm trying to setup a console endpoint so that the UI is accessable, but when I set the mod_rewrite rules to proxy to the console port, the Console itself redirects incorrectly? What is the proper way to do this?

I'm using Apache2 to proxy with.

I have set the following ENV variables:
```
MINIO_BROWSER_REDIRECT_URL=https://<snip>.dev
CONSOLE_SECURE_TLS_REDIRECT="off"
MINIO_OPTS="--address :40099 --console-address :40100"
```
```
> GET / HTTP/2
> Host: <snipped>.dev
> user-agent: curl/7.79.1
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 301 
< date: Sun, 23 Jan 2022 08:00:25 GMT
< server: MinIO Console
< content-type: text/html
< location: ./
< vary: Accept-Encoding
< x-content-type-options: nosniff
< x-frame-options: DENY
< x-xss-protection: 1; mode=block
< content-length: 0
```

**Comment by harshavardhana** [comment]
> CONSOLE_SECURE_TLS_REDIRECT="off

This won't be honored - what is the purpose here ?

**Comment by samip5** [comment]
> > CONSOLE_SECURE_TLS_REDIRECT="off
> 
> This won't be honored - what is the purpose here ? 

I was trying to get it to redirect propeely to /login which it still doesn't do but I dis get it working despite that little inconvenience.

**Comment by bexsoft** [comment]
Closing this issue. If this is still an issue please reopen accordingly.
