### ISSUE TITLE
Add readiness and liveness endpoints to console

### ISSUE THREAD

**Issue by Alevsk** [minio/console#150]
We need to add a couple of new endpoints to check if the mcs service is ready and live by kubernetes following the standard: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes

**Comment by harshavardhana** [comment]
Is this done? @Alevsk

**Comment by Alevsk** [comment]
> Is this done? @Alevsk

Is not implemented yet, but would it be enough for k8s to hit `/api/v1/login` endpoint and if console is able to response that means we are ready to accept connections?

**Comment by harshavardhana** [comment]
> Is not implemented yet, but would it be enough for k8s to hit `/api/v1/login` endpoint and if console is able to response that means we are ready to accept connections?

There is no reason to have this IMO @Alevsk console is stateless - I don't know what value it brings if its ready or live.

**Comment by harshavardhana** [comment]
Closing this as it's not useful to have this functionality in console.
