### ISSUE TITLE
Query - Minio Console : Redirect after login

### ISSUE THREAD

**Issue by satyam-hv** [minio/console#1514]
Hi,
We are using minio as azure gateway. Also, we have integrated to authenticate via Keycloak. 
We are getting the "Login With SSO" button and after successful login user lands up in the first bucket.
Is there a way to ensure that after successful login we are redirected to a specific bucket and inside a specific folder. Furthermore it will be great if the exact folder can be made dynamic per request.
I found this PR and think this might be helpful - https://github.com/minio/console/pull/1227

Can someone please point me to the appropriate documentation for the above feature.

**Comment by Alevsk** [comment]
@satyam-hv that behavior is not supported right now, can you talk more about your use case?

**Comment by harshavardhana** [comment]
> Is there a way to ensure that after successful login we are redirected to a specific bucket and inside a specific folder. Furthermore it will be great if the exact folder can be made dynamic per request.

These are also scope creeps and feature creep - please use the way it is implemented.

**Comment by harshavardhana** [comment]
> I found this PR and think this might be helpful - #1227

This PR has nothing to do with landing on a specific bucket.

**Comment by satyam-hv** [comment]
> @satyam-hv that behavior is not supported right now, can you talk more about your use case?
@Alevsk  @harshavardhana  Thank you for the help.

We have a front end React web application and using keycloak for SSO. Users can see multiple projects on the screen. Each project is uniquely mapped to a specific folder in a predefined bucket in azure blob storage. We are using MinIO as a gateway for azure. We want to use the MinIO console browser for bulk upload of images for a particular project. Against each project we have "Bulk Upload" button. When the user clicks on this button we want the user to directly land on the mapped folder in minio console.

What we have achieved? - 
1. Creating the mapped folder using minio as an azure gateway 
2. Minio Integration with keycloak to ensure user does not have to use another set of credentials to login to minio

What is not achieved yet?
1. Do away with the "Login with SSO" page and directly land up inside minio buckets/folders
2. Redirect to the mapped folder after clicking on the "Bulk Upload" button.
