### ISSUE TITLE
Parsing time

### ISSUE THREAD

**Issue by T-M-A** [minio/console#1527]
Good day!
When setting up "Add Lifecycle Rule", an attempt to enter a date and save a date parsing error appears

```
Parsing time "2022-02-13T23:59:59Z": extra text: "T23:59:59Z"

```
Minio version:  RELEASE.2022-02-05T04-40-59Z
My OS: MacOS 12.2
Browser: Safari 15.3 (17612.4.9.1.5) 
Server: on this OS
Locale: LANG=ru_RU.UTF-8
startup script:
```bash
minio server /mnt/data{1...4} --console-address ":9001"
```

Screenshot:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/19513404/152916982-4b6934ca-3b8e-442d-94ac-03ce48eab6b9.png">

**Comment by Alevsk** [comment]
I was able to reproduce this on https://play.min.io:9443, I'll take a look

**Comment by harshavardhana** [comment]
We should turn-off "date" @Alevsk -- //cc @krisis please fill in why we should be not providing "date" as an option.

**Comment by Alevsk** [comment]
> We should turn-off "date" @Alevsk -- //cc @krisis please fill in why we should be not providing "date" as an option.

So only days should be supported?

**Comment by harshavardhana** [comment]
> So only days should be supported?

Correct "Date" is deprecated by AWS and they suggest users should avoid it.

**Comment by krisis** [comment]
@Alevsk

AWS S3 docs says the following about date-based action. tl;dr Date-based action behaves differently before and after that date has passed. i.e objects may be expired or transitioned sooner than intended. So, it's best to leave Date option out of Console UI.

> The date-based action is not a one-time action. Amazon S3 continues to apply the date-based action even after the date has passed, as long as the rule status is Enabled.

> For example, suppose that you specify a date-based Expiration action to delete all objects (assume no filter specified in the rule). On the specified date, Amazon S3 expires all the objects in the bucket. S3 also continues to expire any new objects you create in the bucket. To stop the Lifecycle action, you must remove the action from the Lifecycle configuration, disable the rule, or delete the rule from the Lifecycle configuration.
