### ISSUE TITLE
Minio Console don't show whitespace on path name

### ISSUE THREAD

**Issue by jjmm0312** [minio/console#1543]
Hello. I want to ask a bug about  Minio console.

## Expected Behavior

When I use Minio console, I can create new path below bucket with this button.
![image](https://user-images.githubusercontent.com/30207891/153340922-787b6a22-7253-4952-ad3f-ef10c0be9a28.png)

If i include whitespace in the path name, i want to see whitespace.

## Current Behavior

For example, 
I want to make a path "minio".
By mistake, I wrote the name " minio" ( include whitespace at the head ).

In this case, Minio console show same name like "minio".
So, I cannot find which factor is problem.

Path "minio" and " minio" show same path name on Minio Console.
(in this case, two "minio" path. I can't discover the difference)

## Possible Solution

I want to see exact name of path.
"minio" and " minio" is different.

**Comment by dvaldivia** [comment]
@harshavardhana do we support spaces in prefixes? I find it odd to use at the start or end of a prefix

**Comment by harshavardhana** [comment]
> @harshavardhana do we support spaces in prefixes? I find it odd to use at the start or end of a prefix

Yes @dvaldivia it is supported since it can be created on the disk - but its hard to read @dvaldivia :-)

**Comment by dvaldivia** [comment]
I see we do create the prefixes with spaces 
```
➜ mc ls myminio/amq-notifications/prefix1/prefix2/prefix3         
[2022-02-15 13:11:10 PST] 368KiB STANDARD minio-operator-4-4-7.yaml
[2022-02-15 13:10:31 PST]   881B STANDARD olm.sh
[2022-02-15 13:33:03 PST]     0B   minio/
(base)  portal-ui git:(fix-upload-button-logic) ✗ 
➜ mc ls myminio/amq-notifications/prefix1/prefix2/prefix3/\ \ minio/
[2022-02-15 13:32:05 PST] 3.3KiB STANDARD Makefile
(base)  portal-ui git:(fix-upload-button-logic) ✗ 
➜ mc ls myminio/amq-notifications/prefix1/prefix2/prefix3           
[2022-02-15 13:11:10 PST] 368KiB STANDARD minio-operator-4-4-7.yaml
[2022-02-15 13:10:31 PST]   881B STANDARD olm.sh
[2022-02-15 13:33:51 PST]     0B   doublespace  /
[2022-02-15 13:33:51 PST]     0B   minio/
(base)  portal-ui git:(fix-upload-button-logic) ✗ 
➜ mc ls myminio/amq-notifications/prefix1/prefix2/prefix3/\ \ doublespace\ \ /
[2022-02-15 13:33:47 PST] 3.3KiB STANDARD Makefile
```

we just need to show this on the breadcrums

**Comment by Alevsk** [comment]
> I see we do create the prefixes with spaces
> 
> ```
> ➜ mc ls myminio/amq-notifications/prefix1/prefix2/prefix3         
> [2022-02-15 13:11:10 PST] 368KiB STANDARD minio-operator-4-4-7.yaml
> [2022-02-15 13:10:31 PST]   881B STANDARD olm.sh
> [2022-02-15 13:33:03 PST]     0B   minio/
> (base)  portal-ui git:(fix-upload-button-logic) ✗ 
> ➜ mc ls myminio/amq-notifications/prefix1/prefix2/prefix3/\ \ minio/
> [2022-02-15 13:32:05 PST] 3.3KiB STANDARD Makefile
> (base)  portal-ui git:(fix-upload-button-logic) ✗ 
> ➜ mc ls myminio/amq-notifications/prefix1/prefix2/prefix3           
> [2022-02-15 13:11:10 PST] 368KiB STANDARD minio-operator-4-4-7.yaml
> [2022-02-15 13:10:31 PST]   881B STANDARD olm.sh
> [2022-02-15 13:33:51 PST]     0B   doublespace  /
> [2022-02-15 13:33:51 PST]     0B   minio/
> (base)  portal-ui git:(fix-upload-button-logic) ✗ 
> ➜ mc ls myminio/amq-notifications/prefix1/prefix2/prefix3/\ \ doublespace\ \ /
> [2022-02-15 13:33:47 PST] 3.3KiB STANDARD Makefile
> ```
> 
> we just need to show this on the breadcrums

Do we want to also show this while listing folders/prefixes ?

**Comment by prakashsvmx** [comment]
Thank you @jjmm0312 , will be fixed in UI once the PR is merged.
