### ISSUE TITLE
share link is docker 's ip

### ISSUE THREAD

**Issue by fanybook** [minio/console#1569]
i used minio via docker
image is minio/minio:latest

when i access minio console by host computer‘s ip (eg. http://xxxxx:9001, xxxxx is host computer‘s ip), the generated sharing link is the  address of docker ((eg. http://yyyyy:9000/test/001.png, yyyyy is docker container‘s ip))

**Comment by harshavardhana** [comment]
if you want a custom hostname and IP you need to `MINIO_SERVER_URL` @fanybook

**Comment by fanybook** [comment]
@harshavardhana thanks, but links of preview and download is valid (is host computer‘s ip)

**Comment by harshavardhana** [comment]
> @harshavardhana thanks, but links of preview and download is valid (is host computer‘s ip)


It is better if you read this https://github.com/minio/minio#things-to-consider - you will understand what we are talking about.

**Comment by fanybook** [comment]
My understanding is the links of preview and download only for admin, share link is for everyone

**Comment by harshavardhana** [comment]
> But by default, should they be consistent without `MINIO_SERVER_URL `

There is no way to magically know what URL you are sharing with your end application. You need to make the necessary config changes. 

There is no magic involved here.
