### ISSUE TITLE
Wildcard policy not allowing bucket browse

### ISSUE THREAD

**Issue by riazarbi** [minio/console#1597]
Hello, 

# Background

We have a policy that we attach to all new users, which allows them full control of any buckets that have their username in the bucket name.

This policy works fine for minio, and things work as expected via the `mc` cli or python clients.

# Issue

However, things do not work as expected via the console. 

Observed behavior is that the buckets are listed under the buckets pane, but when you click browse you are redirected back to the bucket list. 

Browsing works fine in the console for other roles.

We are using the latest version of console (0.14.7) but this issue has been present for the entire time we have used console. It did not occur in the deprecated web UI.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username},*"
            ]
        }
    ]
}
```

**Comment by dvaldivia** [comment]
I'm not sure we substitute the variables on the client side, we will look into this, seems like an easy fix to me

**Comment by harshavardhana** [comment]
> "arn:aws:s3:::${aws:username},*"

This policy is wrong with a `,`

**Comment by riazarbi** [comment]
@harshavardhana I have changed it to the following to test if it resolves the issue, but it does not.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}*/*"
            ]
        }
    ]
}
```

The key thing to note is that I can browse my user prefixed buckets with `mc` or minio python, but not in the console.

**Comment by riazarbi** [comment]
Issue persists in `0.15.2`

**Comment by jaggerwang** [comment]
Same issue!

When using `aws:username` condition key in policy, user `team-10` cannot browse files in bucket `team-10` .
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}/*"
            ]
        }
    ]
}
```

But when not using condition key, it's ok.
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::team-10"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::team-10/*"
            ]
        }
    ]
}
```

**Comment by dvaldivia** [comment]
Do we support variables in the policies already @Alevsk ? I think that's something we need to do

**Comment by Alevsk** [comment]
> substitute the variables on the client side, we will look into

MinIO backend supports variables on policies but the console frontend doesn't, this has to be a new feature

**Comment by cniackz** [comment]
Reported as well in subnet with `jwt:*` variables:
https://subnet.min.io/issues/5636

**Comment by riazarbi** [comment]
Hello,

I tried out both `0.15.11` and `0.15.14`. I'm afraid the issue persists. 

I cannot reopen this issue. Should I create a new one?
