### ISSUE TITLE
Lifecycle Rules creation in Conosle differ from mc ilm

### ISSUE THREAD

**Issue by Kn0lc** [minio/console#1603]
## NOTE
All GitHub issues are addressed on a best-effort basis at MinIO's sole discretion. There are no Service Level Agreements (SLA) or Objectives (SLO). Remember our [Code of Conduct](https://github.com/minio/minio/blob/master/code_of_conduct.md) when engaging with MinIO Engineers and the larger community.

For urgent issues (e.g. production down, etc.), subscribe to [SUBNET](https://min.io/pricing?jmp=github) for direct to engineering support.
 

## Expected Behavior
The mc ilm command and the Minio Console lifcycle rule creation work in the same way. Either both show an error or not when creating the same rule.

## Current Behavior
When creating a lifecycle rule in Minio Console only for noncurrent objects or expired object delete markers I get the error:
 "Expiration days cannot be set to zero"
however if I use the command 
 mc ilm add ALIAS/PATH --noncurrentversion-expiration-days 5 --expired-object-delete-marker
I can create a valid rule

If i open the created rule in Minio Console and try to save the unchanged rule I get the error as well.

## Possible Solution
change error checking in the minio console

## Steps to Reproduce (for bugs)

1. create rule 
 mc ilm add ALIAS/PATH --noncurrentversion-expiration-days 5 --expired-object-delete-marker
2. open the rule in the minio console and try to save it.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-02-16T00-35-27Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Docker Container Linux e2987466dbea 5.16.8-200.fc35.x86_64 minio/minio#1 SMP PREEMPT Tue Feb 8 20:58:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Host: Linux fedora-server 5.16.8-200.fc35.x86_64 minio/minio#1 SMP PREEMPT Tue Feb 8 20:58:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by binbinshi** [comment]
@Kn0lc  hi，my minio bukcet Lifecycle tab  is grey, so i can't use the tab to set  the bucket Lifecycle ; can you tell me how you config , the console Lifecycle can set?

**Comment by prakashsvmx** [comment]
@binbinshi ,  If this bucket access is controlled by access policies, appropriate permissions are required to set lifecycle  configuration.

```
"s3:GetLifecycleConfiguration",
"s3:PutLifecycleConfiguration",
```

**Comment by binbinshi** [comment]
consoleAdmin Policy ;  
 {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
So it's not gray due to permission issues；
I find when i start the minio with more disks (in distribute mode ) , the  tab can use ;
docker run -it -p 9000:9000 -p 9001:9001 --name minio \
>   -v /mnt/data/minio/data1:/data1 \
>   -v /mnt/data/minio/data2:/data2 \
>   -v /mnt/data/minio/data3:/data3 \
>   -v /mnt/data/minio/data4:/data4 \
>   -v /mnt/data/minio/config:/root/.minio \
>   -e "MINIO_ROOT_USER=minioadmin" \
>   -e "MINIO_ROOT_PASSWORD=minioadmin" \
>   -d minio/minio server /data1 /data2 /data3 /data4 \
>   --console-address ':9001'

**Comment by prakashsvmx** [comment]
Lifecycle requires versioning which is available only in Distributed mode.  So it is expected. @binbinshi

**Comment by binbinshi** [comment]
@prakashsvmx  thanks
