### ISSUE TITLE
minio console timeout 

### ISSUE THREAD

**Issue by qw4285632q** [minio/console#1607]
i have one bucket with 100000+ folder. then i use minio console to load this bucket .it's always show me :This operation is taking longer than expected... (***s); and finally until wait 500s  show :Get "http://192.168.102.26:9000/global/?continuation-token=ZmlsZXVwbG9hZC83NmI5YmU3OC1lMjkyLTRkYzQtYThmMC01MTljZDRjODdlZmIvW21pbmlvX2NhY2hlOnYyLGlkOjEyZWRhY2QxLTM5OGYtNGY0Zi04N2NhLTE5YmFiNDYwMDgxZixwOjAsczowXQ%3D%3D&delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=fileupload%2F": net/http: timeout awaiting response headers; so how can i fix

**Comment by prakashsvmx** [comment]
>100000+ folder
 under single bucket Could indicate that not following best practices . As it could be limited by filesystem and hardware drive performance.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html

**Comment by harshavardhana** [comment]
> i have one bucket with 100000+ folder. then i use minio console to load this bucket .it's always show me :This operation is taking longer than expected... (***s); and finally until wait 500s show :Get "http://192.168.102.26:9000/global/?continuation-token=ZmlsZXVwbG9hZC83NmI5YmU3OC1lMjkyLTRkYzQtYThmMC01MTljZDRjODdlZmIvW21pbmlvX2NhY2hlOnYyLGlkOjEyZWRhY2QxLTM5OGYtNGY0Zi04N2NhLTE5YmFiNDYwMDgxZixwOjAsczowXQ%3D%3D&delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=fileupload%2F": net/http: timeout awaiting response headers; so how can i fix

this is working as expected, your disks are slow and your network is slow as well.
