### ISSUE TITLE
Incorrect share file URL

### ISSUE THREAD

**Issue by moracabanas** [minio/console#1632]
Hello there I setup a small minio server with 2 drives with docker and traefik.
When I share a link I can't get my domain on the sharing URL no matter what ENV variable I set. It is taking some internal IP from somewhere instead my `domain.example.com`

![image](https://user-images.githubusercontent.com/4382333/155892722-272c246a-473c-4934-a8fc-4758c343b516.png)

I read and test stackoverflow issues and minio docs for 12h straight and I cannot find how to solve this issue

Thanks you for your suggestions!

**Comment by harshavardhana** [comment]
You need to make sure to setup correct MINIO_SERVER_URL environment variable.

**Comment by moracabanas** [comment]
I used MINIO_SERVER_URL but I get various error regarding letsencrypt certificates and console login:
- Unconsistent letsencript TSL handshake errors and other certificate errors. Sometimes I get both console and server certificates, sometimes I get infinite errors.
```error
time="2022-02-27T18:55:36Z" level=debug msg="http: TLS handshake error from 70.106.224.209:36044: local error: tls: bad record MAC"
time="2022-02-27T18:55:38Z" level=debug msg="http: TLS handshake error from 70.106.224.209:36046: local error: tls: bad record MAC"
time="2022-02-27T18:55:38Z" level=debug msg="http: TLS handshake error from 70.106.224.209:36050: local error: tls: bad record MAC"
time="2022-02-27T18:55:40Z" level=debug msg="http: TLS handshake error from 70.106.224.209:36056: local error: tls: bad record MAC"
time="2022-02-27T18:56:00Z" level=debug msg="http: TLS handshake error from 70.106.224.209:36066: local error: tls: bad record MAC"
time="2022-02-27T18:56:03Z" level=debug msg="http: TLS handshake error from 70.106.224.209:36068: local error: tls: bad record MAC"
time="2022-02-27T18:56:11Z" level=debug msg="http: TLS handshake error from 70.106.224.209:36072: local error: tls: bad record MAC"
time="2022-02-27T18:56:14Z" level=debug msg="http: TLS handshake error from 70.106.224.209:36076: local error: tls: bad record MAC"
```
-  When I get certificates then I had a login problem on console 
![image](https://user-images.githubusercontent.com/4382333/155895967-5a7dab58-3ecc-4c10-99ac-1eed6ec852c7.png)

**Comment by harshavardhana** [comment]
you need to make sure your TLS certs are proper

**Comment by moracabanas** [comment]
When traefik generates a private key for TLS it uses this json format to manage everything. Does it means I cannot use traefik at all?

`acme.json`
```
{
  "myresolver": {
    "Account": {
      "Email": "email@example.com",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "mailto:emai@example.com"
          ]
        },
        "uri": "https://acme-staging-v02.api.letsencrypt.org/acme/acct/************"
      },
      "PrivateKey": <LARGE PRIVATE KEY HERE>",
      "KeyType": "4096"
    },
    "Certificates": [
      {
        "domain": {
          "main": "s3.example.duckdns.org"
        },
        "certificate": "< LARGE LETSENCRYPT OBTAINED CERTIFICATE HERE >",
        "key": "< LARGE KEY HERE >",
        "Store": "default"
      },
      {
        "domain": {
          "main": "console.example.duckdns.org"
        },
        "certificate": "< LARGE LETSENCRYPT OBTAINED CERTIFICATE HERE >",
        "key": "< LARGE KEY HERE >",
        "Store": "default"
      }
    ]
  }
}
```

I have many questions about this:

- Traefik auto obtains certificates with letsencrypt in this weir JSON format instead splitting `.crt` and `.key`files but if I understand right, you must previously have those certificates shared with minio.
- if you use MINIO_SERVER_URL you are telling `console` to communicate with `server` (which is actually in the same container) using the long path making POST request to full domaing `s3.example.duckdns.org` opening TLS conection from the container, resolving ip in DNS, and incoming again, which requires minio to trust certificates due to TLS instead of docker internal network `minio:9000`. 
- How can I handle SSL with traefik only, I don't need minio to trust any certificate as Traefik is my reverse proxy and it is handling TLS automatically for me. Can I disable TSL on minio?

**Comment by moracabanas** [comment]
At the moment this configuration made the trick:

```env
MINIO_BROWSER_REDIRECT_URL=https://storage.deducedata.solutions
MINIO_SERVER_URL=https://s3.deducedata.solutions
CONSOLE_SECURE_TLS_REDIRECT="off"
```

I know disabling console  secured TSL redirect is a security flaw, but I am running TSL from traefic as reverse proxy. 

I tried to convert `acme.json` certificates from traefik to `public.crt` & `private.key` and bind mount them to minio container but I got a blank page with something like `client trying to make http call to https api`.

Trust me I tried everything for the las month to get sharing URL working properly withh traefik, only disablingsecure TLS redirect is working fine. 

It do not work with Staging letsencript certs because console shows an error message for untrusted authority.

It also fails for `MINIO_ROOT_USER` & `MINIO_ROOT_PASSWORD` with the error message:

```error
Unsupported action AssumeRole
```

But it is fine to use `MINIO_ACCESS_KEY` & `MINIO_SECRET_KEY`.

Everithing is working so far with no issues also HTTPS is internally forced by traefik HTTP -> HTTPS redirect.

Please don't close this thread if someone could be more clear about this topic, as Nginx is so much more documented than Traefik and this issue is still a thing.

Thanks you

**Comment by moracabanas** [comment]
This keeps happening every time

![image](https://user-images.githubusercontent.com/4382333/159090250-ada23530-6c4b-4600-a4d1-f7adf55ee0a0.png)

**Comment by moracabanas** [comment]
The overall issues were caused mainly by a linux bug on Raspberry Pi still open from Jan 2021 

https://github.com/raspberrypi/linux/issues/4092

Closing this as solved in the thread. It is a shame it causes errors to my stack to the point I thought it was my stack issue for a month when it was not!

I wouln't consider Raspberry Pi for future projects anymore.

Feel free to reopen this issue if you find better traefik insights to deploy minio with! 😊
