### ISSUE TITLE
Minio Logout does not work with OpenID

### ISSUE THREAD

**Issue by pglavica** [minio/console#1665]
## Expected Behavior
Minio server is configured to do single sign on with OpenID.
When logged in minio admin console, click on logout should terminate session on minio and on keycloak.

## Current Behavior
When logout button is clicked in mino console UI, following XHR request is called: /api/v1/logout
After that, user session remains in keycloak.
Minio logout when OpenID provider is configured does not call end_session_endpoint defined in OpenID metadata, specified in minio environment.

## Possible Solution
Clicking logout button on minio console should also invoke callout to end_session endpoint defined in OpenID metadata configuration.
Current implementation should be upgraded so in case OpenID login is configured on Minio, that along session termination on minio server, session termination on OP should also occur from end_session endpoint.

## Steps to Reproduce (for bugs)
1. Integrate minio server with KeyCloak
2. Login with specified user into minio via OpenID login
3. Click Logout button
4. After internal logout, user is redirected to login page. Clicking 'Log in with SSO' directly lets the user in minio ui console, without redirect to OP for credential challenge.

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-09-18T18-09-59Z
* Server setup and configuration: single node minio server setup
* Operating System and version (`uname -a`): Red Hat Enterprise Linux 8.3 (Ootpa)

**Comment by dvaldivia** [comment]
is this end session call standard on OpenID? if so, we should definitively call it  cc @Alevsk

**Comment by harshavardhana** [comment]
> is this end session call standard on OpenID? if so, we should definitively call it cc @Alevsk

Yes, it is @dvaldivia its called session_endpoint - https://openid.net/specs/openid-connect-session-1_0-17.html#RPLogout

**Comment by pglavica** [comment]
> > is this end session call standard on OpenID? if so, we should definitively call it cc @Alevsk
> 
> Yes, it is @dvaldivia its called session_endpoint - https://openid.net/specs/openid-connect-session-1_0-17.html#RPLogout

Hi,

So we can expect fix soon?

Regards,
Patrik

**Comment by cguermi** [comment]
Hi, 

i'm testing OIDC logout with keycloak, login works well, but when i logout keycloak is sending /logout request to minio but it's not triggering user logout (although i receive 200 code), the url used to logout by minio is "/api/v1/logout" but calling this url instead produce 401 http code (when it's called from keycloak ) 

![image](https://user-images.githubusercontent.com/94621862/205025334-45dece43-908e-46de-ae75-6497446d6a57.png)
