### ISSUE TITLE
Support for other OIDC providers (Gitlab.com and vault)

### ISSUE THREAD

**Issue by Timost** [minio/console#1702]
Hello,
First of all thank you for minio ! 🙏🙏

I'm trying to use Gitlab.com as an OIDC Identity provider for minio and it's not working (in the console) because it seems gitlab supports only `code` and `token` response types:
```shell
curl -s https://gitlab.com/.well-known/openid-configuration | jq
{
  "issuer": "https://gitlab.com",
  // ... omitted for brevity
  "response_types_supported": [
    "code",
    "token"
  ]
  // ... omitted for brevity
}
```

A check was added in https://github.com/minio/console/commit/fb99cf3805dd3bcc9b3de246c566d50986e98047 to ensure only providers with supported `response_types_supported` are used.

Do you think it is possible/desirable to add support for other `response_types` and thus enable other OIDC providers ?
I've also tried using Hashicorp Vault as an OIDC provider but I hit the same issue since it only supports `code` `response_types`.

Thank you for your help

**Comment by harshavardhana** [comment]
@Timost, unfortunately, no since we do need `id_token`  - please use more sane IDPs such as Okta, Ping etc.

**Comment by Timost** [comment]
Alright ! Thank you for your quick reply !

**Comment by Timost** [comment]
For people still stumbling on this issue. 
A fix was pushed in the console here: https://github.com/minio/console/commit/aaa55a1f4afce347e3cf14c4e0fb046dd5342200
