### ISSUE TITLE
Bucket overview line height

### ISSUE THREAD

**Issue by iFrozenPhoenix** [minio/console#1708]
The current bucket overview is really large.
If there are many buckets it is hard to get an overview.

In my opinion it would be good to have a button near "select multiple buckets" that allows to switch the view to a more compact format like the one for bucket objects.
I think it would already improve the experience if the bucket icon, usage and objects were in the same line as bucket name and access, maybe right of the access field.

**Comment by prakashsvmx** [comment]
We will try to improve as we revamp the pages. 

@oscarocastellanos

**Comment by oscarocastellanos** [comment]
Thank you for the input. This will be considered on our ongoing process of improving the overall UX.

**Comment by dvaldivia** [comment]
We already switched to a slimmer list of buckets for object browser to address this
<img width="1818" alt="Screenshot 2023-05-15 at 9 56 29 AM" src="https://github.com/minio/console/assets/18384552/ddae368e-1b4b-4fb7-8468-f43441513979">
