### ISSUE TITLE
Add Lambda Notification Target Flow

### ISSUE THREAD

**Issue by labebe6** [minio/console#171]
<img width="656" alt="Screen Shot 2020-06-26 at 3 50 53 PM" src="https://user-images.githubusercontent.com/57810560/85906969-d39d5d00-b7c4-11ea-81fb-cf484a298916.png">

Will add the corresponding screens for each service to this issue as they're made.

**Comment by labebe6** [comment]
### Postgres SQL

w/o manually adding connection string:
<img width="634" alt="Screen Shot 2020-06-15 at 1 40 16 PM" src="https://user-images.githubusercontent.com/57810560/84703845-c1423a00-af0d-11ea-920a-588f2ca60e7c.png">

w/ manual add of connection string:
<img width="568" alt="Screen Shot 2020-06-15 at 1 44 08 PM" src="https://user-images.githubusercontent.com/57810560/84704191-4cbbcb00-af0e-11ea-9f80-1b0b8bd5e4d8.png">

**Comment by dvaldivia** [comment]
looks stunning, can you share the XD via slack?

**Comment by labebe6** [comment]
sure @dvaldivia Will do that when I get back on a computer. Just stepped away for a moment.

**Comment by bexsoft** [comment]
Wow! Looks really awesome! =D

**Comment by labebe6** [comment]
[Link to the prototype](https://xd.adobe.com/view/21b3249c-034f-4dbf-54b6-e61055c15f77-5782/) for the lambda notification target flow
