### ISSUE TITLE
Deleted Object selection (Delete Marker)

### ISSUE THREAD

**Issue by prakashsvmx** [minio/console#1718]
The deleted object row selection highlight needs a different highlight to differentiate a delete marker row. or we can indicate it as a delete marker in some way.

https://user-images.githubusercontent.com/23444145/158328751-8cedd558-69a8-41f7-9ae2-1582b895a2c7.mp4

@oscarocastellanos

**Comment by oscarocastellanos** [comment]
@prakashsvmx Agree. I was already working on this, please, take a look:

https://xd.adobe.com/view/598f4778-f7d9-45d4-88c6-96d1821bcf6b-0cdc/

**Comment by dvaldivia** [comment]
it was a very subtle color

**Comment by dvaldivia** [comment]
The latest version explorer already has those pills, but I think @prakashsvmx is talking about the background of the row @oscarocastellanos 

<img width="1392" alt="Screen Shot 2022-03-29 at 9 51 22 AM" src="https://user-images.githubusercontent.com/18384552/160664482-d1d38daa-3718-4519-a768-4d17d7e18710.png">

**Comment by oscarocastellanos** [comment]
@dvaldivia @prakashsvmx Yeah, let's use the same gray we use everywhere, to keep consistency. I think it's #FCFCFC. Here's how it would look
![Captura de Pantalla 2022-03-29 a la(s) 11 07 24](https://user-images.githubusercontent.com/89046849/160667092-7c9cd69d-1026-42ab-b6ae-820441ca0f43.png)

**Comment by prakashsvmx** [comment]
The issue isnin 16th second in video. 
In the object list view with deleted objects on,

The row selection should differentiate the deleted object from the normal objcet.

**Comment by oscarocastellanos** [comment]
I think we should not use italics @bexsoft. While it looks functional here, we avoid italics in our branding as much as possible.
