### ISSUE TITLE
minio speed test from the minio operator console.

### ISSUE THREAD

**Issue by fcomte** [minio/console#1734]
I deploy minio RELEASE.2022-03-17T06-34-49Z using minio operator 4.4.11.
I can access either to the operator console or the minio tenant console.

If I execute speed test from the minio tenant console everything works well.
If I execute speed test from the operator console, it fails immediately.

I saw in the console operator logs : 
```
I: 2022/03/17 17:23:27 speedtest started
E: 2022/03/17 17:23:27 error initializing speedtest: Post "http://localhost:9000/minio/admin/v3/speedtest?concurrent=32&duration=10s&size=64000000": dial tcp 127.0.0.1:9000: connect: connection refused
E: 2022/03/17 17:23:27 original ws error: Post "http://localhost:9000/minio/admin/v3/speedtest?concurrent=32&duration=10s&size=64000000": dial tcp 127.0.0.1:9000: connect: connection refused
I: 2022/03/17 17:23:27 speedtest stopped
E: 2022/03/17 17:23:27 error on ReadMessage: read tcp 10.233.86.191:9090->10.233.103.0:60508: use of closed network connection
```

I guess than the console supposed to have the minio api on the same host but this is not the case when it's the operator console.

Is speed test supposed to work on the operator console ?

**Comment by dvaldivia** [comment]
You shouldn't see this problem if you access the tenant console directly

**Comment by fcomte** [comment]
yes I confirm

**Comment by dvaldivia** [comment]
you mean using access/secret key? you can access the Object Store with those credentials, in the case of console it's also possible but if we see OIDC configured, we always prompt you to start SSO

**Comment by fcomte** [comment]
So I have to connect with my SSO account. I can't use access key / secret key  to connect to this console ?

**Comment by fcomte** [comment]
I ask that because my STS account is a normal user account and I use a normal user account as administrator account

**Comment by dvaldivia** [comment]
we don't have support for that scenario right now, the sessions for console are STS based, so in theory we could allow you to login using an STS

**Comment by Alevsk** [comment]
@fcomte you can still use your access/secret credentials via `mc` client, the UI console will allow you only access via SSO for now.

**Comment by harshavardhana** [comment]
Allowing STS is out of scope and simply feature creep.  Just login using normal credentials either

- MinIO as IAM
- OIDC
- LDAP
