### ISSUE TITLE
Cannot use local credentials to log into mcs in minio gateway s3 mode

### ISSUE THREAD

**Issue by jdheyburn** [minio/console#176]
## Expected Behavior
When local credentials are established on the minIO server in gateway s3 mode, and can be used to log into the MinIO server web UI, I should be able to log into mcs with these credentials too 

## Current Behavior
mcs spits out an error:
```
2020/06/16 10:53:55 error obtaining MinIO region: This 'admin' API is not supported by server in 'mode-gateway-s3'
```

The issue does not occur when running MinIO in server mode (not gateway).

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Spin up an etcd cluster (3.3.9 will do)

```
docker run \
-p 2379:2379 \
-p 2380:2380 \
--mount type=bind,source=/tmp/etcd-data.tmp,destination=/etcd-data \
--name etcd-gcr-v3.39 --detach \
gcr.io/etcd-development/etcd:v3.3.9 \
/usr/local/bin/etcd \
--name s1 \
--data-dir /etcd-data \
--listen-client-urls http://0.0.0.0:2379 \
--advertise-client-urls http://0.0.0.0:2379 \
--listen-peer-urls http://0.0.0.0:2380 \
--initial-advertise-peer-urls http://0.0.0.0:2380 \
--initial-cluster s1=http://0.0.0.0:2380 \
--initial-cluster-token tkn \
--initial-cluster-state new
```

2. Spin up MinIO server in gateway s3 mode

```
export MINIO_ETCD_PATH_PREFIX=pathprefix/
export MINIO_ETCD_ENDPOINTS=http://localhost:2379
export MINIO_ACCESS_KEY=AWS_S3_ACCESS
export MINIO_SECRET_KEY=AWS_S3_SECRET

./minio gateway s3
```

3. Use `mc` to add a local admin user

```
# Admin policy
$ mc admin policy info mys3 admin
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "admin:*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:*"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}

# Admin user
mc admin user add gateway mcs password123
# Policy set
mc admin policy set gateway admin user=mcs
```

4. Start up mcs
```
export MCS_ACCESS_KEY=mcs
export MCS_SECRET_KEY=password123
./mcs server
```

5. Attempt to log into mcs with the credentials above

## Context
We are evaluating mcs as an LDAP Auth compatible solution to https://github.com/minio/minio/issues/9836

## Regression
No

## Your Environment

* Version used (`mcs version`): `mcs version 0.1.0 - 48e6b1b`

**Comment by harshavardhana** [comment]
MCS is not meant to used with S3 gateway just yet.

**Comment by dboc** [comment]
Sad but true! :(
It is the same for nas gateway.

I hope console could be used with minio as gateway soon.

**Comment by harshavardhana** [comment]
> Sad but true! :(
> It is the same for nas gateway.
> 
> I hope console could be used with minio as gateway soon.

Currently not a priority @dboc

**Comment by harshavardhana** [comment]
Console will never work with gateway for the near future - closing this PR.
