### ISSUE TITLE
Confused by metrics reported by console

### ISSUE THREAD

**Issue by imadmali** [minio/console#1764]
Hi. I’m testing minio using the krew minio plugin and am confused about the metrics reported by the minio operator/tenant console. The metrics that are reported seem extremely large. Any insight into what and how they are calculated would be much appreciated.

## Setup

2 Servers with 2 mounts of 10GiB each. My understanding is that this would give me 40GiB of raw storage. With EC:2 this would mean I have 20GiB of usable storage. I also created a bucket that contains 23 MiB of data.

## Reported Metrics

I've listed the reported metrics below, the raw capacity metric is the only one that looks correct. The other ones seem far too large. I would expect _Capacity_ to be equal to usable capacity (20GiB) and _Usage_/_Used_ to be equal to the amount of usable capacity that has been used up (23MiB).

Minio Operator Console
| Type  | Size |
| ------------- | ------------- |
| Raw Capacity  | 40Gi  |
| Capacity  | 1.8Ti  |
| Usage  | 34Ti  |

Minio Operator Console (Tenant Summary)
| Type  | Size |
| ------------- | ------------- |
| Storage Capacity  | 40GiB  |
| Used  | 762GiB  |

Minio Operator Console (Tenant Metrics)
| Type  | Size |
| ------------- | ------------- |
| Capacity  | 1.4TiB  |

<details>
<summary>Screenshots</summary>
<br>

<img width="1923" alt="Screen Shot 2022-03-24 at 12 00 22" src="https://user-images.githubusercontent.com/16767381/159991344-6338f289-dc4a-4a5b-b61a-22360d027177.png">

<img width="1920" alt="Screen Shot 2022-03-24 at 12 00 56" src="https://user-images.githubusercontent.com/16767381/159991167-ce33f4dc-3696-4f6d-81de-696124ed8b99.png">

<img width="1865" alt="Screen Shot 2022-03-24 at 12 01 07" src="https://user-images.githubusercontent.com/16767381/159991195-3abe4216-5baf-4c5c-9cf7-6eaf5d64a384.png">
</details>

## Environment

Machine: MacBook Pro Apple M1 Max
OS: MacOS Monterey v12.3
Kubernetes: v1.21.5
Minio Operator: v4.4.12
Storage: 1 TB
```
df -h
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk3s1s1  926Gi   14Gi  736Gi     2%  500632 4293511507    0%   /
devfs           199Ki  199Ki    0Bi   100%     690          0  100%   /dev
/dev/disk3s6    926Gi  2.0Gi  736Gi     1%       2 7720168600    0%   /System/Volumes/VM
/dev/disk3s2    926Gi  494Mi  736Gi     1%    2239 7720168600    0%   /System/Volumes/Preboot
/dev/disk3s4    926Gi  3.8Mi  736Gi     1%      53 7720168600    0%   /System/Volumes/Update
/dev/disk1s2    500Mi  6.0Mi  479Mi     2%       1    4909800    0%   /System/Volumes/xarts
/dev/disk1s1    500Mi  7.4Mi  479Mi     2%      37    4909800    0%   /System/Volumes/iSCPreboot
/dev/disk1s3    500Mi  2.4Mi  479Mi     1%      51    4909800    0%   /System/Volumes/Hardware
/dev/disk3s5    926Gi  173Gi  736Gi    19% 1973087 7720168600    0%   /System/Volumes/Data
map auto_home     0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
```

**Comment by dvaldivia** [comment]
the reason why these numbers are so wacky is that you are suing the same drive for multiple devices, so your `1Ti` HDD shows up as `4TiB` when MinIO is probing the drive usage, if these were separate drives the problem wouldn't occur

**Comment by imadmali** [comment]
Okay, that makes sense for the minio operator console capacity metric (926Gi * 4 / 2 = 1.8Ti). But for Usage, how come that value is at 34Ti instead of 23MiB? Is this metric also behaving oddly because I'm using the same drive?
