### ISSUE TITLE
Unable access objects in bucket

### ISSUE THREAD

**Issue by zj5220924** [minio/console#1774]
access policy config like below：
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*testa*"
            ]
        }
    ]
}
```

click the Browse button can't enter the bucket
![图片](https://user-images.githubusercontent.com/54430024/160532211-5edb75ff-964e-4850-a724-6788dbf996b8.png)

If I set the access policy like below, it back to normal, but the bucket "test-testa-001" not in bucket list, it's not what I want, please help on this, thanks a lot!
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*testa*"
            ]
        }
    ]
}
```
![图片](https://user-images.githubusercontent.com/54430024/160532717-38366a4c-c235-470c-b01f-a8a25e92ef4a.png)
![图片](https://user-images.githubusercontent.com/54430024/160532750-48b868bc-93ea-4aff-8ed2-f8049d15f8d0.png)

**Comment by dvaldivia** [comment]
I was able to replicate this bug, we'll work on a fix

**Comment by Alevsk** [comment]
@zj5220924 the two policies that you shared are exactly the same.
@dvaldivia I tested this against master and the issue is fixed there.

**Comment by dvaldivia** [comment]
I tested on Play, so then the fix will be in the next release

**Comment by zj5220924** [comment]
> @zj5220924 the two policies that you shared are exactly the same. @dvaldivia I tested this against master and the issue is fixed there.

Yes, as you see, I don't know why it was changed, I have edited again, and put on the screenshots.
![图片](https://user-images.githubusercontent.com/54430024/160724664-eb6ce062-e09b-4d15-ad3c-40dd5b4fcade.png)
![图片](https://user-images.githubusercontent.com/54430024/160724699-da5d9863-967c-4473-8ad0-9ed231f2b2d5.png)

I test on the version: minio-20220326064928.0.0.x86_64.rpm
