### ISSUE TITLE
CSS issue Identity/Groups/Set Policies

### ISSUE THREAD

**Issue by cromatyt** [minio/console#1791]
## Expected Behavior

In MinIO console, i can't set policies in groups

## Current Behavior

The policies list does not show correctly in Identity/Groups/Set Policies
Currently, i uncheck jss341 { display: flex; } in div class "MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 jss341 css-1wxaqej" to perform my action.

## Steps to Reproduce (for bugs)

1. Go to Identity/Groups
2. Select one
3. Try to set policies

## Context

Test on Google Chrome 99.0.4844.74 and Firefox 98.0.2

## Your Environment

minio version RELEASE.2022-04-01T03-41-39Z

**Comment by dvaldivia** [comment]
yes, this is broken, we'll have to fix 
<img width="859" alt="Screen Shot 2022-04-03 at 3 12 46 PM" src="https://user-images.githubusercontent.com/18384552/161450977-7141f0f8-5cbe-4566-8e97-4a7f1877e233.png">

**Comment by dvaldivia** [comment]
This is the expected style, it's still present in `RELEASE.2022-03-03T21-21-16Z`
![Uploading Screen Shot 2022-04-03 at 3.17.04 PM.png…]()
