### ISSUE TITLE
Remove the space in the object path

### ISSUE THREAD

**Issue by ThyrixYang** [minio/console#1793]
Hi,
I notice that there are two spaces around / in the path of objects.
For example, like following
```
data / tmp / data.pkl
```
![U` L~FG}O%W2{VZ9 YPJUMV](https://user-images.githubusercontent.com/11371254/161541856-f611fa59-97d6-437e-8edd-993695d2dad5.png)

Are these spaces necessary? I found it cumbersome to remove these spaces if I want to copy the path into my code.

**Comment by dvaldivia** [comment]
Not really, it's a valid point, we'll remove them when we have some bandwidth
