### ISSUE TITLE
Setting "*" Prefix in Bucket Access Rules results in double "**" Resource

### ISSUE THREAD

**Issue by ravindk89** [minio/console#1794]
This is less a "bug" and more of something we need improved UI/UX on.

When configuring bucket access rules (Bucket -> Manage -> Access Rules) you can se a prefix.

A user in Slack specified ``"*"`` thinking this would ensure the rule applies to all paths at the root of the bucket - which is a reasonable use of the wildcard.

However, in S3 `*` is a valid path or object - so we treat this as is. It results in a slightly odd resource statement in the policy:

```
mc policy get-json play/policytest                                                                                                 ✔ 
{
 "Statement": [
  {
   "Action": [
    "s3:GetBucketLocation"
   ],
   "Effect": "Allow",
   "Principal": {
    "AWS": [
     "*"
    ]
   },
   "Resource": [
    "arn:aws:s3:::policytest"
   ]
  },
  {
   "Action": [
    "s3:ListBucket"
   ],
   "Condition": {
    "StringEquals": {
     "s3:prefix": [
      "*"
     ]
    }
   },
   "Effect": "Allow",
   "Principal": {
    "AWS": [
     "*"
    ]
   },
   "Resource": [
    "arn:aws:s3:::policytest"
   ]
  },
  {
   "Action": [
    "s3:GetObject"
   ],
   "Effect": "Allow",
   "Principal": {
    "AWS": [
     "*"
    ]
   },
   "Resource": [
    "arn:aws:s3:::policytest/**"
   ]
  }
 ],
 "Version": "2012-10-17"
}

```

The `GetObject` statement has a double asterisk, probably from putting a `*` as the value for Prefix. I am not sure how we would render this - would it match only prefixes or objects that start with an asterisk?

I think the user's intent here is sensible - we can't catch this in case someone _is_ using asterisks in their prefix or object names. Having a small tooltip or note under Prefix that says the following might help:

```
Leave this field blank to apply the rule to all prefixes and objects at the bucket root. 

Do not include the wildcard asterisk ``*`` as part of the prefix *unless* it is an explicit part of the prefix name. The Console automatically appends an asterisk to the appropriate sections of the resulting IAM policy.
```

**Comment by ovizii** [comment]
Sorry to revive this old thread, but I cannot save the rule unless I fill in the “prefix” field. Any idea?

**Comment by prakashsvmx** [comment]
Could you try `/`  @ovizii

**Comment by ovizii** [comment]
> Could you try `/` @ovizii

Thanks, that worked and I could save the access rule. Does "/" really apply to "all prefixes and objects at the bucket root" like the tool tip said?

**Comment by prakashsvmx** [comment]
I am not sure. I will check this further.

**Comment by ovizii** [comment]
> I am not sure. I will check this further.

Btw. if you check the link which fixed this issue: https://github.com/minio/console/pull/1839 in the screenshot you can see that the "save" button is greyed out until you fill in the field "prefix"
