### ISSUE TITLE
Metrics Dashboard with no Prometheus: Exploration Conversation

### ISSUE THREAD

**Issue by oscarocastellanos** [minio/console#1804]
@prakashsvmx I've been exploring options for the Metrics Dashboard without Prometheus, making adjustments to the Reported Usage section for it to be more useful.

Please, take a look at them and let me know which one you think work best. 

To consider: Option 3 is one I explored thinking we could implement it in the future, once we're able to add more advanced metrics.

Feedback would be really appreciated. Thanks!

**HOW DOES IT LOOK:**
![Metrics Non-Prometheus-option1](https://user-images.githubusercontent.com/89046849/162073970-b9a567d5-b0fd-4c41-b8eb-aa916eaf2b01.png)
![Metrics Non-Prometheus-option2](https://user-images.githubusercontent.com/89046849/162073991-532ec215-7443-46bf-a3dd-95b927662ed8.png)
![Metrics Non-Prometheus-option3](https://user-images.githubusercontent.com/89046849/162073997-de6c3f41-1440-4e6c-9cfd-59cebf4ab228.png)

**ADOBE XD FILE**
https://xd.adobe.com/view/7650c274-1cd0-4234-8ba9-d7ccdb22aa8b-2303/

**Comment by prakashsvmx** [comment]
@oscarocastellanos for the dashboard without Prometheus ,  Mange button would not be available. so you could explore spacing and placement accordingly. 

The 3rd option looks great. ( my thought was to retain the time indicators as is from the first screenshot and use it with 3rd option) :+1:

**Comment by oscarocastellanos** [comment]
Thank you very much for your input @prakashsvmx! This helps me a lot to continue forward. Will adapt these comments in a new screen so we can move on then. Thank you!

**Comment by prakashsvmx** [comment]
This has been implemented. Can be closed.
