### ISSUE TITLE
Openid Configuration properties not effect

### ISSUE THREAD

**Issue by tiswo** [minio/console#1813]
## Description
When saving the `Openid Configuration`, Some properties do not take effect, such as: 'claim userinfo' and 'redirecturidynamic'. The Console will send the value of `'true'` to the back-end, but the back-end will judge that it will be true only when it is `'on'`. Therefore, setting the property of `Radio(on|off)` type through the console is invalid.

## How to test this issue?
Open the `Console - > Setting - > Identity Openid` and click the `Claim Userinfo` option

**Comment by harshavardhana** [comment]
All values in console should use on/off instead of true/false for some values it tries to use.

**Comment by tiswo** [comment]
> All values in console should use on/off instead of true/false for some values it tries to use.

but In the method of line 105 ，set default value is "true/false" 
https://github.com/minio/console/blob/master/portal-ui/src/screens/Console/NotificationEndpoints/ConfTargetGeneric.tsx

**Comment by reivaj05** [comment]
We are removing the section in `Console - > Setting - > Identity Openid`, please use the new screen located in `Console - > Identity - > OpenID`.

This new section handles those values, please re open if the problem persists
