### ISSUE TITLE
can not fetch policies in user policies page

### ISSUE THREAD

**Issue by wyx0k** [minio/console#1822]
![image](https://user-images.githubusercontent.com/19360718/162694074-ae2691b3-3ebe-4b10-9f8a-354e8725d036.png)
the user is signed policies or not ,
 all can not fetch policies in user policies page
version: RELEASE.2022-04-08T19-44-35Z
environment: docker
mode: standalone

**Comment by prakashsvmx** [comment]
Looks like the fix was part of : https://github.com/minio/console/pull/1815

We will investigate if any

**Comment by wyx0k** [comment]
thankyou,i try it again today,and it already fix in [RELEASE.2022-04-12T06-55-35Z],you are so efficient
