### ISSUE TITLE
preview and download broken

### ISSUE THREAD

**Issue by flixr** [minio/console#1844]
With console included in minio 2022-04-12T06:55:35Z the preview and download is broken in console.
In both cases it will try to download a file called `download` which has zero size.

**Comment by vadmeste** [comment]
@flixr this is most likely an UI issue and you don't have permission to download that file.

Most likley duplicated to this, https://github.com/minio/console/issues/945

**Comment by flixr** [comment]
I don't think so, it was working before I updated minio for the security fix.
It also works with same credentials via mc

**Comment by harshavardhana** [comment]
This is mostly a side affect of #1828

**Comment by dvaldivia** [comment]
I think it's more of a side effect of #1826 @harshavardhana the policy changes wouldn't affect the preview

**Comment by dvaldivia** [comment]
the root cause is some context cancellation
```
E: 2022/04/14 08:37:42 Failed to get Stat() response from server for approve.png: Get "http://localhost:9000/memes/?location=": context canceled
```

**Comment by dvaldivia** [comment]
I can confirm it's a bug caused by #1826 will send a fix
