### ISSUE TITLE
Error authenticating user 400 Bad Request

### ISSUE THREAD

**Issue by duylong** [minio/console#190]
Hi,

I'm deploying MCS-v0.1.1 with Minio-vRELEASE.2020-06-18T02-23-35Z and I have a error on the login page.
```
Error: Unauthorized
```
When I see the MCS log: 
```
Serving mcs at http://[::]:9090
error authenticating user 400 Bad Request
```
No problem when I used mc command in order to create a user:
```
mc admin user list local
enabled    mcs                 mcsAdmin
```

The MCS environments are set:
```
            - name: MCS_ACCESS_KEY
              value: "mcs"
            - name: MCS_SECRET_KEY
              value: "testtest"
            - name: MCS_MINIO_SERVER
              value: "http://minio-service.minio.svc.cluster.local:9000"
```
No network problem, I can ping my MCS_MINIO_SERVER (in ipv6). 
The MCS and Minion deployment environment: Kubernetes-v1.18

Do you have also this issue? Can we have more debug?

Best regards,

**Comment by duylong** [comment]
OK, I can trace the queries. My error gives it:
```
14:00:55.361 [400 Bad Request] sts.AssumeRole minio-service.minio.svc.cluster.local:9000/ fd00              424µs       ↑ 126 B ↓ 638 B
```
No more information...

**Comment by duylong** [comment]
Works with this command:
```
mc admin config set local region name=test-s3
```
I don't understand why Minio no set to my region my declaration:
```
        - name: MINIO_REGION_NAME
          value: us-east-1
```

**Comment by dvaldivia** [comment]
hi @duylong when you are trying to login to Console, are you using a user or MinIO's root credentials?

**Comment by duylong** [comment]
A user ;) 

I have the impression that MCS does not provide a default region if Minio does not have its region_name variable in the config.json.

**Comment by Alevsk** [comment]
Hi @duylong right now, during the login process MCS will make a request to minio asking what is the current configured region (via region key in the minio key/value store) and then use that to authenticate the user.

Can you share some logs from MCS?

**Comment by duylong** [comment]
I don't have any more log in MCS, I put everything previously.

If the region is empty in Minion, what does MCS do?

**Comment by dvaldivia** [comment]
Closed due to inactivity, if it's still a problem please re-open

**Comment by northway** [comment]
Hi!

I'm getting the same error:

```
2021-01-21 18:24:40.136646 I | 2021/01/21 18:24:40 server.go:129: Serving console at http://[::]:9090
21/01/2021 18:24:56 2021-01-21 18:24:56.964188 I | 2021/01/21 18:24:56 error.go:44: original error: invalid Login
21/01/2021 18:24:56 2021-01-21 18:24:56.964277 I | 2021/01/21 18:24:56 error.go:124: debugging error: 400 Bad Request
21/01/2021 18:25:07 2021-01-21 18:25:07.456318 I | 2021/01/21 18:25:07 error.go:44: original error: invalid Login
21/01/2021 18:25:07 2021-01-21 18:25:07.456371 I | 2021/01/21 18:25:07 error.go:124: debugging error: 400 Bad Request
```

I tired with my Minio root credentials and with a test user also.

**Comment by cesararana** [comment]
Hi
It only works if you unset the region of minio server and restart minio:
`mc admin config  set [ALIAS] region name=`

> Hi @duylong right now, during the login process MCS will make a request to minio asking what is the current configured region (via region key in the minio key/value store) and then use that to authenticate the user.
> 
> Can you share some logs from MCS?

**Comment by sidsanders** [comment]
i have hit this as well.
2021-03-15 03:38:01.734363 I | 2021/03/15 03:38:01 error.go:44: original error: invalid Login

followed the setup steps, though i do have some questions  based on how some other folks appear to use some of the env vars
CONSOLE_PBKDF_*  --> plain text or base64 encoded?  are those the only ones that need to be set along with CONSOLE_MINIO_SERVER?  what about CONSOLE_ACCESS_KEY and CONSOLE_SECRET_KEY?  i unset region name as i did have one set, still no luck.  must be something simple i am missing.

as the console user (with role set), i am able to connect using mc or the standard ui (https://:9000).

**Comment by northway** [comment]
With version `v0.6.8` I added the `CONSOLE_MINIO_REGION` environment setting with my region value and it seems to work.

Can someone confirm it?

**Comment by dvaldivia** [comment]
I think setting `CONSOLE_MINIO_REGION` only is needed if the MinIO region is different from the default one, but I need to confirm this

**Comment by northway** [comment]
I'm using a different one and not the `us-east-1`.

**Comment by ruben-herold** [comment]
hi,

same problem here withe console 0.7.4 an minio  RELEASE.2021-05-27T22-06-31Z:

[minio@wgs-minio-01 bin]$ ./mc admin config get wgs region
region name= 

But i can't login with console. If I make an tcpdump on lo I get the message that the region is wrong.
I also add export CONSOLE_MINIO_REGION=us-east-1. It does not help.


[log.pcap.log](https://github.com/minio/console/files/6571316/log.pcap.log)

**Comment by yelhouti** [comment]
facing the same bug here, can not login to console due to 400 bad request

**Comment by Bacto** [comment]
Hi,

Same problem here.
I set the the region, restart the server (kill MinIO server and start it, it seems that the "soft" restart doesn't provoc the bug). Then when trying to connect again with MinIO Console I get "The authorization header is malformed; the region is wrong; expecting 'us-east-1'".

If I reset the region to an empty string using the CLI, it works then.
