### ISSUE TITLE
Upload directory with nested directories doesn't work correctly

### ISSUE THREAD

**Issue by dnskr** [minio/console#1946]
I found that directory upload doesn't work correctly and result structure depends on file names.

### Test case 1
Upload _test_ folder with the following structure to _my_images_ bucket
```
test/aaa.jpeg
test/in_test/bbb.jpeg
```
gives/expected
```
my_images/test/aaa.jpeg
my_images/test/bbb.jpeg
-------------------------------
my_images/test/aaa.jpeg
my_images/test/in_test/bbb.jpeg
```

### Test case 2
Upload _test_ folder with the following structure to _my_images_ bucket
```
test/ccc.jpeg
test/in_test/bbb.jpeg
```
gives/expected
```
my_images/test/in_test/ccc.jpeg
my_images/test/in_test/bbb.jpeg
-------------------------------
my_images/test/ccc.jpeg
my_images/test/in_test/bbb.jpeg
```

**Comment by harshavardhana** [comment]
looks like the dirname is ignored instead only `basename` is used.

**Comment by dnskr** [comment]
Not in test case 2.

**Comment by harshavardhana** [comment]
yeah its using dirname of the sorted first file.
