### ISSUE TITLE
admin console page blank, timeout, over glusterfs (probably slow filesystem)

### ISSUE THREAD

**Issue by sgalam** [minio/console#1952]
Hi, 

we have an issue with the docker image "minio/minio:RELEASE.2022-04-30T22-23-53Z" (and all the latest build of 2022, no issues with oldest ones of 2021).

My minio is running standalone into a container with the /data mounted. The path of /data belong to a mounted volume of a glusterfs.

The issue is that the the web admin console is not correctly shown. After the login (that works fine) the page remain blank.

I see the last request of the browser to:
https://[myminiourladmin]/api/v1/session and it's stuck in pending status for lot of time and then fails.

We did a lots of tests and the issue seems related to the glusterfs that probably it's too slow and the console is doing something that takes lot of time to be completed. If we try to copy the data content outside the glusterfs to a local folder of the server, the console opens correctly and immediately.

In my data directory I have:
$ find . -type d |wc -l
13727
$ find . -type f |wc -l
27314
$ du -hs
3.7G	.

Someone can help me to understand and find a workaround/solution to the issue?

Thanks

Matteo

**Comment by mtumidei** [comment]
same behavior here. :(

**Comment by vadmeste** [comment]
Saying that moving data to another location fixes the issue is enough to prove something is wrong with your glusterfs setup, unless you did not copy all the data (missing .minio.sys?)

Is this a standalone setup ? `mc admin trace --all <alias>` can help figuring out what is not slow or not responding

**Comment by bexsoft** [comment]
We made improvements to list objects listing in the latest version of Console. (https://github.com/minio/console/pull/2419)

Please reopen this issue if it is still visible.
