### ISSUE TITLE
Cannot login unless policy allows "admin:ConfigUpdate"

### ISSUE THREAD

**Issue by phucduong86** [minio/console#200]
Hi,

I'm trying to create a user that is scoped to creating user/group/policy but not update any of the server's configurations.
This is my current policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "admin:StorageInfo",
        "admin:DataUsageInfo",
        "admin:ServerInfo",
        "admin:ConfigUpdate",
        "admin:CreateUser",
        "admin:DeleteUser",
        "admin:ListUsers",
        "admin:EnableUser",
        "admin:DisableUser",
        "admin:GetUser",
        "admin:AddUserToGroup",
        "admin:RemoveUserFromGroup",
        "admin:ListGroups",
        "admin:EnableGroup",
        "admin:DisableGroup",
        "admin:CreatePolicy",
        "admin:DeletePolicy",
        "admin:GetPolicy",
        "admin:AttachUserOrGroupPolicy",
        "admin:ListUserPolicies"
      ],
      "Effect": "Allow",
      "Sid": ""
    },
    {
      "Action": [
        "s3:*"
      ],
      "Effect": "Deny",
      "Resource": [
        "arn:aws:s3:::*"
      ],
      "Sid": ""
    }
  ]
}
```

Now I want to remove ```"admin:ConfigUpdate"``` from the list of actions (hence remove this user's access to update configuration). However as soon as I do that I get the following error:

```
Error: {"code":401,"message":"an error occurred, please try again"}
```

**Comment by phucduong86** [comment]
![image](https://user-images.githubusercontent.com/21692768/88243850-bb9fe880-cc5f-11ea-9beb-c2935e8b554f.png)

**Comment by Alevsk** [comment]
I'll take a look and try to replicate

**Comment by Alevsk** [comment]
@phucduong86 can you try this with the latest version of `Console`, I couldn't replicate the issue, I create a new IAM Policy using the json you provided, then create a new user and assigned the policy to him and finally I logged in as that user without seeing any issue.

Please re-open if you still seeing the issue, also if you can provide some logs from console that would help.
