### ISSUE TITLE
Can a normal user change himself's password?

### ISSUE THREAD

**Issue by HaoLiuHust** [minio/console#2005]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

I am upgrade from RELEASE.2021-04-06T23-11-00Z.hotfix.e46577116 which was old Web UI, a normal user can change himself's password, but when use the latest version, I can not find where can a normal user change himself's password
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-05-08T23-50-31Z.fips
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by mshanmu** [comment]
On the left nav, click Identity -> Service Accounts, in the Service Accounts Page, you can see the Change Password button in the upper right corner.

**Comment by harshavardhana** [comment]
@dvaldivia can we make this more apparent - changing password is perhaps not in the right place for the "logged" in user.

**Comment by HaoLiuHust** [comment]
> > > On the left nav, click Identity -> Service Accounts, in the Service Accounts Page, you can see the Change Password button in the upper right corner.
> > 
> > 
> > so if someone want to change his password, he should create a service account at first?
> 
> Not needed. Just the functionality is present in the Service Accounts Page.

I tried.. if the user did not create a service account, he can not click the change password button:
![image](https://user-images.githubusercontent.com/7233091/168737489-4746ceea-0374-4e54-8eb0-5e63a5e6c3a4.png)

**Comment by dvaldivia** [comment]
yeah we can make it more apparent @harshavardhana , perhaps we should push it to the bottom left of the Menu, we'll review with @oscarocastellanos and see what we come up with

**Comment by mshanmu** [comment]
> > > > On the left nav, click Identity -> Service Accounts, in the Service Accounts Page, you can see the Change Password button in the upper right corner.
> > > 
> > > 
> > > so if someone want to change his password, he should create a service account at first?
> > 
> > 
> > Not needed. Just the functionality is present in the Service Accounts Page.
> 
> I tried.. if the user did not create a service account, he can not click the change password button: ![image](https://user-images.githubusercontent.com/7233091/168737489-4746ceea-0374-4e54-8eb0-5e63a5e6c3a4.png)

Check the users page then.

**Comment by HaoLiuHust** [comment]
> > > > > On the left nav, click Identity -> Service Accounts, in the Service Accounts Page, you can see the Change Password button in the upper right corner.
> > > > 
> > > > 
> > > > so if someone want to change his password, he should create a service account at first?
> > > 
> > > 
> > > Not needed. Just the functionality is present in the Service Accounts Page.
> > 
> > 
> > I tried.. if the user did not create a service account, he can not click the change password button: ![image](https://user-images.githubusercontent.com/7233091/168737489-4746ceea-0374-4e54-8eb0-5e63a5e6c3a4.png)
> 
> Check the users page then.

![image](https://user-images.githubusercontent.com/7233091/168936651-2e088cff-1c0b-4664-9c7f-af80c9a69a0b.png)
 can do nothing in the users page

**Comment by mshanmu** [comment]
> > > > > > On the left nav, click Identity -> Service Accounts, in the Service Accounts Page, you can see the Change Password button in the upper right corner.
> > > > > 
> > > > > 
> > > > > so if someone want to change his password, he should create a service account at first?
> > > > 
> > > > 
> > > > Not needed. Just the functionality is present in the Service Accounts Page.
> > > 
> > > 
> > > I tried.. if the user did not create a service account, he can not click the change password button: ![image](https://user-images.githubusercontent.com/7233091/168737489-4746ceea-0374-4e54-8eb0-5e63a5e6c3a4.png)
> > 
> > 
> > Check the users page then.
> 
> ![image](https://user-images.githubusercontent.com/7233091/168936651-2e088cff-1c0b-4664-9c7f-af80c9a69a0b.png) can do nothing in the users page

@HaoLiuHust ,  It looks like there is a change password bug, which got fixed in https://github.com/minio/console/pull/1973. This is NOT yet released. @jinapurapu , can you confirm?

**Comment by HaoLiuHust** [comment]
RELEASE.2022-05-23T18-45-11Z.fips release fix it,   thanks
