### ISSUE TITLE
can't preview text/plain files without .txt extension

### ISSUE THREAD

**Issue by buptzhoutian** [minio/console#2021]
For example, one file named `service.log` was uploaded to MinIO, the Content-Type of this object is "text/plain".

This `service.log` file can't be previewed. However, the same file uploaded as `service.log.txt` can be previewed.

**Comment by prakashsvmx** [comment]
It depends on browsers too.

e.g
`.log`
 Chrome can load `.log` files in an iframe for Preview 
 Firefox Will not load.

`.txt`
for `.txt` both browsers will display.

**Comment by prakashsvmx** [comment]
as per code the below are the supported extensions for preview.

```javascript
export const extensionPreview = (
  fileName: string
): "image" | "text" | "audio" | "video" | "none" => {
  const imageExtensions = [
    "jif",
    "jfif",
    "apng",
    "avif",
    "svg",
    "webp",
    "bmp",
    "ico",
    "jpg",
    "jpe",
    "jpeg",
    "gif",
    "png",
    "heic",
  ];
  const textExtensions = ["pdf", "txt", "json"];
  const audioExtensions = ["wav", "mp3", "alac", "aiff", "dsd", "pcm"];
  const videoExtensions = [
    "mp4",
    "avi",
    "mpg",
    "webm",
    "mov",
    "flv",
    "mkv",
    "wmv",
    "avchd",
    "mpeg-4",
  ];

```

**Comment by dvaldivia** [comment]
We stopping previewing text files for security reasons. The alternative is to generate a share link and paste it in another tab.
