### ISSUE TITLE
MinIo Console - New path name gets saved as obscure character 

### ISSUE THREAD

**Issue by Schuits** [minio/console#2048]
## Expected Behavior
Creating a new sub path, the original path name should not change when saved

## Current Behavior
Creating a new path within a path called 'Stage', the path 'Stage' gets changed to a strange character.

## Steps to Reproduce (for bugs)

1. Create a bucket 'testbucket'
2. Create a path in the bucket named 'Stage'
3. Create a path in the 'Stage' path named 'Test'
4. The 'Stage' path name gets obscured to J֠
5. An example of a link to a file in such a path "http://172.17.0.2:9000/testbucket/J%D6%A0%7B/Test/touch.txt"

## Context
Cannot use a path named 'Stage' 

## Regression
No

## Your Environment

* Version used (`minio --version`): MinIO VERSION 
2022-04-16T04:26:02Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Windows10

**Comment by bexsoft** [comment]
Issue not reproducible on Chrome, MacOS 12.4 & latest version of MinIO.
<img width="1154" alt="Screen Shot 2022-05-30 at 23 57 08" src="https://user-images.githubusercontent.com/33497058/171095955-ca2eb8d8-e45a-4088-97b9-fae3394ec6ec.png">
<img width="1705" alt="Screen Shot 2022-05-30 at 23 57 01" src="https://user-images.githubusercontent.com/33497058/171095958-7d8f2cd4-c4b0-49db-8b86-c1e62ce19120.png">
<img width="1707" alt="Screen Shot 2022-05-30 at 23 56 50" src="https://user-images.githubusercontent.com/33497058/171095962-a08b97f5-fc9e-4705-b9ba-45bc25b6eee9.png">
<img width="1696" alt="Screen Shot 2022-05-30 at 23 56 39" src="https://user-images.githubusercontent.com/33497058/171095965-08ed69b6-deb9-40f3-8e06-fd8ea0159788.png">
<img width="1707" alt="Screen Shot 2022-05-30 at 23 56 31" src="https://user-images.githubusercontent.com/33497058/171095970-60ac8b80-0707-4885-a537-1dfc7dfe2933.png">

**Comment by bexsoft** [comment]
Hi @Schuits!, 

Would you please help us to provide the browser version that you are using?

Thank you!

**Comment by Schuits** [comment]
Chrome : Version 102.0.5005.62 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/27768399/171113298-d159545c-02d8-4df0-b062-5b65dd4ad622.png)
![image](https://user-images.githubusercontent.com/27768399/171113563-48985061-fdf5-4e88-b828-71bc38ab2a78.png)

**Comment by RobertSchuitemaker** [comment]
I probably should have mentioned I'm using a docker image of Minio
I've update the docker image to MinIO VERSION 2022-05-26T05:48:41Z
The issue now seems to be gone. 

Thanks for the support.

**Comment by bexsoft** [comment]
No problem @RobertSchuitemaker! Thank you for the confirmation! =D

Have a nice day!
