### ISSUE TITLE
Secrets are not being deleted on tenant deletion

### ISSUE THREAD

**Issue by cesnietor** [minio/console#206]
Delete tenant api must delete tenants' secrets as well

**Comment by dvaldivia** [comment]
When we delete a tenant the underlying PVC remains, thus not permanently deleting the data, if that data was encrypted the original keys would be needed to be kept, this is for the MinIO secrets, however for mcs secrets we can delete it

**Comment by harshavardhana** [comment]
> When we delete a tenant the underlying PVC remains, thus not permanently deleting the data, if that data was encrypted the original keys would be needed to be kept, this is for the MinIO secrets, however for mcs secrets we can delete it

But I think the issue was perhaps when the reclaim policy on PV is delete them secrets should go as well.

If PV has Retain policy then we should keep the secrets and add it back to the same deployment.

**Comment by cesnietor** [comment]
solved on https://github.com/minio/console/pull/253
