### ISSUE TITLE
User with readonly policy can't access buckets

### ISSUE THREAD

**Issue by mieseprem** [minio/console#2073]
We configured MinIO to use OpenID authentication by providing the following env variables:
* MINIO_IDENTITY_OPENID_CLAIM_NAME
* MINIO_IDENTITY_OPENID_CLIENT_ID
* MINIO_IDENTITY_OPENID_CLIENT_SECRET
* MINIO_IDENTITY_OPENID_CONFIG_URL

A user with policy readwrite can access buckets and upload/download files.
A user with policy readonly can see how many files are within bucket but can't access it. Click on 'Browse' doesn't go anywhere but remain on bucket overview page.

## Expected Behavior

Click on 'Browse" step into bucket and show it's content.

## Current Behavior

A user with policy readonly can see on bucket overviwe page how many files are within bucket but can't access it. Click on 'Browse' doesn't go anywhere but remain on bucket overview page.

## Possible Solution

not known

## Steps to Reproduce (for bugs)

Only set readonly policy to a user/group and login.

## Context

Users with readonly policy can't access files right now. Our workaround is to grant readwrite policy to users and kindly ask them to not do harmfull things. But we would like to set it back to readonly as soon as possible

## Regression

Maybe this was already found with minio/minio#14045 but due to missing information in Issue not solved.

## Your Environment

We use RELEASE.2022-05-26T05-48-41Z right now as Docker Conainer with Fedora Linux base image.

**Comment by mieseprem** [comment]
Hey Harshavardhana, this is the default readonly policy. We didn't create it by our own. Isn't it shipped with MinIO?
However, I will use mc admin to get policy details and provide output here.

**Comment by mieseprem** [comment]
> $ mc admin policy info myminio readonly

```json
{
    "PolicyName": "readonly",
    "Policy": {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "s3:GetBucketLocation",
                    "s3:GetObject"
                ],
                "Resource": [
                    "arn:aws:s3:::*"
                ]
            }
        ]
    }
}
```

This is the information you need?

**Comment by mieseprem** [comment]
This is how it looks like (webm screencast
[Screencast from 02.06.2022 15:57:55.zip](https://github.com/minio/console/files/8824574/Screencast.from.02.06.2022.15.57.55.zip)
)

**Comment by mieseprem** [comment]
Hello @harshavardhana , I am confused now. Isn't the policy the official policy to grant users read-only access?
The policy is supplied by MinIO and therefore we have always used it so far. Maybe something just happened to work the way we needed it to. And you are right, the [documentation](https://docs.min.io/minio/baremetal/security/minio-identity-management/policy-based-access-control.html#userpolicy.readonly) describes that a listing of the objects in a bucket is not intended.
What do we have to change to restore the old behaviour (users can log in, see the contents of buckets and download files)? Is only `s3:ListBucket` missing in policy?

For my understanding, was in last 2 month a commit done that "fixed" the readonly policy that the policy does exactly what the documentation says?

**Comment by harshavardhana** [comment]
> Hello @harshavardhana , I am confused now. Isn't the policy the official policy to grant users read-only access? The policy is supplied by MinIO and therefore we have always used it so far. Maybe something just happened to work the way we needed it to. And you are right, the [documentation](https://docs.min.io/minio/baremetal/security/minio-identity-management/policy-based-access-control.html#userpolicy.readonly) describes that a listing of the objects in a bucket is not intended. What do we have to change to restore the old behaviour (users can log in, see the contents of buckets and download files)? Is only `s3:ListBucket` missing in policy?
> 
> For my understanding, was in last 2 month a commit done that "fixed" the readonly policy that the policy does exactly what the documentation says?

Yes but it presented itself to allow only 'read' access i.e GetObject if you want more then you need to ask for more actions to be allowed.
