### ISSUE TITLE
Performance Test cannot start if TLS Cert doesnt have an IP SAN

### ISSUE THREAD

**Issue by sma777** [minio/console#2103]
![2022-06-08_15h44_52](https://user-images.githubusercontent.com/107125113/172633241-ea082aa3-893f-41ca-a8fd-8c6442436286.png)

As shown in the screenshot, the Performance test cannot be started, even though the MINIO_SERVER_URL="https://my.server.here:9000" has been set. Thus im able to access the console.

Is there any possibility of telling the console to use the MINIO_SERVER_URL here instead?

**Comment by sma777** [comment]
@harshavardhana 

Hello,

Im running a Standalone Binary server, which runs the API and the Console, if that is what you asked.

I have downloaded the Binary with this command:
wget https://dl.min.io/server/minio/release/linux-amd64/minio

**Comment by harshavardhana** [comment]
how is your MINIO_SERVER_URL set? @sma777

**Comment by sma777** [comment]
@harshavardhana 

Hello,

I have created a config file in /etc/default called "minio" which I have passed as a Path in the "minio.service" file as "EnvirormentFile=/etc/default/minio"

I know the file is working since without that Variable i cannot login to the Console since it gives me the same error then.

**Comment by harshavardhana** [comment]
> I have created a config file in /etc/default called "minio" which I have passed as a Path in the "minio.service" file as "EnvirormentFile=/etc/default/minio"

Please paste your `cat /etc/default/minio` and lets see if MINIO_SERVER_URL is set properly.

**Comment by dvaldivia** [comment]
We do honor the `MINIO_SERVER_URL` @harshavardhana, if we weren't, we usually default to `localhost:9000`

**Comment by prakashsvmx** [comment]
With latest releases, Performance Tests can be run with  registration of cluster in  SUBNET with a valid subscription only.  Please have a look at https://min.io/pricing.
