### ISSUE TITLE
Console logged out when trying to set policy for a bucket

### ISSUE THREAD

**Issue by HansBug** [minio/console#2112]
We are trying to deploy the latest version of minio in the intranet server. However, when the policy is set for the new bucket, the console will directly exit to the login page and the session will be lost.

On this server, we tried to deploy stand-alone applications with docker-compose, deploy distributed applications with docker-compose, and directly install deb package and then start it up. This phenomenon still occurred.

We tried to analyze the interfaces' behavior. The `PUT /api/v1/buckets/test1/set-policy` returns 302 in the Network of the Chrome browser, and its redirect target is http://1.1.1.2/disable/disable2.htm . Then the session is logged out and the policy is not changed when we logged in back.

![0d2f62c70d06f5bf367160b296dba23](https://user-images.githubusercontent.com/20508435/173051074-a15836b3-fe96-42a0-9306-5859f66875d9.png)
![ab38b4bbed776e288f3979ae3f1b81c](https://user-images.githubusercontent.com/20508435/173051089-487309e2-a32f-4126-bbd6-8069f551ed2c.png)
![85050f434d92e84f3c5482e040b2c81](https://user-images.githubusercontent.com/20508435/173051105-0f7bed05-1e9c-4b0a-9f15-06b0774ab26b.png)
![663f5d2dda7d648e90854a374214b0f](https://user-images.githubusercontent.com/20508435/173051125-51eb71c6-352b-46ee-870b-e3f9b1e64b36.png)

After that, we tried to install minio directly with the deb package and run it on the personal computer, but this problem did not occur. The above interface returned 200 normally and the policy was successfully modified.

What could be the problem please? It doesn't seem to be a problem with the operating environment. Any suggestions?

**Comment by dvaldivia** [comment]
the 302 is very odd, I don't think we have anything to redirect upon policy failure, are you still experiencing this problem? what is the policy you are trying to set?

can you provide the steps to replicate

**Comment by dvaldivia** [comment]
the 302 is very odd, I don't think we have anything to redirect upon policy failure, are you still experiencing this problem? what is the policy you are trying to set?

can you provide the steps to replicate

**Comment by dvaldivia** [comment]
Cannot reproduce, but a problem related to errors being returned by the backend logged you has been fixed a while back.

It's recommended to install MinIO by downloading it from our website, perhaps the `deb` package you installed was a little outdated
