### ISSUE TITLE
Configure few login options to Minio Console

### ISSUE THREAD

**Issue by valterartur** [minio/console#2135]
Hi!

I've connected OIDC to my Minio Console with Keycloak as provider. Everything works as expected and at login page I can see button "Login With SSO". 
In same time we need ability to save possibility of basic auth with access key and secret key. 
As I didn't found any way to do it in documentation and discussions about it. I'm creating this request.
If it's implemented let me please know how to do it and close the issue.
Thanks.

**Comment by sebastian-luna-valero** [comment]
Hi,

Then, after configuring OIDC, the minio admin cannot log back in via the web console (since it's using local credentials).

The only solution at the moment is to fall back to the CLI?

Thanks,
Sebastian

**Comment by MrArabboy** [comment]
I had the same issue and to back basic auth use command below:
`mc admin idp openid disable local`
and then 
`mc admin service restart {TARGET}`

**Comment by bexsoft** [comment]
Added multi IDP login support in https://github.com/minio/console/pull/2758, https://github.com/minio/console/pull/2695 & https://github.com/minio/console/pull/2807. Closing this issue, Please feel free to reopen if issue persists

**Comment by sebastian-luna-valero** [comment]
Thank you very much!
