### ISSUE TITLE
Can't enter the Chinese directory in the console

### ISSUE THREAD

**Issue by vinsonzou** [minio/console#2151]
Version: RELEASE.2022-06-25T15-50-16Z

Can't enter the Chinese directory in the console, access the Chinese directory and automatically jump to the bucket page.

**Comment by bexsoft** [comment]
Hi @vinsonzou!

Do you have an example of the folder name you are trying to use?

Thank you in advance!

**Comment by vinsonzou** [comment]
current folder name: 工具，浏览器，输入法

**Comment by IamMaxim** [comment]
Version: RELEASE.2022-07-06T20-29-49Z

I have the same problem with Cyrillic names of files and directories.
