### ISSUE TITLE
OIDC login flaky starting with console v0.19.2

### ISSUE THREAD

**Issue by Timost** [minio/console#2214]
Hi, 
First of all thank you for minio 🙏.

I've been going through a round of upgrades on my minio clusters and I'm facing a flaky behaviour with OIDC login on the console.

The behaviour can be described as follows:
- login flows works perfectly fine until the `api/v1/login/oauth2/auth` call at the end were I get an "Error from IDP", "Invalid Login"
- At that point, refreshing the page (one or more times until it works) succesfully logs me in.

The behaviour is flaky in the sense that 1 out of 10 logins works successfully on first try.

I've spent some time digging into the issue and it seems it was introduced with [release v.0.19.2](https://github.com/minio/console/pull/2194) and minio's side with [RELEASE.2022-07-24T01-54-52Z](https://github.com/minio/minio/tree/RELEASE.2022-07-24T01-54-52Z). This is still present on [the latest available release (RELEASE.2022-07-30T05-21-40Z) ](https://github.com/minio/minio/releases/tag/RELEASE.2022-07-30T05-21-40Z).

 I'm suspecting https://github.com/minio/console/commit/118cf97e1d2313fe67839210706c45fcb5ed4e1d but I have no definite proof this is the cause of the problem.

**Comment by donatello** [comment]
Could you check:
1. that all minio nodes in your cluster are in the same (latest) version?
2. if there is more detail in the minio logs?

Could you also share the IDP configuration in MinIO and details of your MinIO deployment (e.g. node count, OS, etc) so we can attempt to reproduce this?

**Comment by Timost** [comment]
Hi,
Thank you for the quick reply ! 🙏
> 1. that all minio nodes in your cluster are in the same (latest) version?

```
●  minio-1.priv:9000
   Uptime: 1 minute
   Version: 2022-07-30T05:21:40Z
   Network: 3/3 OK
   Drives: 2/2 OK
   Pool: 1st

●  minio-2.priv:9000
   Uptime: 1 minute
   Version: 2022-07-30T05:21:40Z
   Network: 3/3 OK
   Drives: 2/2 OK
   Pool: 1st

●  minio-3.priv:9000
   Uptime: 1 minute
   Version: 2022-07-30T05:21:40Z
   Network: 3/3 OK
   Drives: 2/2 OK
   Pool: 1st
```

Yes all nodes are in the same (latest) version, I use an orchestration system to deploy the minio nodes. 
I've tried several versions to pinpoint the issue though.
The console and minio are running within the same rootless podman container (no separate console instance).
There is a load-balancer in front of the minio cluster (and the console) that round-robins the requests to the cluster nodes.

> 2. if there is more detail in the minio logs?

The only logs I get (sometimes, not always) are:
```
Aug 01 10:57:03 minio-1 conmon[3654431]: found ${jwt:sub}
Aug 01 10:57:03 minio-1 conmon[3654431]: found ${jwt:iss}
Aug 01 10:57:03 minio-1 conmon[3654431]: found ${jwt:aud}
Aug 01 10:57:03 minio-1 conmon[3654431]: found ${jwt:name}
Aug 01 10:57:03 minio-1 conmon[3654431]: found ${jwt:groups}
Aug 01 10:57:03 minio-1 conmon[3654431]: found ${jwt:email}
```

I was expecting to have console errors show up in the logs but I can't find anything.
I'm using [podman's journald driver](https://docs.podman.io/en/latest/markdown/podman-run.1.html#log-driver-driver)

The fact that the login can finish successfully after one or more browser refresh is quite intriguing.
Do you think it depends on which minio server receives the request ?

Another thing to note is that the first login after a cluster reboot always succeeds directly. Subsequent logins then fail almost systematically

**Comment by donatello** [comment]
If you are configuring openid for MinIO via env variables, could you make sure they are set identically for all the nodes? In fact, all env vars for minio should be identical for all nodes in the same deployment.

After making sure of this, could you:

1. start a trace with `mc admin trace -v -a myminio`
2. make a login attempt (where it fails and then succeeds if possible)
3. share the trace output here?

**Comment by Timost** [comment]
> If you are configuring openid for MinIO via env variables, could you make sure they are set identically for all the nodes? In fact, all env vars for minio should be identical for all nodes in the same deployment

👍I manually checked on all cluster nodes, env vars are indeed the same on every node. Is there another way of configuring OIDC apart from env vars ?

Here is the trace, I had to refresh two times to have a successful login (this is coherent with the 3 node cluster where 2 of the nodes can't finish the login)
[trace.log](https://github.com/minio/console/files/9240124/trace.log)

**Comment by Timost** [comment]
Alright,

I tried enabling session stickiness on my load-balancer and **it solves the issue** 👍.
So the issue is probably that the login flow needs to run on the same node from start to finish.

I am not sure if this is a desirable behaviour though and also not sure what introduced that new behaviour.
I'm pretty sure the changed happened on minio's side though since rolling back the version makes this behaviour disappear.

**Comment by harshavardhana** [comment]
> I am not sure if this is a desirable behaviour though and also not sure what introduced that new behaviour.

It is not a new behavior the Cookies require that you use sticky sessions for Console logins. The behavior is due to Console's reliance on Cookies but that is the cleanest approach here.

Our nginx examples talk about how Console service must be using sticky sessions based on the same clientIP

```
    upstream console {
        ip_hash;
        server minio1:9001;
        server minio2:9001;
        server minio3:9001;
        server minio4:9001;
    }
```

**Comment by Timost** [comment]
Ha I missed this [blog post](https://blog.min.io/minio-nginx-letsencrypt-certbot/), sorry for the noise 🙏 and thank you for the quick replies !

It's weird the login worked before without session stickiness.
