### ISSUE TITLE
Invalid Login.  Elliptic Curve P-384

### ISSUE THREAD

**Issue by njavilas2015** [minio/console#2223]
After a certificate update Let's Encrypt interface cannot be accessed

![image](https://user-images.githubusercontent.com/47610140/182702159-8e2bac75-a7a7-4fb9-ac63-5a587443666e.png)

## Environment
minio/minio:RELEASE.2022-08-02T23-59-16Z

**Comment by njavilas2015** [comment]
Now I will try to see if I can access through api, and I will update the problem

**Comment by njavilas2015** [comment]
the api does not work invalidates the connection
```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: s3.jwit.ar. is not in the cert's altnames:

```

**Comment by harshavardhana** [comment]
> Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: s3.jwit.ar. is not in the cert's altnames:

Your cert is wrong for the DNS @njavilas2015
