### ISSUE TITLE
Error message for the invalid site replication endpoint takes too long to get displayed.

### ISSUE THREAD

**Issue by bh4t** [minio/console#2228]
Actual Behavior:

- On entering an invalid port at the site replication endpoint, the error message
   takes more than 30 s to get displayed.
- The message doesn't stay on the page or gets hidden after few secs.

Expected Behavior:

Can the message be displayed for longer/stay on page for better experience?
Can the error message get displayed within 10s?

Steps to Reproduce:
- On the site replication page, enter access key and secret key
- Enter site name and Console port instead of API port.
- Click save.

minio version RELEASE.2022-08-02T23-59-16Z (commit-id=76f950c6632fe67b17e9f0cc00905d7093ef837d)

**Comment by cniackz** [comment]
Ok, I will start by reproducing this issue and documenting the reproduction. Then based on that I will take the next step.

**Comment by cniackz** [comment]
Creating the replication: 

![Screenshot 2023-06-14 at 12 39 59 PM](https://github.com/minio/console/assets/6667358/f58f91e8-762c-417a-8c16-79b20477f166)

**Comment by cniackz** [comment]
Replication created:

![Screenshot 2023-06-14 at 12 40 25 PM](https://github.com/minio/console/assets/6667358/533b9651-284b-41df-8c27-9a4e4c6921af)

**Comment by cniackz** [comment]
Add wrong replication as suggested in this issue:

![Screenshot 2023-06-14 at 12 42 11 PM](https://github.com/minio/console/assets/6667358/75530dfd-af76-4bbb-b66f-7e6479a476cf)

**Comment by cniackz** [comment]
Got error right away:

![Screenshot 2023-06-14 at 12 42 27 PM](https://github.com/minio/console/assets/6667358/21380df9-a3f9-4d3c-983d-b2b4134d4029)

**Comment by cniackz** [comment]
```
Can the message be displayed for longer/stay on page for better experience?
```

This is a good petition, error goes away after few seconds, this is still same. Let me ask this internally and get back to you.
