### ISSUE TITLE
Outer border showing list of sites overlaps with the text within it.

### ISSUE THREAD

**Issue by bh4t** [minio/console#2230]
The outer border of the Box displaying the list of replicated sites
overlaps with the text within.

Attaching the screenshot
![Screenshot from 2022-08-05 13-52-27](https://user-images.githubusercontent.com/109562845/183188826-4eb9beee-74ae-44f4-a91d-274f4ed4a441.png)

minio version RELEASE.2022-08-02T23-59-16Z (commit-id=76f950c6632fe67b17e9f0cc00905d7093ef837d)

**Comment by dvaldivia** [comment]
thanks for the report, what browser+os are you using?

**Comment by bh4t** [comment]
@dvaldivia  ah, I should have mentioned that. Its on Linux and chrome browser.
