### ISSUE TITLE
download method need use  subpath

### ISSUE THREAD

**Issue by dockerclubs** [minio/console#2234]
i find preview buttom use method like  ：
 let basename = document.baseURI.replace(window.location.origin, "");
 path = `${window.location.origin}${basename}api/v1/buckets/${bucketName}/objects/download?preview=true&prefix=${encodedPath}`;
but download has not use basename!
 now like that :
 let path = `/api/v1/buckets/${bucketName}/objects/download?prefix=${objectPath}${
    overrideFileName !== null && overrideFileName.trim() !== ""
      ? `&override_file_name=${encodeURLString(overrideFileName || "")}`
      : ""

**Comment by ryanmelt** [comment]
dup of #2272
