### ISSUE TITLE
500 unknown sub-system # after setting up LDAP

### ISSUE THREAD

**Issue by y-young** [minio/console#2247]
## Version
```
minio version RELEASE.2022-08-13T21-54-44Z (commit-id=49862ba3470335decccecb27649167025e18c406)
Runtime: go1.18.5 linux/amd64
```

## Steps to reproduce
- Setup LDAP
```bash
export MINIO_IDENTITY_LDAP_SERVER_ADDR=ldap.forumsys.com:389
export MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN='cn=read-only-admin,dc=example,dc=com'
export MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=password
export MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN='dc=example,dc=com'
export MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER='(uid=%s)'
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
export MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER='(&(objectClass=groupOfUniqueNames)(uniquemember=%d))'
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN='dc=example,dc=com'
```
- Start MinIO server: `./minio server ./data --console-address ":9001"`
- Open http://localhost:9001/settings/configurations/identity_ldap
- Received error from http://localhost:9001/api/v1/configs/identity_ldap:
```json
{"code":500,"detailedMessage":"unknown sub-system #","message":"an error occurred, please try again"}
```

PS: `minio version RELEASE.2022-07-08T00-05-23Z (commit-id=ed0cbfb31e00644013e6c2073310a2268c04a381)` works fine.

**Comment by harshavardhana** [comment]
> * Received error from http://localhost:9001/api/v1/configs/identity_ldap:

This looks like a bug in console UI

**Comment by maclermo** [comment]
Having the same issue with the same release but we are not using LDAP.

`{"code":500,"detailedMessage":"unknown sub-system #","message":"an error occurred, please try again"}`

**Comment by donatello** [comment]
Thanks, we're working on fixing this bug.
