### ISSUE TITLE
EOF on creating new policy in GUI

### ISSUE THREAD

**Issue by udf2457** [minio/console#2257]
I am getting EOF when attempting to create a new policy in the GUI.  Am logged in as  `MINIO_ROOT_USER`.

Other than the issue at hand, I might point out that simply erroring `EOF` with no context is not a helpful error !

<img width="1050" alt="Screenshot 2022-08-22 at 10 38 39" src="https://user-images.githubusercontent.com/6958684/185890954-35269a77-5b10-425b-b7af-c29ada3fbc9b.png">

## Your Environment
minio version RELEASE.2022-08-13T21-54-44Z (commit-id=49862ba3470335decccecb27649167025e18c406)
Runtime: go1.18.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
Linux mio1 5.10.0-17-amd64 minio/minio#1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux

**Comment by bexsoft** [comment]
Not a defect, You must write a policy in the Write Policy field.

Will create a new PR to highlight this field as it is not noticeable

**Comment by udf2457** [comment]
@bexsoft Well, it's a defect insofar that `EOF` is a completely unhelpful error message.
