### ISSUE TITLE
Subpath not working for download links

### ISSUE THREAD

**Issue by vmire** [minio/console#2272]
Subpath feature works except for download links, which ignores it.

I use the latest docker image (minio/minio:latest)
Environment :
```
MINIO_BROWSER_REDIRECT_URL: 'http://localhost:8080/minio/'
```
Reverse proxy rewrite : 
```
"proxy-rewrite": {
      "regex_uri": [
        "^/minio/(.*)",
        "/$1"
      ]
    }
```

Console URL : http://localhost:8080/minio/
=> works fine
Generated download link example : http://localhost:8080/api/v1/buckets/orgo/objects/download?prefix=ZmlsZXMvU3ludGglQzMlODMlQzIlQThzZSUyMGRlJTIwR2FyYW50aWVzLTIucGRm&version_id=null
=> doesn't work : subpath is missing

_Originally posted by @vmire in https://github.com/minio/console/issues/2045#issuecomment-1227189017_

**Comment by LiuYuWei** [comment]
Same Question as this. Does anyone know how to solve it?

**Comment by ryanmelt** [comment]
Same Issue.  Share urls are also incorrect and show internal ip address.
I think an additional environment variable is needed to provide the console with the correct external path to download or share files.
