### ISSUE TITLE
Different files, but with similar file prefixes. more versions

### ISSUE THREAD

**Issue by CxistHans** [minio/console#2274]
## NOTE
Different files, but with similar file prefixes. more versions

## Expected Behavior
config history only v1

## Current Behavior
![image](https://user-images.githubusercontent.com/52312956/186812361-50361c57-f3b5-4955-a5c8-860484358ec1.png)

## Steps to Reproduce (for bugs)
Prepare:
1. One file is named "config"（non empty）
2. the other is named "config2" （non empty）
3. Create a new bucket（versioning）, upload config times in the root directory once, upload config2 twice, and look at the version history of config

## Your Environment

docker swarm:  minio/minio:RELEASE.2022-08-13T21-54-44Z
single node，single drive

**Comment by bexsoft** [comment]
Issue reproduced. Working on a fix for this
