### ISSUE TITLE
Users > "Set Policies" layer does preselect current selected policies 

### ISSUE THREAD

**Issue by tecbird** [minio/console#2282]
We've currenty the problem that the current selected policies are not pre-selected in the layer, so every time when we change policies for a user you have to re-select all existing policies.

Go to "Users", click "Assign Policies" and you see that currently assigned policies are not pre-selected (checkbox is not selected)

Server Version: 2022-08-25T07:17:05Z

It would be great if policies are pre-selected
![Eingefügtes_Bild_29_08_22__17_37](https://user-images.githubusercontent.com/16688055/187239698-d3dc7a2f-442d-4e30-ae01-27af732accbc.png)

**Comment by bexsoft** [comment]
Hi @tecbird! We will be reviewing this.

Issue is not visible if you review policies just after creation, to be able to reproduce it you need to hard refresh and then go into Policies page.
