### ISSUE TITLE
Creating policies may fail silently

### ISSUE THREAD

**Issue by lkiesow** [minio/console#2296]
Creating a policy, I had an invalid version set and therefore, MinIO correctly wouldn't let me set this policy. The problem, however, is that I won't get an error on the interface. When you click “Save”, simply nothing happens. Only going into the developer tools, you will find out that the request fails with an internal server error.

![Screenshot from 2022-09-03 22-00-40](https://user-images.githubusercontent.com/1008395/188321396-7a7acd13-d474-4187-82c4-730ae1cb6349.png)

- From a technical point of view, instead of an internal server error, I would expect this to result in a `400 Bad Request` instead of a `500 Internal Server Error`.
- From a usability point of view, I would expect the user interface to show an error message instead of seemingly doing nothing.

**Comment by bexsoft** [comment]
Hi @lkiesow! Can you please share the MinIO & Console versions that you are using? Thank you!

**Comment by lkiesow** [comment]
Sure. It's the latest stable:

```
❯ minio --version
minio version RELEASE.2022-09-01T23-53-36Z (commit-id=cf52691959f6707337466d8c7d6c774c9ce4c6e6)
```

It's a single node test set-up. I'm not running Console separately.

**Comment by bexsoft** [comment]
Can you please double check your MinIO Version?, The attached screenshot seems to be from a different version

Thank you.

<img width="1411" alt="Screen Shot 2022-09-04 at 12 59 10" src="https://user-images.githubusercontent.com/33497058/188327171-d3c132f0-f3e6-41ed-a84d-45b695da3767.png">

**Comment by lkiesow** [comment]
I'm so sorry. I updated just before testing, but it seems like my browser had the old one cached :see_no_evil: 
I get an error now. Thanks for your answers.
