### ISSUE TITLE
Metrics page blank after disk failure

### ISSUE THREAD

**Issue by jstiops** [minio/console#2304]
i'm testing a 4-disk EC setup, single node.
i'm simulating a disk failure. Disk is confirmed failed and things continue as normal regarding storage and storage access.
After triggering the disk failure, i went to the console and navigated to monitoring->metrics page.
It went completely blank. I tried firefox and edge browser, same behaviour. All other pages seem to work, just not the metrics page.
url is http://ipaddress/tools/metrics

when i initiate a disk recovery, and have it return to active state (mounted etc.), the page starts working again and all is OK.
So seems to be some issue in the metrics page on disk failure scenario?

used minio_20220811043728.0.0_amd64.deb for installation on ubuntu 22.04 LTS fully patched.

**Comment by harshavardhana** [comment]
Can you provide screen shot sample of these situations?

**Comment by jstiops** [comment]
> Can you provide screen shot sample of these situations?

Sure, but what exactly you want me to screenshot? i guess it's not that helpfull to see a completely empty browser tab :)

its basically like this: when "mc admin info local/" shows 1 (out of 4) disk as failed, the web page is completely blank on the mentioned metrics url, and when i restore that failure situation and minio completes healing, the page is reachable again.

not sure if it's helpfull: using single node, EC:2 as storage class configuration for standard storage class.

**Comment by bexsoft** [comment]
Can you please right click on the page, click on inspect and help us to provide a screenshot of the console & network tabs?

<img width="292" alt="Screen Shot 2022-09-09 at 17 58 45" src="https://user-images.githubusercontent.com/33497058/189456458-b21306c0-c44e-4119-b85d-68ec77adb51b.png">
<img width="1123" alt="Screen Shot 2022-09-09 at 17 58 11" src="https://user-images.githubusercontent.com/33497058/189456463-2e42e276-7b9f-4699-aeea-d1896f34abe6.png">

Also have you tried with the latest version to see if issue is still present? 

Thank you.

**Comment by jstiops** [comment]
so here are the screenshots. first one is under normal disk health. Second and third is after failing a single disk. I will try the same with the latest version later today.
![image](https://user-images.githubusercontent.com/1699208/189872878-b0638567-f9ab-448f-a636-a57d9297b54b.png)
![image](https://user-images.githubusercontent.com/1699208/189872907-4584d9d5-389c-428b-82f2-67ceef1c8ac1.png)
![image](https://user-images.githubusercontent.com/1699208/189872943-d5e4a0bc-aff6-4fce-8cd6-3c115419b74d.png)

**Comment by bexsoft** [comment]
Ok, Thank you for the details. Will send a fix for this
