### ISSUE TITLE
Error 403 when trying to preview a object

### ISSUE THREAD

**Issue by sawa-ko** [minio/console#2344]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

To be able to see the preview of the object, in this case, an image.

## Current Behavior

A loading screen with a corrupted image due to a 403 http error.

![image](https://user-images.githubusercontent.com/56084970/192910774-7ccc1311-00fe-48e0-99f0-5e29c3db033b.png)

![image](https://user-images.githubusercontent.com/56084970/192910864-2f396e21-1542-44b9-bb11-2fd7e53c37a2.png)

## Steps to Reproduce (for bugs)

1. Create bucket
2. Create path
3. Upload object
4. Try to preview the object

## Context

It affects me in the point that I want to know what the object is, its content, without the need to generate a download link to be able to see it.

## Regression

I am not sure.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-09-25T15-44-53Z (go1.18.6 linux/arm64)
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux vps 5.15.0-1017-oracle # 22~20.04.1-Ubuntu SMP Wed Aug 24 11:13:15 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by bexsoft** [comment]
Hi @kaname-png!

Can you please describe your environment?

- Is this a baremetal or K8s deployment?
- Is it behind a Load Balancer?
- Are you using `MINIO_BROWSER_REDIRECT_URL` env variable?

Thank you

**Comment by kaname-png** [comment]
1. Hosted using the Docker image
2. No
3. Yes, It is the URL of the console

**Comment by rayhannabi** [comment]
Same issue for me. 
- Single node installation using docker
- Using Nginx as a reverse proxy
- `MINIO_BROWSER_REDIRECT_URL` is set to my console address (e.g `https://console-minio.example.com` for console address, `https://minio.example.com` for API)

**Comment by kaname-png** [comment]
Hi again @bexsoft, I just realized that this problem happens when using minio with cloudflare.

I tried using minio without cloudflare using the same configuration that gave me error before and it works perfectly, the endpoint `https://console-minio.example.com/api/v1/buckets/.../objects/metadata?prefix=...=` works without problems, but when I enable cloudflare in the minio installation I get error 403.

**Comment by sawa-ko** [comment]
I have come to the conclusion that it is cloudflare's fault (this without changing any configuration), because if I use it without cloudflare there is no problem.

**Comment by rameshdon1** [comment]
I changed the domain to development mode in cloudflare dashboard and it works.

**Comment by echoface** [comment]
localhost without nginx-reverse-proxy and issue still;   403 
```bash
curl 'http://100.64.0.7:6001/api/v1/buckets/image/objects/metadata?prefix=ZnJlZXNjYWxlX2Nhci5qcGVn' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9,zh;q=0.8,zh-CN;q=0.7,zh-TW;q=0.6,ja;q=0.5' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: token=AOQP0FgVGkKi/HjUJEMfV+cRtRs1DEclwo3kEHYc2LnRQy2EA9D+6fGTliEWaY8t7g/AT/bFUdt9r+R8bS631sHom0aI9EsRTtmCf/lHJXDCPalE62m6L9ti8Bv+Ac8GI8eLQcfFjTi5+HFcJVLDKknKzRWHP0+Y8xTilW5TSHPvlBTAARD/m2ZiCpvY7Cdd/lL7+XlwmmU3wwqHNeIfjpQAN77sgS3U0c04Z5NSQ8z1B2AhUPW7IBi5MVzdHGxiKT3uOFPdSieJlVW880+AX5cu1Are+v9KBdc5Zap34GnRg6JBmqRGoaujkr8bwSjDbWDYSsFUJ+ppRPpvf2ro8nW3OoJGi0ZBl+RrsTTKYsfUUNeIVXfStYEAOodcg2PUdMMJ1sO8QQmEbclhiNOoNhjdMYsmyxAJweFN8fRVvcRxkiSe+0du2ZTm9pgnBZyJKtbSKvIqlzYYB646ir1lnM9lAa8WwHgSwgTgljKF58ILbbJj/+Tg7FvVSnpOjb63jSywkbgmnRDfUSpsHnSzlQrIs7BN2KPLJm6X4SNP9gdOXBCvohv8' \
  -H 'DNT: 1' \
  -H 'Pragma: no-cache' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  --compressed \
  --insecure
```

**Comment by sonyarianto** [comment]
> Yeah this is because they convert a GET into a head call which is malicious.

is this something that stated clearly in the documentation for people that using Minio with Nginx reverse proxy behind Cloudflare? I also experience the same thing, due to I use Cloudflare proxy on the DNS, after disable it, preview runs well :)

**Comment by mredodos** [comment]
Same problem here but with deployed via coolify with traefik as reverse proxy, all image ,if i click on preview, return 403
