### ISSUE TITLE
Amazon Managed Prometheus credentials

### ISSUE THREAD

**Issue by jallaix** [minio/console#2357]
**Is your feature request related to a problem? Please describe.**
Our MinIO metrics are directly sent to Amazon Managed Prometheus (AMP) using Grafana Agent.
But the MinIO console can't access Amazon Managed Prometheus metrics. Minio metrics are thus unavailable in the console.

**Describe the solution you'd like**
Implement SigV4 authentication to allow the console to access Amazon Managed Prometheus.
More generally, implement authentication to access remote Prometheus tools (Thanos, Cortex, Mimir...).

**Describe alternatives you've considered**
- Not using the console at all for metrics, anyway we use Grafana Cloud to query AMP.
- Using another Prometheus instance instead of Grafana Agent, acting as a proxy for AMP. 

**Additional context**
N/A

**Comment by cesnietor** [comment]
We did some changes with Prometheus a couple of months ago so we'll try to reproduce and see if it's compatible with the Amazon one.

**Comment by cesnietor** [comment]
Hi @jallaix we verified this and we don't support it. This is not a priority for us right now. But we welcome PRs and we can help testing. Thanks.

**Comment by bayasdev** [comment]
Sorry, we're discontinuing Prometheus support in MinIO Console
