### ISSUE TITLE
Console crashes with bucket replication setup

### ISSUE THREAD

**Issue by bh4t** [minio/console#2358]
Console seems to be crashing at weird place on setting up bucket replication.

Setup 2 minio instances. Trying to upload an object on one site. The object loads fine.
when I try to refresh the other site to check the bucket, the console crashes. I tried to capture the crash on the console but unable to.
I am running the version 2022-10-02T19:29:29Z of MinIO.

**Comment by bh4t** [comment]
@prakashsvmx I have tried to record it. 
[Screencast from 10-06-2022 07:24:26 AM.webm](https://user-images.githubusercontent.com/109562845/194342100-189ef7de-b100-4d6a-950c-c06f2199a71d.webm)
[Screencast from 10-06-2022 07:29:51 AM.webm](https://user-images.githubusercontent.com/109562845/194342107-04dcf659-0504-403e-b643-cf64f0df054a.webm)

**Comment by prakashsvmx** [comment]
It could not be replicated in the latest version.
```bash
➜ mc replicate add local22/source-bucket --remote-bucket http://minio:minio123@localhost:23000/dest-bucket --priority 1  
Replication configuration rule applied to local22/source-bucket successfully.

 ➜ mc replicate ls local22/source-bucket
Rules:
Remote Bucket: localhost:23000/dest-bucket
  Rule ID: cin4h7j0mbmr3l7j2gfg
  Priority: 1

```

![image](https://github.com/minio/console/assets/23444145/7a182ced-1241-4754-85ba-47bc99a3267a)


No Crash or logout or delay of replication observed.
