### ISSUE TITLE
Console Logout Unuse Addition "SubPath" 

### ISSUE THREAD

**Issue by j13tw** [minio/console#2362]
We Create MinIO Console behind with istio gw, 
setting with subpath "minio-console", and also set ENV [MINIO_BROWSER_REDIRECT_URL](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_BROWSER_REDIRECT_URL)
when login and upload, delete, dowload object is well,
just "Logout" is not use the subpath, will direct goto "/logout" API

**Comment by asianman35** [comment]
can you post your istio virtual service you used to access the console? once you set MINIO_BROWSER_REDIRECT_URL to 'minio-console'? thank you
