### ISSUE TITLE
IAM Policy, Cannot create subdirectory & update files in MinIO Console, But MinIO Client Success.

### ISSUE THREAD

**Issue by madcatlove** [minio/console#2400]
MinIO Version : RELEASE 2022-10-15T19-57-03Z
UserManagement : OpenID with Dex

BucketName : se-test
Policy(IAM) for Bucket (se-test)
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::se-test/*"
            ]
        }
    ]
}
```
Service Accout for MinIO Client
(I create service account from minio console)

Operation:
In MinIO Console (login with Dex)
 1. Click Bucket 'se-test'
 2. Create New Path & type 'a'
 3. Upload small file on created 'a'
 4. MinIO Console Says  'it requires additional permission. s3:PubObject'
    **--> Failed**

But..
In MinIO Client (login with ServiceAccount)
 1. mc alias set testsrv http://minio-1:9000  setest 123456789
 2. mc ls testsrv/  --> Success
 3. mc mb testsrv/a --> Success
 4. mc cp test.dat testsrv/a/ **--> Success**  

Why MinIO Console requires S3 Object Permission for uploading new file in new path?
(as you can see iam policy, i already gave all s3 permission for that OpenIDC user)

**Comment by madcatlove** [comment]
MinIO Console requires permission checks when I drag&drop files.
 --> I think it is a bug.
But, It doesn't say permssion check when I upload file throught 'Upload File' button. And Successfully uploaded in new directory.

**Comment by cesnietor** [comment]
Issue should be solved with above's PR please reopen if not the case.
