### ISSUE TITLE
Dark mode for console

### ISSUE THREAD

**Issue by iFrozenPhoenix** [minio/console#2429]
A dark mode / theme for the console UI would be nice.
The current UI uses a white background which is very disturbing, especially in dark environments.

**Comment by kaankabalak** [comment]
Hi @iFrozenPhoenix, we have been exploring dark mode internally, we will keep you updated 👍

**Comment by iFrozenPhoenix** [comment]
@bexsoft any updates / eta on the topic?

**Comment by harshavardhana** [comment]
@iFrozenPhoenix there is no ETA, sorry.

**Comment by prakashsvmx** [comment]
PR merged. For improvements if any , new issue can be used.
