### ISSUE TITLE
I developed a script that automatically adds i18n to this project.

### ISSUE THREAD

**Issue by lvyueyang** [minio/console#2438]
This script can automatically handle about 90% of the tasks for you.

You can check the detailed usage in this repository.
https://github.com/lvyueyang/minio-console-i18n.git

Here is the documentation
https://github.com/lvyueyang/minio-console-i18n/blob/main/readme_en.md

Also check out this branch, this is the code after my script is executed
https://github.com/lvyueyang/minio-console/tree/dev/i18n

>我开发了一个为这个项目自动添加国际化的脚本。
该脚本可以自动处理大约 90% 的任务。
您可以在此存储库中查看详细用法。
https://github.com/lvyueyang/minio-console-i18n.git
这是文档
https://github.com/lvyueyang/minio-console-i18n/blob/main/readme_en.md
也可以查看这个分支，这是我脚本执行完成后的代码
https://github.com/lvyueyang/minio-console/tree/dev/i18n

**Comment by harshavardhana** [comment]
This looks neat @lvyueyang would you be interested in sending a PR? - we can also do it on our end if you are not comfortable.

**Comment by lvyueyang** [comment]
@harshavardhana 
No problem, I'll submit a PR in a moment

**Comment by prakashsvmx** [comment]
Closing this based on 
https://github.com/minio/console/pull/2443#issuecomment-1538701838

>Hello, our team has decided not to move forward with this since we won't be able to keep with all the languages since we can't guarantee the quality of the translations yet.

**Comment by GMYXDS** [comment]
so is i18n support yet?

**Comment by JustinYi922** [comment]
so is i18n support yet? +1

**Comment by qmjy** [comment]
so is i18n support yet? +2

**Comment by cesnietor** [comment]
not a priority right now.

**Comment by yinyuncan** [comment]
WCNMD , 还要讨论多久才能合并？

**Comment by willzhang** [comment]
hope Chinese language support is available. 
BTW,that guy upstairs is a real retard!

**Comment by lvyueyang** [comment]
> WCNMD , 还要讨论多久才能合并？

哥们儿你这太丢人了，友好一点

**Comment by mosynaq** [comment]
+1
