### ISSUE TITLE
Service Accounts missing

### ISSUE THREAD

**Issue by Teekuningas** [minio/console#2440]
Using a container created from quay.io/minio/minio:RELEASE.2022-11-08T05-27-07Z I am missing "Service Accounts" under "Identity" in the UI. "Service Accounts" exists there with quay.io/minio/minio:RELEASE.2022-10-29T06-21-33Z.

Is this intentional?

-- Tk

**Comment by harshavardhana** [comment]
Service Accounts have been renamed to "Access Keys" to be in-line with AWS S3 IAM.

**Comment by harshavardhana** [comment]
![image](https://user-images.githubusercontent.com/622699/200712179-87e7d22a-b30f-4668-8657-b26c53db29f3.png)
