### ISSUE TITLE
How to add user in minio group

### ISSUE THREAD

**Issue by Gibson-Joseph** [minio/console#2477]
I'm using Minio and running a Minio server locally. In the Minio console, I create Minio users and groups. And I want to add a user to my minio group but I am getting the following errors.

```
TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Indexed property setter is not supported.
    at ve (react-dom.production.min.js:49:159)
    at Ks (react-dom.production.min.js:230:381)
    at bc (react-dom.production.min.js:281:85)
    at xc (react-dom.production.min.js:280:450)
    at gc (react-dom.production.min.js:280:320)
    at vc (react-dom.production.min.js:280:180)
    at oc (react-dom.production.min.js:271:88)
    at lc (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
```

**Comment by kannappanr** [comment]
@Gibson-Joseph What is the version of MinIO here? and can you paste the output of `mc admin info` Do you have external IDP enabled?

**Comment by prakashsvmx** [comment]
@Gibson-Joseph  thank you for reporting the issue,


I have tested the 
- latest master ( minio, console)
- latest minio release (RELEASE.2022-11-26T22-43-32Z)

- tried different scenarios 
  - create group -> create user -> assign user to group
  - create group -> create user -> select group -> save user
 - Tried in Chrome, Firefox, Browser stack -  Safari.
  
  I could not replicate the issue.

Please share the 
- browser used and browser version as well.
- MinIO version used

**Comment by muc** [comment]
Running into the same problem. The error occurs when doing the following scenario:

- click on an existing user under Identity › Users
- in the Groups tab click the Button "Add to Groups"

MinIO version: `2022-12-12T19:27:27Z`
Browser: `Chrome/Brave Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)`
Logged in user has the default `consoleAdmin` policy.
