### ISSUE TITLE
OIDC logout with keycloak [Backchannel Logout ]

### ISSUE THREAD

**Issue by cguermi** [minio/console#2478]
Hi, 

i tried minio OIDC login with keycloack i'm able to login successfully but when i try to logout i'm facing two issues: 

1. After login out from minio console, the session on keycloak still remaining (this [PR](https://github.com/minio/console/pull/2281) doesn't seems to works properly as
Minio does not call end_session_endpoint  )

2 . If i try to manually kill the session from Keycloak admin console  a Backchannel Logout request is sended to minio at **/logout** but it's not ending the session in minio side. i noticed that the effective api endpoint to end the session is /api/v1/logout but when i use this url instead in keycloack i receive a 401 response from mino 

### Mnio version 
minio version DEVELOPMENT.2022-10-24T18-35-07Z (commit-id=fc6c7949727ec261cd57fbdb02fa7575d0fd8e61)

**Comment by valterartur** [comment]
Facing with same issue on version RELEASE.2022-11-08T05-27-07Z
