### ISSUE TITLE
Console under subpath

### ISSUE THREAD

**Issue by mworzala** [minio/console#2483]
Hi
 I am trying to run the console under the subpath `/console`, but I am getting the following javascript error:
```
TypeError: e.console.session is null
    u consoleSlice.ts:54
    Redux 2
    yn ConsoleKBar.tsx:25
    React 7
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
    36813 scheduler.production.min.js:14
    Webpack 12
```

I have tried setting `CONSOLE_SUBPATH`, which does not solve the issue. I am running the console behind Envoy and using a `prefix_rewrite` to `/`, otherwise the console returns `index.html` instead of other assets like js.

Any help is appreciated!

**Comment by christophsing** [comment]
Hi - any updates on this Topics? 
We try to use minio behind a traefik ingress controller and are also not able to use it as designed.

**Comment by avnav88** [comment]
same with nginx:
i have a similar problem.  i'm using a subpath of `/minio`, the console works and the session request returns 200.

```
Request URL: http://10.235.77.22/minio/api/v1/session
Request Method: GET
Status Code: 200 OK
Remote Address: 10.235.77.22:80
Referrer Policy: strict-origin-when-cross-origin
```

but when you try to use certain pages like buckets, you get:

```
Request URL: http://10.235.77.22/api/v1/buckets
Request Method: GET
Status Code: 404 Not Found
Remote Address: 10.235.77.22:80
Referrer Policy: no-referrer
```

**Comment by mskyttner** [comment]
@avnav88, related:

https://github.com/minio/console/issues/2166#issuecomment-1500533953
https://github.com/minio/console/pull/2174
https://github.com/minio/console/pull/2725
