### ISSUE TITLE
Inconsistent Capacity on Console

### ISSUE THREAD

**Issue by midorinet** [minio/console#2505]
I have minio installed with 1 server pools, with 4 servers

However the capacity on console showing inconsistent data while refreshing
<img width="522" alt="Screenshot 2022-12-14 at 08 17 44" src="https://user-images.githubusercontent.com/5847819/207482677-cdf5a9a5-7129-4a60-ae05-44ad79648cca.png">
<img width="522" alt="Screenshot 2022-12-14 at 08 17 52" src="https://user-images.githubusercontent.com/5847819/207482686-b61bf61d-cfeb-46a4-a0d6-bac7123f6dcf.png">
<img width="522" alt="Screenshot 2022-12-14 at 08 18 11" src="https://user-images.githubusercontent.com/5847819/207482688-01e1065b-cbd6-4913-8f1f-8d6e923fc877.png">

is there something I'm missing? Specially the weird ones is having 144% capacity

**Comment by prakashsvmx** [comment]
Could you also share `mc admin info --json` ?

**Comment by midorinet** [comment]
It's been fixed. I wrongly put all nodes on the prometheus. i fixed it by put the load balancers address on prometheus
