### ISSUE TITLE
Make console login timeout configurable 

### ISSUE THREAD

**Issue by emutree** [minio/console#2511]
As a developer and frequent user of the console via the browser web UI, I find that I'm constantly entering my username and password. When I'm logged in via the browser the automatic logout timeout is way too short. Ideally I'd like to be able to configure this parameter as an admin

**Comment by linpan** [comment]
automatic logout

**Comment by dvaldivia** [comment]
We actually support this, the default is `12 hours` but it can be increased via `CONSOLE_STS_DURATION` however, we have not exposed this environment variable via MinIO, so I'll look into that

**Comment by phantom943** [comment]
> We actually support this, the default is `12 hours` but it can be increased via `CONSOLE_STS_DURATION` however, we have not exposed this environment variable via MinIO, so I'll look into that

I don't believe it's 12 hours. I get logged out after 30 minutes of inactivity or so.
It's most frustrating when uploading a big file via the UI, and it fails because you got logged out during the operation.

**Comment by squishyu** [comment]
Any updates on this? I also get constantly logged out of the web interface, feels like every hour.
