### ISSUE TITLE
Identity Menu collapses when selecting LDAP or OpenID

### ISSUE THREAD

**Issue by Alevsk** [minio/console#2527]
[Peek 2022-12-21 22-26.webm](https://user-images.githubusercontent.com/1795553/209071112-67cd18ca-00c5-4c3f-b03b-9ef8cd4a053a.webm)

Probably a one liner :D

**Comment by prakashsvmx** [comment]
@Alevsk  Thank you  :+1: . the fix has been sent in PR #2529
