### ISSUE TITLE
Error Getting Quota Status:  Access Denied.

### ISSUE THREAD

**Issue by titansmc** [minio/console#2528]
I get this error when browsing a bucket where I have full access. It has no quota configured.

![image](https://user-images.githubusercontent.com/8192096/209098729-2b18be31-1609-4582-8ff1-a6b3a470c6c6.png)

**Comment by prakashsvmx** [comment]
>I have full access

do you mean  the user has `consoleAdmin`   policy or 
``` 
{
    "Effect": "Allow",
    "Action": [
     "admin:*"
    ]
   },

```

Have you checked with admin credentials  `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` ? 

could you also share the policy associated with the user you have used for logging in?
`mc admin user list <alias>` - find the policy name(s) associated with the user
`mc admin policy info <alias> <policy_name>`

**Comment by titansmc** [comment]
```
{
 "PolicyName": "bm_bucket-murphy-1_admin",
 "Policy": {
  "Version": "2012-10-17",
  "Statement": [
   {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::bucket-murphy-1/*"
    ]
   }
  ]
 },
 "CreateDate": "2022-12-21T12:39:55.785Z",
 "UpdateDate": "2022-12-21T12:39:55.785Z"
}
```
This is the policy the user has.
`MINIO_ROOT_USER` is not working since we use LDAP (which I think they should work)

Server is:
`2022-12-12T19:27:27Z`
MC is:
`RELEASE.2022-11-17T21-20-39Z`

**Comment by prakashsvmx** [comment]
As per the above policy , it only allows s3 APIs. 

Please check that, Bucket Quota related admin actions like:
```
"admin:SetBucketQuota",
"admin:GetBucketQuota",
```
needs to be enabled if you are looking for fine grained access.

Please refer to:  https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#minio-policy-built-in

**Comment by titansmc** [comment]
are we allow to mix admin and s3 policies ?

```
xemacs@samaruc:/tmp$ mc admin policy add  alias/ bm_moscardo1_admin  kk.json
mc: <ERROR> Unable to add new policy: unsupported admin action 's3:*'.
xemacs@samaruc:/tmp$ cat kk.json 
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:*",
	"admin:SetBucketQuota",
        "admin:GetBucketQuota"
      ],
      "Effect": "Allow",
      "Principal": {
       "AWS": [
        "*"
       ]
      },
      "Resource": [
	"arn:aws:s3:::moscardo1/*"
      ],
      "Sid": ""
    }
  ]
}
```

**Comment by hugokoopmans** [comment]
the problem is still there... 

MinIO VERSION 
2023-03-24T21:41:23Z

minio console is loading... F12 gives error getting quota status.

my policy for a new group

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::sensingclues*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "admin:GetBucketQuota",
                "admin:SetBucketQuota"
            ],
            "Resource": [
                "arn:aws:s3:::sensingclues*"
            ]
        }
    ]
}

still no luck, any suggestion
