### ISSUE TITLE
Bug with policies trying to match on ${aws:username}

### ISSUE THREAD

**Issue by ryanmasse** [minio/console#2531]
Having upgrade to the latest version of minio we are experiencing permissions issues with our policies that refer to the ${aws:username} variable.

We have a bucket named `clients` and have a path for each of client name under this bucket that matches their minio username.  The below policy was in place and was working flawlessly up to this latest release.

It looks like the url conventions have changed from the actual pathname to some form of hash?

Example: /buckets/clients/browse/Y29tbXVuaXR5bGl2aW5nZXNzZXgv

```shell
root@minio1:~# minio --version
minio version RELEASE.2022-12-12T19-27-27Z
```
policy 

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
              "s3:ListBucket"
      ],
      "Resource": ["arn:aws:s3:::clients"],
      "Condition": {"StringLike": {"s3:prefix": ["${aws:username}/*"]}}
    },
    {
      "Effect": "Allow",
      "Action": [
              "s3:GetReplicationConfiguration"
      ],
      "Resource": ["arn:aws:s3:::clients"]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": ["arn:aws:s3:::clients/${aws:username}/*"]
    }
  ]
}
```

**Comment by ryanmasse** [comment]
@harshavardhana just a follow up.  It appears as if the bug is related to the upload feature of the console as I'm able to use `mc cp` via the cli using the same credentials successfully.

Console:
/api/v1/buckets/clients/objects/upload
{"code":500,"detailedMessage":"Access Denied.","message":"an error occurred, please try again"}

CLI:
rmasse@unifi ~/TMP> mc cp Updated\ CSV\ File.csv ALIAS/clients/essex/test4.csv
/Users/rmasse/TMP/Updated CSV File.csv:       48.17 KiB / 48.17 KiB

**Comment by harshavardhana** [comment]
Yes @ryanmasse it is a UI thing, that's why it's moved to this repo.

**Comment by vivekjainmaiet** [comment]
Is it resolved or still open ? I am also facing same issue.

**Comment by prakashsvmx** [comment]
@vivekjainmaiet  @ryanmasse 

i have verified with the latest it works fine. Please upgrade to latest and check.

Admin:
![image](https://github.com/minio/console/assets/23444145/51894665-b8ea-4175-a2f9-fc60135e8d5f)

Users/Client Prefix:

![image](https://github.com/minio/console/assets/23444145/dc6e74e5-66e2-49a9-94ed-cca7f4b09e62)


![image](https://github.com/minio/console/assets/23444145/8544be2a-6420-47b1-9573-498618b26fdb)

<details>
<summary> Policy </summary>

```js
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::clients"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "${aws:username}/*"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetReplicationConfiguration"
            ],
            "Resource": [
                "arn:aws:s3:::clients"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::clients/${aws:username}/*"
            ]
        }
    ]
}
```

</details>
