### ISSUE TITLE
Add CONSOLE_MINIO_SERVER to ui?

### ISSUE THREAD

**Issue by jeessy2** [minio/console#2534]
Use one minio-console to access different minio servers without change env `CONSOLE_MINIO_SERVER`

Like this:
![](https://user-images.githubusercontent.com/6205259/209527291-864983f8-d3e8-4821-9aba-bff1b4ae92d8.png)

**Comment by prakashsvmx** [comment]
Console is embedded in MinIO Server as a modular package.  It is not recommend to deploy console as a standalone UI to access multiple deployments.
