### ISSUE TITLE
Show assigned policy

### ISSUE THREAD

**Issue by csc-solution** [minio/console#255]
At first, thanks for your great work. Is there a way to show the currenty assigned policy for a user or group?

Thanks,
Tom

**Comment by csc-solution** [comment]
Is there a plan to implement this function?

**Comment by dvaldivia** [comment]
Yes we have plans to implement this, it's just that we don't have enough bandwidth right now, but you are welcome to send a PR in the meanwhile

**Comment by dvaldivia** [comment]
We already show the assigned policies inside the user/group details
