### ISSUE TITLE
Preview depending on Content-Type

### ISSUE THREAD

**Issue by NecatiMeral** [minio/console#2573]
Hi, 

we're uploading objects with arbitary guids as object names (without file extensions).
Instead we upload files with the correct Content-Type set.

How about enabling image preview depending on the set Content-Type if there isn't a extension?
Prior separating the console code from minio/minio to minio/console this seemed to be a thing (minio/minio#9239).

I wanted to discuss this topic first before opening a contribution.

**Comment by prakashsvmx** [comment]
Tracked in https://github.com/minio/console/pull/2930 and issue #2919
