### ISSUE TITLE
mc --insecure admin idp ldap add ....     fails with certificate validation error

### ISSUE THREAD

**Issue by tsvgmi** [minio/console#2585]
I tried to add an internal LDAP server for IDP.  It could not pass certificate validation, so tried to use the --insecure flag to bypass it for testing.   But it returns with the same error.

mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
Runtime: go1.19.4 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.

```
% mc --debug --insecure admin idp ldap add local server_addr=**** lookup_bind_dn=**** lookup_bind_password=**** user_dn_search_base_dn=**** user_dn_search_filter=****

...
mc: <ERROR> Unable to add LDAP IDP config to server. Result: LDAP Server Connection Error
Detail: Could not connect to LDAP server: LDAP Result Code 200 "Network Error": x509: certificate is not valid for any names, but wanted to match ****
Suggestion: Check:
    (1) server address
    (2) TLS parameters,
    (3) LDAP server's TLS certificate is trusted by MinIO (when using TLS - highly recommended)
    (4) SRV Record lookup if given, and
    (5) LDAP service is up and reachable
Due to: LDAP Result Code 200 "Network Error": x509: certificate is not valid for any names, but wanted to match adldap1m3-lb.etrade.com
 (0) admin-idp-ldap-add.go:80 cmd.mainAdminIDPLDAPAdd(..)
 Release-Tag:RELEASE.2023-01-11T03-14-16Z | Commit:14c2e506fa78 | Host:*****  | OS:linux | Arch:amd64 | Lang:go1.19.4 | Mem:70 MB/96 MB | Heap:70 MB/78 MB.
```

**Comment by dvaldivia** [comment]
the `--insecure` flag only applies to `mc` going to `MinIO`, this seems to be a problem from `MinIO -> IDP`, if you are using self-signed certificates, you should add the certificates to `~/.minio/certs` so that MinIO can trust the certificates and connect to your IDP

**Comment by dvaldivia** [comment]
To get MinIO to trust a self-signed certificate, you can add the root CA certificate to MinIO's trusted CA certificate store.

Here are the steps to achieve this:

1. Obtain the root CA certificate in PEM format. If you created the self-signed certificate yourself, this should be the same certificate that you used to sign the server certificate.
2. Copy the root CA certificate to the MinIO server. You can use a tool like scp to transfer the file to the server.
3. On the MinIO server, create a directory to store the trusted CA certificates. For example:
```bash
sudo mkdir /etc/minio/certs
```
4/ Copy the root CA certificate to the directory you just created. For example:
```bash
sudo cp my-root-ca.crt /etc/minio/certs/
```
5. Start the MinIO server with the --certs-dir option set to the directory where you stored the trusted CA certificates. For example:
```bash
minio server /data --certs-dir /etc/minio/certs
```
6. Finally, you should be able to access MinIO using the self-signed certificate.

Note: This process is only useful for testing and development environment and it's not recommended for production usage, as it's less secure than using a certificate from a trusted CA.

**Comment by kannappanr** [comment]
@tsvgmi Closing this issue as answered.
