### ISSUE TITLE
MinIO Console / old Minio server version

### ISSUE THREAD

**Issue by Eduardo1977** [minio/console#2598]
Hi, i'm completely new about MinIO. 
Now, I have to take care of a very old Minio Server version, installed on Windows in 2019:
    Version
    2019-10-02T21:19:38Z
    Memory
    Used: 2.5 GB | Allocated: 209 GB | Used-Heap: 2.5 GB | Allocated-Heap: 7.0 GB
    Platform
    Host: ser-anpr01 | OS: windows | Arch: amd64
    Runtime
    Version: go1.13.1 | CPUs: 8 

In localhost at port 9000 is reachable a "MinIO Browser" like in image:

![immagine](https://user-images.githubusercontent.com/27421449/214359181-158d1d39-0ca4-41d6-8f7b-da0a49857b0f.png)

but from this I can't do anything (is the embed console of old Minio version ?)

So I'd like to install new "MinIO Console" like in image :
![immagine](https://user-images.githubusercontent.com/27421449/214359901-5a406536-c7e3-4ac6-8032-1c9b74374deb.png)
 
I tryed without success following instructions for Windows at [https://github.com/minio/console#binary-releases](url) 

Maybe, I think new "MinIO Console" is embed version of new Minio server version. 
So, I must update Minio server ? Or is it possible to install new "MinIO Console" with old minio server version?
Thanks !

**Comment by harshavardhana** [comment]
New Console won't work with such an old release of MinIO - you have to upgrade.

**Comment by klauspost** [comment]
> So, I must update Minio server?

Correct.

**Comment by harshavardhana** [comment]
If you are on single drive mode (FS) this is legacy you need to follow https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html

To migrate your data to the latest supported format, you won't be able to upgrade your existing setup.

**Comment by Eduardo1977** [comment]
Before migrate, I need to delete a big number of useless files (objects) that are in a bucket named "rep0956d2fc39".
In particular, I must delete older files created. So I need command line to run in windows prompt:

- to delete all files/objects created in a certain date 
- to delete all files/objects created before a certain date (or older than N days)

Thanks for all

**Comment by klauspost** [comment]
@Eduardo1977 This is the [documentation for `mc rm`](https://min.io/docs/minio/linux/reference/minio-mc/mc-rm.html)

If you need further guidance I suggest you look into out [subscription offer](https://min.io/pricing).
