### ISSUE TITLE
Console does a POST to 127.0.0.1 even when 127.0.0.1 is not configured

### ISSUE THREAD

**Issue by hamalchristiaan** [minio/console#2604]
- Running minio: ./minio server --address 192.168.0.10:9000 --console-address 192.168.0.10:9001
- We don't want to have 127.0.0.1 in our certificate
- IDP enabled (openID)

## Expected Behavior
Everything should work fine when logging into console with IDP (openID).

## Current Behavior
Error from IDP: An error occurred, please try again
Post "https://127.0.0.1:9000": x509: certificate is valid for 192.168.0.10, not 127.0.0.1

## Steps to Reproduce (for bugs)
- Provide internal ip-address in command for address and console-address
- Don't provide 127.0.0.1 in certificates
- Enable IDP (openID?)
- Try to log in

## Your Environment
* Version used (`minio --version`): RELEASE.2023-01-06T18-11-18Z (commit-id=ebd4388cca5e28619970032e32ddeb2cb51a6b38)
* Operating System and version (`uname -a`): Linux 5.10.0-15-amd64 1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
fixed via #2603
