### ISSUE TITLE
How to display remote s3 bucket in console?

### ISSUE THREAD

**Issue by ahvahsky2008** [minio/console#2621]
I added remote host, but it doesn't show in console. How add it to webui?
`/usr/bin/mc config host add cos https://hb.bizmrg.com xxx yyy --api s3v4;`

**Comment by prakashsvmx** [comment]
Not sure if `https://hb.bizmrg.com` is a MinIO Server Instance . ( if it is, then the console needs to be exposed)

The above command only connects an S3 compatible provider to the mc client.

MinIO console is designed to be modular and tightly integrated with MinIO Server.
