### ISSUE TITLE
Minio Console (S3 api error)

### ISSUE THREAD

**Issue by mberbero** [minio/console#2637]
When I try to login to the console, I get the error "S3 API Requests must be made to API port". I start getting this error when I set the 'MINIO_SERVER_URL' variable.
Minio Version: RELEASE.2023-01-31T02-24-19Z

**Comment by harshavardhana** [comment]
as the error indicates you shouldn't set MINIO_SERVER_URL to be the console port, you need to set this to the value for API port. 

There are two ports in MinIO `--address` for API port and `--console-address` for Console UI port. MINIO_SERVER_URL must point to API port.

**Comment by harshavardhana** [comment]
as the error indicates you shouldn't set MINIO_SERVER_URL to be the console port, you need to set this to the value for API port. 

There are two ports in MinIO `--address` for API port and `--console-address` for Console UI port. MINIO_SERVER_URL must point to API port.

**Comment by mberbero** [comment]
Sorry for again. "The request signature we calculated does not match the signature you provided. Check your key and signing method." I'm getting the error now.
