### ISSUE TITLE
Login to the console using access keys

### ISSUE THREAD

**Issue by titansmc** [minio/console#2654]
Even though Access Keys are meant to be used for programmatic  access, it would be very nice they can log in to the console. My scenario used to be: I manage local accounts and distribute them to the users, so they could just drag and drop files, but now we moved to LDAP, so only people with an account in our server would be able to drag and drop files, the rest would need to go via Cyberduck, Filestash....or similar.

**Comment by harshavardhana** [comment]
Service accounts are not meant for Console UI login @titansmc they are designed on purpose to avoid Console login. 

if you are using LDAP - LDAP credentials must be used to login via Console.
