### ISSUE TITLE
How can I stay logged-in?

### ISSUE THREAD

**Issue by odigity** [minio/console#2662]
I'm running docker image "minio/minio:RELEASE.2022-10-24T18-35-07Z" with env vars MINIO_ROOT_USER and MINIO_ROOT_PASSWORD set.  I am able to login just fine - however, I have to do it every time I open a new tab or refresh the existing one.

Is there a way to remain logged-in, perhaps via some sort of cookie-based mechanism?

I tried all kinds of googling and could find no mention of this feature/issue.

**Comment by bexsoft** [comment]
Hi @odigity!

Sessions were changed to last 12 hours in https://github.com/minio/console/pull/2434, This change was applied in console v0.21.2

Unfortunately there is no way to bypass login using root user and password params at this time, Can you please describe your use case for this requirement? 

Thank you.

**Comment by odigity** [comment]
My use case is I use MinIO and MinIO Console in development as a local replacement for S3, and having to login every time I want to browse my buckets is an unnecessary nuisance.  I have no need for security to protect my local dev buckets from myself.  :)

BTW - I'm running docker image "minio/minio:RELEASE.2022-10-24T18-35-07Z".

**Comment by bexsoft** [comment]
Hi @odigity!

In this case, as you mention that no security is required here, an alternative would be to set Anonymous Access for each of them, we just implemented Anonymous access in [v0.23.1](https://github.com/minio/console/releases/tag/v0.23.1).

This option will allow you to browse your buckets directly without having to use your login credentials each time you enter console. https://github.com/minio/console/pull/2600

Meanwhile we are discussing this feature internally for future console releases.

**Comment by odigity** [comment]
Thank you for the suggestion of Anonymous Access (didn't know about that), but I'd rather wait for the upcoming Console feature you're discussing (to bypass or automate console auth entirely), and continue logging in each time until then.

You can close this thread, or leave it open for people like me to subscribe to for updates on the feature.

**Comment by linpan** [comment]
minio often logout,  need login.

**Comment by dvaldivia** [comment]
Will be fixed by https://github.com/minio/minio/pull/17885 on the next MinIO release via the `MINIO_BROWSER_SESSION_DURATION` environment variable
