### ISSUE TITLE
Mistake in traffic monitoring

### ISSUE THREAD

**Issue by AlexZIX** [minio/console#2667]
Seems that is a mistake in Monitoring - Traffic panel at Node IO diagram - all values are RChar but half of them should be the WChar I think. See the screenshot attached. May be somebody copy-paste code which shows this data.
![image_2023-02-16_093819188](https://user-images.githubusercontent.com/13428863/219287607-650d8179-9c97-4ea7-b9ad-bef6a634f868.png)

**Comment by cesnietor** [comment]
@AlexZIX  do you mind sharing more details on what Rchar and Wchar is and probably some test steps so that we can better understand your issue and expectations thanks.

We have now a new issue template in case you want to close this and create a new one to fill those details.

**Comment by AlexZIX** [comment]
@cesnietor if I understand right - R means **R**EAD and W means **W**RITE. So each node should have 2 metrics: READ IO and WRITE IO. But at my screenshot above you can see only READ for all nodes twice. So I suggested that it's a mistake because each node should have read and write metric values.
