### ISSUE TITLE
Policy for private buckets

### ISSUE THREAD

**Issue by sebastian-luna-valero** [minio/console#2669]
Hello,

Apologies in advance since I am new to the object storage domain.

If I configure access to a MinIO deployment with OIDC and `readwrite` built-in policy:
https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#userpolicy.readwrite

```yaml
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

Users are able to delete each others buckets even when they are configured as private. Is that expected?

If so, how should a policy look like to make sure that private buckets are private (i.e. only the owner can list/modify/delete them).

Best regards,
Sebastian

**Comment by dvaldivia** [comment]
hi @sebastian-luna-valero that is because `s3:*` implies `s3:DeleteBucket` so you are giving users permission to do so

**Comment by dvaldivia** [comment]
you could add a statement to deny this
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
 {
            "Effect": "Deny",
            "Action": [
                "s3:DeleteBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

**Comment by sebastian-luna-valero** [comment]
Thanks @dvaldivia 

With your example I assume that even the owner of the bucket won't be able to delete it, correct?

Also others will still be able to list/modify private buckets, right?

Best regards,
Sebastian

**Comment by dvaldivia** [comment]
There's no concept of bucket ownership in MinIO @sebastian-luna-valero, something you could do is assign users a policy that allows the to create a bucket prefixed with their username and to only access that for example

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}/*"
            ]
        },
 {
            "Effect": "Deny",
            "Action": [
                "s3:DeleteBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

**Comment by sebastian-luna-valero** [comment]
Thanks!

Is there a way to check the actual value of `${aws:username}`?

**Comment by dvaldivia** [comment]
there's no way to check, if your users are coming via `IDP` you additionally have

```
jwt:upn
jwt:name
jwt:groups
jwt:given_name
jwt:family_name
jwt:middle_name
jwt:nickname
jwt:preferred_username
jwt:profile
jwt:picture
jwt:website
jwt:email
jwt:gender
jwt:birthdate
jwt:phone_number
jwt:address
jwt:scope
jwt:client_id
```

**Comment by sebastian-luna-valero** [comment]
Thank you very much, exactly what I was looking for!
