### ISSUE TITLE
trusted CAs are ignored for `MINIO_IDENTITY_OPENID_CONFIG_URL`

### ISSUE THREAD

**Issue by thesuperzapper** [minio/console#2681]
The when the console queries the `MINIO_IDENTITY_OPENID_CONFIG_URL`, it ignores trusted CA certificates under the [`CAs/` subfolder of the `--certs-dir`](https://min.io/docs/minio/linux/operations/network-encryption.html?ref=docs-redirect#id2).

___NOTE:__ this is ONLY the case for the console, not the server, and the `x509: certificate signed by unknown authority` error will ONLY show up in the console web interface when attempting to log in (which will fail)._

This means that its not possible to use a self-signed certificate on your OPENID discovery url (e.g. `https://example.com:8443/dex/.well-known/openid-configuration`) unless you:

1. Mount the certificate to `/etc/pki/ca-trust/source/anchors/`
3. Run `update-ca-trust` on container start (and obviously running as root)

---

I am fairly sure this is a related issue: https://github.com/minio/minio/issues/12381

**Comment by vadmeste** [comment]
@thesuperzapper are you using latest MinIO version ? if yes, can you paste the exact error, like a screenshot from console.

**Comment by thesuperzapper** [comment]
> @thesuperzapper are you using latest MinIO version ? if yes, can you paste the exact error, like a screenshot from console.

I am using version `2023-02-17T17:52:43Z`, and have attached a screenshot below, but it looks like you have found the issue as @harshavardhana has raised PR https://github.com/minio/console/pull/2682 to fix it.

<img width="1461" alt="Screenshot 2023-02-26 at 12 13 30" src="https://user-images.githubusercontent.com/5735406/221434747-bc778da2-f201-43e8-b525-75e5bd9ec401.png">

**Comment by fsdrw08** [comment]
Hi, I still have the same issue when using the latest `RELEASE.2023-03-24T21-41-23Z` minio

**Comment by harshavardhana** [comment]
> Hi, I still have the same issue when using the latest `RELEASE.2023-03-24T21-41-23Z` minio

will be fixed in the next release.
