### ISSUE TITLE
ErrorWithContext:Access Denied *errors.errorString=invalid session

### ISSUE THREAD

**Issue by Qinxl0921** [minio/console#2687]
The following error occurs when I run the console.exe server. Why? Please tell me how to solve it.
![7d57e3cf30015b95a0073ba35cc0ce2](https://user-images.githubusercontent.com/79916629/221753217-48d28be2-7159-488e-9847-67d72ab803cc.png)

**Comment by cesnietor** [comment]
So this is just a warning it means you were not authenticated when trying to login. It's a bit verbose, we'll see if we can remove this unnecessary log.
