### ISSUE TITLE
Bug with policies trying to match on ${aws:username} 

### ISSUE THREAD

**Issue by vivekjainmaiet** [minio/console#2690]
It’s LDAP integrated authentication and I have created bucket for all user and assigned below policy. When user login it console it shows blank white page. Refreshing page go to login screen. I can upload files to bucket but only login to console and browse is not possible.

But when I change variable ${aws:username} with username like (vivekjainmaiet) , I am able to login to console and have access to my bucket. So issue seems when I use variable ${aws:username} in policy.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3::: ${aws:username}",
                "arn:aws:s3::: ${aws:username}/*"
            ]
        }
    ]
}

**Comment by dvaldivia** [comment]
Could you update the ticket with an example and a description of the issue @vivekjainmaiet ?

**Comment by vivekjainmaiet** [comment]
Updated description

**Comment by harshavardhana** [comment]
With LDAP there is no aws:username in LDAP it should be used as `ldap:username`

**Comment by harshavardhana** [comment]
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:"
            ],
            "Resource": [
                "arn:aws:s3::: ${ldap:username}",
                "arn:aws:s3::: ${ldap:username}/*"
            ]
        }
    ]
}
```

Correct policy for LDAP users.

**Comment by vivekjainmaiet** [comment]
@harshavardhana Thanks. Where I can find all these variables list. I will check above policy today and confirm you.

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks. Where I can find all these variables list. I will check above policy today and confirm you.

This list is not fully documented yet, this is a work in progress. However there are indications of its usage here https://github.com/minio/minio/tree/master/docs/multi-user#policy-variables
