### ISSUE TITLE
SetBucketLifecycle not in effect

### ISSUE THREAD

**Issue by hukang6677** [minio/console#2705]
Lifecycle was set at 9:40 yesterday morning. And objects not deleted today
![image](https://user-images.githubusercontent.com/102129512/224884133-d4e7c2d3-337e-41ba-8a9d-3413be37c3ef.png)
![image](https://user-images.githubusercontent.com/102129512/224884148-a76a907e-1efd-4d9b-9e75-bd2326f7067b.png)
![image](https://user-images.githubusercontent.com/102129512/224884164-523b3c9f-93a5-4e35-ba6c-1899f060c729.png)
![image](https://user-images.githubusercontent.com/102129512/224884194-542853c2-7889-414f-9175-fca9df65c402.png)

**Comment by prakashsvmx** [comment]
could you check `mc stat <alias>/test05/hk01/kh.zip` ? for the Expiration?  

and also `mc ilm export <alias>/test05`  along with `mc version info <alias>/test05` ?

Expiration happens UTC and also depends on cluster load

https://min.io/docs/minio/container/administration/object-management/object-lifecycle-management.html#lifecycle-management-object-scanner.

**Comment by hukang6677** [comment]
I set "after 1"
How to explain "after 1" ?
When is the clean operation performed ?

**Comment by hukang6677** [comment]
@prakashsvmx 
but I set "after 1"
How to explain "after 1" ?
When is the clean operation performed ?

**Comment by prakashsvmx** [comment]
https://min.io/docs/minio/linux/administration/object-management/create-lifecycle-management-expiration-rule.html

**Comment by harshavardhana** [comment]
Please open issue in one repo @hukang6677 https://github.com/minio/minio/issues/16804
