### ISSUE TITLE
minio console automatic logout for modification operation

### ISSUE THREAD

**Issue by mifashion** [minio/console#2727]
When I modify the bucket's Access Policy on the web interface, I will automatically return to the login page，but the operation did not change when I logged in again

**Comment by dvaldivia** [comment]
Sounds like a bad 403 getting returned, we'll investigate

**Comment by linpan** [comment]
Sounds like a bad, waste me time. logout, then need to login...

**Comment by winktool** [comment]
Any updates?

**Comment by jinapurapu** [comment]
![Image](https://github.com/minio/console/assets/65002498/f0af218e-3ec4-4352-98ac-13ed1f877388)

Is this the Bucket policy selector you are using? I have not been able to reproduce this issue. We recommend updating to the latest version. If the issue persists, or I have misunderstood the feature you are using, please resubmit the issue and provide steps to reproduce, thank you.
