### ISSUE TITLE
Mismatch in offline drives under metrics

### ISSUE THREAD

**Issue by cniackz** [minio/console#2731]
### Issue:

![image](https://user-images.githubusercontent.com/6667358/227040235-b0dddf19-01ed-45ef-83d6-98eb130827d5.png)

### Steps to reproduce:

https://github.com/cniackz/public/wiki/UI-Issue:-How-to-reproduce-mismatch-on-disks

**Comment by harshavardhana** [comment]
what is the output of `mc admin info` @cniackz can you share that?

**Comment by prakashsvmx** [comment]
PR merged.
