### ISSUE TITLE
minio console from helm operator Post "http://localhost:9000/": dial tcp [::1]:9000: connect: connection refused

### ISSUE THREAD

**Issue by stepanovdg** [minio/console#2733]
Just do helm install minio-operator
Everything is deployed -> trying to login to operator console with admin/<jwt token>
Results in red banner with 
`Post "http://localhost:9000/": dial tcp [::1]:9000: connect: connection refused`
in logs 
`Serving console at http://[::]:9090
ErrorWithContext:Post "http://localhost:9000/": dial tcp [::1]:9000: connect: connection refused
%!(EXTRA *errors.errorString=invalid Login)`

attached to the pod and looks like "/console server" is running but listens only on ipv6 localhost :9090.

`bash-4.4$ cat /proc/1/net/tcp6
  sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
   0: 00000000000000000000000000000000:2382 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000  1000        0 2375640 1 0000000000000000 100 0 0 10 0
bash-4.4$ cat /proc/1/net/tcp 
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode                                                     
bash-4.4$ `

Tried to change CONSOLE_MINIO_SERVER to http://0.0.0.0:9090 (to connect to open port) -> got exception `S3 API Requests must be made to API port.`

running console server in pod result in nothing
`bash-4.4$ time ./console server

real    0m0.869s
user    0m0.655s
sys     0m0.088s
bash-4.4$ `

Is any way to debug why server is not listening on 9000?

**Comment by harshavardhana** [comment]
Console binary is not meant to be run standalone, use it along with https://github.com/minio/minio

**Comment by stepanovdg** [comment]
Hi @harshavardhana,

Maybe I missed something - but I am not running console alone - I am installing helm operator on k8s and console pod there started with 
CONSOLE_OPERATOR_MODE : on

So do you mean I need some more pods? 
According to the docs I should be able to access operator console to create/manage tenants and later tenant will have there own console.

**Comment by harshavardhana** [comment]
> Maybe I missed something - but I am not running console alone - I am installing helm operator on k8s and console pod there started with
> CONSOLE_OPERATOR_MODE : on

This requires you run Console inside k8s and its not there anymore this code has entirely moved to `https://github.com/minio/operator` - so you are looking at the wrong repo.

**Comment by stepanovdg** [comment]
Thank you.
