### ISSUE TITLE
Potentially misleading message when deleting replication rule

### ISSUE THREAD

**Issue by rossng** [minio/console#2741]
When deleting a replication rule in the UI, the user is warned that:

> the corresponding remote buckets will also be deleted

This makes it sound like the bucket will be fully deleted from the remote Minio instance, but surely this isn't actually the case. Does the error message actually mean that the _reference_ to the remote bucket will be deleted from the local Minio instance?

**Comment by prakashsvmx** [comment]
@rossng Thank you. yes, the buckets will not be removed when a replication rule is removed. so we can remove the warning message.
