### ISSUE TITLE
how to login use usename and password

### ISSUE THREAD

**Issue by zlwzlwzlw** [minio/console#2749]
i use Helm chart for MinIO Operator deply and login used JWT in old version and can get secret form commad as
1.kubectl get serviceaccount console-sa --namespace storage-for-project -o jsonpath=\"{.secrets[0].name}\") --namespace storage-for-project -o jsonpath=\"{.data.token}\" | base64 --decode
2.kubectl --namespace storage-for-project port-forward svc/console 9090:9090
3.login create tenants
when i update new version it use usename and password login but i don't know usename and password.i use some default login it have  error like this
<img width="960" alt="1680058729667" src="https://user-images.githubusercontent.com/33961256/228415295-65da2dde-ebe6-44f2-88c5-15c6e17bad7f.png">
update images 
minio/console:v0.25.0
minio/operator:v4.5.8
minio/minio:RELEASE.2023-03-22T06-36-24Z

**Comment by harshavardhana** [comment]
you need to first configure your tenant to talk to your ingress port to expose the API port. This will not work otherwise.

**Comment by zlwzlwzlw** [comment]
can i update console and use jwt login as old version?
