### ISSUE TITLE
"Network error occured" when downloading large file

### ISSUE THREAD

**Issue by heiko-ma** [minio/console#2760]
When downloading a large file (97GB in my test) via the console, the download interrupts after a while with the following error:
_Error: A network error occurred._

The browser console shows the following error
![image](https://user-images.githubusercontent.com/64192965/230032649-97946147-9fd1-453c-81b9-9d1159330c8a.png)
When I download die file via the direct link (<<URL>>/objects/download?prefix=dGVzdA==&version_id=null) the download completes without error. I suspect a problem in the JavaScript.

**Comment by dvaldivia** [comment]
that is a valid assumption, perhaps the `XMLHttpRequest` object is not great for dealing with large files but we use it to show some progress when downloading the file, when you download the file directly you are not going through the JS, perhaps we should STAT the file and if it's beyond a certain mark just do direct download, unless we implement some chunking on the client

**Comment by heiko-ma** [comment]
The nice thing about the JS-Solution is that it is relatively CPU friendly. I observed a high CPU/GPU-Usage due to scanning from Windows Defender (Microsoft Network Realtime Inspection Service). When passing the download through JS, it doesnt trigger the Inspection Service.

**Comment by dvaldivia** [comment]
looking around, perhaps this [gist](https://gist.github.com/semlinker/8453bbad093caaf321b153285b350d84) approach which downloads the file using byte ranges, worth trying

**Comment by allanrogerr** [comment]
1MB, 10MB, 100MB, 1G, 10G file uploaded and downloaded without issue. Testing 100G file.

**Comment by allanrogerr** [comment]
@reivaj05 Failed at 100G with "Resource requested is unreadable, please reduce your request rate". My steps:

- clone console repo
- run make assets
- replace the console entry in the minio go.mod file
- make docker in minio
- load the docker image to kind
- create a minio tenant using this minio image
- attempt an upload/download of a 100G file
- face above issue
