### ISSUE TITLE
ILM rule add non-current version broken

### ISSUE THREAD

**Issue by T-M-A** [minio/console#2767]
In the console version ```minio-console version 0.26.3 - 7519fad6d```, the addition of ilm was broken, indicating current or non-current versions.

![image](https://user-images.githubusercontent.com/19513404/230851184-a4d215fa-1f38-4259-b76d-61a0ea38ea45.png)

**Comment by dvaldivia** [comment]
thanks, we'll look into it, We should also add a test to make sure this doesn't happen again
