### ISSUE TITLE
Error 403 when trying to view buckets

### ISSUE THREAD

**Issue by Igorgro** [minio/console#2800]
I have Minio deployed using docker compose.  Minio server and console are proxied using nginx with following config:
```
server_name s3.example.com;
location / {
    proxy_pass http://127.0.01:9000/;
}

location /console/ {
    proxy_pass http://127.0.0.1:9001/;
}
```

I have `MINIO_BROWSER_REDIRECT_URL` env variable set to `https://s3.example.com/console/`, but have the following bug: when I try to view buckets in console, it sends request to `https://s3.example.com/api/v1/buckets` instead of `https://s3.example.com/console/api/v1/buckets` which results in 403 error. I tried to remove slashes from nginx config, but this results in completely broken console and more errors. What should I change to make it working correctly without changing domain? It is strange that all other requests (users for example) are sent to correct `/console/` endpoint

UPD. Found the difference: all requests are sent by `client.js:870` while this broken request is sent by `consoleApi.ts:1554`

**Comment by cassidy3** [comment]
Dupe of #2774 I believe. Started in RELEASE.2023-04-07T05-28-58Z

**Comment by Igorgro** [comment]
Ok, closing in flavor of mentioned one
