### ISSUE TITLE
Bucket name not checked against ETCD in federated bucket setup, results in a silent error on the UI

### ISSUE THREAD

**Issue by vdombrovski** [minio/console#2802]
Setup:
---

2 minio tenants with MINIO_ETCD_ENDPOINTS, MINIO_DOMAIN set

Integrated MinIO console, RELEASE.2023-04-28T18-11-17Z

To reproduce:
---

1. Log into the console of the first tenant, create a new bucket "test"
2. Log into the console of the second tenant, try creating the same bucket "test"

Expected behavior:
---

Bucket creation fails with the error message returned by the API (as a notification for example):

"The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again."

Actual behavior:
---

Bucket creation fails silently, the bucket is not created and nothing shows on the UI. User stays on the add bucket screen.

**Comment by harshavardhana** [comment]
This is not something that will be supported, you should be migrating away from Federated setups.

Console UI is not going to further support federation anymore.
