### ISSUE TITLE
AssumeRoleWithLDAPIdentity error message when user does not have any policy set logs too much information

### ISSUE THREAD

**Issue by pablodamico** [minio/console#2803]
When adding ldap authentication to MinIO and when the user doesn't have any policy set, it shows an error message in the GUI with this information Expecting a policy to be set for user `CN=xxxxxx` or one of their groups <all user's groups> - rejecting this request, in the case the user has a lot of groups, it will cover all the screen with this error message. I found this in the code fmt.Errorf("expecting a policy to be set for user `%s` or one of their groups: `%s` - rejecting this request", so my doubt is if there is any way to disable this or reduce the verbosity to only show something like Expecting a policy to be set for user `CN=xxxxxx` or one of their groups  - rejecting this request.

Thanks!

**Comment by cesnietor** [comment]
duplicates: https://github.com/minio/console/issues/1859
