### ISSUE TITLE
How to set bucket to public by mc command?

### ISSUE THREAD

**Issue by winktool** [minio/console#2840]

**Comment by shtripat** [comment]
`mc policy set public ALIAS/BUCKET`

**Comment by prakashsvmx** [comment]
`mc anonymous set public <alias>/<bucket>`  

same can be set in ui via bucket settings 

http://<url>/buckets/<bucket>/admin/prefix  -> Add  Access Rule ->  
prefix '/' 
Policy : `readWrite`
