### ISSUE TITLE
Console UI white screen "You need to enable JavaScript to run this app."

### ISSUE THREAD

**Issue by TCGOGOGO** [minio/console#2854]
Minio Version:
![image](https://github.com/minio/console/assets/10043464/576f2176-0ef4-4927-8d16-7350472bf400)
Minio cluster is provisioned by minio operator in k8s
![16855911053335](https://github.com/minio/console/assets/10043464/d3d49f74-2cf3-408a-9919-2e734454c6af)
click whatever button in console portal result in a white screen
![16855915399254](https://github.com/minio/console/assets/10043464/7742940f-5c20-4845-a5ba-c634571f76e6)
![image](https://github.com/minio/console/assets/10043464/ebf980eb-f217-48f7-85ad-2faad1f6dd7e)
![image](https://github.com/minio/console/assets/10043464/bd730fcc-cd82-490b-a6a0-6f1dc6132375)

BTW, I could use mc to connect and control this minio cluster, while console is down, [This is not work for me](https://github.com/minio/minio/issues/12654)

**Comment by kambei** [comment]
Same here

![Schermata del 2023-06-05 22-57-40](https://github.com/minio/console/assets/10435317/ebe91ec2-f661-43ab-9467-9f87b57cf5a1)

**Comment by TCGOGOGO** [comment]
Any update for this?

**Comment by cesnietor** [comment]
Hi  @TCGOGOGO  this issue is happening in Operator so this ticket should be in Operator. We verified it. Closing and reopening this one https://github.com/minio/operator/issues/1620
