### ISSUE TITLE
Virtualize the "Downloads/Uploads" popup's items

### ISSUE THREAD

**Issue by ali-garajian** [minio/console#2878]
I recently had to upload a large batch of image(around 2000), and noticed this popup's item list is not virtualized, hence is very laggy and memory consuming and makes the entire UI unresponsive.

![image](https://github.com/minio/console/assets/50337133/bd59a88d-b547-4d13-a503-1ce22dc13da6)

I'd be happy to send a PR

**Comment by cesnietor** [comment]
Hi @ali-garajian  I just tested it with 500 files of 40M size and it do see that the upload component lags a bit but the responsivness of the UI works fine, is it different for you?, is just the other api calls  (when moving to buckets, access keys, etc) that take a bit more time. 

This is the issue that you are describing right?
<img width="414" alt="Screenshot 2023-06-14 at 11 04 27 AM" src="https://github.com/minio/console/assets/11819101/ba44b868-8c65-4184-8746-c7adc78296ae">


Please feel free to send a PR we'll be happy to review it.

**Comment by cesnietor** [comment]
Uploading a video on what I've described above.
https://github.com/minio/console/assets/11819101/6510ed82-7976-49eb-bc33-37e6b231c8d2

**Comment by ali-garajian** [comment]
Yes, that's exactly the issue, plus the list becomes hardly scrollable. 
I guess it's just a classic list rendering issue; The more items, the more memory it takes to store and render them. 
I'm using a medium tier device with 16GBs of RAM, and as I described, when uploading 2000 objects, UI is hardly responsive
