### ISSUE TITLE
Healing Page shows "Drives" title instead

### ISSUE THREAD

**Issue by cesnietor** [minio/console#2880]
The following page is about the Healing feature but it's being named as `Drives` also the page doesn't show anything about what it does.

![Screenshot 2023-06-14 at 10 28 29 AM](https://github.com/minio/console/assets/11819101/362abc6a-4ca9-4c45-a0a8-f398337a2889)

The page shows some docs in the `?` button but probably we can just rename the button to `Start Healing` to be a bit more descriptive about what it will do without needing the user to click on the help button.

![Screenshot 2023-06-14 at 10 33 14 AM](https://github.com/minio/console/assets/11819101/fc7e7798-64d5-4bd1-beef-ee7a6f8072b5)

Version Minio Console  v0.29.0

**Comment by bexsoft** [comment]
This page was deprecated in v0.45.0, closing this issue as it is no longer required
