### ISSUE TITLE
Ldap IDP configuration not shown in web gui when configured without enable: on

### ISSUE THREAD

**Issue by acottre** [minio/console#2881]
In minio, the `enable: on` is optional, with the default being on, however in the code for the console, it explicitally looks for this to display the configuration.

This leads to an instance which has not got the enable flag set, showing that ldap is not enabled in the web gui

https://github.com/minio/console/blob/fc4263e2f9201a2ab6dbf4122642ae340c47f62b/portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx#L83

https://github.com/minio/minio/blob/0474791cf8b990c7d44774e7f06f55c415dc3291/internal/config/identity/ldap/config.go#L192

Unless I am misunderstanding this, but it matches my current experience of the variable not being set while ldap is functional, and it not showing up in the console

**Comment by cesnietor** [comment]
We will remove the flag that is causing this.

**Comment by BiniKP** [comment]
Hi, is this planned to be fixed soon?
