### ISSUE TITLE
'Cannot read properties of null (reading 'close')' issue while downloading folders

### ISSUE THREAD

**Issue by bexsoft** [minio/console#2890]
## Description

There is an issue while downloading multiple files or folders in Object browser:

<img width="432" alt="Screenshot 2023-06-16 at 12 16 04" src="https://github.com/minio/console/assets/33497058/c5ca4c56-bd71-44f9-a3be-7e23e6579b08">
<img width="1394" alt="Screenshot 2023-06-16 at 12 10 28" src="https://github.com/minio/console/assets/33497058/0fd59ce4-990e-4bcf-b64e-a443e349c401">

## How to reproduce

1. Go into a bucket with a folder in it
2. Click on the checkbox next to the folder name and click download
3. Expand Download manager. Issue is seen here

------
1. Go into a bucket with multiple files (more tan 100)
2. Click on the select all checkbox and click download button
3. A failure may be seen and multiple files will start to fail during download

## Expected Behavior

No errors should be seen and files should get downloaded correctly. Folders should be downloaded as zip files.

**Comment by cesnietor** [comment]
Might be related to https://github.com/minio/console/pull/2773

**Comment by cesnietor** [comment]
Code is panicking here https://github.com/minio/console/blob/master/portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/utils.ts#LL182C10-L182C10

**Comment by dhzoo30** [comment]
Hi, I faced the same issue. I used latest version (v0.30.0). It happens regardless of file size.
