### ISSUE TITLE
MinIO Console Websocket connections don't work if using no-default port for console-address

### ISSUE THREAD

**Issue by gjaekel** [minio/console#2900]
When using the configuration parameter `--console-address` to change the port used to access the MinIO Console UI, the Console application will fail on features like "Oject Browser" with a Websocket Communication error. 

## Expected Behavior
The application should work using the chosen Port other than 9080. Of course, this have to be >=1024 if the JVM is not running as root, 

## Current Behavior
The websocket connection fail. The application even detect this in a well-controlled way and displays an error banner. 

## Possible Solution
Maybe the Listener for the websocket don't respect the chosen port settings.

## Steps to Reproduce (for bugs)

1. use a non-default port for console-adresse, e.g. `--console-address 1.2.3.4:19080` as parameter
2. access the MinIO Console UI
3. switch to the "Object Browser"
4. enter a Bucket 

Using the browsers Dev Tool, I found that the requested Websocket URL is something like `GET ws://minio.dnb.de.appr:19080/ws/objectManager`

## Regression
I'm not sure if this is an regression, because I don't know if the version we used before even use Websockets. But we use a not-default-port setting since at least 2022-04.

## Your Environment

* Version used (`minio --version`):
    `minio version RELEASE.2023-06-16T02-41-06Z (commit-id=25db1e4eca2f81b760446147006fe255e240e4be)` (binary distribution package)
* Server setup and configuration:
  E.g. `/usr/bin/minio server /data/minio --anonymous --address minio.dnb.de.appr:19000 --console-address minio.dnb.de.appr:19080 --certs-dir /var/lib/minio/.minio`
* Operating System and version (`uname -a`):
    ` Linux apprio0 5.15.102-gentoo minio/minio#1 SMP Wed May 10 14:23:18 CEST 2023 x86_64 Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz GenuineIntel GNU/Linux`

**Comment by bexsoft** [comment]
Hi @gjaekel!

Are you behind a load balancer such NGINX?

**Comment by gjaekel** [comment]
@bexsoft No, this is direct access to the daemon. Today I try to get some time to figure out if I'm able to trace a difference between using `9080` and another port.

**Comment by gjaekel** [comment]
**Solved**: Was caused by an Squid proxy:

_will add informations_

**Comment by gjaekel** [comment]
Like the clues about a **forward proxy** or **load balancer**, this issue concerning a **reverse proxy** might be useful for the hint section of the documentation ...
