### ISSUE TITLE
Preview not taking mime-type into account but only file extension

### ISSUE THREAD

**Issue by ssendev** [minio/console#2919]
The preview at the right only works if the file name ends in .png or another image extension if it has no extension the preview is disabled.

## Expected Behavior
Enable the preview button if a compatible mime type is set

## Current Behavior
The prieview button is disabled even if an image mime type is set

## Steps to Reproduce (for bugs)

1. upload an image with a key of `foo.png`
2. upload the same image with a key of `foo` and set the mime type to `image/png`
3. see that `foo.png` has a the preview while `foo` has not

## Context

The correct mime type is listed at the bottom and is also returned when generating a share url.

## Your Environment

* Version used (`minio --version`): RELEASE.2023-06-29T05-12-28Z (commit-id=aae684641325e1c37375d455c790e58d902bd7b6)
* Server setup and configuration: Docker

**Comment by harshavardhana** [comment]
In that case we can provide preview.

**Comment by prakashsvmx** [comment]
Thank you @ssendev . for the supported preview types, we will also add `Content-Type` based  preview along with extension based preview.
