### ISSUE TITLE
OIDC env variables not correctly represented in UI

### ISSUE THREAD

**Issue by PKizzle** [minio/console#2936]
## Expected Behavior
Environment variables correctly alter the configuration and are correctly displayed in the MinIO console.

## Current Behavior
When setting environment variables in the official helm chart i.e. `MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC` to `on` as mentioned in https://github.com/minio/docs/issues/913 the console does not display an enabled switch. I have discovered that this also applies to `MINIO_IDENTITY_OPENID_CLIENT_SECRET` (no text is shown). Other env vars might also be affected.

## Steps to Reproduce (for bugs)
1. Set all possible OIDC environment variables in the official helm chart (set variables not available under `oidc` section in the `environment` section)
2. Install the helm chart
3. Open the MinIO console and check the default OIDC configuration

## Regression
Unknown.

## Your Environment
* MinIO version used: RELEASE.2023-07-07T07-13-57Z
* Server setup and configuration: MinIO helm chart 5.0.11 on a 1.27.2 k3s cluster (3x RaspberryPi 4B)
* Operating System and version: 6.1.21-v8+ aarch64 GNU/Linux

**Comment by cesnietor** [comment]
This is a missing feature and we'd have to add it to Console.

**Comment by bexsoft** [comment]
Fix applied to LDAP page, Will add this same fix to OpenID page
