### ISSUE TITLE
No new versions after 0.30 available on hub.docker.com/r/minio/console 

### ISSUE THREAD

**Issue by shoce** [minio/console#2937]
## Expected Behavior
New versions 0.31 and 0.32 of minio/console docker images expected to be available on hub.docker.com

## Current Behavior
The most recent minio/console docker image available on hub.docker.com is version 0.30

## Steps to Reproduce (for bugs)
https://hub.docker.com/r/minio/console/tags

**Comment by harshavardhana** [comment]
Console is part of MinIO UI, there are no more containers or binaries published from this project. 

It is a library now.

**Comment by shoce** [comment]
> Console is part of MinIO UI, there are no more containers or binaries published from this project.
> 
> It is a library now.

Oh sorry, didn't know this. I used to have two containers in docker compose: one for minio and another for minio console linked to the minio container. How should I proceed now? Is the console included into minio/minio container now?

**Comment by harshavardhana** [comment]
> Oh sorry, didn't know this. I used to have two containers in docker compose: one for minio and another for minio console linked to the minio container. How should I proceed now? Is the console included into minio/minio container now?

This has been true since 2.5yrs now @shoce
