### ISSUE TITLE
Unobvious behavior of Download button

### ISSUE THREAD

**Issue by andy812** [minio/console#2939]
<img width="1241" alt="изображение" src="https://github.com/minio/console/assets/29895539/2b874fd4-72b6-48f7-bfa7-6d08bf2a934f">
You can select file (without using a checkbox) and then you see Download button. When you click it nothing happens.
You can download a file only when you click on checkbox. I think it's an unobvious behavior.

## Expected Behavior
Hide download button when checkbox is not selected. Or allow to download selected file (without using a checkbox).

## Your Environment
RELEASE.2023-07-07T07-13-57Z

**Comment by prakashsvmx** [comment]
Looks like it is a bug. Possible fix in https://github.com/minio/console/pull/2930

**Comment by prakashsvmx** [comment]
We can reopen if required.
