### ISSUE TITLE
console not loading - "you need to enable javascript to run this app"

### ISSUE THREAD

**Issue by pasztorl** [minio/console#2943]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I've installed the latest RELEASE.2023-07-11T21-29-34Z minio from debian package.
It sits behind nginx ( https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html )
mc command works well, console not loading.
nginx accesslog:
``
172.23.9.20 - - [14/Jul/2023:11:20:34 +0200] "GET / HTTP/1.1" 307 88 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:34 +0200] "GET /minio-console HTTP/1.1" 200 601 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:35 +0200] "GET /minio-console/manifest.json HTTP/1.1" 200 980 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:35 +0200] "GET /minio-console/static/css/main.7f39beab.css HTTP/1.1" 200 4823 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:35 +0200] "GET /minio-console/styles/root-styles.css HTTP/1.1" 200 336 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:35 +0200] "GET /minio-console/static/css/main.7f39beab.css.map HTTP/1.1" 200 8552 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:35 +0200] "GET /minio-console/Loader.svg HTTP/1.1" 200 18052 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:35 +0200] "GET /minio-console/images/background.svg HTTP/1.1" 200 586 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:35 +0200] "GET /minio-console/static/js/main.81adfdde.js HTTP/1.1" 200 2854813 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:35 +0200] "GET /minio-console/images/background-wave-orig2.svg HTTP/1.1" 200 663820 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:36 +0200] "GET /minio-console/static/media/Inter-Regular.c8ba52b05a9ef10f4758.woff2 HTTP/1.1" 200 98868 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
172.23.9.20 - - [14/Jul/2023:11:20:36 +0200] "GET /minio-console/static/js/main.81adfdde.js.map HTTP/1.1" 200 5177250 "https://backup1.int.eu-west-1a.int1.wl/minio-console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"
``
There is no request with errors.

## Expected Behavior
Console loads correctly.

## Current Behavior
Blank screen.

## Steps to Reproduce (for bugs)

1. install minio from deb package
2. configure nginx as minio site recommends

## Your Environment

* MinIO version used (`minio --version`): RELEASE.2023-07-11T21-29-34Z
* Server setup and configuration: Jammy base system
* Operating System and version (`uname -a`): 5.19.0-1026-aws

**Comment by prakashsvmx** [comment]
have you tested without a proxy @pasztorl  ?

**Comment by pasztorl** [comment]
@prakashsvmx yes it works, so maybe the example wrong in the minio site. Do you have a working sample config for the "subpath" example?

**Comment by prakashsvmx** [comment]
Please refer to https://github.com/minio/console/pull/2818 @pasztorl . 

Closing this issue.

**Comment by enriquecaballero** [comment]
@prakashsvmx This is still happening for me. FWIW, I'm using Traefik. It loads without proxy.
