### ISSUE TITLE
Console appears to not save LDAP config, always missing bind pw

### ISSUE THREAD

**Issue by feorlen** [minio/console#2967]
Configuring LDAP from Console doesn't appear to succeed because the Lookup Bind Password isn't saved. LDAP always shows as not configured. 

But `mc admin config get myminio identity_ldap` shows the expected configuration and LDAP works.

Tested with the LDAP server from Will Dinyes' `dinyes.co` IAM lab, which uses `mc`. Will has the same problem with Console, so it's not only my test VM.

## Expected Behavior

Console saves the LDAP configuration and shows LDAP enabled.

## Current Behavior

All the other settings are saved, but Console always says the Lookup Bind Password is missing. "LDAP Enabled" is always "No" even when LDAP login works.

## Steps to Reproduce (for bugs)

1. Install SNSD following docs.
1. Log in to Console as admin.
1. Configure LDAP, restart.
1. Log out and return to login page.
1. No LDAP shown in Other Authentication Methods.
1. Log in as admin, view LDAP configuration.
1. Bind password is missing and GUI reports LDAP is not enabled.
1. In terminal, `mc` shows expected configuration.
1. With `mc`, able to attach consoleAdmin policy to an LDAP user and login.

```
$ mc admin config get myminio identity_ldap
identity_ldap server_addr=blahblah.dinyes.co:389 srv_record_name= user_dn_search_base_dn=dc=minio,dc=io user_dn_search_filter=(cn=%s) group_search_filter= group_search_base_dn= tls_skip_verify=off server_insecure=on server_starttls=off lookup_bind_dn=cn=admin,dc=minio,dc=io 
```

## Your Environment

Ubuntu VM on Ubuntu host with KVM/Virtual Machine Manager

Guest OS:
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-78-generic x86_64)

MinIO:
https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20230718174940.0.0_amd64.deb

Terminal session from MinIO install
[ldap-console-bug-scrollback-annotated.txt](https://github.com/minio/console/files/12188411/ldap-console-bug-scrollback-annotated.txt)

Video of Console login and reproduction available privately (contains live URLS, etc)

**Comment by cesnietor** [comment]
This might be caused by a recent change done in minio https://github.com/minio/minio/pull/17380, we'll try to reproduce.

**Comment by cniackz** [comment]
Ok guys, finally I will reproduce this today. If reproducible, then I will see if it is related to minio change above and finally a fix has to be provided!. So starting today! 👍

**Comment by cniackz** [comment]
### Reproduced:

I have configured MinIO with LDAP:

```
$ mc admin idp ldap info myminio
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│        lookup_bind_dn: uid=cniackz,ou=Users,o=64678734a355340072e048a0,dc=jumpcloud,dc=com  (environment)│
│           server_addr: ldap.jumpcloud.com:636  (environment)                                             │
│       tls_skip_verify: on  (environment)                                                                 │
│user_dn_search_base_dn: ou=Users,o=64678734a355340072e048a0,dc=jumpcloud,dc=com  (environment)            │
│ user_dn_search_filter: (uid=%s)  (environment)                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯

$ mc admin idp ldap list myminio
╭─────────────────────────╮
│ On?    Name     RoleARN │
│ 🟢   (default)          │
╰─────────────────────────╯

$ mc admin idp ldap policy attach myminio consoleAdmin --user='uid=cniackz,ou=Users,o=64678734a355340072e048a0,dc=jumpcloud,dc=com'
Attached Policies: [consoleAdmin]
To User: uid=cniackz,ou=Users,o=64678734a355340072e048a0,dc=jumpcloud,dc=com
```

And indeed our UI has not reflected that:

<img width="1840" alt="Screenshot 2023-08-04 at 11 12 13 AM" src="https://github.com/minio/console/assets/6667358/bb135359-42a3-4562-952e-ee95c90e805d">

So now, based on those findings, I will proceed to determine when this got broken or how is supposed to work, as I do remember, this was previously working. Very likely this has to do with a change in MinIO repo.

**Comment by cniackz** [comment]
Ok, this time I was able to configure it via UI but only reflected in the Network tab or mc cli:

```sh
$ mc admin idp ldap info myminio
╭────────────────────────────────────────────────────────────────────────────────────────────╮
│                enable: on                                                                  │
│        lookup_bind_dn: uid=cniackz,ou=Users,o=64678734a355340072e048a0,dc=jumpcloud,dc=com │
│           server_addr: ldap.jumpcloud.com:636                                              │
│user_dn_search_base_dn: ou=Users,o=64678734a355340072e048a0,dc=jumpcloud,dc=com             │
│ user_dn_search_filter: (uid=%s)                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
```

<img width="1840" alt="Screenshot 2023-08-04 at 11 37 23 AM" src="https://github.com/minio/console/assets/6667358/d2f35256-e411-4fee-a8ea-451555d76239">

meaning, our UI/React code is struggling to render this configuration.
Definitely an ui issue here!

**Comment by cniackz** [comment]
Now, let's root cause when and why this got broken to proceed to fix it!.

**Comment by cniackz** [comment]
Update is an easy one, all we need is to remove the password as it is not longer passed down to the UI for security reasons:

```sh
$ git diff portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
diff --git a/portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx b/portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
index 243cc08f9..28c879f22 100644
--- a/portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
+++ b/portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
@@ -50,7 +50,6 @@ import HelpMenu from "../../HelpMenu";
 const enabledConfigLDAP = [
   "server_addr",
   "lookup_bind_dn",
-  "lookup_bind_password",
   "user_dn_search_base_dn",
   "user_dn_search_filter",
```
