### ISSUE TITLE
Minio LDAP is enabled but ui show disabled

### ISSUE THREAD

**Issue by oscaratienza92** [minio/console#2984]
Minio CLI show ldap is enabled

![image](https://github.com/minio/minio/assets/37838280/20197155-661f-42be-a764-c6c9a82a809d)

but ui show disabled, and not permit click entities tab

![image](https://github.com/minio/minio/assets/37838280/07c4a22d-38fe-406b-bfa7-5d5e87e0733a)

Edit:
and also if ldap is enabled, it allows to use user and password root and the default console user

**Comment by cesnietor** [comment]
Hi this is a duplicate from https://github.com/minio/console/issues/2881

**Comment by BiniKP** [comment]
Sorry to write in a closed ticket but with the new version I'm still having the same issue.
Installed Packages
minio.x86_64  20230809233022.0.0-1

**Comment by cesnietor** [comment]
@BiniKP  it has been solved in console but it still has to be released on minio repository, we will do that soon.
