### ISSUE TITLE
Errors not being exposed in the UI

### ISSUE THREAD

**Issue by cesnietor** [minio/console#2997]
When an error occurs, tipically a 500 error, there is no visual feedback on what went wrong.
Currently we need to go to the browser's Inspector to see what went wrong which makes debugging more difficult.

This can happen due to e.g. a wrong policy, an ldap user with not enough permissions, etc.
e.g.

<img width="685" alt="Screenshot 2023-08-14 at 4 58 50 PM" src="https://github.com/minio/console/assets/11819101/94f7c761-66fb-4e52-bfa9-219c328548c2">

## Expected Behavior
500 errors should be shown in the UI could be a snack bar or something related.

## Current Behavior
Errors are not being shown

## Possible Solution
Show snackbar on all non 200 codes for all requests unless 400 codes and permission denied errors are already being handled.

## Steps to Reproduce (for bugs)
Example with wrong Policy
- Go to Access Keys
- Add new Access Key
- click on created object
- A policy builder should pop up
- Type only `{` 
- Click on Set
- An error should occur due to the invalid policy
- [Error] The error is not being shown, only on inspector you'd see the 500

## Your Environment

* MinIO version used (`minio --version`): RELEASE.2023-08-09T23-30-22Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by bexsoft** [comment]
This should be fixed with https://github.com/minio/console/pull/2954

**Comment by bexsoft** [comment]
> This should be fixed with #2954

Checked this issue against fix, it doesn't solve in all cases, need to review all error cases

**Comment by cesnietor** [comment]
we'll check in which places we are not catching the errors properly and fix them.

**Comment by cniackz** [comment]
more spots fixed: https://github.com/minio/console/pull/3008

**Comment by cniackz** [comment]
Some of these issues have already been addressed, and things are evolving. While having a list would be beneficial, it will take time, and currently, it is considered a low priority. I will close this issue for now. If we encounter the same issue in the future, please open a new issue as needed, and we can reassign accordingly.
