### ISSUE TITLE
web console:local logins unreachable if SSO is down

### ISSUE THREAD

**Issue by bpedersen2** [minio/console#3018]
If  the configured SSO (openid) provider is not reachable (due to expired certificate), then the frontend does not offer the alternate login with local credentials, instead only an error is displayed: 

```
An error has occurred
The backend cannot be reached.
```

I would expect the switch to login with a local password to be available in this case. 
minio Version: RELEASE.2023-08-16T20-17-30Z (go1.19.12 linux/amd64)

**Comment by bexsoft** [comment]
Hi @bpedersen2! How are you doing?

In the Login page we offer the ability to login using embedded IDP (Local Password) in case of necessary.

To access this option, you have to select the `Other Authentication Methods` dropdown and then Select the `Use Credentials` option:

<img width="1498" alt="Screenshot 2023-09-25 at 12 10 29" src="https://github.com/minio/console/assets/33497058/66acd9d4-507e-45fb-acc3-c0d9737bc43d">

This will display the Login fields to use admin or embedded credentials:

<img width="1498" alt="Screenshot 2023-09-25 at 12 10 36" src="https://github.com/minio/console/assets/33497058/fea6f227-468b-4fe2-a6a9-6663dbcdbbf4">

Please let us know if you have further questions.

Regards.

**Comment by bpedersen2** [comment]
The problem is (only a single oidc login configured)  that the selector is not shown, instead there is only an error message:

![screenshot-minio storage frm2 tum de_9001-2023 09 26-08_28_24](https://github.com/minio/console/assets/5336494/52a562de-900a-4099-bbfb-8c6602a25180)

**Comment by bpedersen2** [comment]
To test, you should use e.g. a keycloak instance and shut it down. Testing with github/google/etc. will be tricky as you need to make them unreachable.

**Comment by bpedersen2** [comment]
I suspect https://github.com/minio/console/pull/2258/files#r1336700937 could be the culprit here.

**Comment by cesnietor** [comment]
thanks @bpedersen2 we'll reopen and investigate. Also feel free to send a PR and we can test it. It won't be prioritized right now.

**Comment by ribeaud** [comment]
This happens during _local_ testing (http://localhost:9001/) as well. My **OpenID** provider is up and running.

@bpedersen2: by certificate expiration, do you mean HTTPS certificate? So, does it mean, I would not get this error if I am using HTTPS and the certificate is OK?

**Comment by bpedersen2** [comment]
> This happens during _local_ testing (http://localhost:9001/) as well. My **OpenID** provider is up and running.
> 
> @bpedersen2: by certificate expiration, do you mean HTTPS certificate? So, does it mean, I would not get this error if I am using HTTPS and the certificate is OK?

No, on my side the problem only occured if the  openId-provider is unreachable for any reason.

**Comment by ribeaud** [comment]
Thanks. Forget my previous comment. Somehow, I messed up my configuration. By reverting the changes, it is working now.

**Comment by tsuzu** [comment]
I have the same issue.
When I use kube-apiserver as an OIDC provider for minio, the console always shows the error login page.
Because kube-apiserver doesn't implement the login flow.

**Comment by harshavardhana** [comment]
Hopefully #3168 might address it.
