### ISSUE TITLE
JSON object (Content-Type application/json) not previewing in the console

### ISSUE THREAD

**Issue by tgy** [minio/console#3019]
## Expected Behavior

The console should allow previewing JSON objects (maybe up to a certain size).

The JSON string should be prettified for better readability.

## Current Behavior

No preview is possible for application/json objects. You can only download the file.

## Your Environment

MinIO VERSION 
2023-08-23T10:07:06Z

Rocky Linux 9

Docker Hub image (latest)

**Comment by vokamut** [comment]
Expect heading: `Content-Type: application/json`
Heading given: `Content-Type: application/octet-stream`

**Comment by vokamut** [comment]
Old jsion files are returned successfully. Оnly the new ones have a different header

**Comment by prakashsvmx** [comment]
JSON file type is not supported for preview. 
only image, audio, video are supported.

**Comment by mnowaczyk** [comment]
> JSON file type is not supported for preview. only image, audio, video are supported.

Can you explain why? It's just text, the browser is perfectly capable of displaying it.

**Comment by harshavardhana** [comment]
> > JSON file type is not supported for preview. only image, audio, video are supported.
> 
> Can you explain why? It's just text, the browser is perfectly capable of displaying it.

Our choice, JSON can be a bigfile that can negatively impact normal operations. If we concentrate unnecessarily previewing such content. We do this already for videos and audio.

What we are providing is already an artisanal functionality. It does what is presented.

**Comment by tgy** [comment]
siding with @mnowaczyk here. previewing JSON data would be useful. even if trimmed.

**Comment by matutter** [comment]
@harshavardhana is the project open to a MR to restore support for JSON preview? And perhaps a flag to enable it so that JSON previews are not available by default.

**Comment by GXMark** [comment]
I'm currently using MinIO for my MMO object storage solution and I love it but not having a JSON previewer is ultra annoying to me since alot of my development is checking JSON file content that its ID reference fields match up.  Can i suggest an option to preview json file text like was suggested with a user definable size limit? 

I've also used couchbase and that has a super json preview facility on its documents.

**Comment by harshavardhana** [comment]
It is what it is; you can send a PR without assurances on merging it. To avoid more bike shedding on this topic, we are locking this issue.
