### ISSUE TITLE
MINIO_BROWSER_REDIRECT_URL Inspect Object not working 

### ISSUE THREAD

**Issue by LexPanov** [minio/console#3030]
MinIO configured behind reverse proxy with MINIO_BROWSER_REDIRECT_URL using incorrect URL for Inspect Object

![image](https://github.com/minio/console/assets/4084213/8abd801b-67d0-4eae-8207-a39b68692718)

## Expected Behavior

Correct API URL for Inspect Object

## Current Behavior

Incorrect API URL for Inspect Object because of 
https://github.com/minio/console/blob/a6eee73c11ac9792dea9a5f4fcdd58a51cff3e92/portal-ui/src/screens/Console/Tools/Inspect.tsx#L149

## Possible Solution

Maybe, it will work if this line will be like this

https://github.com/minio/console/blob/a6eee73c11ac9792dea9a5f4fcdd58a51cff3e92/portal-ui/src/api/index.ts#L4

```js
    const urlOfInspectApi = `${new URL(document.baseURI).pathname}api/v1/admin/inspect?volume=${volume}&file=${file}&encrypt=${isEncrypt}`;
```

## Steps to Reproduce (for bugs)

1. MinIO Console behind reverse proxy at `$HOST/minio/ui/`
2. `MINIO_BROWSER_REDIRECT_URL="$HOST/minio/ui/"`
3. Open "test" bucket at `$HOST/minio/ui/browser/test`
4. Select file
5. Right panel -> Actions -> Inspect

## Context
Issue #2774
PR #2818

## Your Environment

* MinIO version used (`minio --version`): `RELEASE.2023-08-31T15-31-16Z (commit-id=e47e625f73bb1c9672e6c8e4c3b3f9a0e93423a0)`

**Comment by wxrl** [comment]
running `mcli admin config set local-s3 MINIO_BROWSER_REDIRECT_URL https://my.domain.com/s3` on my server (as known as `local-s3` in the config.json with API key set correctly)
returns
`mcli: <ERROR> Unable to get help for the sub-system: unknown sub-system MINIO_BROWSER_REDIRECT_URL.`
