### ISSUE TITLE
2023.09.04 redirects from /ui/ to /login, not to /ui/login

### ISSUE THREAD

**Issue by hashworks** [minio/console#3036]
## Expected Behavior

When one sets `MINIO_BROWSER_REDIRECT_URL="https://minio.example.net/ui/"` it should redirect unauthenticated users to `https://minio.example.net/ui/login`.

## Current Behavior

2023.09.04 redirects unauthenticated users to `https://minio.example.net/login`, which displays an S3 error (since it isn't pointing to console).

## Steps to Reproduce (for bugs)
1. Install minio 2023.09.04
2. Use a reverse proxy like nginx to provide console at `/ui`
3. Set `MINIO_BROWSER_REDIRECT_URL="`https://minio.example.net/ui/"`
4. Open `https://minio.example.net` or `https://minio.example.net/ui/`

## Regression

This is a regression in 2023.09.04, works in 2023.08.31.

## Your Environment
* MinIO version used (`minio --version`): `2023-09-04T19-57-37Z (commit-id=ffc03545aa908d9ec46e5d813ff0cefa158815f7)`
* Server setup and configuration: nginx reverse proxy
* Operating System and version: Arch Linux, `6.4.12-arch1-1`

**Comment by Morethanevil** [comment]
Exactly the same problem, I need to press the back butoon, then it loads

**Comment by cesnietor** [comment]
Thanks for raising  indeed there was an issue which is being solved in the PR above ^.
