### ISSUE TITLE
Update Styling

### ISSUE THREAD

**Issue by dvaldivia** [minio/console#305]
We need to update the styling following the new designs.

<img width="1374" alt="Screen Shot 2020-10-01 at 9 31 26 AM" src="https://user-images.githubusercontent.com/18384552/94837257-e24d6e80-03c8-11eb-8fd2-0717e7a725d4.png">

**Comment by bexsoft** [comment]
Navbar, Titles & login completed. Need to update search boxes styles

**Comment by bexsoft** [comment]
Input styles & some modal boxes are ready, reviewing flows & fixing non updated modals with new components

**Comment by bexsoft** [comment]
Completed lambda styles, will continue with settings adjustments

**Comment by bexsoft** [comment]
Completed settings page changes #334
