### ISSUE TITLE
Docker images are not populated.

### ISSUE THREAD

**Issue by ivan-genev** [minio/console#3052]
From version v0.30.0 new docker images are not populated.

https://quay.io/repository/minio/console?tab=tags
https://hub.docker.com/r/minio/console/tags

**Comment by prakashsvmx** [comment]
Since console is bundled, it is not published as a separate image .

**Comment by yordis** [comment]
I would suggest to update the readme of `minio/console`! I will help the next person like me! 🙏🏻
