### ISSUE TITLE
UI user with 'consoleAdmin' policy can't change his own password

### ISSUE THREAD

**Issue by nixargh** [minio/console#3053]
**Local** user can change other's passwords but not his own. Well, he can enter a new one and save but no real change happens.
His password can be changed using another user.

## Expected Behavior
User with proper permissions can change his own password using UI button "Change Password".

## Current Behavior
UI shows no errors, save button became not active but password stays unchanged.

## Steps to Reproduce (for bugs)
1. Create user with *consoleAdmin* policy and password.
2. Log in to UI console.
3. Change password.
4. Try to login with a new password.

## Your Environment
* MinIO version used (`minio --version`):
```minio version RELEASE.2023-08-31T15-31-16Z (commit-id=e47e625f73bb1c9672e6c8e4c3b3f9a0e93423a0)
Runtime: go1.19.12 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration: [this type of setup](https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html)
* Operating System and version (`uname -a`):
```Linux minio.dev 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by prakashsvmx** [comment]
I checked the latest version and i am able to change the password.

however the user experience can be improved by providing feedback and forcing the user to re-login after changing the password.

![image](https://github.com/minio/console/assets/23444145/0365f6d7-2923-49bd-8973-cc00d2baff63)

**Comment by nixargh** [comment]
> I checked the latest version and i am able to change the password.
> 
> Only MINIO_ROOT_USER login cannot change the password. all other users can change the password.
> 
> however the user experience can be improved by providing feedback when password change is success and forcing the user to re-login after changing the password.
> 
> ![image](https://user-images.githubusercontent.com/23444145/269320411-0365f6d7-2923-49bd-8973-cc00d2baff63.png)

@prakashsvmx Have you checked you can log in with the new password then? In my case I can login only with the old one.

**Comment by nixargh** [comment]
OK, issue solved :) I was pushing another button and it doesn't work that way, so maybe you should hide it for user matching the logged one?
![2023-09-21_11-14](https://github.com/minio/console/assets/2868978/c0dadd3a-2c21-4300-bf19-a345644e3c95)

**Comment by prakashsvmx** [comment]
Thank you for these details @nixargh :+1:
