### ISSUE TITLE
Clicking the amd64 binary release download link in the readme results in a 404

### ISSUE THREAD

**Issue by estolman** [minio/console#3072]
When clicking the amd64 binairy link on the github page in the install section of the readme, the page is not found.

![image](https://github.com/minio/console/assets/8892688/67e22d29-8ded-4e40-9ec8-87dbd909e4de)
![image](https://github.com/minio/console/assets/8892688/e186a26a-4d11-4bf1-a7ab-d4374ffbb609)

**Comment by klauspost** [comment]
Must be old stuff. Have we ever produced standalone binaries?

**Comment by prakashsvmx** [comment]
console is bundled and not published as a standalone package or as a container any more.
i think https://github.com/minio/console/pull/2915/files is the change.
We will check and update the README.md
