### ISSUE TITLE
Trying to change the mds components library

### ISSUE THREAD

**Issue by abdallahifox** [minio/console#3083]
trying to change things in the MDS component library and when I rebuild it after changing some layout of the components or accept some additional props it gives me a conflict can't know why he told me can't find the module of MDS

**Comment by bexsoft** [comment]
Hi @abdallahifox!

Can you please help us to provide more information about the changes you are willing to make?

MDS is a components library only so it is not designed to handle special logic, components can be customized by using the `sx` prop in each of them
