### ISSUE TITLE
Minio Logout is not working from OIDC(keycloak)

### ISSUE THREAD

**Issue by ravisingareddy** [minio/console#3099]
Hi,

i tried minio OIDC login with keycloack i'm able to login successfully but when i try to logout i'm facing issue.

After log out from minio console, the session on keycloak still remaining.

Minio version used is RELEASE.2022-09-17T00-09-45Z

As mentioned in the ticket https://github.com/minio/console/issues/2478,i also tried with the version RELEASE.2022-12-12T19-27-27Z but still issue persists.
i followed the below steps for integrating minio with keycloak.
https://github.com/minio/minio/blob/RELEASE.2022-09-17T00-09-45Z/docs/sts/keycloak.md
Please suggest a fix.

**Comment by adriangitvitz** [comment]
Hi, what keycloak version are you using ? testing with latest Minio console version works and Keycloak v22.0.4

**Comment by ravisingareddy** [comment]
We are using keycloak version 21.0.1.

**Comment by ravisingareddy** [comment]
iam using Keycloak version 21.0.1

**Comment by cesnietor** [comment]
@ravisingareddy  please try with latest MinIO.

**Comment by ravisingareddy** [comment]
i have tested with the below version  but logout issue persists.
minio-RELEASE.2023-07-21T21-12-44Z

**Comment by cesnietor** [comment]
please try with latest minio version.
