### ISSUE TITLE
"Expires cannot be greater than 7 days" when sharing even when under 7 days

### ISSUE THREAD

**Issue by septatrix** [minio/console#3106]
## Expected Behavior

Creating a share link for a duration less than or equal to 7 days should generate a link and not not raise a warning.

## Current Behavior

Selecting a duration larger than 6d23h already triggers the warning and fails to create links.

This is most likely due to not handling DST correctly (which changes this weekend). If the max limit of 7 days is not from the console but the MinIO backend itself, I wonder how AWS S3 handles this and whether MinIO has the same behaviour here.

## Possible Solution

Create a link for a shorter duration.

## Steps to Reproduce (for bugs)

1. Open any bucket with a file inside
2. Select the "Share" action from the sidebar on the right
3. As the default duration is 7 days, there is instantly a warning and no link is generated

## Context

n/a

## Regression

Not sure, though likely not.

## Your Environment

* MinIO version used (`minio --version`): `minio version RELEASE.2023-10-25T06-33-25Z (commit-id=c60f54e5be7302d82d0d8fc404c056fea4e2bf4e)`
* Server setup and configuration: Single-Node, Docker
* Operating System and version (`uname -a`): `Linux <hostname> 6.1.0-11-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux`

**Comment by cesnietor** [comment]
Hi, please see the following issue https://github.com/minio/console/issues/922.
We are still working on improving this feature.
Creating share links with minio client can only be done for up to 7 days. but creating them through console will only be able to share them up to the session's lifetime.

Closing this since it's a duplicate.

**Comment by nreisingercres** [comment]
I'm pretty sure this is a different issue than #922. We had this issue appear after an update from `2023-10-07T15-07-38Z` -> `2023-10-25T06-33-25Z`
Whenever you click the share button, it defaults to 7 days. However the error message `Expires cannot be greater than 7 days.` now pops up even though the expiration is exactly 7 days. In order for the url to appear, we need to set the active time for 6d23h or less. 
Of course as you mentioned, the url will expire with the session no matter how long you set the active time for.
![image](https://github.com/minio/console/assets/141150843/957f5004-892c-4134-a454-b88959d7951c)

In addition, when I set the url to expire after six hours it sends a request with the following. Note that expires is `522000s`, I would expect that to be `518400s`(6 days) so we have an excess of `3600s` or `1h`
![image](https://github.com/minio/console/assets/141150843/89ae605d-df66-46e2-8a1e-7e67ca136800)

**Comment by cesnietor** [comment]
cc @adriangitvitz

**Comment by cesnietor** [comment]
@nreisingercres  thanks feel free to send the PR.

**Comment by septatrix** [comment]
> I would assume that the backend should not account for daylight savings as that's different person person.

This should definitely be checked that it has the same behaviour as AWS in the backend (though I do not know the codebase)!

**Comment by nreisingercres** [comment]
> This should definitely be checked that it has the same behaviour as AWS in the backend (though I do not know the codebase)!
I can't say as far as the backend, but the client limits itself to 604800 seconds or 7 days no accounting for daylight savings.
https://github.com/aws/aws-sdk-js/blob/b22a8b68f597066a16bab162e121515a8d3835ee/lib/signers/presign.js#L20C19-L20C25
