### ISSUE TITLE
Configurations set by env variables are not shown in the UI

### ISSUE THREAD

**Issue by cesnietor** [minio/console#3111]
Relates to: https://github.com/minio/minio/discussions/18328

We currently don't show if env variables are set for a particular configuration. Which causes confusion since the value is shown as the one returned by the config values.

based on the [following](https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-config.html#mc.admin.config.set):
```
Sets a configuration key on the MinIO deployment. Configurations defined by environment variables override configurations defined by this command.
```

We need to add a way to show the value properly.
## Expected Behavior
Disable editing the value if env variable for that config is set

## Current Behavior
We are only returning the equivalent of doing `mc admin config get minio api` but without considering if an env variable was set:
```
ash-4.4# mc admin config get minio api
# MINIO_API_REQUESTS_MAX=2000
api requests_max=0 requests_deadline=10s 
```

## Steps to Reproduce (for bugs)

1. Set a value with env variable e.g. MINIO_API_REQUESTS_MAX
2. Go to UI config `/settings/configurations/api`
3. Value shows as the one returned by mc and not the env variable

## Your Environment

* MinIO version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by bexsoft** [comment]
Reviewing implementation of ENV vars display in Configuration pages
