### ISSUE TITLE
Users with `s3:PutObject` permission on `/foobar/*` are not allowed to create path `foobar`

### ISSUE THREAD

**Issue by hashworks** [minio/console#3122]
## Expected Behavior
If one has `s3:PutObject` permissions to `/foobar/*`, the `Create new path` button should be available.

## Current Behavior
The button is disabled. One has no way to use the UI to upload a file to `/foobar/` if the path doesn't exist. This is possible with `mcli` or the general S3 API, since the `Create new path` button does not execute any S3 action.

## Possible Solution
The disable-logic of the button should check for partial write rights as well.

## Steps to Reproduce (for bugs)
1. Create a new bucket `bucketname`
2. Create a policy `writeInSubpath`
4. Assign the policy to a user
5. Note that the user can't upload files to `/foobar/` if the path doesn't exist already

`writeInSubpath`:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname/foobar/*"
            ]
        }
    ]
}
```

## Context
Users requested permission to a path that didn't exist yet, and were unable to upload files when the appropriate permission was granted.

Might be related to #2951.

## Your Environment
* MinIO version used: `2023-10-25T06-33-25Z`

**Comment by harshavardhana** [comment]
That is expected you are saying that you want to store content starting with prefix foobar, not foobar included.

For what you need provide foobar* instead

**Comment by hashworks** [comment]
But then users could create a file called `foobar`, right?

What I mean is: Over the Web-UI users have no way to upload `/foobar/whatever` files if I just give them access to `/foobar/*`. This isn't an issue with other S3 clients.

**Comment by harshavardhana** [comment]
Okay then that looks like a legitimate bug
