### ISSUE TITLE
Unable to change access policy for the bucket.

### ISSUE THREAD

**Issue by h56983577** [minio/console#3125]
## NOTE
I'm new to Minio and just started exploring it today, so I can't tell whether this is a bug or a feature. This issue has been confusing me,  and I can't find an answer through the Internet.

## Expected Behavior
After creating a bucket, I would like to set it as public directly.

## Current Behavior
When I click the 'Set' button, there is no response. Upon checking the network request history, I found that the request to `/api/v1/buckets/file2/set-policy` failed, with the message `net::ERR_CONNECTION_RESET`.
![image](https://github.com/minio/console/assets/49408466/90a4482b-3338-445d-a7fb-9ba3dd8fb739)
![image](https://github.com/minio/console/assets/49408466/949f204a-b8e4-4c8f-b185-089ca79b0c8f)

This is the body of the request.
![image](https://github.com/minio/console/assets/49408466/f3544bcf-c038-4f44-9452-0efdf117580e)

## Steps to Reproduce (for bugs)

1. Create a new bucket.
![image](https://github.com/minio/console/assets/49408466/71fd833b-77ca-415b-ae38-789539b9d7a8)

2. Access the management interface of the bucket.
![image](https://github.com/minio/console/assets/49408466/dd9ff3db-edbb-4274-a4c6-7875502b44a5)

3. Switch to 'Public' and click the 'Set' button.
![image](https://github.com/minio/console/assets/49408466/0fb0836b-2d73-4ccb-827d-fb70f0bc9296)

4. Then, I saw the error message.
![image](https://github.com/minio/console/assets/49408466/be9b722d-4960-462d-8fb4-0f44412920df)

## Context

I want to quickly set up a testing bucket for personal application development, not for production use. So I set it to public directly.

## Your Environment

* MinIO version used (`minio --version`):
```
minio version RELEASE.2023-11-06T22-26-08Z (commit-id=754f7a8a395e87a744050476d8b16c16af50a800)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
I run this Minio server using Docker.
```bash
docker run -p 9000:9000 -p 9090:9090 --name minio \
  -d --restart=always \
  -e "MINIO_ACCESS_KEY=admin" \
  -e "MINIO_SECRET_KEY=admin123456" \
  -v /data/minio/data:/data \
  minio/minio:RELEASE.2023-11-06T22-26-08Z \
  server /data --console-address ":9090"
```
* Operating System and version (`uname -a`): Linux ubuntu2004 5.4.0-166-generic

**Comment by prakashsvmx** [comment]
Could you please try with `mc anonymous set public ALIAS/bucket`

https://min.io/docs/minio/linux/reference/minio-mc/mc-anonymous-set.html

**Comment by h56983577** [comment]
> Could you please try with `mc anonymous set public ALIAS/bucket`
> 
> https://min.io/docs/minio/linux/reference/minio-mc/mc-anonymous-set.html

Thank you! I successfully set it to 'Public' using the `mc anonymous` command.

**Comment by h56983577** [comment]
@prakashsvmx I'm so sorry. I found that PUT requests are not allowed in my internal network environment, which leads to the error mentioned above. This is not a bug of the Minio console itself.

**Comment by prakashsvmx** [comment]
Sure. thank you,  I have verified this on our hosted instance and local env. it is working as expected.
