### ISSUE TITLE
There is no way to  add or edit `expire time`/`name` /`description` when i craete `Access Keys`

### ISSUE THREAD

**Issue by carolcoral** [minio/console#3133]
* Install method: docker compose
* minio version: RELEASE.2023-11-20T22-40-07Z

When i create access key, there is no way to add or edit fileds like `expiry`/`name`/`description`.
And i had search in docs from your website to find how to resolve it.
I can only find use command in console and i can not login into my console.

Would you plan to add some ways to add or edit them in UI ?Thanks a lot.

<img width="1652" alt="image" src="https://github.com/minio/minio/assets/8952687/624169e9-d840-40b3-87ac-329a33e13e05">
<img width="1652" alt="image" src="https://github.com/minio/minio/assets/8952687/cfc086d8-4eae-49bf-a34e-41b4134f3702">

**Comment by prakashsvmx** [comment]
https://github.com/minio/console/pull/3116

Here is the PR for UI changes

**Comment by carolcoral** [comment]
> #3116
> 
> Here is the PR for UI changes

But i had take note of this PR `Merging is blocked` ?

**Comment by carolcoral** [comment]
@bexsoft hello, i had update `minio/minio` to latest version `RELEASE.2023-12-02T10-51-33Z`,but it not work in my new UI ?
There is no way to set these fileds in my `MinIO Console`.

When can i set them in `MinIO Console` rather than use terminal console command ?

<img width="1678" alt="image" src="https://github.com/minio/console/assets/8952687/307abaf4-6e34-48e1-940e-58a83f829fc0">
<img width="1652" alt="image" src="https://github.com/minio/console/assets/8952687/895f58b6-faaa-49b8-b0f2-0ab18c79a407">
