### ISSUE TITLE
Minio Login is not working from OIDC(keycloak).

### ISSUE THREAD

**Issue by Ayur541** [minio/console#3165]
Hi,

I tried logging into MinIO with Keycloak which is failing and throwing below error.

<img width="957" alt="Capture" src="https://github.com/minio/console/assets/60057656/8c5464a0-3a25-43c8-a54e-514ea7322bcb">

Earlier versions of MinIO were logging in fine as stated in #3099 but when trying it with above mentioned (which was latest release) MinIO verison is failing. 

I followed below steps for integrating MinIO with Keycloak.
https://github.com/minio/minio/blob/RELEASE.2022-09-17T00-09-45Z/docs/sts/keycloak.md
Please suggest a fix. 

Thanks.

**Comment by dvaldivia** [comment]
We'll look into this @Ayur541

**Comment by adriangitvitz** [comment]
Could you share your keycloak version ? And also could you verify that you are able to reach your keycloak instance, and any logs from your minio instance would be useful

**Comment by Ayur541** [comment]
> Could you share your keycloak version ? And also could you verify that you are able to reach your keycloak instance, and any logs from your minio instance would be useful

Sure @adriangitvitz ,

Keycloak version : 22.0.5

Yes, it's able to reach keycloak and after entering the login credentials for keycloak, I see the above pasted error page but no logs from any instances are seen.

**Comment by adriangitvitz** [comment]
could you follow these instructions instead ? 
https://min.io/docs/minio/macos/operations/external-iam/configure-keycloak-identity-management.html

and verify your URL on the Keycloak client side

<img width="948" alt="Screenshot 2024-01-11 at 12 04 39 a m" src="https://github.com/minio/console/assets/39295224/f7408986-c6d4-488c-a6b2-23eff49832f0">

Also verify your client scopes ( just in case ), and use this env variables

MINIO_IDENTITY_OPENID_CLIENT_ID_PRIMARY_IAM=client-id;
MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM=client-secret;
MINIO_IDENTITY_OPENID_CONFIG_URL_PRIMARY_IAM=well-known-url;
MINIO_IDENTITY_OPENID_DISPLAY_NAME_PRIMARY_IAM=SSO_IDENTIFIER;
MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_PRIMARY_IAM=on;
MINIO_IDENTITY_OPENID_SCOPES_PRIMARY_IAM=openid

**Comment by cesnietor** [comment]
We'll change the README docs to point to the proper doc link.

**Comment by dvaldivia** [comment]
please re-open if the problem persists
