### ISSUE TITLE
Unable to modify Transition Days in the console

### ISSUE THREAD

**Issue by wuyanfeiwork** [minio/console#3182]
See：https://github.com/minio/minio/issues/18753

**Comment by prakashsvmx** [comment]
@wuyanfeiwork ,

we recommend latest version to be used by  community members to report issues.
the latest version works as expected. please upgrade . 
Before update:
![image](https://github.com/minio/console/assets/23444145/d527f14d-258a-4edd-9d4d-6fe9e6d22a2f)

After Update:
![image](https://github.com/minio/console/assets/23444145/e07713ca-eeb8-478d-9098-04d46d4a9bfe)

**Comment by prakashsvmx** [comment]
Thank you for reporting @wuyanfeiwork . the fix is in PR #3183
