### ISSUE TITLE
The MINIO_STS_DURATION parameter is invalid

### ISSUE THREAD

**Issue by shadowwalker-xu** [minio/console#3184]
For the newly installed minio cluster, the environment variable MINIO_STS_DURATION does not take effect. When a file sharing link is generated, the maximum expiration time is 12 hours. The value cannot be extended
![image](https://github.com/minio/console/assets/54296133/fc2bc54b-e8d2-4b42-b4e6-c374e9bc87f9)

**Comment by harshavardhana** [comment]
Please open issues properly by providing more details. 

Closing the issue as non actionable.
