### ISSUE TITLE
First login lands at blank screen

### ISSUE THREAD

**Issue by jamincollins** [minio/console#3195]
As requested in minio/minio#18797, updated version and re-reporting.

## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

After a successful login, the UI ends at a blank screen.

## Expected Behavior

After a successful login, the user should be taken to the normal UI/dashboard.

## Current Behavior

After a successful login, the UI ends at a blank screen.

## Steps to Reproduce (for bugs)

1. Unknown

## Context

Requires that I login twice each time I want to access the UI.  First time results in the blank page.  Going back and logging in a second time results in a usable UI.

## Regression

Unknown

## Your Environment

* Version used (`minio --version`): 
```
$ minio --version
minio version 2024-01-16T16-07-38Z (commit-id=d169ca9c049bd9c99af90a34aa397d1afccc391b)
Runtime: go1.21.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```
* Server setup and configuration:
  * Minio running via systemd
  * Nginx reverse proxy in front of it
  * LDAP used for identity

* Operating System and version (`uname -a`): 
```
Linux archive 6.7.0-arch3-1 minio/minio#1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000 x86_64 GNU/Linux
```

**Comment by prakashsvmx** [comment]
@jamincollins ,  Could you try without `nginx` and share the results?  

i tried with ldap login in console and could not observe the above mentioned issue.

**Comment by jamincollins** [comment]
Going straight to port 9000 does not result in the blank screen after first login.

**Comment by cesnietor** [comment]
This sounds like an nginx config issue, please post it here so that we can check it.  We'll also share with you some examples.

**Comment by pjuarezd** [comment]
please look at the example Nginx configuration here https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html

**Comment by jamincollins** [comment]
It looks like the configuration has been enhanced with a UI rewrite since I set it up initially, I'll adapt my configuration to the above example and see if that improves things.

**Comment by jamincollins** [comment]
it looks like the UI rewrite section may have solved this.

**Comment by cesnietor** [comment]
closing as per comment. Please create a new issue if issue persists.
