### ISSUE TITLE
Can't download some files via Web UI

### ISSUE THREAD

**Issue by AlexZIX** [minio/console#3203]
Sometimes I can't download different files via console. It shows me the network error (see screenshot). At the same time I can download this files via S3 clients like WinSCP for ex.

![image](https://github.com/minio/console/assets/13428863/7f2e1270-f611-4207-8a82-800f1da9dcac)

## Steps to Reproduce (for bugs)
I still can't understand the pattern of this issue - which files able to download and which return an error.

## Your Environment

* MinIO version used (`minio --version`): 2024-01-16T16:07:38Z
* Server setup and configuration: 4 nodes with 4 disks on each
* Operating System and version (`uname -a`): Linux minio-cold-1 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by prakashsvmx** [comment]
Please share `mc admin trace <ALIAS> -v`  . how is minio deployed ?

is there any proxy/loadbalancer/ ?

**Comment by AlexZIX** [comment]
There is no proxy/loadbalancer between my PC and minio node. It's not running in FTP mode (I even don't know how to run it in FTP mode). I just login into Web UI using my browser (Opera), select file and press the Download button. Trace in attachments. As I understand from the trace file sent successfully from the minio node to browser. But in browser I see the download error anyway.

[trace.txt](https://github.com/minio/console/files/13992762/trace.txt)

**Comment by AlexZIX** [comment]
This is headers from my browser - may be it also can help.

[headers.txt](https://github.com/minio/console/files/13992794/headers.txt)

**Comment by cesnietor** [comment]
We'll share with you some steps to enable  the Console logs so that you can share them with us caus eI couldn't see much from the trace. Additionally we'll do some changes in the ui to better expose the download error since now it's too generic.

**Comment by prakashsvmx** [comment]
@AlexZIX could you confirm the minio version by running `mc admin info <ALIAS>` once ?

**Comment by AlexZIX** [comment]
@prakashsvmx yes, there is the result:

root@minio-cold-1:~# mc admin info minio-cold
●  minio-cold-1.bazissoft.ru:9001
   Uptime: 6 days
   Version: 2024-01-16T16:07:38Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  minio-cold-2.bazissoft.ru:9001
   Uptime: 6 days
   Version: 2024-01-16T16:07:38Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  minio-cold-3.bazissoft.ru:9001
   Uptime: 6 days
   Version: 2024-01-16T16:07:38Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  minio-cold-4.bazissoft.ru:9001
   Uptime: 6 days
   Version: 2024-01-16T16:07:38Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 16

14 TiB Used, 53 Buckets, 2,617,018 Objects, 669,078 Versions
16 drives online, 0 drives offline

**Comment by bexsoft** [comment]
Hi @AlexZIX!

We sent a couple of improvements in Download manager for error cases.

Can you please help us to test with the latest version of MinIO (`RELEASE.2024-02-17T01-15-57Z`) and test if issue still persists?

If it is still visible can you please post a screenshot of the download manager with the new error provided?

Thank you in advance.

**Comment by AlexZIX** [comment]
@bexsoft, yes will do it this week and let you know. Thanks.

**Comment by kotbajan** [comment]
Hello.
minio version RELEASE.2024-02-17T01-15-57Z
I received the same error in the firefox browser when trying to download text files. In the developer tools, in the network tab, the contents of the file are visible. The download dialog does not appear, the file is not saved to disk.
In the chrome browser, the file download is completed by saving to disk.

**Comment by cesnietor** [comment]
@kotbajan this had been fixed for firefox please use the latest release.
