### ISSUE TITLE
lifecycle rules information displayed in the window pop-up is inconsistent with the actual information 

### ISSUE THREAD

**Issue by nineep** [minio/console#3216]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Current Behavior

![ccedf9519e2160bd551daa06ba301857](https://github.com/minio/console/assets/20335786/d1e3431c-8930-4630-a94c-9a8212652761)
![bb0beb245fcf2d30ebcabcbefc0ec835](https://github.com/minio/console/assets/20335786/9c30aaa0-43b3-4238-a4e0-e4a5223270e5)
The rule type and storage class information displayed in the window pop-up is inconsistent with the actual information of the life cycle rules, which may lead to misunderstandings.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
minio:  RELEASE.2024-01-18T22-51-28Z
console: 0.45.0

**Comment by prakashsvmx** [comment]
thank you for reporting @nineep , we will check this.
