### ISSUE TITLE
Could the console server allow cors and add "Access-Control-A1low-Credentials:true"?

### ISSUE THREAD

**Issue by shawn-maxiao** [minio/console#3222]
When I use the console api to login , no cookie added for cors.

Could the console server allow cors and add "Access-Control-A1low-Credentials:true" like the minio service?

 minio/cmd/api-router.go:
<img width="637" alt="image" src="https://github.com/minio/console/assets/88022115/d0daad9c-a251-42fc-a24d-318ad4012a5a">

**Comment by cesnietor** [comment]
This won't be supported  cause it'd enable cross-site scripting.
We recommend to go straight to the MinIO server.
 If you want to allow this you can add an nginx in front.
