### ISSUE TITLE
How make Minio Cluster (4 nodes) + Nginx load balancer + Keep alived

### ISSUE THREAD

**Issue by kramchas** [minio/console#3240]
Can u help me? 
GIve me links please

**Comment by cesnietor** [comment]
https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html

**Comment by cesnietor** [comment]
For more community based questions and doubts feel free to join our Slack community https://slack.min.io/

**Comment by harshavardhana** [comment]
> Can u help me?
> GIve me links please

@kramchas please learn to google search and reach docs at https://docs.min.io
