### ISSUE TITLE
Hard to navigate in bucket with many sub-folders

### ISSUE THREAD

**Issue by AlexZIX** [minio/console#3254]
We have few buckets which contains thouthands of folders with objects. And it impossible to navigate into this sub-folders using console because searching only works after all data will be loaded from minio. For such big buckets it can take 5+ minutes which aren't very useful. And console haven't another ways to enter to sub-folders. It will be great if user can navigate into sub-folders using navbar like in Explorer. In this case I can directly enter into sub-directory in case of I know its name.

* MinIO version used (`minio --version`): minio version RELEASE.2024-02-24T17-11-14Z (commit-id=c2b54d92f66ea02642be4ede26f2b7ecac1f2056)

**Comment by bexsoft** [comment]
Hi @AlexZIX!

In this case you can use the create folder functionality, this will open the desired path and in case that it already exists, it will display the data contained as well.

**Comment by bexsoft** [comment]
Closing this ticket as there is a WA for this. Please reopen this ticket in case the WA doesn't work
