### ISSUE TITLE
MINIO_SHARE_URL

### ISSUE THREAD

**Issue by vanodevium** [minio/console#3256]
While searching for a solution to my problem, I realized that there are already a ton of questions about how to use **MINIO_SERVER_URL** if minio is running behind a proxy or a server. There is no solution, except to puzzle with certificates, or by opening the port to public access.

Why not just create a new variable **MINIO_SHARE_URL** that (if configured) will handle specifically the case of creating a share link in the console without breaking the download or preview functionality.

I absolutely understand that the link sharing functionality is designed to be used from the client or SDK, but sometimes it can't be done programmatically and needs to be done from the console (say, a human manager)

--- 

briefly about the problem, for context:

When the minio is running behind traefik, creating a share link in the console returns **127.0.0.1:9000** as the host.
To change this behavior, it is suggested to configure **MINIO_SERVER_URL**, but after that, downloading, previewing and sometimes logging into the console stops working in general.

**Comment by cesnietor** [comment]
Hi, @vanodevium  this should be solved with the following proposal https://github.com/minio/console/issues/3255

**Comment by vanodevium** [comment]
@cesnietor 

Awesome! Thanks!
