### ISSUE TITLE
URL entered directly redirects logged-in user to the Dashboard

### ISSUE THREAD

**Issue by kaankabalak** [minio/console#326]
When the logged-in user enters a URL directly for the console like https://play.min.io:9443/users, they are being redirected to the dashboard (https://play.min.io:9443/dashboard) instead of being navigated to the URL itself. We might want to look into how we are handling the routing in the app and see if anything is wrong

**Comment by harshavardhana** [comment]
For me it seems to be to `/buckets` instead of `/dashboard`

**Comment by Alevsk** [comment]
Issue fixed in https://github.com/minio/console/pull/336, closing issue now
