### ISSUE TITLE
Configure MinIO for Authentication using Keycloak

### ISSUE THREAD

**Issue by balaKarur** [minio/console#3262]
**## Expected Behavior**
I used 
MinIO Version: RELEASE.2024-03-10T02-53-48Z (go1.21.8 linux/amd64) 
keycloak :  24.0.1
MInio console has to access keycloak by using this URL
http://localhost:8088/kc/realms/icido_weave/.well-known/openid-configuration
**Note** : http://localhost:8088/kc/realms/icido_weave/.well-known/openid-configuration -> url can be accessible from 
browser.
![image](https://github.com/minio/console/assets/13732401/f306f4ee-94a5-4d14-8041-baac752422c5)

## Current Behavior
Error : No such IDP configuration exits
![IDP_Error](https://github.com/minio/console/assets/13732401/664eb903-f090-47cb-b856-acf56e232d50)
## Possible Solution
Nill ,Need support to fix 

## Steps to Reproduce (for bugs)
I followed this steps:
https://min.io/docs/minio/linux/operations/external-iam/configure-keycloak-identity-management.html
And attached the doc 
[Configure or Create a Client for Accessing Keycloak.docx](https://github.com/minio/console/files/14590723/Configure.or.Create.a.Client.for.Accessing.Keycloak.docx)
what i configured in keycloak

## Context

In minio console UI 
From Administrator Tab ->Identity -> OpenID 
try to configure keycloak details 
**My gola:**
configure keycloak as a authentication tool

## Regression
I am sure this is not a regression, may be i am missing some configuration ,need support to identify

## Your Environment

* MinIO Version: RELEASE.2024-03-10T02-53-48Z (go1.21.8 linux/amd64)
*Running minio inside docker image

**Comment by balaKarur** [comment]
Thanks @cesnietor , @adriangitvitz 
Could you please review my configuration and advise if any updates are needed?

**Comment by adriangitvitz** [comment]
please verify your configuration, here is mine, verify your claims

![Screenshot 2024-03-19 at 10 59 48 p m](https://github.com/minio/console/assets/39295224/c5a074a4-c60c-4c7a-bb7e-c88fe4c5e106)

![Screenshot 2024-03-19 at 11 00 32 p m](https://github.com/minio/console/assets/39295224/4aa43227-ce51-40dc-9bba-6f80ee019a0e)

Result:

![Screenshot 2024-03-19 at 11 01 38 p m](https://github.com/minio/console/assets/39295224/f6248b62-bcd6-4008-8ec5-5d65591069bd)

let me know if you still have issues

**Comment by balaKarur** [comment]
@adriangitvitz 
Thanks for the response , Issue resolve .

**Use case** i configured all keycloak info in docker.yaml file as environment variable .and run **podman-compose build**
the keycloak configured in minio smoothly. 
even i updated **user attribute in keycloak as you mentioned**

version: "3.8"
services:
    minio:
        image: quay.io/minio/minio:RELEASE.2024-03-21T23-13-43Z
        container_name: minio
        volumes:
          - ./minio_data:/data
        command: server /data --console-address=":9001"
        ports:
          - 9000:9000
          - 9001:9001
        environment:
          - MINIO_ROOT_USER=admin
          - MINIO_ROOT_PASSWORD=miniopassword
          - MINIO_SERVER_URL=http://localhost:9000
          - MINIO_DOMAIN=http://localhost:9000
          - MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY=http://host.containers.internal:8088/kc/realms/myrealm/.well-known/openid-configuration
          - MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY=minio
          - MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY=WPBfZpbPTdeSVz4q
          - MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY=MinIO OpenID Login
          #- MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY=openid,preferred_username
          - MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
          - MINIO_IDENTITY_OPENID_VENDOR=keycloak
          - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY=on
          - MINIO_IDENTITY_OPENID_SCOPES=minio-authorization
          - MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=myrealm
          - MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=http://host.containers.internal:8088/kc/admin
         
volumes:
    minio_data:
