### ISSUE TITLE
Access restriction: Unable to add specific user per bucket

### ISSUE THREAD

**Issue by manju-rn** [minio/console#3268]
## Expected Behavior
Access isolation: Specific users can be assigned to specific buckets
## Current Behavior
Any user that is added via the console is added to all the buckets. This should not be the case, each bucket should be allowed to have specific user

## Possible Solution
Is there a way to allocate this via console?

## Steps to Reproduce (for bugs)
1.  Create multiple buckets
2.  Add users
3. Check the Access section is the bucket, all the users are listed there
![image](https://github.com/minio/minio/assets/26291847/77b03afa-6407-4812-b160-a25e8bfa59f5)

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by dvaldivia** [comment]
What policies are you using? if the right policy is used and assigned per user, your expected behavior can be achieved

**Comment by prakashsvmx** [comment]
Are you looking for something like
```
 {
     "Version": "2012-10-17",
     "Statement": [
         {
             "Effect": "Allow",
             "Action": [
                 "s3:*"
             ],
             "Resource": [
                 "arn:aws:s3:::specific-bucket/*"
             ]
         }
     ]
 }
```
this allows All s3 operations on bucket specific-bucket  other buckets/options are not allowed to the user whom the policy is assigned.

Policies are at user/group level. You allow or deny Resources which can be one or more buckets or prefixes in a bucket.
