### ISSUE TITLE
Create a directory under the storage bucket

### ISSUE THREAD

**Issue by Fant2019** [minio/console#3288]
I created the "test" directory in "bucket1" and uploaded the "anaconda-ks.cfg" file.
When I viewed "bucket1/test", the "anaconda-ks.cfg" file and "/" appeared, but I did not create the "/" directory.
```
[root@minio1 ~]# mc ls myminio/bucket1
[2024-04-08 17:15:55 CST] 183MiB STANDARD jdk-8u201-linux-x64.tar.gz
[root@minio1 ~]# mc mb myminio/bucket1/test
Bucket created successfully `myminio/bucket1/test`.
[root@minio1 ~]# mc cp anaconda-ks.cfg  myminio/bucket1/test
/root/anaconda-ks.cfg:            1.31 KiB / 1.31 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 7.72 KiB/s 0s
[root@minio1 ~]# mc ls myminio/bucket1/test
[2024-04-09 11:14:34 CST]     0B STANDARD /
[2024-04-09 11:14:43 CST] 1.3KiB STANDARD anaconda-ks.cfg
```
When I access the console to view the storage bucket.
I found that under "bucket1/test", there is a "test" directory and "anaconda-ks.cfg".
This is different from what is displayed on the command line

![test](https://github.com/minio/console/assets/54030365/a1a223fb-d6a9-4ccf-b009-2bbe16558144)

Viewing the storage bucket on the console is like this
```
bucket1/
├── jdk-8u201-linux-x64.tar.gz
└── test
    ├── anaconda-ks.cfg
    └── test
```

I didn't create "bucket1/test/test", but it appeared
Display as "/" on the command line and "test" on the console
I created "bucket1/test", and I don't think there should be a "test"  or "/"

## Your Environment

```
[root@minio1 ~]# mc -v 
mc version RELEASE.2024-03-30T15-29-52Z (commit-id=9f8147bf0e037730077a1b3baef25e53181099b0)
Runtime: go1.21.8 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
[root@minio1 ~]# minio -v
minio version RELEASE.2024-04-06T05-26-02Z (commit-id=9d63bb1b418f6c1bbcc8434fff5d8aba810ee5d7)
Runtime: go1.21.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```

**Comment by Fant2019** [comment]
I also performed this operation on another old version of the minio service, which is different from the previous display. I think it is normal here.


```
[root@mysql ~]# mc mb minio1/bucket1
Bucket created successfully `minio1/bucket1`.
[root@mysql ~]# mc cp jdk-8u201-linux-x64.tar.gz  minio1/bucket1
/root/jdk-8u201-linux-x64.tar.gz: 182.93 MiB / 182.93 MiB ━━━━━━━━━━━━━━━━ 49.27 MiB/s 3s
[root@mysql ~]# mc mb minio1/bucket1/test
Bucket created successfully `minio1/bucket1/test`.
[root@mysql ~]# mc cp anaconda-ks.cfg  minio1/bucket1/test
/root/anaconda-ks.cfg:            1.74 KiB / 1.74 KiB ━━━━━━━━━━━━━━━━━━━━━━━ 40.19 KiB/s 0s
[root@mysql ~]# mc ls   minio1/bucket1/test
[2024-04-09 16:41:31 CST] 1.7KiB STANDARD anaconda-ks.cfg
```

![ttt](https://github.com/minio/console/assets/54030365/1d4f454d-c5d1-4a6e-b6a6-6d0ba436334b)


```
[root@mysql ~]# /usr/local/minio/minio -v
minio version RELEASE.2022-10-20T00-55-09Z (commit-id=a8332efa948fd84507158c1d95df33116ee58a5a)
Runtime: go1.19.2 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
[root@mysql ~]# mc -v
mc version RELEASE.2022-09-16T09-16-47Z (commit-id=ad4441ef2b4b1d0a6b90b5dd0d71d0423952e417)
Runtime: go1.18.6 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

**Comment by prakashsvmx** [comment]
@Fant2019  . The command shared like: 
 ```
[root@mysql ~]# mc mb minio1/bucket1/test
Bucket created successfully `minio1/bucket1/test`.
```
This creates a **directory** marker. 

so to create a bucket  just use `mc mb minio1/bucket1` 

When you are looking to create path it should be part of the object name like:. 
```
mc mb minio1/bucket1

mc cp /etc/hosts minio1/bucket1/my-prefix/hosts.txt # my-prefix is the prefix (directory) 
```
Read more

https://min.io/docs/minio/linux/operations/concepts/thresholds.html#object-name-limitations

 https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html

**Comment by Fant2019** [comment]
What you mean is, if I want to create a directory in the bucket, I don't actually need to create it separately.
When I upload a file, if I specify a directory in the storage bucket, will the program automatically create it for me?

**Comment by Fant2019** [comment]
But why does the old version of minio have different performance compared to the new version of minio, and is there an update?

**Comment by prakashsvmx** [comment]
> When I upload a file, if I specify a directory in the storage bucket, will the program automatically create it for me?

Yes, In Object Storage there is no "Folder" it is just a representation.  please try and explore  with any sdk or mc client .


For performance related discussion, please consider a subscription [min.io/pricing ](https://min.io/pricing)

**Comment by Fant2019** [comment]
Thank you for your answer.
