### ISSUE TITLE
Errant localhost lookups when minio server is remote

### ISSUE THREAD

**Issue by eco-minio** [minio/console#329]
Noticed that if I configured console on a host, with minio as a remote host, logins would fail.  This is using latest release console_0.4.1.
Followed steps from https://github.com/minio/console
Set the following env vars
```
CONSOLE_ACCESS_KEY=console
CONSOLE_SECRET_KEY=console123
CONSOLE_MINIO_SERVER=http://<remote minio server>:9000
```
Started console as ./console server --port 9080

Tried to log in to the web UI as console user, saw the following error:

![image](https://user-images.githubusercontent.com/41090896/96310386-1ffee980-0fbc-11eb-8af2-274652de4e4e.png)

Checking console logs, saw entries like the following:
```
-- Logs begin at Mon 2020-10-12 17:47:07 EDT. --
Oct 16 17:06:18 client1 console[3393]: 2020/10/16 17:06:18 error obtaining MinIO region: Get "http://localhost:9000/minio/admin/v3/help-config-kv?key=&subSys=region": dial tcp [::1]:9000: connect: connection refused
Oct 16 17:06:18 client1 console[3393]: 2020/10/16 17:06:18 original error: an error occurred, please try again
Oct 16 17:07:03 client1 console[3393]: 2020/10/16 17:07:03 error obtaining MinIO region: Get "http://localhost:9000/minio/admin/v3/help-config-kv?key=&subSys=region": dial tcp [::1]:9000: connect: connection refused
Oct 16 17:07:03 client1 console[3393]: 2020/10/16 17:07:03 original error: an error occurred, please try again
```
It is looking for region, and querying http://localhost:9000.  Since minio is not running on the same server as console, this will always fail.

Got around this by setting `MINIO_REGION_NAME=us-east-1` on the console server and restarting console but it seems like it should be looking at the remote host configured by env var, not trying to check locally.

**Comment by dvaldivia** [comment]
I think `CONSOLE_MINIO_SERVER` should point to your remote MinIO server, for example `CONSOLE_MINIO_SERVER=https://play.min.io`

**Comment by cesnietor** [comment]
he was using an ip, he just removed it in this issue.

**Comment by eco-minio** [comment]
Formatting issue, I put it in quoteblock, but yes server was remote

**Comment by Alevsk** [comment]
> Formatting issue, I put it in quoteblock, but yes server was remote

I'm trying to replicate the issue but no luck so far, `dial tcp [::1]:9000: connect: connection refused` could mean there's nothing listening on port `9000`, in my local test im running minio and console in same machine and different ports, and also both services in different machines and it's working fine.

`CONSOLE_ACCESS_KEY ` should be a minio account with enough privileges, basically a minio admin.

**Comment by eco-minio** [comment]
Not able to repro with latest master, closing
