### ISSUE TITLE
When starting a project Proxy error May I ask how to solve it （windows environment ）

### ISSUE THREAD

**Issue by 15607306950** [minio/console#3293]
Proxy error: Could not proxy request /api/v1/login from localhost:5005 to http://localhost:9090/ (ECONNREFUSED).
![screenshot-20240411-100808](https://github.com/minio/console/assets/31731847/0e381210-932b-4e3b-839d-169d27c2b2fb)
![screenshot-20240411-100821](https://github.com/minio/console/assets/31731847/7a3d2444-4ac9-46f1-83e9-1af291deb4e2)

**Comment by prakashsvmx** [comment]
is it dev setup ? is the console server running?

**Comment by 15607306950** [comment]
Yes, it runs locally. The proxy configuration in the package.json file
"Proxy":“ http://localhost:9090/ ",",
this http://localhost:9090/ Do I need to restart the service?

![1](https://github.com/minio/console/assets/31731847/d7f299d9-f30f-485c-9dc8-89d39e13c0b5)


> 是开发设置吗？控制台服务器正在运行吗？

**Comment by prakashsvmx** [comment]
https://github.com/minio/console/blob/master/DEVELOPMENT.md

**Comment by 15607306950** [comment]
> https://github.com/minio/console/blob/master/DEVELOPMENT.md
Can the backend service be started in Java?
