### ISSUE TITLE
Has minio/console docker repo gone?

### ISSUE THREAD

**Issue by buzzdan** [minio/console#3298]
this link doesnt exist anymore ...

https://hub.docker.com/layers/minio/console/latest/images/sha256-1f920002afb6ab7541205b939a8c99ddac069a4e10f405046d37856ec4a31086

nor does the repo generally:
https://hub.docker.com/r/minio/console

## Expected Behavior
docker hub repo should exist

## Current Behavior
i get a 404

**Comment by harshavardhana** [comment]
minio/console is not a product shipped separately; it is shipped as part of minio/minio. It would be best if you moved to that. 

If you are a customer needing access, please ping us at https://subnet.min.io

**Comment by se7entyse7en** [comment]
Is it possible to run only the console? So that have console and server in separate instances?

**Comment by XhmikosR** [comment]
So, this is a weird situation @harshavardhana.

While you guys must have your reasons for this change, it results in breakage of existent old deployments. For example:

```
[user@node1 ~]$  kubectl get pods -A | grep -iv "Running" | grep -iv "Completed"
NAMESPACE              NAME                                                              READY   STATUS             RESTARTS   AGE
prod-minio01           prod-minio01-console-69b97d579f-6d8qs                             0/1     ImagePullBackOff   0          10m
prod-minio01           prod-minio01-console-69b97d579f-qpmw5                             0/1     ImagePullBackOff   0          10m
```

Unfortunately, updating the cluster is not viable right now and I'm pretty sure I'm not the only one in this case.

Is there any chance you guys bring back the old repo?
