### ISSUE TITLE
Question: missing docker.io/minio/console

### ISSUE THREAD

**Issue by yshashix** [minio/console#3303]
Hi Team,
I am not able to get minio/console from dockerhub. Is it removed or something happened in docker hub. I tried to look up manually login dockerhub but I can't get.

I tried below:
pulling docker.io/minio/console:v0.22.5
and get error- Error response from daemon: pull access denied for minio/console

**Comment by prakashsvmx** [comment]
Duplicate https://github.com/minio/console/issues/3298
