### ISSUE TITLE
After authentication with Keycloak, I get stuck on the Login with SSO page.

### ISSUE THREAD

**Issue by SHIVANI-MISHRA-WTT** [minio/console#3312]
I'm encountering an issue while integrating Minio with Single Sign-On (SSO). Could someone help me troubleshoot?
Here's what I've done:

I configured client roles and required mappers following the documentation.
Expected Behavior: After authenticating with Keycloak, I should be able to access the Minio console dashboard.
Current Behaviour: After authentication with Keycloak, I get stuck on the Login with SSO page.
Documentation Link :
https://github.com/minio/minio/blob/master/docs/sts/keycloak.md

I integrated SSO with Minio and i am able to login to minio after clicking on the login with sso button by following above provided documentation.

But if I log in to one application and then redirect to Minio, it shouldn't ask me to log in again. I should Log in automatically without click on Login with SSO button . I get stuck on the login page, and the session API is failing, which shouldn't happen.
Could someone please help me with this issue?

I attached the api details below:
https://abc.erd.com/minio/api/v1/session
{"detailedMessage":"Access Denied.","message":"invalid session"}

**Comment by cesnietor** [comment]
@SHIVANI-MISHRA-WTT  please share your minio and keycloak config.

**Comment by SHIVANI-MISHRA-WTT** [comment]
> @SHIVANI-MISHRA-WTT please share your minio and keycloak config.

These below are the Environment variables i am passing to configure Minio with my kecloak configurations:

       name: MINIO_ROOT_USER
       value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio123
        - name: MINIO_BROWSER_REDIRECT_URL
          value: <hostURL>/minio
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY
          value: <hostURL>/identity/auth/realms/<RealmName>/.well-known/openid-configuration
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY
          value: minio
        - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY
          value: xyz....
        - name: MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY
          value: Login With SSO
        - name: MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY
          value: email, profile, openid
        - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
          value: <hostURL>/minio/oauth_callback
	- name: MINIO_IDENTITY_OPENID_CLAIM_NAME
          value: sub
          
          
          
          --------------------------------------------------------------------------
         ---------------------------------------------------------------------------

I can successfully log in to Minio with Keycloak (using "Login with SSO") with my user credentials, but I'm unable to redirect from my main application to the Minio application with the same user session.

For the Keycloak configuration, I followed the documentation linked below and completed every step to set up SSO for Minio.

Documentation Link: (https://github.com/minio/minio/blob/master/docs/sts/keycloak.md).

Can you please check my configurations and Let me know what i should add in the configurations to make SSO work .

**Comment by adriangitvitz** [comment]
> > @SHIVANI-MISHRA-WTT please share your minio and keycloak config.
> 
> 
> 
> These below are the Environment variables i am passing to configure Minio with my kecloak configurations:
> 
> 
> 
>        name: MINIO_ROOT_USER
> 
>        value: minio
> 
>         - name: MINIO_ROOT_PASSWORD
> 
>           value: minio123
> 
>         - name: MINIO_BROWSER_REDIRECT_URL
> 
>           value: <hostURL>/minio
> 
>         - name: MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY
> 
>           value: <hostURL>/identity/auth/realms/<RealmName>/.well-known/openid-configuration
> 
>         - name: MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY
> 
>           value: minio
> 
>         - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY
> 
>           value: xyz....
> 
>         - name: MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY
> 
>           value: Login With SSO
> 
>         - name: MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY
> 
>           value: email, profile, openid
> 
>         - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
> 
>           value: <hostURL>/minio/oauth_callback
> 
> 	- name: MINIO_IDENTITY_OPENID_CLAIM_NAME
> 
>           value: sub
> 
>           
> 
>           
> 
>           
> 
>           --------------------------------------------------------------------------
> 
>          ---------------------------------------------------------------------------
> 
> 
> 
> I can successfully log in to Minio with Keycloak (using "Login with SSO") with my user credentials, but I'm unable to redirect from my main application to the Minio application with the same user session.
> 
> 
> 
> For the Keycloak configuration, I followed the documentation linked below and completed every step to set up SSO for Minio.
> 
> 
> 
> Documentation Link: (https://github.com/minio/minio/blob/master/docs/sts/keycloak.md).
> 
> 
> 
> Can you please check my configurations and Let me know what i should add in the configurations to make SSO work .
> 
> 
> 
> 
> 
> 
> 
> 

Could you share your minio and keycloak version ?

**Comment by adriangitvitz** [comment]
Also are you testing with nginx or if you could provide more details about your environment

**Comment by SHIVANI-MISHRA-WTT** [comment]
Minio Version : RELEASE.2024-03-30T09-41-56Z
Keycloak Server Version : 16.1.1

**Comment by SHIVANI-MISHRA-WTT** [comment]
> Also are you testing with nginx or if you could provide more details about your environment

we are using nginx Version(1.15.8) in our main application  path (/etc/nginx/html/qiplatform)
from their we are redirecting to minio using  SSO , regarding environment we are using kubernetes version 1.27

one more problem we are facing is not able to see the minio logs. Can you please help us how we can see the logs ?

**Comment by SHIVANI-MISHRA-WTT** [comment]
Could someone help me with an issue I'm experiencing? I'm redirecting from my main application to the MinIO application using a redirect URL, and I've integrated SSO for MinIO. However, I want to bypass the login page when accessing MinIO after logging in to my primary platform (QIplatform). Ideally, if I'm already logged into QIplatform and then redirect to MinIO, it shouldn't ask me to log in again.

Minio Redirect URL:  https://qa.qritrim.com/minio/browser/minioutil/2024-04-10/qiworkflow_1795_2024-04-10t17-58-05/minioIngestor-6160/metaData_info.json

Do i need to change the Redirect URL to redirect to Minio Application?

I suspect this problem could be due to missing configurations or limitations with MinIO's SSO integration. Could you provide guidance or suggest how to achieve seamless SSO with MinIO? I'm stuck and would appreciate any assistance.

**Comment by prakashsvmx** [comment]
MinIO Console requires login with SSO as the credentials and token are obtained post login . so it looks like it is specific to your own environment's integration requirements.  If the platform acts as a SSO provider please check and configure the required environment variables 

https://min.io/docs/minio/linux/operations/external-iam/configure-openid-external-identity-management.html
