### ISSUE TITLE
"invalid login"  error when trying to login to minio console when using proxy

### ISSUE THREAD

**Issue by raulkmbl** [minio/console#3317]
Seeing below error 
![image](https://github.com/minio/console/assets/167618810/f5c172ee-86c3-4053-a757-815172d52157)

:- Below is the /etc/default/minio

opsg@lc0-hibiz-minio1:~$ cat /etc/default/minio

MINIO_VOLUMES="https://lc0-hibiz-minio{1...4}:9000/mnt/disk{1...4}/minio"

MINIO_OPTS="--console-address :9001 --certs-dir /home/minio-user/.minio/certs"

MINIO_ROOT_USER=<username>

MINIO_ROOT_PASSWORD=<pass>

MINIO_SERVER_URL="https://lc0-hibiz-minio-haprxy:9000"
MINIO_ERASURE_SET_DRIVE_COUNT=16
MINIO_STORAGE_CLASS_STANDARD=EC:2

haproxy.cfg setting -

frontend app1_ssl
    bind *:9000 ssl crt /etc/haproxy/server.pem
    bind *:9001
    stats uri /haproxy?stats

backend backend_app1_ssl
    mode http
    balance leastconn
    server lc0-hibiz-minio1 172.16.0.10:9000 check inter 2s
    server lc0-hibiz-minio2 172.16.0.11:9000 check inter 2s
    server lc0-hibiz-minio3 172.16.0.12:9000 check inter 2s
    server lc0-hibiz-minio4 172.16.0.13:9000 check inter 2s

opsg@lc0-hibiz-minio1:~$ /usr/local/bin/minio -v
minio version RELEASE.2024-04-06T05-26-02Z (commit-id=9d63bb1b418f6c1bbcc8434fff5d8aba810ee5d7)
Runtime: go1.21.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
opsg@lc0-hibiz-minio1:~$

1. for MINIO_SERVER_URL="https://lc0-hibiz-minio-haprxy:9000" if i remove the proxy and mention one of the endpoint it works but i am trying to setup using proxy 
2. minio service is running on all 4 nodes
3. prxy is up as well
4. when try to create alias using mc showing below- 
![image](https://github.com/minio/console/assets/167618810/8f097fe3-5b3e-48ee-ab5f-db8755a4b29d)
5.this is lab setup and i have generated crt and key using certgen

Can anyone point out the issue and fix? thanks

**Comment by prakashsvmx** [comment]
>if i remove the proxy and mention one of the endpoint it works but i am trying to setup using proxy

^^ So If direct endpoint works, there is no problem with MinIO. 

Setting up proxy is outside of MinIO.  Please refer to the docs for the guidance.

https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html

For placing the certs please refer to https://min.io/docs/minio/linux/operations/network-encryption.html
