### ISSUE TITLE
Cannot find minio/console image in docker hub,

### ISSUE THREAD

**Issue by lgu-ampere** [minio/console#3318]
## Expected Behavior
Expected to have image pulled

## Current Behavior
when I use micok8s install minio
it shows:
Failed to pull image "minio/console:v0.20.3": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/minio/console:v0.20.3": failed to resolve reference "docker.io/minio/console:v0.20.3": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

Didn't find image on docker hub too
https://hub.docker.com/u/minio

## Steps to Reproduce (for bugs)
$ microk8s enable minio -c 100Gi -t  tenant-1 -n 4  -v 8

## Context
Is there any changes for console deployment process?

Thanks

**Comment by cesnietor** [comment]
we no longer upload images for console since it's now part of minio/minio same binary. Please use that one instead. Thanks.

**Comment by lgu-ampere** [comment]
Got it.Thanks

**Comment by harshavardhana** [comment]
Older images are available for existing customers, privately. For public images use minio/minio with embedded Console UI.

**Comment by sereneshikari** [comment]
Hey @cesnietor / @harshavardhana, could you please point me to the release notes where this change was announced? Thanks!

**Comment by harshavardhana** [comment]
> Hey @cesnietor / @harshavardhana, could you please point me to the release notes where this change was announced? Thanks!

@sereneshikari https://github.com/minio/console/blob/master/CHANGELOG.md#release-v0310 - it was done on Jun 29, 2023.

**Comment by harshavardhana** [comment]
We also waited nearly a year to turn off public access to the container images, and now they're gone. 

If you still want access to it, come and talk to us https://min.io/pricing
