### ISSUE TITLE
Console image not found while installing minio operator using helm

### ISSUE THREAD

**Issue by miteshjadia** [minio/console#3336]
Followed installation step documented at [official documentation](https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-operator-helm.html#).

## Expected Behavior

helm installation should succeed with default options as documented.

## Current Behavior

Installation fails because console image not found.

## Possible Solution

Correct image for console deployment should be updated in the official helm chart.
There should be boolean option to helm chart values, which decides whether to create console deployment or not.

## Steps to Reproduce (for bugs)

1. helm upgrade --install --atomic minio-operator minio-operator/operator --version 4.3.7

**Comment by harshavardhana** [comment]
Console image is no more, migrate to newer operator.
