### ISSUE TITLE
Add ability to disable Console as proxy for share object logic

### ISSUE THREAD

**Issue by hashworks** [minio/console#3348]
#3284 has its use case, but introduced some bugs (#3305, #3328, #3334).

## Expected Behavior
Users can decide if they want to use Console as a proxy for the share logic.

## Current Behavior
Users are forced to use this new feature.

## Possible Solution
It would be great if one could disable this feature using an environment variable (f.e. `MINIO_BROWSER_PROXY_SHARE=false`, default `true`), since it introduced unneeded complexity if the `MINIO_SERVER_URL` is publically accessible.

## Steps to Reproduce (for bugs)
Run a MinIO cluster with a recent Console version and run into the linked bugs.

## Context
The new feature broke the share functionality on our production cluster since not all fixes are provided in the latest version (1.4.0).

## Regression
This wasn't needed before #3284.

**Comment by hashworks** [comment]
We are currently affected by #3334 - its fix is not included in the latest stable release (1.4.0). Share URLs created by console need to be fixed manually (`/ui/` path prefix in our case).

I'm aware that the `mc` command line can create direct links, but I can't expect that from web interface users.

The redirect is simply not needed if the MinIO server is publically reachable, so it seems reasonable that it's an optional feature.

**Comment by hashworks** [comment]
Looks like it simply would require a flag-check to [skip those three lines](https://github.com/cesnietor/console/blob/2ad7833022fad1f7b3d9763b524fc94b5ec37d60/api/user_objects.go#L1103-L1105) and return `minioURL` instead.

**Comment by cesnietor** [comment]
@hashworks  take a look at the latest release, it should be there.
Adding an env variable to disable this is not the right approach but rather fixing the bugs that we encounter. Cause if you already have access to console, then the share url will have access to it.
If you have access to the server then you can use mc.
If there is a special scenario on why this feature might cause some issues, please let us know but latest release should address the issue you mentioned.
