### ISSUE TITLE
Upgrade from ts-prune to knip for detecting dead code

### ISSUE THREAD

**Issue by ramondeklein** [minio/console#3355]
The [ts-prune](https://github.com/nadeesha/ts-prune) to [knip](https://github.com/webpro/knip) package has been deprecated since December 2023 and it is recommended to upgrade to [Knip](https://knip.dev/).

Knip uses different detection algorithms and the output format is different too, so simply switching from ts-prune to knip will break the build.

**Comment by bayasdev** [comment]
https://github.com/minio/console/pull/3426
