### ISSUE TITLE
Use `--check-resolutions` when installing packages using Yarn 4

### ISSUE THREAD

**Issue by ramondeklein** [minio/console#3356]
Raised, because of https://github.com/minio/console/pull/3353.

Yarn 4 switches to a hardened CI/CD mode when building public PRs. This results in YN0078 errors (more specific: `Invalid resolution loader-utils@npm:^3.2.0 → npm:2.0.4`). The build now specifies `--no-check-resolutions` during installation, but we would rather have this option enabled.

**Comment by cesnietor** [comment]
this should be closed by https://github.com/minio/console/pull/3353 right @ramondeklein

**Comment by cesnietor** [comment]
reopen if not  :D

**Comment by ramondeklein** [comment]
@cesnietor Yarn 4 automatically adds the `--check-resolutions` parameter when running in CI/CD mode (i.e. in a Github action) and it fails with the following error:
```
yarn install --check-resolutions
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0078: │ Invalid resolution glob-parent@npm:^5.1.2 → npm:6.0.2
➤ YN0000: └ Completed in 0s 241ms
➤ YN0000: · Failed with errors in 0s 254ms
```
When adding the `--no-check-resolutions` explicitly, I disable the check. But I guess it would be better to have this check, because we may run into issues.
