### ISSUE TITLE
Disk list cannot be bounced back

### ISSUE THREAD

**Issue by FourSpaces** [minio/console#3357]
## NOTE
If this case is urgent, please subscribe to [SUBNET](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior and current Behavior
On the `metrics` page, under the `Info` tab, the disk list in the `servers` list should be in a bounce back state, but it is now in a semi pop up state. Clicking the expand button will correctly expand, but when clicking the rebound button again, it will become this state.

![image](https://github.com/minio/console/assets/13359726/e9048d7d-c12f-4e42-9722-35759f3acf6e)

## Possible Solution
![image](https://github.com/minio/console/assets/13359726/1d0bfdd7-48f9-43ed-824a-5320fbf30171)

Change the `margin-top: -100%` in the above figure to `margin-top: -200%`, and it will work normally

**Comment by FourSpaces** [comment]
I think modifications should be made https://github.com/minio/mds The code for the Accordion can solve this problem. But I see that the latest version of the MDS module is v2.2.5, but v1.0.2 is being used here. Is there any problem?

https://github.com/minio/mds/blob/bb726ae83ac248b590f46ab41e70a1135eeece7a/src/components/Accordion/Accordion.tsx#L67

**Comment by bexsoft** [comment]
> I think modifications should be made https://github.com/minio/mds The code for the Accordion can solve this problem. But I see that the latest version of the MDS module is v2.2.5, but v1.0.2 is being used here. Is there any problem?
> 
> https://github.com/minio/mds/blob/bb726ae83ac248b590f46ab41e70a1135eeece7a/src/components/Accordion/Accordion.tsx#L67

Hi @FourSpaces!

mds 1 and mds 2 are two different base codes but we can fix this for both versions.
