### ISSUE TITLE
share file don't work

### ISSUE THREAD

**Issue by papandadj** [minio/console#3378]
I'm utilizing Minio on my cloud server, which I've installed using Docker and have exposed port 9001 for access. However, a peculiar issue arises when I upload a file via the web interface and attempt to share it. The system consistently sends POST requests to the share API, which prevents me from copying the link. I need assistance with this issue.

iamge : quay.io/minio/minio@sha256:e2a488767bd967b02627e559cf5e6ec846ea53e7d086038163b3035ed9aac20e

https://github.com/minio/minio/assets/25424898/81eec3df-b886-4b96-b3f6-b7639d52801e

**Comment by cesnietor** [comment]
@papandadj thanks for raising, we'll look into it.
For now, you can check the response of one of those requests and the url will be there for you to copy paste.

**Comment by papandadj** [comment]
<img width="1452" alt="image" src="https://github.com/minio/console/assets/25424898/f95f47b6-5f46-45ea-ba55-dcb3ae989312">
<img width="583" alt="image" src="https://github.com/minio/console/assets/25424898/737460ff-0d3c-4216-a2d5-6fe133be1ab1">

### request:
url: http://los.jiadj.com:9001/api/v1/buckets/public/objects/share?prefix=text.txt&version_id=null&expires=43200s
payload: 
            prefix: text.txt
            version_id: null
            expires: 43200s

<img width="1696" alt="image" src="https://github.com/minio/console/assets/25424898/0f94d483-bcc2-4ffa-b007-7229fee378fc">

### response:
"http://los.jiadj.com:9001/api/v1/download-shared-object/http:%2F%2F127.0.0.1:9000%2Fpublic%2Ftext.txt%3FX-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XWCFB12OH3EZG68P85RX%252F20240614%252Fus-east-1%252Fs3%252Faws4_request&X-Amz-Date=20240614T074303Z&X-Amz-Expires=43200&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJYV0NGQjEyT0gzRVpHNjhQODVSWCIsImV4cCI6MTcxODM4NzAyNiwicGFyZW50Ijoicm9vdCJ9.Az_Ud1lEqR7Q108DP09yBTbHLKfVGG7jgq_boG57W3H1Z60XRm1mGzHXYbSJU0MMDHic9vB1G1YiGOGCf9FBhQ&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=b482f188cb06becbaf387fc37f9924add39dceb8d2cb0b059b75d91562e2afeb"


minio container logs:
<img width="1227" alt="image" src="https://github.com/minio/console/assets/25424898/798183a8-ed6a-4a70-bfe7-509a4a382a07">

**Comment by bexsoft** [comment]
Hi @papandadj!, How are you doing?

The second issue you are reporting was fixed in `RELEASE.2024-06-13T22-53-53Z`, please update accordingly.

For the first issue We've just sent a fix for it in #3387 

Thanks for reporting.

**Comment by papandadj** [comment]
thanks, I will try again after updating the image.
