### ISSUE TITLE
Share link not working

### ISSUE THREAD

**Issue by MICCustomsSolutions** [minio/console#3382]
The link generated by the "share" feature is not working.

The generated link for example looks like this and is not working:

https://url:port/api/v1/download-shared-object/https:%2F%2Furl%2Fpath%2Fpath%2Fpath%2Ffile%3FX-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F2BECNBK55NM466E1L7D%252F20240613%252Fus-east-1%252Fs3%252Faws4_request&X-Amz-Date=20240613T061126Z&X-Amz-Expires=43200&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJGMkJFQ05CSzU1Tk00NjZFMUw3RCIsImV4cCI6MTcxODMwMDE3NywicGFyZW50IjoibWljdXNlciJ9.Jn_oercMlyPR7AUUBNS4o42XaX_aimbn2_Mw8u4jk6HlEX93BGAIuYGrGBtdmUtKUMLSq60FEdgBndIzURnuog&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=42b717feed3a1eb156fe223e11c9e8b9e08249ea7a0145d7f68708e51a600b3b

If we manually edit the above link to this:
https://url/path/path/path/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F2BECNBK55NM466E1L7D/20240613/us-east-1/s3/aws4_request&X-Amz-Date=20240613T061126Z&X-Amz-Expires=43200&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJGMkJFQ05CSzU1Tk00NjZFMUw3RCIsImV4cCI6MTcxODMwMDE3NywicGFyZW50IjoibWljdXNlciJ9.Jn_oercMlyPR7AUUBNS4o42XaX_aimbn2_Mw8u4jk6HlEX93BGAIuYGrGBtdmUtKUMLSq60FEdgBndIzURnuog&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=42b717feed3a1eb156fe223e11c9e8b9e08249ea7a0145d7f68708e51a600b3b

It works.

MinIO VERSION 2024-06-11T03:13:30Z
Linux 5.4.17-2136.331.7.el8uek.x86_64 #3 SMP Mon May 6 15:17:51 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cesnietor** [comment]
encoding of the url is not working, we'll take a look.
