### ISSUE TITLE
font end progress

### ISSUE THREAD

**Issue by gaoyang666** [minio/console#3394]
Using the front end to directly pass to the backend, can the putObject method in JavaScript obtain the file upload progress? It seems that the documentation does not mention this,thanks!

**Comment by prakashsvmx** [comment]
The console already displays progress when file is uploading or downloading . 
Please share more details if you have found issue elsewhere ( if you meant minio-js, it is not supported yet, feel free to send a PR) 


![image](https://github.com/minio/console/assets/23444145/4db40510-e420-431e-90ef-f98899e30a87)
