### ISSUE TITLE
Allow the option to disallow the local idp login when OIDC is set up

### ISSUE THREAD

**Issue by MFYDev** [minio/console#3396]
Hi, I have been trying to find out how to achieve this in the doc for a long time and got nothing.

Please add this feature to disallow the other two log in when sso is enabled, thanks

**Comment by cesnietor** [comment]
We used to have that behavior but then users wanted to be able to select multiple authentication methods.
Unfortunately this is not something we would be supporting any time soon.
If this is something your company requires please reach out to https://min.io/pricing and we discuss more your requirements.
