### ISSUE TITLE
Front-end direct upload to the backend does not get the progress bar. Is it possible to obtain the progress bar through the backend and push it to the front end?

### ISSUE THREAD

**Issue by gaoyang666** [minio/console#3399]
Front-end direct upload to the backend does not get the progress bar. Is it possible to obtain the progress bar through the backend and push it to the front end? thanks！

**Comment by prakashsvmx** [comment]
Console is built only for the use within minio. it already has progress bar for while uploading. 
i remember similar issue was raised in minio-js repo.

**Comment by gaoyang666** [comment]
I am using minio-js for direct front-end to back-end file uploads, but currently, the progress bar is not displaying. I want the backend to return the progress and push it to the front end

**Comment by prakashsvmx** [comment]
it is not supported.
