### ISSUE TITLE
Acces Denied at Metadata, download and preview for files from console

### ISSUE THREAD

**Issue by jpacora** [minio/console#3409]
## NOTE

Please subscribe to our [paid subscription plans](https://min.io/pricing) for 24x7 support from our Engineering team.

## Expected Behavior
Get metadata, download and preview files using the MinIO console with root account

## Current Behavior
Metadata, download preview features isn't working on a fresh docker container setup (throws Acces Denied, see screenshots below) through console, but `mc get` is working

![image](https://github.com/user-attachments/assets/2e3a002c-eecc-4d13-91e7-7a65dea08ee4)
![image](https://github.com/user-attachments/assets/3e884500-ff2b-443f-b8e9-2cfd3bd152a6)

## Steps to Reproduce (for bugs)

1. Setup docker
2. Use the minio/minio:latest image from docker hub
3. Start with server --console-address ":9001" /data and ["MINIO_ROOT_USER", "MINIO_ROOT_PASSWORD", "MINIO_SERVER_URL", "MINIO_BROWSER_REDIRECT_URL"] env vars

## Context
When I want to download: `failed to get Stat() response from server for Screenshot 2024-04-28 at 19.58.10.png (version null): Access Denied.`

When I choose a file from the console: `{"detailedMessage":"Access Denied.","message":"Access Denied."}`

## Your Environment

* MinIO version used (`minio --version`): RELEASE.2024-07-10T18-41-49Z (commit-id=6c6f0987dc04c942c33a2a90ffbe7075c0e2e5eb)
* Server setup and configuration:  Raspberry Pi 8GB RAM
* Operating System and version (`uname -a`): Linux raspberrypi 6.6.31+rpt-rpi-2712 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

**Comment by harshavardhana** [comment]
> 3\. MINIO_ROOT_USER", "MINIO_ROOT_PASSWORD", "MINIO_SERVER_URL", "MINIO_BROWSER_REDIRECT_URL

Please paste values for each of these.

**Comment by harshavardhana** [comment]
Just tested this at https://play.min.io its all working as expected 

![image](https://github.com/user-attachments/assets/317676dd-7080-4a90-9b5f-f7767d305f24)

So need more details from your end.

**Comment by harshavardhana** [comment]
jul 13 11:10:40 play.min.io minio[1215063]: Version: DEVELOPMENT.2024-07-13T02-08-28Z (go1.22.5 linux/amd64)

> * MinIO version used (`minio --version`): RELEASE.2024-07-10T18-41-49Z (commit-id=6c6f0987dc04c942c33a2a90ffbe7075c0e2e5eb)

MinIO version running also docker pull minio/minio:RELEASE.2024-07-13T01-46-15Z as I mentioned previously, please report only after you have upgraded the setup - which you did not do.

**Comment by jpacora** [comment]
Still with the same issue using the `minio version RELEASE.2024-07-13T01-46-15Z (commit-id=459985f0fa5c5c9bc19e8bf2b81f624cee18519b)` version, my env vars are:
      - MINIO_ROOT_USER=jpacora
      - MINIO_ROOT_PASSWORD=admint3st
      - MINIO_SERVER_URL=https://tcqstorage.REDACTED.pro
      - MINIO_BROWSER_REDIRECT_URL=https://tcqstorage.REDACTED.pro/console/ui
      
I already have another MinIO deployment with the same docker-compose and its working, but not in my raspberry

**Comment by harshavardhana** [comment]
> - MINIO_SERVER_URL=https://tcqstorage.REDACTED.pro
> - MINIO_BROWSER_REDIRECT_URL=https://tcqstorage.REDACTED.pro/console/ui

You must ensure that these domains can resolve appropriately to the docker container you are running.  This is what needs to be done to make this work properly. 

As you can see, it is working fine on our public deployments.
