### ISSUE TITLE
Can I use MinIO Console as the control panel for my object storage service?

### ISSUE THREAD

**Issue by iabetor** [minio/console#3416]
I have developed an S3-compatible object storage service, and I’m lacking a control panel. Can I use MinIO Console as the control panel for my object storage service?

If it's possible, how should I modify the MinIO Console?

**Comment by prakashsvmx** [comment]
This repo (minio console ) is designed to be modular and to be integrated exclusively only with MinIO server https://github.com/minio/minio

It is protected by AGPL v3  https://min.io/compliance  and also protected with the below:
https://min.io/compliance#compliance-logo
https://min.io/compliance#compliance-trademark

So you shall not use this without compliance.

**Comment by iabetor** [comment]
I understand your point, and we will definitely comply with the AGPL v3 regulations. If I want to implement such an S3 browser, how should I go about it?

**Comment by iabetor** [comment]
> This repo (minio console ) is designed to be modular and to be integrated exclusively only with MinIO server https://github.com/minio/minio
> 
> It is protected by AGPL v3 https://min.io/compliance and also protected with the below: https://min.io/compliance#compliance-logo https://min.io/compliance#compliance-trademark
> 
> So you shall not use this without compliance.
I understand your point, and we will definitely comply with the AGPL v3 regulations. If I want to implement such an S3 browser, how should I go about it?
