### ISSUE TITLE
Audit log setups are not clearly visible from the Console

### ISSUE THREAD

**Issue by allanrogerr** [minio/console#3434]
## Expected Behavior
Audit log setups should be visible from the Console from quick validation

## Current Behavior
Audit log setups are not visible from the Console

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
1.- Check audit log setup
```
mc admin config get play audit_webhook
```
```
audit_webhook enable=off endpoint= auth_token= client_cert= client_key= batch_size=1 queue_size=100000 queue_dir= 
```

1.- Setup audit default and an extra
```
mc admin config set play audit_webhook \
  endpoint="https://webhook.site/1234"
mc admin config set play audit_webhook:PRIMARY \
  endpoint="https://webhook.site/5678"
```
```
Successfully applied new settings.
Successfully applied new settings.
```

1.- Check audit setup
```
mc admin config get play audit_webhook
```
```
audit_webhook endpoint=https://webhook.site/1234 auth_token= client_cert= client_key= batch_size=1 queue_size=100000 queue_dir= 
audit_webhook:PRIMARY endpoint=https://webhook.site/5678 auth_token= client_cert= client_key= batch_size=1 queue_size=100000 queue_dir= 
```

1.- Observe Console incorrectly indicating that Audit is not setup
<img width="814" alt="image" src="https://github.com/user-attachments/assets/42f30b41-41da-4c5c-a3bd-5945bedaaf77">

1.- Cleanup
```
mc admin config reset play audit_webhook
mc admin config reset play audit_webhook:PRIMARY
```

## Context
It is not possible to check the MinIO Audit setup using the Console

## Regression
Not clear

## Your Environment

* `mc` version used:
```
mc --version
mc version RELEASE.2024-08-17T11-33-50Z (commit-id=2c94b8d03979ed96a6379ecabc3435b271398efc)
Runtime: go1.22.6 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```
* MinIO version used (`minio --version`):
```
mc admin info play | grep Version | head -n1
   Version: 2024-09-03T18:23:41Z
```
* Server setup and configuration:
* Operating System and version (`uname -a`): `Linux ... 5.15.0-118-generic #128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by allanrogerr** [comment]
Audit setups are here. This is not clear. Please evaluate removing the unused UI shown above.

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/b331077f-80eb-4bbc-97b2-9b812d1e8b06">

**Comment by bexsoft** [comment]
This feature will be removed in future versions of Console. Closing right now
