### ISSUE TITLE
Unable to register MinIO deployment via UI/Console

### ISSUE THREAD

**Issue by Smoerrebroed** [minio/console#3458]
## NOTE

Please subscribe to our [paid subscription plans](https://min.io/pricing) for 24x7 support from our Engineering team.

Trying to register a deployment of MinIO upstream in SUBNET using SUBNET credentials does not work.

## Expected Behavior
Registering a MinIO (upstream) deployment from the UI using credentials for SUBNET should (a) activate the deployment and (b) register the deployment on SUBNET.

## Current Behavior
Trying to register a deployment, the attached error message is shown, regardless of which email address and/or password is being used.

## Possible Solution
It used to work before, so I'm going to go out on a limb and say that we can make this work again. :-)

## Steps to Reproduce (for bugs)

1. Create a fresh installation of MinIO (upstream)
2. Log in to Console/UI using admin credentials
3. Go to License --> Register your cluster
4. Enter any email address (+ password) and click "Register"
![image](https://github.com/user-attachments/assets/74784bcf-7461-4b20-b370-e02398f1d1e7)
5. Trying to register via API key also gives a (different) error message (see attachment)
![image](https://github.com/user-attachments/assets/5c139029-44cd-4769-8bfa-b28534cc639b)
## Context
Stumbled on this by accident. Registering via mc cli seems to work.

## Regression
 Yes
 ?

## Your Environment
Running on a 2 node docker setup with current Ubuntu images

**Comment by ramondeklein** [comment]
I can reproduce. Let me check...

**Comment by ramondeklein** [comment]
It looks like there was an intermittent problem on the Subnet side, because it now works fine (without making any changes). I do get an error, because I'm not a customer, but I guess that would be correct.

@Smoerrebroed Can you check again?

**Comment by Smoerrebroed** [comment]
Hmmh, weird. So either it is an intermittent problem, or it is somehow linked to the fact that I've been running my two-node cluster with MINIO_CI_CD=true to allow for folders on the root drive to be used. Could that have an impact on the connectivity to SUBNET?

**Comment by ramondeklein** [comment]
I don't think so. I didn't use `MINIO_CI_CD=true` and I also had a failure. The response looks very much like a MinIO response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>BadRequest</Code>
  <Message>An error occurred when parsing the HTTP request POST at &#39;;/api/auth/login&#39;</Message>
  <Resource>/api/auth/login</Resource>
  <RequestId></RequestId>
  <HostId></HostId>
</Error>
```
It looks like MinIO tried to connect to Subnet and got an invalid response. Either it connected to an incorrect endpoint (should be https://subnet.min.io/api/auth/login) or the API didn't respond properly for a while during the time of the failed requests.

**Comment by cesnietor** [comment]
@Smoerrebroed  we did see a couple of errors happening on the 24th, https://status.apps.min.dev. Please retry and if fails we can reopen and investigate.
