### ISSUE TITLE
unpkg.com call in the front

### ISSUE THREAD

**Issue by p1r4t3-s4il0r** [minio/console#3468]
## NOTE

Please subscribe to our [paid subscription plans](https://min.io/pricing) for 24x7 support from our Engineering team.

Trough a web browser, the login page of minio is making a request to `https://unpkg.com/detect-gpu@5.0.38/dist/benchmark/d-amd.json`.

## Expected Behavior

I want do deactivate this request. 

## Current Behavior

Request to `https://unpkg.com/detect-gpu@5.0.38/dist/benchmark/d-amd.json`.

## Steps to Reproduce (for bugs)

1. Go to login page
2. Open the inspector
3. Go to network and reload the page
4. You should see a request to `unpkg.com`

## Context

I need to deactivate this request. Because I want to prevent unwanted call to internet.

## Regression

No regression (as far as I know).

## Your Environment

* MinIO version used (`minio --version`): `RELEASE.2024-07-16T23-46-41Z`
* Server setup and configuration: docker compose
* Operating System and version (`uname -a`): `Alma Linux 4.18`

**Comment by ramondeklein** [comment]
Just confirmed that `RELEASE.2024-10-29T16-01-48Z` is making this request.

**Comment by p1r4t3-s4il0r** [comment]
Thanks for your answer.

Are you planning on implementing a environment variable to control this behavior ? 

Thanks.

**Comment by harshavardhana** [comment]
> Are you planning on implementing a environment variable to control this behavior ?

Set 

```
export MINIO_BROWSER_LOGIN_ANIMATION=off
```

**Comment by ramondeklein** [comment]
@harshavardhana This disables the login animation, but it still makes the call to `unpkg.com`.

**Comment by ramondeklein** [comment]
See https://github.com/minio/mds/pull/1091.

**Comment by p1r4t3-s4il0r** [comment]
Hello @ramondeklein , 
Thank you very much for you work. Do you when the new container image of minio will be released on the docker hub ?
Thanks

**Comment by ramondeklein** [comment]
We are planning some more work on the next console release, so it may take some time. We don't consider this a high-priority item, so we won't release a new MinIO release, because of this. When a new console is merged into MinIO, this feature will become available automatically.

In the mean-time you may want to block `unpkg.com` by settings `.spec.hostAliases` for this hostname.

PS: Thanks for reporting. We don't want MinIO to contact the internet unless explicitly being told to...

**Comment by p1r4t3-s4il0r** [comment]
No worries, I'll wait.

I'm happy to contribute to open source projects : )
