### ISSUE TITLE
Add change password behavior

### ISSUE THREAD

**Issue by dvaldivia** [minio/console#348]

**Comment by Alevsk** [comment]
- Do we have some wireframes for this? if not I can do some proposals.
- Admin users will be allowed to change the passwords of all other users? or this feature will be limited to a user changing its own password only? in the second scenario we will need a profile page

**Comment by dvaldivia** [comment]
you can propose

**Comment by dvaldivia** [comment]
Admins should be able to change anyone's password, however for a user to change their own password it's tricky since they would need permission

**Comment by Alevsk** [comment]
Update:

Regarding latest console call the change-password functionality will be now part of the `service accounts` screen (now renamed to `Accounts`), the screen will be divided in two sections, on the top user/parent account configurations (change password here) and on the bottom the existing service accounts list
