### ISSUE TITLE
[Features Requst]  Minio Console Is it possible to add a checkbox for chunked uploads when uploading files?

### ISSUE THREAD

**Issue by PunkFleet** [minio/console#3490]
It is intended for: NAS self-hosted users
Scenario:
When NAS self-hosted users perform intranet penetration via Cloudflare tunnels to allow public access to the minio console via a domain name, minio is unable to upload files > 100M or > 500M (depending on cloudflare). At the same time, however, cloudflare does allow chunked uploads on the requesting end. One can programmatically fulfill requests for large file uploads, but there is no way around this limitation on the minio console page.

Is it possible in the future to add a checkbox to minio console file uploads to provide the option of chunking?

**Comment by ramondeklein** [comment]
The proper way to deal with this is not to enable chunking, but the implement multi-part file upload instead.

**Comment by harshavardhana** [comment]
Community Console UI is frozen and is under maintenance. It is not taking any more feature requests.

**Comment by PunkFleet** [comment]
> The proper way to deal with this is not to enable chunking, but the implement multi-part file upload instead.

This can only be done through a programmatic method, it can't be set via console right?

**Comment by ramondeklein** [comment]
No, it would require client-side changes.

**Comment by harshavardhana** [comment]
> The proper way to deal with this is not to enable chunking, but the implement multi-part file upload instead.

@ramondeklein this a proxy problem single PUT supports uploading upto 5Ti on MinIO if you don't use cloudflare things are all good.

**Comment by PunkFleet** [comment]
> 
> @ramondeklein this a proxy problem single PUT supports uploading upto 5Ti on MinIO if you don't use cloudflare things are all good.

Yes, everything is ok if i using it directly. I just thought using domain name is friendly. And now...i stuck

**Comment by PunkFleet** [comment]
> No, it would require client-side changes.

Can you explain in detail how to do this? For the programmatic approach I know how to modify it, but that should be after finishing the local minio server, but right now it seems like I have to make a trade-off between Cloudflare tunnel and minio console.

**Comment by ramondeklein** [comment]
@harshavardhana I know, but multi-part upload would also enable partial retry and chunk automatically. I've implemented a client-side (Javascript) "smart upload" for [TransferXL](https://www.transferxl.com/) before that parallelizes uploads and automatically chooses appropriate part-sizes depending on upload speed. That would also fix issues with reverse-proxies that maximize body sizes. But the code is 10 years old and written for AngularJS, so it wouldn't be an easy port to MinIO.

More importantly... I don't think our console should require that kind of flexibility. The management console is meant for management, not daily operations. It doesn't need to have such a complex upload mechanism.

**Comment by harshavardhana** [comment]
> > @ramondeklein this a proxy problem single PUT supports uploading upto 5Ti on MinIO if you don't use cloudflare things are all good.
> 
> Yes, everything is ok if i using it directly. I just thought using domain name is friendly. And now...i stuck

It is a cloudflare problem they should fix their arbitrary limit.

There is no reason to have 100mib limit.
