### ISSUE TITLE
New design for Settings

### ISSUE THREAD

**Issue by dvaldivia** [minio/console#355]
we need to come up with a refresh design for our `Settings` screen (formerly configuration list) that gathers all the configurations in a single screen and allows you to modify it.

**Comment by labebe6** [comment]
Sure. I'll get started on this.

**Comment by belvid** [comment]
This is what Leya was working on @dvaldivia, as far as I know I think she completed it.

https://xd.adobe.com/view/f6b2205e-20aa-4e09-b545-89c6bd5b5bd7-a3e1/

Could we review it soon so I can follow up on any changes required?
