### ISSUE TITLE
MCS ldap support

### ISSUE THREAD

**Issue by tomsozolins** [minio/console#364]
Hello!
Does Minio Console UI support LDAP?

I configured all settings according to this guide: https://github.com/minio/minio/blob/master/docs/sts/ldap.md , but when i click login in Minio Console is showing error:
![image](https://user-images.githubusercontent.com/48243828/97783240-14f0af80-1b9f-11eb-8220-a01c4bcd9fe1.png)

In console it logs this message:
`original error: The specified user does not exist. (Specified user does not exist)
`
How can i assign permissions to ldap users, so they can login in mcs console?

**Comment by Alevsk** [comment]
@tomsozolins hi, you need to configure and assign the policy manually to your LDAP user, very similar as in the following examples: https://github.com/minio/console/blob/master/DEVELOPMENT.md

**Comment by tomsozolins** [comment]
> @tomsozolins hi, you need to configure and assign the policy manually to your LDAP user, very similar as in the following examples: https://github.com/minio/console/blob/master/DEVELOPMENT.md#add-the-consoleadmin-policy-to-user-billy-on-minio

If i try to add ldap user to group as suggested in example, i get error:
mc: <ERROR> Unable to set the policy. The specified user does not exist. (Specified user does not exist).

Also minio logs following:
Error: LDAP server connection failure: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C090446, comment: AcceptSecurityContext error, data 52e, v2580
