### ISSUE TITLE
Create Role Wireframe

### ISSUE THREAD

**Issue by dvaldivia** [minio/console#370]
Need to wireframe the new role creation screen that selects from a list of `Role Templates` and a bunch of resources that will be mixed with the `role template` to create a `role` which then can be assigned to either users or groups

**Comment by bexsoft** [comment]
![New Role - Template 1](https://user-images.githubusercontent.com/33497058/98157511-140d9580-1e9f-11eb-8fbb-abdf54768566.png)
![New Role – JSON 1](https://user-images.githubusercontent.com/33497058/98157513-153ec280-1e9f-11eb-8d48-174100bbf7bf.png)
![New Role – JSON 2](https://user-images.githubusercontent.com/33497058/98157519-166fef80-1e9f-11eb-9e89-0397ce151917.png)
![New Role – JSON 2B](https://user-images.githubusercontent.com/33497058/98157521-166fef80-1e9f-11eb-8a91-13e390bc501a.png)
![New Role – JSON 3](https://user-images.githubusercontent.com/33497058/98157524-17088600-1e9f-11eb-9b52-058089022f88.png)
![New Role – Template 2](https://user-images.githubusercontent.com/33497058/98157526-17a11c80-1e9f-11eb-88d6-24471a2a131a.png)
![New Role – Template 3](https://user-images.githubusercontent.com/33497058/98157527-17a11c80-1e9f-11eb-9097-0e783cfe168d.png)
![Roles List – 1](https://user-images.githubusercontent.com/33497058/98157528-1839b300-1e9f-11eb-8bf5-cbab64ec5298.png)
![Roles List](https://user-images.githubusercontent.com/33497058/98157529-1839b300-1e9f-11eb-919f-c733f7e09762.png)
