### ISSUE TITLE
Confirm tenant name when deleting a tenant

### ISSUE THREAD

**Issue by dvaldivia** [minio/console#391]
We need to confirm the tenant name when a tenant is marked for deletion in the UI on the operator console

**Comment by bexsoft** [comment]
Can we confirm if this issue is still happening? couldn't reproduce it

<img width="916" alt="Screen Shot 2020-11-30 at 22 59 34" src="https://user-images.githubusercontent.com/33497058/100699684-45c03200-3361-11eb-9cc1-499a1d14107a.png">

**Comment by cesnietor** [comment]
@bexsoft I think the issue here is to **retype** the name as we do in vsphere to double confirm
