### ISSUE TITLE
Console UI behind nginx subpath

### ISSUE THREAD

**Issue by harshitmahapatra** [minio/console#396]
Hi,
Is there a way to set up the console UI at a subpath behind a reverse proxy like Nginx?
It would be nice if we could provide an environment variable like SERVER_BASEPATH to start the server at a subpath.

**Comment by kevinlul** [comment]
Can't you just rewrite the request path in nginx?

**Comment by dvaldivia** [comment]
We can look into this as soon as we have some buffer time for development, we also welcome PRs.

We'll need react to be ready to work with the sub folder

**Comment by mqu** [comment]
hello, same behavior wanted here. It would be nice to have at same URL minio and minio-console in subpath. I have tried to put console to https://minio.example.org/admin, but it does not work.

thanks and best regards, Marc.

**Comment by hypervtechnics** [comment]
We also need this

**Comment by dvaldivia** [comment]
This is supported with the latest on master, will be there on the next release

**Comment by TomHellier** [comment]
@dvaldivia what is the config option needed? or a link to the PR which adds this functionality? thanks :)

**Comment by thesuperzapper** [comment]
@dvaldivia as of `v0.10.4` it is still not possible to use Minio Console under an HTTP prefix, see: https://github.com/minio/console/issues/853#issuecomment-947179997.

**Comment by berendiwema** [comment]
@TomHellier were you able to find the config option?

**Comment by TomHellier** [comment]
@berendiwema I've fixed this in #952 #964 I've been running the docker version created from that PR in ops for several months now without issue.

**Comment by berendiwema** [comment]
@TomHellier I see. Does that fix work without nginx as well? #964 looks like it's depending on nginx rewrites right?

**Comment by TomHellier** [comment]
dunno, I only tested it using nginx-ingress for kubernetes, I don't know enough about your use case to help more. Maybe just give it a go?

alternatively @reddec wrote something here:
https://github.com/reddec/miniconsole
