### ISSUE TITLE
Add progress bar when uploading a large object

### ISSUE THREAD

**Issue by dvaldivia** [minio/console#415]
- [x] Design for how the upload of a file will look @belvid @Jayshreemagdum 
- [ ] Implementation @cesnietor

**Comment by cesnietor** [comment]
@dvaldivia this requires a design, right now it works with snack bars as temporal notification.

**Comment by dvaldivia** [comment]
@belvid @Jayshreemagdum can we have a design specification for how will uploading files look like in the UI?

**Comment by tomsozolins** [comment]
Will there be a folder upload feature like in MinIO Browser?

**Comment by belvid** [comment]
Here's the link for the prototype.

We can review it tomorrow in the sync call if need it.

https://xd.adobe.com/view/67050b39-0e9b-41ae-8d3f-31ee833e6d4b-3256/

(to see the progress bar animation, keep clicking on the line at the top bar)
