### ISSUE TITLE
Question about the Super Admin

### ISSUE THREAD

**Issue by bkief** [minio/console#438]
I'd like to better understand the role of the Super Admin, i.e. what is provide via the env variables, CONSOLE_ACCESS_KEY/CONSOLE_ACCESS_SECRET. Why do we need this user, couldn't everything be done via the provided user credentials during console login?  I'm thinking about console as a UI based Minio Client tool, so maybe that premise is false.

**Comment by harshavardhana** [comment]
> I'd like to better understand the role of the Super Admin, i.e. what is provide via the env variables, CONSOLE_ACCESS_KEY/CONSOLE_ACCESS_SECRET. Why do we need this user, couldn't everything be done via the provided user credentials during console login? I'm thinking about console as a UI based Minio Client tool, so maybe that premise is false.

This is going to be changed completely @bkief and we will update the docs henceforth.

**Comment by bkief** [comment]
@harshavardhana Great, that makes a lot of sense from a security perspective. One additional question, has any thought been given to how anonymous access could work? Maybe a 'Anonymous Access' link under the login boxes that only shows the Object Browser?

**Comment by harshavardhana** [comment]
This has been removed as a requirement to start console already since many releases, closing this as fixed.
