### ISSUE TITLE
Please add feature to upload folders.

### ISSUE THREAD

**Issue by tomsozolins** [minio/console#451]
Hello! 
Currently it is possible to only upload single file in Console, but i need to upload thousands of directories with many subfolders and files. Single object upload for this use case becomes non usable, so im stuck with MinIO Browser. 

Will there be support for folder upload in Console like there is in MinIO Browser?

**Comment by Alevsk** [comment]
@tomsozolins hi, we will discuss internally about this feature, but for uploading multiple files the recommendation is to use the mc client: `mc cp -r /tmp/folder/ alias/bucket/folder/`

**Comment by tomsozolins** [comment]
> @tomsozolins hi, we will discuss internally about this feature, but for uploading multiple files the recommendation is to use the mc client: `mc cp -r /tmp/folder/ alias/bucket/folder/`

Terminal based client will not be suitable for people who will use the system unfortunately. Web based solution would be much more nicer for end users.

**Comment by HaoLiuHust** [comment]
Agree, Web based solution would be much more easier for clients., not every client should use command line tool, it's difficult to setup and learn to use it for some customers
