### ISSUE TITLE
Alignment for text boxes in modals

### ISSUE THREAD

**Issue by belvid** [minio/console#456]
The text boxes should be align to the pink line.
The text on the left should align to the blue line.

<img width="1475" alt="Screen Shot 2020-11-30 at 9 19 24 PM" src="https://user-images.githubusercontent.com/20955366/100700223-ce36d680-3351-11eb-8a3b-dafcb05e71bb.png">

**Comment by bexsoft** [comment]
This styles were updated in the latest version

<img width="824" alt="Screen Shot 2020-12-04 at 13 13 35" src="https://user-images.githubusercontent.com/33497058/101204983-b2258480-3632-11eb-8942-ea2ada2a0a4a.png">
