### ISSUE TITLE
Diagnostic module

### ISSUE THREAD

**Issue by Alevsk** [minio/console#460]
This page will be used to run and display OBD reports about the MinIO cluster, further discussion about what kind of information we will display is need it.

![diagnostics](https://user-images.githubusercontent.com/1795553/100929673-d94a4d80-349c-11eb-9b5d-1ef98319a6b5.png)

This `Diagnostic` page will be available under a new category called `Subscription Network` in the Menu and be part of the Subnet Integration modules

**Comment by dvaldivia** [comment]
We should confirm with @abperiasamy if we are showing a preview of the OBD

**Comment by cesnietor** [comment]
solved on https://github.com/minio/console/pull/543
