### ISSUE TITLE
Remove download icon on folder in Object Browser

### ISSUE THREAD

**Issue by cesnietor** [minio/console#468]
Folder download is not supported
<img width="506" alt="Screen Shot 2020-12-02 at 7 05 13 PM" src="https://user-images.githubusercontent.com/11819101/100950145-55f71f00-34d1-11eb-8ce4-dd1edf6311aa.png">

**Comment by tomsozolins** [comment]
Is it possible to support this feature, not remove it?

**Comment by cesnietor** [comment]
@tomsozolins  it is possible, right now we are working towards a releasable status with our planned features but PRs are more than welcome.

**Comment by dvaldivia** [comment]
@tomsozolins we are going to track that feature request via https://github.com/minio/console/issues/481
