### ISSUE TITLE
Can the number of nodes be increased in Dashboard?

### ISSUE THREAD

**Issue by imopro** [minio/console#479]
Why don't you see the number of nodes in Dashboard？
Can the number of nodes be increased in Dashboard?
[https://minio.slack.com/files/U01EU1W4S9K/F01G5CQF6KF/minio-console-dashboard.png](url)

**Comment by harshavardhana** [comment]
Don't know what this means, the link doesn't work anymore. Closing as a non-actionable invalid issue.
