### ISSUE TITLE
Empty list of bucket

### ISSUE THREAD

**Issue by adenau** [minio/console#528]
With the current version of minio-console ( 0.4.6 ), when I try to browse the list of buckets on the server, I get an empty list. This occurs when using the latest version of minio ( RELEASE.2020-12-16T05-05-17Z ). However, if I use the same minio-console, with the same user, the same policy but an older version of Minio ( RELEASE.2020-08-27T05-16-20Z ), i works perfectly.

The Minio user for this test was created using the instruction on the Minio Console webpage ( all permissions for diagnostics )

When I check the logs for Minio Console, I find the following error 
original error: This 'admin' API is not supported by server in 'mode-server-fs'

It's true that I'm running Minio on a simple file system, but I think that listing bucket should a simple enough API. Could this be a bug with Minio itself?

**Comment by harshavardhana** [comment]
@adenau minio console does not support FS mode - it is perhaps incidental that it worked.   Console is meant for bigger scale deployments. 

FS mode is generally toy setups for that just use the regular MinIO browser that comes pre-baked with MinIO.  

So bottom line this is out of scope for this project.

**Comment by adenau** [comment]
Hi,

I can understand that and won't try to argue the point. However, I would like to express a lot of confusion since what you have just mentioned is not stated on the main page of the projet. If I look at the front page, the software is described as:

_A graphical user interface for MinIO._

Maybe a better description would be

_A graphical user interface for MinIO for cluster deployments. Please note that this tool is not designed for toy setup that just uses the regular MinIO browser that comes pre-baked with MinIO._

I would save us "toy" users a lot of time.

Cheers,
