### ISSUE TITLE
Admin Interface - no Buckets yet

### ISSUE THREAD

**Issue by tinohager** [minio/console#531]
Hi, i have start the minio/console with docker. But if i goto bucket i have an error in the console log. How can I set in which mode the server runs?

![image](https://user-images.githubusercontent.com/8215186/102764325-443fc380-437b-11eb-9cb8-a7094ae65482.png)

**Error in the docker minio/console output**
> 2020/12/21 09:49:53 original error: This 'admin' API is not supported by server in 'mode-server-fs'

**my start command**
`docker run -p:9090:9090 -e CONSOLE_PBKDF_PASSPHRASE=SECRET -e CONSOLE_PBKDF_SALT=SECRET -e CONSOLE_ACCESS_KEY=console -e CONSOLE_SECRET_KEY=mysecretofminio -e CONSOLE_MINIO_SERVER=https://minio.mydomain.tld minio/console server`

**Comment by harshavardhana** [comment]
console does not support single drive deployments @tinohager

**Comment by tinohager** [comment]
Does this mean that I simply have to specify 2 hard drives for the server?

**Comment by harshavardhana** [comment]
> @harshavardhana Does this mean that I simply have to specify 2 hard drives for the server?

4 minimum for erasure set-up.

**Comment by tinohager** [comment]
@harshavardhana I have deploy today a new server with 4 drives but now i have a new error code.

> This 'admin' API is not supported by server in 'mode-server-xl'
