### ISSUE TITLE
MIME Type Mismatch

### ISSUE THREAD

**Issue by stevefan1999-personal** [minio/console#532]
```
The resource from “http://localhost:9090/static/js/main.494f118c.chunk.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```
nuff said. you need to change text/plain to application/javascript or some other valid entries

**Comment by Alevsk** [comment]
> ```
> The resource from “http://localhost:9090/static/js/main.494f118c.chunk.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
> ```
> 
> nuff said. you need to change text/plain to application/javascript or some other valid entries

can you try latest version of console? i think this problem is already fixed

<img width="566" alt="Screen Shot 2021-01-22 at 16 04 35" src="https://user-images.githubusercontent.com/1795553/105553791-b2a1d980-5ccb-11eb-9d72-34c8ea7bfec9.png">
