### ISSUE TITLE
This 'admin' API is not supported by server in 'mode-server-distributed-xl'

### ISSUE THREAD

**Issue by JannikZed** [minio/console#534]
I just started to try out the minio console dashboard. We have a little minio federated cluster in Kubernetes, built up with bitnami/minio. When trying to access the user object browser I receive this error: `original error: This 'admin' API is not supported by server in 'mode-server-distributed-xl'`
I don't even know, what the difference between user and admin object browser is, but user doesn't work.. do you guys know why?

**Comment by harshavardhana** [comment]
Most probably you are using an older version of MinIO - also bitnami/minio is supported by MinIO - you may need to ask bitnami for more guidance on newer releases. 

We advise that you use minio/operator instead of bitnami/minio

**Comment by JannikZed** [comment]
I'm using version `2020.12.18-debian-10-r0`- that pretty new I would say .. yes I tried to use the operator for a very long time but failed because of so many things not working and missing docs - the bitnami federated cluster works at least! 
the bitnami container is the not modified by bitnami so I don't know, if this is really the problem here.

**Comment by harshavardhana** [comment]
> I'm using version `2020.12.18-debian-10-r0`- that pretty new I would say .. yes I tried to use the operator for a very long time but failed because of so many things not working and missing docs - the bitnami federated cluster works at least!
> the bitnami container is the not modified by bitnami so I don't know, if this is really the problem here.

I can't really say @JannikZed I don't see this problem locally so I suspect something to do with the bitnami deployment.  Please test operator version v3.0.29 and let us know - I can't really really help with bitnami here, unfortunately.
