### ISSUE TITLE
User list only shows 10 at a time without indication that there may be more

### ISSUE THREAD

**Issue by kevinlul** [minio/console#544]
![image](https://user-images.githubusercontent.com/6320810/104041140-9455bd00-51a6-11eb-92ab-719cc0a56d9a.png)

The disabled scrollbar on the right suggests that these are all the users in the system, especially with the blank space at the bottom. However, if I use the search feature, I can find users not in the initial list, but the search results are again limited to 10 results.

**Comment by dvaldivia** [comment]
We probably show the scroll bar regardless of the content, what release of console are you using?

**Comment by kevinlul** [comment]
```
console version 0.4.6 - d573007
```

**Comment by bexsoft** [comment]
Hi!, This issue was addressed in https://github.com/minio/console/commit/8404baecd8d9e562b413be02fcd75c032e52c950 and it will be released in the next version of console. In the meantime you can create a new binary by running `make build` in the source folder. Thank you for reporting!
