### ISSUE TITLE
Info Policy renders a read-only copy of the policy in an area labelled "Write Policy"

### ISSUE THREAD

**Issue by kevinlul** [minio/console#545]
![image](https://user-images.githubusercontent.com/6320810/104045469-9cb0f680-51ac-11eb-8700-5311ee22341e.png)

Despite being labelled "Write Policy" like when creating a policy, this area is actually not writeable

**Comment by dvaldivia** [comment]
@kevinlul you mean it cannot be edited?

**Comment by kevinlul** [comment]
Yes
