### ISSUE TITLE
How does authentication work after #535?

### ISSUE THREAD

**Issue by kevinlul** [minio/console#569]
I just updated and noticed that in #535 the console user environment was removed and now I can no longer sign in to the Console — it comes back as 401 Unauthorized. I looked at the new README and tried adding a user called `console` with policy `consoleAdmin` as described but I still cannot sign in as any user or the newly added console. I can still sign in through the MinIO Browser and command-line client.

```
console version 0.5.0 - e7f220b
minio version RELEASE.2021-01-16T02-19-44Z
```

For some reason it seems like the `latest` tag for console on Docker Hub is still on 0.5.0 rather than the latest 0.5.1.

**Comment by harshavardhana** [comment]
> For some reason it seems like the `latest` tag for console on Docker Hub is still on 0.5.0 rather than the latest 0.5.1.

latest is now v0.5.2

**Comment by Alevsk** [comment]
> I just updated and noticed that in #535 the console user environment was removed and now I can no longer sign in to the Console — it comes back as 401 Unauthorized. I looked at the new README and tried adding a user called `console` with policy `consoleAdmin` as described but I still cannot sign in as any user or the newly added console. I can still sign in through the MinIO Browser and command-line client.
> 
> ```
> console version 0.5.0 - e7f220b
> minio version RELEASE.2021-01-16T02-19-44Z
> ```
> 
> For some reason it seems like the `latest` tag for console on Docker Hub is still on 0.5.0 rather than the latest 0.5.1.

@kevinlul is this user-credentials authentication?, do you see any errors on the console logs? what changed in https://github.com/minio/console/pull/535 was we removed the need for a privileged account in console, its not longer need it.

If your MinIO deployment is configured with a different region that the default value (`""`) you can set the region using `CONSOLE_MINIO_REGION`

**Comment by kevinlul** [comment]
Thank you! That was the problem (I changed the region). Authentication is working again.
