### ISSUE TITLE
Policies with slashes in their name cannot be deleted through Console

### ISSUE THREAD

**Issue by kevinlul** [minio/console#575]
Reproduction steps:
1. Create a policy `foo/bar`
1. Try to delete it through the console. Result:
![image](https://user-images.githubusercontent.com/6320810/105725444-f75d8880-5ef6-11eb-96bf-dde4de34fcad.png)
1. Delete through `mc admin policy remove` (success)

**Comment by dvaldivia** [comment]
this is a valid bug, thanks for the report!

**Comment by bexsoft** [comment]
Issue was fixed in #591. Thank you for reporting!
