### ISSUE TITLE
Contextual form when editing configurations

### ISSUE THREAD

**Issue by dvaldivia** [minio/console#58]
We  need a screen to list configurations
- [x] UI List Configurations

When editing a configuration on the UI we need to display a form with the proper fields for each type of configuration, each configurations has different typed fields:

- [x] region
- [x] cache
- [x] compression
- [x] etcd
- [x] identity_openid
- [x] identity_ldap
- [x] policy_opa
- [ ] kms_vault
- [ ] kms_kes
- [x] logger_webhook
- [x] audit_webhook
- [x] notify_webhook
- [x] notify_amqp
- [x] notify_kafka
- [x] notify_mqtt
- [x] notify_nats
- [x] notify_nsq
- [x] notify_mysql
- [x] notify_postgres
- [x] notify_elasticsearch
- [x] notify_redis

**Comment by bexsoft** [comment]
Created a component for csv input fields. This way the user only needs to write each element in a separated field

**Comment by bexsoft** [comment]
kms forms missing since those will be implemented for m3
