### ISSUE TITLE
UI feedback while fetching large file

### ISSUE THREAD

**Issue by hijak** [minio/console#593]
Hi

i have noticed a delay between clicking the download button in the ui to eventually downloading the file. the file size is around 200mb

this is confusing my users as there is no feedback to tell you the file is being fetched

maybe a spinner somewhere :D

**Comment by cesnietor** [comment]
Hi, latest release has a loading progress bar introduced in https://github.com/minio/console/pull/526. Is at the top of the window when you upload a file.

**Comment by hijak** [comment]
hi that appears to only be for upload. the request was for download. i am using latest version and there is no feedback
