### ISSUE TITLE
UI hide version box on non versioned buckets

### ISSUE THREAD

**Issue by hijak** [minio/console#594]
Hi

when clicking the file in the ui it will open a window with the versioning information. this appears also on non versioned buckets and produces an "error occurred" box at the top.

Can we hide the versioning box so that does not query the api that isnt active on the bucket?

**Comment by bexsoft** [comment]
Hi @hijak! Would you please provide us which version of Console are you using? Thank you

**Comment by hijak** [comment]
hey that would be version:

```
