### ISSUE TITLE
minio/console:v0.6.0 - 4 node limit can not be overriden

### ISSUE THREAD

**Issue by jhoblitt** [minio/console#610]
I am in the process of attempting to evaluate minio-operator v4.0.0/master on 3 physical node test system.  It is possible to create tenant using only 3 servers directly via a tentant CRD.  However, the `minio/console:v0.6.0` refuses to allow this and reports this error:

![image](https://user-images.githubusercontent.com/948901/108876133-21b86980-75bb-11eb-94d4-110030c9cb3b.png)

Which seems to be coming from:

https://github.com/minio/console/blob/7121dbfcea50aa3a5a1db6f7c3671b96730d8648/portal-ui/src/screens/Console/Tenants/ListTenants/AddTenant.tsx#L573

It would be incredibly useful for testing if there was a command line switch or env var I could set to disable the minimum node limit.

**Comment by cesnietor** [comment]
@jhoblitt on ui we only allow 4 servers minimum, even-though it is supported on yaml since we recommend that as a minimum for a distributed cluster.

**Comment by jhoblitt** [comment]
@cesnietor I understand... I'm asking for a flag to bypass the check so it is possible to test the console without having 4 nodes.  This would also be useful for spinning up acceptance tests in one node k8s cluster under CI.

**Comment by cesnietor** [comment]
@jhoblitt  thanks. I will bring it to discussion. But for now I would probably suggest using kind if that can help you.

**Comment by jhoblitt** [comment]
:+1:   I'm going to change the check so I can try make progress on evaluation today.  Longer term I will try to shake loose some more physical nodes or resort to running up VMs on the test nodes I've got.
