### ISSUE TITLE
Dashboard personalization

### ISSUE THREAD

**Issue by s1ckn3s5** [minio/console#629]
The dashboard is pictured like this on the main project page on github:
![pic1](https://raw.githubusercontent.com/minio/console/master/images/pic1.png)
But after following the install guide I have only allbuckets/usage/totalobjects:
![minioconsoledashboard](https://user-images.githubusercontent.com/74710308/109962720-d2c1b100-7ceb-11eb-933b-10ec2f6c93e2.png)
Is it possible to personalize it?
Thanks

**Comment by bexsoft** [comment]
Hi!

To enable full dashboard view, you will need to enable Prometheus metrics for MinIO, you can find more information [here](https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html
)

Once you have enabled it, you will need to set the following env var in your console instance:

`CONSOLE_PROMETHEUS_URL=http://localhost:9091` where `http://localhost:9091` is the server & port where Prometheus is running

if everything is configured correctly, you will start more metrics in dashboard.

Thank you for your message!

**Comment by s1ckn3s5** [comment]
I already had a prometheus configured, which I was using with grafana, and pointing at it effectively changed the dashboard, but I think it's pulling just the prometheus metrics and not the minio-job, is this configurable somewhere?
![minioconsoledashboardprometheus](https://user-images.githubusercontent.com/74710308/110046578-94101300-7d4c-11eb-8077-ab328fd878b2.png)
(btw it is a cluster, so I had to put this in prometheus.yml to make it work "metrics_path: '/minio/v2/metrics/cluster'" maybe there's some way to tell the dashboard to pull cluster metrics?)
thanks

**Comment by dvaldivia** [comment]
@s1ckn3s5 some metrics are collected, such as uptime and total goroutines for example, seems like other metrics have not been collected, did it update after some time?

**Comment by s1ckn3s5** [comment]
> @s1ckn3s5 some metrics are collected, such as uptime and total goroutines for example, seems like other metrics have not been collected, did it update after some time?

yeah, I suppose those metrics are from prometheus itself, I checked and that is the uptime of prometheus which I've just restarted to check it was working, the cluster, or even the single minio node, should have an uptime of days

**Comment by norfair00** [comment]
No data on dashboard

My console container logs: https://bin.norfair.stream/demofekoyi.pl
Prometheus container is in database ip: 172.19.0.201

**Comment by harshavardhana** [comment]
> (btw it is a cluster, so I had to put this in prometheus.yml to make it work "metrics_path: '/minio/v2/metrics/cluster'" maybe there's some way to tell the dashboard to pull cluster metrics?)
> thanks

Using `/minio/v2/metrics` is not supported yet with console use the older one at `/minio/prometheus/metrics` use this instead.

**Comment by harshavardhana** [comment]
Refer to issue https://github.com/minio/console/issues/588 for the upcoming work on the console to use the newer Prometheus endpoint.
