### ISSUE TITLE
Adding of 2 lambda notifications of the same type

### ISSUE THREAD

**Issue by Lumiond** [minio/console#666]
Hello.
We need to use namespace and access notifications for elasticsearch. When we have tried to add the second target through Console - it's just rewrite the first target (also, it has "elasticsearch:_" name). Through mc we can add as many target as we want.
Also after target adding we can not view info about target in Console.
I think that adding multiple notifications targets through Console is very useful. And viewer of current targets settings too.

**Comment by dvaldivia** [comment]
@Lumiond we'll look into this, you are basically trying to add multiple notification targets that are identical?

**Comment by Lumiond** [comment]
Hi! I have tried to add namespace notification (for content type analyze) and access notification (just access logs) to the same elasticsearch. Everything is fine in mc, but doesn't work in Console, at least it have not worked in March. We use mc nowadays because it gets us full functionality.
