### ISSUE TITLE
Console displaying minimal interface for cluster but full interface for single node

### ISSUE THREAD

**Issue by tkg61** [minio/console#676]
Using Console version 0.6.6 - 14fe7c1 and Minio version 2021-03-26T00:00:41Z

On my single node test instance i am able to see the full console window

![image](https://user-images.githubusercontent.com/3945114/113320232-47ced900-92e0-11eb-8754-277ca00320e1.png)

but on my 4 node cluster (same versions) i can only see a small subset of the items:

![image](https://user-images.githubusercontent.com/3945114/113320409-7a78d180-92e0-11eb-9648-2bf49d3dab84.png)

I am using the same consoleAdmin policy for both instances that came with Minio: 

![image](https://user-images.githubusercontent.com/3945114/113320557-9e3c1780-92e0-11eb-8571-d328af39a97c.png)

When I try to directly go to the /dashboard page on my cluster it just redirects me back to the original page with no errors in the console log.

Unsure as to what is going on or what the difference is. Would appreciate some clarity. Happy to provide any more info

**Comment by tkg61** [comment]
I have also tried adding the prometheus stats to the page on each and on the single node instance it adds it (doesn't populate due to #629 and #588)  but on the clustered instance it does not. 

Does it matter that i am running console locally on the single instance and remote on the cluster?

**Comment by tkg61** [comment]
- Tried running the console on one of the cluster nodes, didn't get any different, still the minimal interface. 

- Tried pointing console at each of the nodes and that didn't help either 

- Tried running console versions (6.0-6.6), all of them have this issue.

**Comment by dvaldivia** [comment]
@tkg61 are you assigning the policy to the user?

**Comment by dvaldivia** [comment]
I don't think single node should behave differently

**Comment by tkg61** [comment]
> @tkg61 are you assigning the policy to the user?

Yes, using the same policy on the same user. I am using LDAP auth which i think might be part of the issue here but still doesn't explain why it works on the single node but not the cluster. 

I have made a little bit of progress though after thinking about your comment more of the user aspect... 


On my cluster instance i attempted to re-apply the consoleAdmin policy to my user DN and it applied successfully but nothing changed in the view of the console app. Command used was: 

`mc admin policy set myminio consoleAdmin user="CN=Firstname Middle. Lastname,OU=Users,DC=local,DC=com"` (note spaces)

Now i tried another test account and applied the same policy: 

`mc admin policy set myminio consoleAdmin user=CN=Test_account_temp,OU=Users,DC=local,DC=com` (note no spaces)

This time, the test account worked for some reason and i saw the full dashboard. Same policy, same LDAP, just a different username. i also re-applied the same command but with quotes around the user string and it still worked.

If i try to run a ` mc admin user info myminio user=...` on either of the accounts i don't get back anything and it says that neither user exists (this is an MC issue not an console one but it prohibits further diagnostics)

At this point i am unsure how to proceed since it seems as if users can't have spaces in their names. Happy to test further if needed.

**Comment by tkg61** [comment]
I also discovered that `mc admin user info myminio user=CN=...` is not the correct syntax. Instead it should just be the first part of the DN without the user= so: 
`mc admin user info myminio test_account_temp` 

but 

`mc admin user info myminio "Firstname Middle. Lastname"` does not work and returns that the user can't be found. I can make a ticket in the other repo for that

**Comment by tkg61** [comment]
After doing a little more investigating i figured out  that minio needed a reboot before my new permissions for our users would take effect. Upon rebooting i was able to have my user see the full interface. The minimal interface is shown when a user does NOT have dashboard (admin:...) permissions but has bucket permissions.

**Comment by tkg61** [comment]
> I also discovered that `mc admin user info myminio user=CN=...` is not the correct syntax. Instead it should just be the first part of the DN without the user= so:
> `mc admin user info myminio test_account_temp`
> 
> but
> 
> `mc admin user info myminio "Firstname Middle. Lastname"` does not work and returns that the user can't be found. I can make a ticket in the other repo for that
> 
> But this only works on my single node, not the cluster mc (same version) but i need to probably do some more digging as to why this is and if there is another issue at play

I have figured out that my comment above was not completely flushed out. 

When the user info command is run and there is no policy set on an LDAP user (full DN: "CN=test_account_temp,OU=users,DC=local,DC=com"), it will return as if the user can not be found. 

It is possible to set a policy (when in LDAP mode) on a username that is matching of the beginning of a full DN (e.g. "test_account_temp") but that policy will not work and while it will be possible to do a "user info" command on that user it doesn't mean anything. 
This applies to both users/full-DNs without spaces in their name and users/full-DNs with spaces. I was incorrect in thinking spaces were an issue (it was an issue of not using the full DN).

The requirement to *not* have "user=FULL-DN..." in the user info command is still valid but it is a requirement when setting and unsetting permissions.

Hope this helps someone else out

**Comment by Alevsk** [comment]
Many LDAP integration issues has been fixed on the latest versions for MinIO/Console, please test and re open the issue if necessary
