### ISSUE TITLE
Unsupported action AssumeRole error

### ISSUE THREAD

**Issue by fostermi** [minio/console#677]
I'm trying to deploy minio Console in a Docker container to connect to a minio instnace that is a gateway-nas. The gateway is configured to use etcd and has been set up to use Keycloak for user authentication. I've created a local user and admin policy per the README (technically its just an ACCESS_KEY called "console" and a random SECRET_KEY) however, the "console" user cannot login to the Console UI and the following error appears in the gateway-nas trace log:

```
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>Unsupported action AssumeRole</Message></Error><RequestId>16719909286EFF6B</RequestId></ErrorResponse>
```

I'm not sure why its trying to do `Action=AssumeRole&DurationSeconds=3600&Version=2011-06-15` since this would be a local login.

Since there is nothing in the README on how to run the Docker container version of Console, this is my command:

```
docker run \
  -p 9090:9090 \
  -d \
  --name minio-console \
  -e CONSOLE_PBKDF_PASSPHRASE=SECRET \
  -e CONSOLE_PBKDF_SALT=SECRET \
  -e CONSOLE_MINIO_SERVER=http://minio.example.com \
  minio/console server
```

I have no idea what the PBKDF vars are used for, what they should be or if the gateway-nas needs them, so I'm just copying/pasting what's in the README.

The default minio UI works just fine with this "console" user and works fine with Keycloak users after much trial and error. 

Supposedly the console is supposed to work with Open ID per https://github.com/minio/console/issues/54, but there isn't any documentation on how to configure this and it should work with local "users" (i.e. ACCESS_KEYS).

Is there some other missed configuration that needs to be done (i.e. ENV vars, etc) to get this to work?

**Comment by harshavardhana** [comment]
> I'm trying to deploy minio Console in a Docker container to connect to a minio instnace that is a gateway-nas. The gateway is configured to use etcd and has been set up to use Keycloak for user authentication. I've created a local user and admin policy per the README (technically its just an ACCESS_KEY called "console" and a random SECRET_KEY) however, the "console" user cannot login to the Console UI and the following error appears in the gateway-nas trace log:

MinIO Console won't work with NAS gateway if you do not have etcd configured in MinIO NAS instance.

**Comment by fostermi** [comment]
As I mentioned above I am using etcd. Additionally, I thought the console was to be the new preferred UI (although that is not documented well)? Why would you not support managing minio when configured as a gateway-nas if gateway-nas is a "supported" product/configuration? Should we not be using a gateway-nas? Some better documentation, disclaimers, or use cases would go a long way here.

**Comment by fostermi** [comment]
I just switched from using minio as a gateway-nas to a server instance and I still get the same error message:
```
Unsupported action AssumeRole
```

**Comment by harshavardhana** [comment]
> ```
> <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>Unsupported action AssumeRole</Message></Error><RequestId>16719909286EFF6B</RequestId></ErrorResponse>
> ```

**Comment by harshavardhana** [comment]
Let me take a look - this looks strange @fostermi

**Comment by harshavardhana** [comment]
This perhaps has been long fixed, please upgrade to latest MinIO.

**Comment by pschichtel** [comment]
@harshavardhana  I've just observed this, when switching my minio instance from http to https. I forgot to fix the `MINIO_SERVER_URL` env var to use https, this caused this exact issue when logging in. Sadly nothing was logged in any pod.
