### ISSUE TITLE
Display users and groups IAM Policies are applied to

### ISSUE THREAD

**Issue by tkg61** [minio/console#694]
Similar to https://github.com/minio/mc/issues/3691 

When viewing the IAM policies and click on each one, have a section to view which users and groups that policies are applied to.

**Comment by dvaldivia** [comment]
This makes sense, we'll improve the policy details screen with this information

**Comment by tkg61** [comment]
@dvaldivia 

If this can work for LDAP users as well that would be great!

**Comment by tkg61** [comment]
@dvaldivia i see that in the latest update we can now see ldap users and which policies are applied to them, this is great! if we can get ldap groups next that would be awesome!

**Comment by dvaldivia** [comment]
@tkg61 I think we we planning to show that as well, can you confirm @Alevsk

**Comment by dvaldivia** [comment]
Implement
