### ISSUE TITLE
Add capability to apply policies to users and groups

### ISSUE THREAD

**Issue by tkg61** [minio/console#695]
Currently policies can be created inside of Console but the application of them to groups and users still has to done via the mc cli negating the usefulness of creating new policies in the web browser.

**Comment by dvaldivia** [comment]
@tkg61 you can assign multiple policies to a user or group with the bookmark icon we have on the users screen

<img width="977" alt="Screen Shot 2021-05-03 at 8 46 09 AM" src="https://user-images.githubusercontent.com/18384552/116899135-0c2f7380-abec-11eb-9bd7-8abb2da63545.png">


Perhaps we need to improve the UX on this one.

@bexsoft @belvid  what do you think making it like a bulk action as well? or would it be too crowded up there?

**Comment by tkg61** [comment]
David, 

Thanks for the reply. i should have stated i was looking at this from an LDAP perspective, not internal users

**Comment by dvaldivia** [comment]
@tkg61 that makes it more clear, we are working on something for that use case, @Alevsk any updates on that?

**Comment by jameswu2** [comment]
This is the same behavior I'm observing as well and we're very interested in being able to set LDAP group/user bindings to policies via the Console UI as well. Also based on my conversations with @ravindk89 over Slack, there may be a discrepancy in the documentation.

Step 3 of the [LDAP auth flow docs](https://docs.min.io/minio/baremetal/security/ad-ldap-external-identity-management/external-authentication-with-ad-ldap-identity-provider.html#authentication-and-authorization-flow) states:

> MinIO checks for any policy whose name matches a returned group DN and assigns that policy to the authenticated user

But it doesn't seem like I should actually name a custom policy something like `CN=MyGroup,OU=MyGroupOU,DC=MyCompany,DC=com` if I want it to bind that policy to one of my groups. Instead the [ldap documentation ](https://github.com/minio/minio/blob/master/docs/sts/ldap.md#managing-usergroup-access-policy) is accurate - currently the only way I've been able to successfully bind LDAP permissions to any policy is by using `mc` and there doesn't seem to be a way to do it via the console.
