### ISSUE TITLE
Getting x509 certificate error after integrating with idp

### ISSUE THREAD

**Issue by ssharma2089** [minio/console#707]
Hi All,
I have deployed minIO on 2 nodes on a K3S cluster with below steps
1. Created certificate by using the link " https://github.com/minio/operator/blob/master/docs/tls.md#using-cert-manager ". I am using cert-manager for issuing certificate
2. Deployed minIO console in minio namespace by using both the link "https://github.com/minio/operator/blob/master/examples/tenant-with-external-idp.yaml"
"https://github.com/minio/operator/blob/master/examples/tenant-with-custom-ca-certs.yaml"
Changed requestAutoCert from true to false and added externalCertSecret.

Below are the deployment status and logs

[root@mwsdev01 dev1]# kubectl get pods -n minio
NAME                             READY   STATUS    RESTARTS   AGE
minio-ss-0-0                     1/1     Running   0          2m28s
minio-ss-0-1                     1/1     Running   0          2m28s
minio-console-67b474f446-gvp54   1/1     Running   0          87s

Configured IDP with console and enterning dex credentials, its redirectiring to welcome screen. Getting below error while checking logs
**Error:
error.go:46: original error: invalid Login
debugging error: Post "https://login.mwsdev.tri.int/dex/token": x509: certificate signed by unknown authority**

**Comment by dvaldivia** [comment]
sounds like the certificate offered by `login.mwsdev.ti.int` is not trusted by the Console server itself, is that using a TLS certificate that was issued inside the kubernetes cluster?

**Comment by ssharma2089** [comment]
@dvaldivia  It is a cert-manager issued cert which has CA that can be successfully validated by intranet nodes and clients/browsers

**Comment by itmwiw** [comment]
Hello,
I have the a similar problem.
I've tried 2 different options:

1. 
   adding keycloak CA as mentionned:
```
    spec:
      externalCaCertSecret:
      - name: yourCertificateSecretHere
     ...
     ...
    console:
      externalCaCertSecret:
      - name: yourCertificateSecretHere
```
    to confirm that the CA is the correct one, i've added it to chrome trusted CAs and checked that keycloak became green
    I've also checked the /tmp/certs/CAs/ folder inside the pods: the ca is here

2.
    I've tried a second option: sign the tenant, console and keycloak with the same CA (both using cert-manager). nothing changed. same x509: certificate signed by unknown authority

Can you help me please?
PS: The tenants works fine with keycloak. this problem occurs only with the console.

**Comment by Alevsk** [comment]
Is this still a problem? there are many fixes related to ca certificates that were fixed on newest releases, please test and re open if necessary
