### ISSUE TITLE
error validating user identity against idp

### ISSUE THREAD

**Issue by ddzobov** [minio/console#712]
Hello!
minio console deployed to 3 nodes and configured IDP with Keycloak

Sometimes i receive this error in logs:
```
Apr 28 13:33:39 s3-app.local minio-console[22691]: 2021/04/28 13:33:39 user_login.go:211: error validating user identity against idp: an error occurred, please try again
Apr 28 13:33:39 s3-app.local  minio-console[22691]: 2021/04/28 13:33:39 error.go:46: original error: invalid Login
Apr 28 13:33:39 s3-app.local  minio-console[22691]: 2021/04/28 13:33:39 error.go:134: debugging error: invalid Login
```

But when i leave just 1 node, all works perfectly (but sometimes at first login i can catch this error).

Two questions:
1) can be minio/console be deployed more than on 1 instance?
2) how can i prevent this error?

**Comment by dvaldivia** [comment]
@ddzobov this sounds like you are not setting up the pbkdf variables, you need to set these with the same value on all 3 nodes, this way they can decrypt each other sessions

```
CONSOLE_PBKDF_SALT
CONSOLE_PBKDF_PASSPHRASE
```

**Comment by harshavardhana** [comment]
> @ddzobov this sounds like you are not setting up the pbkdf variables, you need to set these with the same value on all 3 nodes, this way they can decrypt each other sessions
> 
> ```
> CONSOLE_PBKDF_SALT=JKHASDS
> CONSOLE_PBKDF_PASSPHRASE=ASDLASDASDKJASD
> ```

Please let us know if this doesn't work with this setting either. Closing until then.
