### ISSUE TITLE
Validate total space available

### ISSUE THREAD

**Issue by idealtech-i3dlabs** [minio/console#713]
Hi,

I am trying to use the console to see what the total available space is for a given cluster to validate the space that was setup at cluster creation. Couldn't find anything in the docs.

[How] can this be done with the console? Alternatively, with mc ?

**Comment by dvaldivia** [comment]
When you setup the console for a MinIO, we have a small a small widget that will show the usage, however I don't think we have anything to estimate free space in the console, which would be a calculation of `totalSpace - usage`

**Comment by idealtech-i3dlabs** [comment]
Yes, I saw the widget for usage, but I'd like to make sure MinIO is "seeing" the total available space.
I think this would be useful to have in general to validate a given deployment

**Comment by dvaldivia** [comment]
with `mc` you can see what MinIO see, mainly the size of the disks

`mc admin info ALIAS --json` will show you the information you seek

**Comment by tkg61** [comment]
If you use Prometheus this is also an available metric (minio_cluster_capacity_usable_free_bytes) if you need to query it regularly and view in grafana once the dashboard is fixed

**Comment by idealtech-i3dlabs** [comment]
@dvaldivia are you sure ?

Which metric am I looking for ? All I see is totalSpace as being values of my individual volumes. Maybe I'm missing one but I don't see a "totalSpace" that is bigger than (~8TB)
"totalspace":7581742833664

I would expect something in the range of 100+ TB ?

**Comment by idealtech-i3dlabs** [comment]
Any chance to get an update before closing this? It is not resolved imho.
Or is Prometheus the only way to get that metric?

**Comment by dvaldivia** [comment]
I think prometheus is the only mechanism available at the moment, what we did in operator was calling the prometheus endpoint and reading these values

**Comment by harshavardhana** [comment]
This has been overhauled and re-implemented. Please upgrade to latest release.

**Comment by srstsavage** [comment]
This worked for me (minio 20230120020544.0.0, mcli 20230111031416.0.0)

```
mcli admin prometheus metrics TARGET | grep minio_cluster_capacity
```
