### ISSUE TITLE
OAuth2 - Not decoded code param in LoginCallback 

### ISSUE THREAD

**Issue by jrpedrianes** [minio/console#720]
If we are trying to use Google as IDP, Google returns a code that contains a slash "/" (ie: code=4/0BYa-adfjakldfkdADSfasdfASDF....), but this is not decoded here:

https://github.com/minio/console/blob/0b0cb785b5e040f3fb9c0edfbf5d54f82a0f485b/portal-ui/src/screens/LoginPage/LoginCallback.tsx#L26

So when you call "/api/v1/login/oauth2/auth" the code sent is no correct because the code is not the correct one, in this case, you sent to the API "44%2F0BYa-adfjakldfkdADSfasdfASDF...." instead of "4/0BYa-adfjakldfkdADSfasdfASDF...."

I think that you need to call "decodeURIComponent" before to send the code to the API

**Comment by dvaldivia** [comment]
Can you try to reproduce with the latest? we do `decodeURIComponent` almost everywhere now

**Comment by dvaldivia** [comment]
aaah, I see the problem, its still there, we will fix it

**Comment by Alevsk** [comment]
This PR fixes the encoding/decoding issue https://github.com/minio/console/pull/1217

**Comment by Alevsk** [comment]
@jrpedrianes can you test using the above branch/PR ^

**Comment by Alevsk** [comment]
Tested from our side, please re open if have any more issues

**Comment by jrpedrianes** [comment]
Ok, maybe the next week have a chance to test it. Sorry but this week is impossible
