### ISSUE TITLE
Change access policy of bucket through MinIO console

### ISSUE THREAD

**Issue by xi1149-ashurana** [minio/console#722]
Hi All,

I am trying to set a bucket policy to public through the MinIO console but cannot see the option available there.

This can be done using the MinIO client but is there any way to do it using GUI. 

Please help!

**Comment by bexsoft** [comment]
Hi @xi1149-ashurana!,

There is an option inside bucket details to enable this feature:

<img width="975" alt="Screen Shot 2021-07-29 at 18 44 08" src="https://user-images.githubusercontent.com/33497058/127579152-5331626d-4e70-4548-86ad-0b9c94edbfa7.png">
<img width="461" alt="Screen Shot 2021-07-29 at 18 43 47" src="https://user-images.githubusercontent.com/33497058/127579154-6977d3a2-b697-43b8-a84d-35b7b981c814.png">

Please let us know if you still have issues with this, or if you have any other questions!
