### ISSUE TITLE
Insufficient error handling in user interface

### ISSUE THREAD

**Issue by lkiesow** [minio/console#748]
Some actions cause the user interface to be in a weird state, making it hard for users to understand what's going on. For example, the following screencap shows a user trying to create a bucket which results in an error, but leaves the user in the “create bucket” screen. Assuming that the failure might have something to do with the settings (it did), you would try again. But that will always fail since the first operation did actually create the bucket. It's just missing a feature and (most confusing) is not displayed in the list of buckets:

https://user-images.githubusercontent.com/1008395/118416974-6d5a4b00-b6b2-11eb-90ac-6b376310ed63.mp4

- console shouldn't show options which are not yet implemented
- If part of the operation fails, a rollback would be preferable instead of the operation partly succeeding
- The user interface should represent the server state after such an operation

**Comment by dvaldivia** [comment]
We need to add clearer errors from the server to the client
