### ISSUE TITLE
Console fails to handle some characters in access key

### ISSUE THREAD

**Issue by lkiesow** [minio/console#752]
Opening console and creating a user with an access key like `<b>xy</b>` will cause the user interface to misbehave, and you cannot access the user details:

https://user-images.githubusercontent.com/1008395/118556469-35134500-b764-11eb-9487-8d79d587f619.mp4

**Comment by dvaldivia** [comment]
Thanks for the report! Looks like we need to URL the access key for the routing not to break!

**Comment by lkiesow** [comment]
Something similar happens for the groups:

![Screenshot from 2021-05-17 23-06-09](https://user-images.githubusercontent.com/1008395/118556882-b5d24100-b764-11eb-8c38-f3a502247edb.png)

**Comment by dvaldivia** [comment]
seems like the routing for both our restful APIs and on react router breaks with this, I'm testing encoding the values and it's not working either
