### ISSUE TITLE
"An error occurred, please try again" after integrating with keycloak

### ISSUE THREAD

**Issue by irudayambics** [minio/console#805]
**Problem statement**
Unable to view "Login with SSO" button after setting up Keycloak as IDP with MinIO console. The progress bar will keep loading. Below is the error screenshot.

<img width="720" alt="eror" src="https://user-images.githubusercontent.com/3430078/121501807-24c45200-ca12-11eb-9f50-9fe21caebcc5.PNG">

**Current Context**
_Below are the MinIO server details._
MinIO Server Version: 2021-05-22T02:34:39Z
Installation method: Installed using Linux binaries 
SSL type: Custom CA
Certs directory: /etc/minio/certs
CA cert directory: /etc/minio/certs/CAs

_Below are MinIO Console details:_
MinIO Console Version: 0.7.3 (I tested with 0.7.4 as well but the same error)
Installation method: Installed using Linux binaries 
SSL type: Custom CA
Certs directory: ~/.console/certs
CA cert directory: ~/.console/certs/CAs
Keycloak and MinIO servers` CA root certs have been copied to ~/.console/certs/CAs directory.

_IDP environment variables as below_
<img width="491" alt="idp details" src="https://user-images.githubusercontent.com/3430078/121502460-c6e43a00-ca12-11eb-8bf5-f2210683e21e.PNG">

I can't see any specific error in MinIO console backed.

 Any solution for this?

**Comment by Alevsk** [comment]
Please share here the logs for console pods

**Comment by irudayambics** [comment]
Below is the log from console backend.
<img width="591" alt="console-error" src="https://user-images.githubusercontent.com/3430078/122142538-4befa900-ce82-11eb-8ec6-5990d298f989.PNG">

**Comment by harshavardhana** [comment]
You need to trust your IDP in console, grab the public cert for your keycloak and drop it at `~/.console/certs/CAs` folder for console to trust your IDP.
