### ISSUE TITLE
unable to login with users created with root account

### ISSUE THREAD

**Issue by MorphBonehunter** [minio/console#823]
After mergin https://github.com/minio/minio/pull/12511 i can create new users with the root account (the `minioadmin:minioadmin` one...if you don't change it).
But afterwards i'm unable to login with this created user in console BUT i can login with the user on the minio integrated s3 browser.

minio trace only shows:
`2021-06-18T06:37:34:000 [200 OK] sts.AssumeRole <domain>/ 192.168.210.3     683µs       ↑ 239 B ↓ 977 B`

minio console logs shows:
```
2021-06-18 08:37:34.907626 I | 2021/06/18 08:37:34 error.go:52: user_login.go:50: original error: invalid Login
2021-06-18 08:37:34.907652 I | 2021/06/18 08:37:34 error.go:154: debugging error: The Access Key Id you provided does not exist in our records.
```
The user exists:
```
mc admin user list uv
enabled    testuser
```

minio version: RELEASE.2021-06-17T00-10-46Z
minio console version: v0.7.4

works:
![Screenshot 2021-06-18 083249](https://user-images.githubusercontent.com/4989388/122517099-e8938180-d00f-11eb-9599-becb94a89574.png)

doesn't work:
![Screenshot 2021-06-18 083319](https://user-images.githubusercontent.com/4989388/122517142-f6490700-d00f-11eb-92c8-8556966e5c71.png)

**Comment by harshavardhana** [comment]
Just adding users they do not gain any access - by default all users have access denied, you need to assign policies for such users @MorphBonehunter

**Comment by harshavardhana** [comment]
If you want service accounts then you generate service accounts not create more users.

**Comment by MorphBonehunter** [comment]
@harshavardhana yes, you are right i missed this indeed. 🤦‍♂️ 
But what i wonder is why the login works in the s3 browser in minio.
Should this not also deny the access?

**Comment by harshavardhana** [comment]
> @harshavardhana yes, you are right i missed this indeed. 🤦‍♂️ 
> But what i wonder is why the login works in the s3 browser in minio.
> Should this not also deny the access?

It doesn't work it just shows the UI since you don't have any content.

It simply would have failed.

**Comment by MorphBonehunter** [comment]
So if this is expected than sorry for the noise.
