### ISSUE TITLE
why my minio/console don't have the charts?And my dashboard don't have the summary tab

### ISSUE THREAD

**Issue by gaoyangcaiji** [minio/console#845]
![image](https://user-images.githubusercontent.com/26948255/124075653-c3732a00-da77-11eb-9939-c0ed8c58a29e.png)

thanks for your replay

**Comment by dvaldivia** [comment]
@gaoyangcaiji you need to configure Prometheus, first to collect metrics from MinIO and then passing the URL to console

**Comment by gaoyangcaiji** [comment]
thanks for your replay,i will try it!

**Comment by gaoyangcaiji** [comment]
> @gaoyangcaiji you need to configure Prometheus, first to collect metrics from MinIO and then passing the URL to console

thanks for your replay,i will try it!

**Comment by gaoyangcaiji** [comment]
@dvaldivia thanks for your replay,i will try it!

**Comment by harshavardhana** [comment]
@gaoyangcaiji set `CONSOLE_PROMETHEUS_URL` to point to Prometheus setup.
