### ISSUE TITLE
An error is reported when Minio adds buckets

### ISSUE THREAD

**Issue by AbnerMai** [minio/console#855]
An error is reported when Minio adds buckets to set Features and Versioning and Quota
![image](https://user-images.githubusercontent.com/26241803/124905709-e45bf200-e018-11eb-85d5-9dcba6aa363a.png)
![image](https://user-images.githubusercontent.com/26241803/124905732-eaea6980-e018-11eb-8fc4-29c07f669077.png)

**Comment by 0x13ens** [comment]
Same issues, i have 6 buckets created and can't even view them.

**Comment by harshavardhana** [comment]
> Same issues, i have 6 buckets created and can't even view them.

This is because of a different bug in MinIO server fixed here https://github.com/minio/minio/pull/12681

**Comment by harshavardhana** [comment]
> An error is reported when Minio adds buckets to set Features and Versioning and Quota

Versioning and Quota are not allowed in single drive mode - we need to fix console to make sure these are not shown or report appropriate errors instead of just vague errors.

**Comment by bexsoft** [comment]
Fixed in https://github.com/minio/console/pull/880
