### ISSUE TITLE
Allow users to change their password

### ISSUE THREAD

**Issue by markovendelin** [minio/console#857]
Earlier WebUI of MinIO allowed users to change their password. As pointed out by @harshavardhana, Console restricts "Change password" only to users with `admin:CreateUser` permissions which is interpretation of Console of users privileges. As older WebUI is phased out, it is currently impossible for users to change passwords without admin privileges using available tools. At the same time, permission to change user password for her/himself is implicit. Unfortunately, it is not reflected currently in Console.

Please allow users to change their passwords to replicate older functionality of WebUI in Console.

Issue earlier discussed in https://github.com/minio/minio/discussions/12649

**Comment by harshavardhana** [comment]
Yes we need to fix the UI portion here.

**Comment by markovendelin** [comment]
Thank you very much for a quick fix of this and other issues that we encountered!
