### ISSUE TITLE
Adding Internationalization Support

### ISSUE THREAD

**Issue by jumana-s** [minio/console#860]
Our team is working on internationalization for MinIO, with the purpose of supporting both English and French.  We have started the work on implementing i18n in MinIO Console.  @wg102 has done a previous [PR](https://github.com/minio/minio/pull/12063) for adding i18n and localization support for MinIO before it was closed due to the browser UI code freeze.

We are using [react-i18next](https://react.i18next.com), an internationalization framework for React.

Is there interest in this feature? 

The initial scope would be the UI components.

**Comment by harshavardhana** [comment]
@jumana-s we are okay with the support but is there a way to automate this? so that it can be done as part of the assets? automatically? 

how does a user choose one language over the other?

**Comment by jumana-s** [comment]
We are using a package, [i18n-parser](https://github.com/i18next/i18next-parser), that parses the code and maintains the translation catalog. It automatically adds missing keys to the translation files, and gives them a default value such as "Not_Translated".  At the moment in portal-ui/package.json a command has been added to the scripts to extract those keys.


As for choosing a language, right now the code is setup so that it uses the browser language, and if translation doesn't exist for the locale then it defaults to English.  https://github.com/i18next/i18next-browser-languageDetector

**Comment by jumana-s** [comment]
@harshavardhana I have a couple of questions/comments regarding upstreaming and error handling.

1. Work for i18n in portal-ui is nearly complete. I would like to split the work in MinIO Console into two PRs. The first for the work done to portal-ui and then the work for error handling. This way most of the UI is internationalized. 
2. Are there any plans for changing error handling moving forward?  Is the current plan for new error handling complete?
3. Depending on if things change I am considering two ways to implement i18n for error messages
   - Handling them in the browser by adding a key property to returned errors.
   - Or, implementing i18n in the backend using [go-i18n](https://github.com/nicksnyder/go-i18n).
4. I’ve noticed that some errors displayed in the UI seem to come from other repos, for now the focus will be on errors in MinIO Console.

**Comment by bexsoft** [comment]
Hi @jumana-s 

Answering your questions:

1. Awesome! Do you need that we do any change on our side? 
2/3. Those changes are done and pushed to master branch. basically we added two variables to errors, one with a simplified error message and another one with a detailed error message (Message from external entities). We were thinking for backend to work, maybe to introduce some numeric errors and handling these translations in the frontend in case selected language is different from english. This can be added as an extra prop to error message interface

Thank you very much!

**Comment by PC-Chiu** [comment]
Half a year has passed, Is there any progress?

**Comment by bexsoft** [comment]
We will be handling this in an upcoming version of Console / MinIO. Closing this issue and creating a new one

**Comment by lvyueyang** [comment]
Hello, I have made a new script that can automatically add internationalization to this project (about 90% of the code can be processed), you can see it here https://github.com/minio/console/issues/2438

@PC-Chiu @bexsoft

**Comment by mosynaq** [comment]
+1

**Comment by MrPoint1400** [comment]
+1
