### ISSUE TITLE
This 'admin' API is not supported by server in 'mode-server-fs'

### ISSUE THREAD

**Issue by capriciousduck** [minio/console#863]
I am getting the following error after bucket creation. Please look into it. This is the error.

This 'admin' API is not supported by server in 'mode-server-fs'

**Comment by harshavardhana** [comment]
This is part of an overhaul needed to handle certain missing APIs in single drive mode and gateway needed.

**Comment by hmwdt** [comment]
me too , same problem！！

**Comment by harshavardhana** [comment]
Closing as duplicate of #723
