### ISSUE TITLE
The sharing function of the latest program cannot be used

### ISSUE THREAD

**Issue by xyzzen** [minio/console#866]
I use it on windows, stand-alone version, mainly used to share my local files to colleagues to download;
I just downloaded the latest version and found that I can’t share it;
Is the sharing function not yet made, or is there a bug?

**Comment by harshavardhana** [comment]
Moved this to relevant project @xyzzen

**Comment by hmwdt** [comment]
me too ,can not share ,is it a bug ?

**Comment by djerfy** [comment]
Duplicate with issue #723
