### ISSUE TITLE
Console browser fails to display items for user with variable in policy

### ISSUE THREAD

**Issue by craigyk** [minio/console#868]
I figured I'd file this bug against the console, since the following seems to work from other S3 clients like rclone and CloudMounter, but not the browser in the console.  

I tried creating a single policy that uses a variable to provide users with access to a bucket under their username:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}/*"
            ]
        }
    ]
}
```

In the console browser the above gives a "There are no rewind objects yet" error when listing a bucket like `foo` if user `foo` is logged in.  Accessing the exact same resource works when the policy does not use the ${was:username} variable vs. a hardcoded access to the bucket `foo`.

**Comment by harshavardhana** [comment]
This has been fixed in MinIO embedded console @craigyk - we haven't made a release yet for console after these fixes. 

Fixed by #861
