### ISSUE TITLE
Prometheus basic auth support

### ISSUE THREAD

**Issue by SteeveRan** [minio/console#870]
For now the MinIO Console supports visualizing collected metrics from Prometheus. But if we configure basic auth on prometheus MinIO Console can't get metrics:

```
Unexpected error from prometheus https://prom.example.com/api/v1/query_range?query=minio_heal_time_last_activity_nano_seconds%7Bjob%3D%22minio-job%22%7D&start=1626260773&end=1626261673&step=60, Unauthorized (401 Unauthorized)
```
So, we need a way to configure Authorization headers

**Comment by harshavardhana** [comment]
@SteeveRan what is your prometheus URL look like when using basic auth?

**Comment by SteeveRan** [comment]
Oh, I understand what you mean. But it's not secure. For example [link](https://developer.mozilla.org/ru/docs/Web/HTTP/Authentication#access_using_credentials_in_the_url)

Therefore, it would be better to pass the credentials through the headers.

**Comment by harshavardhana** [comment]
If you are willing to use Basic Auth - I don't see any security issue here..

**Comment by SteeveRan** [comment]
I have investigated this problem in more detail and I have to agree that using TLS + Basic auth in the URL provides a sufficient level of security in the Minio Console.
