### ISSUE TITLE
Console Share File signed URLs

### ISSUE THREAD

**Issue by sniffingsugar** [minio/console#872]
Hi everyone,

I think there is an option missing that you can set a custom domain url for the minio console. 
If I share a File through the console, it will automatically go to my IP and not through the domain (proxy). 
![Image of the Feature](https://i.imgur.com/WcfMDBw.png)

**Comment by harshavardhana** [comment]
are you running console standalone or `minio` embedded?

**Comment by dvaldivia** [comment]
we have that in the pipeline, a mechanism to seed the domain that is being used for MinIO, are you running this console on kubernetes?

**Comment by sniffingsugar** [comment]
embedded swarm cluster / I guess i am in the wrong repo right?

**Comment by dvaldivia** [comment]
@sniffingsugar and does your MinIO have a public domain? are you accessing it via it?

**Comment by sniffingsugar** [comment]
@dvaldivia yes it has one domain for Minio and one for the console.

**Comment by harshavardhana** [comment]
> embedded swarm cluster / I guess i am in the wrong repo right?

CONSOLE_MINIO_SERVER sets the correct value if you used console standalone if you did not use that then embedded console thinks that MinIO to be available locally so generates presigned URLs based on the internal IP.

This needs to be fixed.

**Comment by sniffingsugar** [comment]
@harshavardhana 
So there is no workaround about this?
If I want that feature to be here I must go standalone?

**Comment by harshavardhana** [comment]
> @harshavardhana
> So there is no workaround about this?
No workaround

> If I want that feature to be here I must go standalone?
yes

**Comment by harshavardhana** [comment]
As a workaround use `mc share download` @sniffingsugar

**Comment by djerfy** [comment]
You can set variable `MINIO_SERVER_URL` with your public url (`MINIO_SERVER_URL="https://minio.example.com"`)

**Comment by Phynecs** [comment]
thx, looks like it was implemented in minio/minio#12770
I think this closes this ticket

**Comment by sniffingsugar** [comment]
@harshavardhana 
Thanks for your PR, I also created my branch, but I've saw yours and it's really nice :)
