### ISSUE TITLE
Console Tiering Name field in UI needs more information

### ISSUE THREAD

**Issue by eco-minio** [minio/console#881]
If you go to set up tiering in Console Settings, there is a "Tier Name" field.  The UI does not direct you that this must be all capitals.

![image](https://user-images.githubusercontent.com/41090896/126410678-fb2529c8-96e9-495f-bd31-5b154fd395c0.png)

If you do not enter the value in all caps, only a generic error message.is thrown "An error occurred, please try again".  We throw a proper log message in the terminal "original error -> (admin_tiers.go:43: Tier name must be in uppercase)" but the UI should guide the users on this so they don't have to check the logs each time.

**Comment by kannappanr** [comment]
does this need to be in caps?

**Comment by bexsoft** [comment]
yes @kannappanr It is a requirement, I'm working on improve this

**Comment by dvaldivia** [comment]
we should force the input to be caps all the time, plus show the error on the UI if any
