### ISSUE TITLE
Abnormal display of the policies assigned to a user with LDAP enabled

### ISSUE THREAD

**Issue by duchy** [minio/console#891]
The version deployed is: minio/minio:RELEASE.2021-07-15T22-27-34Z

Issues:
1. In the user page, no policy will be displayed for a LDAP user who has some policy assigend.
2. When click the assign buttion to add a new policy to an user. it will display all the policies  without any policy checked though the user has some policies assigned.
3. When check a policy to assign to some user, it will remove all other policies already assigned to that use silently.

**Comment by harshavardhana** [comment]
> The version deployed is: minio/minio:RELEASE.2021-07-15T22-27-34Z
> 
> Issues:
> 
> 1. In the user page, no policy will be displayed for a LDAP user who has some policy assigend.
> 2. When click the assign buttion to add a new policy to an user. it will display all the policies  without any policy checked though the user has some policies assigned.
> 3. When check a policy to assign to some user, it will remove all other policies already assigned to that use silently.

This is a work in progress - UI not yet ready to display the LDAP heirarchies yet.

**Comment by reivaj05** [comment]
Policy displays as expected with an LDAP user and n ew policies can be assigned to it without removing previous policies


![Image](https://user-images.githubusercontent.com/10521119/210419140-8d638065-9ef4-40d7-abd3-d259993ef7a3.png)
![Image](https://user-images.githubusercontent.com/10521119/210419138-408eee14-a28d-4593-b0ed-3dc0ef805574.png)
![Image](https://user-images.githubusercontent.com/10521119/210419139-63eb30c3-6a81-4264-9548-3410aa8bc589.png)
![Image](https://user-images.githubusercontent.com/10521119/210419137-34604060-e71e-4be9-b044-33be46a0c5a7.png)
