### ISSUE TITLE
Missing preview feature on new release

### ISSUE THREAD

**Issue by gustavorps** [minio/console#902]
## New release
![image](https://user-images.githubusercontent.com/516827/127347312-fa3630b7-9ce8-4676-961d-de5bfdf3edca.png)

## Old release
![image](https://user-images.githubusercontent.com/516827/127347717-aa364b44-b8df-4776-bb81-6e46a0318610.png)

![image](https://user-images.githubusercontent.com/516827/127348196-fcca8047-319a-4e63-9f54-f93d6872c14c.png)

**Comment by bexsoft** [comment]
Hi @gustavorps!, This feature is in the Pipeline, will be available in an upcoming release
