### ISSUE TITLE
The new version lacks the ability to set prefix access

### ISSUE THREAD

**Issue by AbnerMai** [minio/console#907]
![image](https://user-images.githubusercontent.com/26241803/127470330-eb25db22-fba1-4f83-9fe1-37efe5073a60.png)
![image](https://user-images.githubusercontent.com/26241803/127470423-ae6186ed-bdbc-4612-a755-3a32ac6cfc23.png)
![image](https://user-images.githubusercontent.com/26241803/127470457-4e90586f-5592-428d-90d7-c979fd7da11a.png)
I can set the prefix access policy through minio Browser, but it cannot be achieved through minio console. In particular, the new version of minio has removed the Browser function, but I cannot use the new version of the console.

**Comment by dvaldivia** [comment]
This is solved in #941
