### ISSUE TITLE
Operator Console: Tenant Edit YAML popover is full screen

### ISSUE THREAD

**Issue by ravindk89** [minio/console#927]
# Summary

When clicking on the Tenant vertical menu to access the *Edit YAML* option, clicking anywhere on the screen opens the YAML dialog.

Looking at the inspector, it looks like the `#long-menu` item is full screen. Screencap using inspector to confirm attached.

This is a minor bug, as you can close the edit screen without saving - but it is surprising.

**Comment by dvaldivia** [comment]
cannot see the video :P

**Comment by ravindk89** [comment]
Yeah github doesn't like it. Going to put into #console

**Comment by bexsoft** [comment]
Fixed in latest version of console

<img width="1838" alt="Screen Shot 2021-08-06 at 15 43 50" src="https://user-images.githubusercontent.com/33497058/128569103-f54fc64a-2abf-4999-b71d-806ffdd94053.png">
