### ISSUE TITLE
Append CAs from  /var/run/secrets/ on k8s as system cert directory

### ISSUE THREAD

**Issue by dkhachyan** [minio/console#933]
Hi! We have an error when integrating with external IDP with custom CA cert

```
 x509: certificate signed by unknown authority
```

Minio server appends certs from  /var/run/secrets/  directory:

https://github.com/minio/minio/pull/11123

**Comment by vadmeste** [comment]
@dkhachyan what's your console version ?

**Comment by dkhachyan** [comment]
> @dkhachyan what's your console version ?

0.8.2

**Comment by dvaldivia** [comment]
This is already supported
