### ISSUE TITLE
is it possible to use accesskeyId/secretKey

### ISSUE THREAD

**Issue by obeyler** [minio/console#934]
Hy,
I see that the main access mode is by 'JWT token' but is it possible to use this console to log into minio by 'accessKeyId/secretKey' ?  and in this case how configure installation to make it possible (and by default) ?

**Comment by harshavardhana** [comment]
That is for operator console, tenant console allows login with username/password

**Comment by obeyler** [comment]
Can operator console be use on an existing  minio cluster (not installed in a K8S) ?

**Comment by harshavardhana** [comment]
> Can operator console be use on an existing minio cluster (not installed in a K8S) ?

Operator console is meant to deploy MinIO tenants. The purpose is different.. and no it cannot be used for existing cluster outside of k8s.

Do not think there is an issue here, closing.
