### ISSUE TITLE
Console provides a 0 byte file for download when user has no permission to access the object

### ISSUE THREAD

**Issue by Mohitsharma44** [minio/console#945]
If a user has `listBucket` permissions but not `GetObject`, console provides a 0 byte file download instead of throwing an error.

**minio version**: `RELEASE.2021-08-05T22-01-19Z`

**Steps to reproduce**:
- Spin up a minio server instance
- Create a test object (e.g. `foo/bar/log.txt`)
- Add a user and assign the following policy to the user:
  ```
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": [
          "s3:ListBucket"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::*"
        ],
        "Sid": ""
      }
    ]
  }
  ```
- Try downloading a file via aws s3 cli and you shall see permission denied (as expected):
  ```
  aws s3 --profile=foostorage --endpoint-url https://foostorage.sharmamohit.com cp s3://foo/bar/log.txt .
  fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden 
  ```
- Login via console and it will give you a 0 byte file to download

**Comment by dvaldivia** [comment]
This has been fixed since the introduction of secure component, now we don't let you perform an action if you are not allowed 
<img width="303" alt="Screen Shot 2022-04-14 at 8 45 23 AM" src="https://user-images.githubusercontent.com/18384552/163426009-30ff2c4e-2659-4591-8c47-b51f918902f2.png">
