### ISSUE TITLE
please bring up the bucket/folder path in minio console like in minio browser

### ISSUE THREAD

**Issue by pusintek** [minio/console#949]
### Discussed in https://github.com/minio/minio/discussions/12969

<div type='discussions-op-text'>

<sup>Originally posted by **pusintek** August 15, 2021</sup>
please bring up the bucket/folder path in minio console like in minio browser, to make it easier to search and manage objects/files, I use minio console to manage a lot of files, failed to load/failed to search. The folder path is very helpful. thank you.
MinIO Browser :
![chosepath](https://user-images.githubusercontent.com/10806090/129457354-bd1f9c34-6af2-4d16-91b3-27499102d23c.png)

MinIO Console:
![searchobject](https://user-images.githubusercontent.com/10806090/129457403-b65da573-b31e-4bf2-b329-3697b478fd08.png)

</div>

**Comment by harshavardhana** [comment]
Moved to the relevant repo.

**Comment by pusintek** [comment]
the latest version of minio already comes with the minio-console, I hope to be able to use the folder path on the minio console on the latest version of minio.

**Comment by bexsoft** [comment]
This feature is already implemented as Create Folder inside Object Browser. Will Change the labels to mention the "choose option" too.
