### ISSUE TITLE
upload api  default content-type, need other content-type.

### ISSUE THREAD

**Issue by overstarry** [minio/console#965]
Files upload through console always get the content type: application/octet-stream
However, files upload through minio client (mc) or copy direct to data folder will get correct content type.
console upload: 
![image](https://user-images.githubusercontent.com/23260162/130221018-4308583b-dee4-4d7a-b6b0-0d1f95f0f6c3.png)
mc: 
![image](https://user-images.githubusercontent.com/23260162/130221089-118778f9-e796-44fe-b779-6f8f3b69eb2f.png)

example: upload png image file,I want the content-type of image/png, but the system gives me application/octet-stream.

https://github.com/minio/console/blob/2332a1347771ee62de58421723db07c75970dc39/restapi/user_objects.go#L510

**Comment by dvaldivia** [comment]
Thanks for the report, we are aware of this and will fix as soon as we have some bandwidth, we also welcome PRs! I think we just need to detect the content type from the browser

**Comment by harshavardhana** [comment]
Fixed in #968

**Comment by overstarry** [comment]
thanks
