### ISSUE TITLE
Display Errors on UI

### ISSUE THREAD

**Issue by cesnietor** [minio/console#99]
If an error is returned from the backend there should be a way to display them, for instance: 400, 401, 201, we can display as a snack bar or something:
proposal : https://material-ui.com/components/snackbars/
<img width="842" alt="Screen Shot 2020-05-06 at 12 16 07 PM" src="https://user-images.githubusercontent.com/11819101/81218645-6246e800-8f93-11ea-909a-33635b886886.png">

**Comment by dvaldivia** [comment]
@belvid @Jayshreemagdum we need some design on how to display the errors in the console UI

**Comment by belvid** [comment]
This is how it is right now. 

I will be working this week on the solution for these alerts.

<img width="1001" alt="Screen Shot 2020-11-03 at 5 06 45 PM" src="https://user-images.githubusercontent.com/20955366/100699697-895e7000-3350-11eb-9307-c4a4df748363.png">

**Comment by bexsoft** [comment]
<img width="830" alt="Screen Shot 2021-01-12 at 13 58 49" src="https://user-images.githubusercontent.com/33497058/104365990-59bd8e80-54de-11eb-943e-f1687d8bb586.png">
