### ISSUE TITLE
Is this a usage error?

### ISSUE THREAD

**Issue by chengfeiZhou** [minio/console#992]
![image](https://user-images.githubusercontent.com/24206386/131436914-45ea36f3-ab20-4b2e-b9da-abe3ccb97dff.png)

**Comment by chengfeiZhou** [comment]
This function should have no arguments, but it does. 🤔

**Comment by harshavardhana** [comment]
Please report an actual issue @chengfeiZhou - not sure what you are talking about here

**Comment by dvaldivia** [comment]
there's no argument being passed @chengfeiZhou , we are invoking reloading on location for the iframe document
