### ISSUE TITLE
FR: Add link to docs when MINIO_PROMETHEUS_URL or CONSOLE_PROMETHEUS_URL is not set

### ISSUE THREAD

**Issue by eco-minio** [minio/console#994]
A frequent question that keeps coming up is "why are metrics not showing in the console" due to users not knowing they need prometheus running and one of the aforementioned environment variables set.  When users do not have the env var set, we should display a banner with links to the docs for prometheus and setting the proper env var.

**Comment by ravindk89** [comment]
It would be enough (I think) to have text like

```
The MinIO Dashboard is displaying basic metrics only due to missing the [necessary settings](https://docs.min.io/minio/baremetal/console/minio-console.html#configuration) for displaying extended metrics.

See [Collect MinIO Metrics Using Prometheus](https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.html#minio-metrics-collect-using-prometheus) for a complete tutorial on scraping and visualizing MinIO metrics with Prometheus.
```
